import React from "react";
import type { AnimalProps } from "./types";
import AnimalImage from "./AnimalImage";

import catImg from "@/assets/animals/cat.png";
import dogImg from "@/assets/animals/dog.png";
import elephantImg from "@/assets/animals/elephant.png";
import rabbitImg from "@/assets/animals/rabbit.png";
import birdImg from "@/assets/animals/bird.png";
import fishImg from "@/assets/animals/fish.png";
import lionImg from "@/assets/animals/lion.png";
import turtleImg from "@/assets/animals/turtle.png";
import butterflyImg from "@/assets/animals/butterfly.png";
import frogImg from "@/assets/animals/frog.png";
import horseImg from "@/assets/animals/horse.png";
import owlImg from "@/assets/animals/owl.png";
import penguinImg from "@/assets/animals/penguin.png";
import monkeyImg from "@/assets/animals/monkey.png";
import giraffeImg from "@/assets/animals/giraffe.png";
import bearImg from "@/assets/animals/bear.png";
import dolphinImg from "@/assets/animals/dolphin.png";
import snakeImg from "@/assets/animals/snake.png";
import beeImg from "@/assets/animals/bee.png";
import pigImg from "@/assets/animals/pig.png";
import pandaImg from "@/assets/animals/panda.png";
import koalaImg from "@/assets/animals/koala.png";
import zebraImg from "@/assets/animals/zebra.png";
import sharkImg from "@/assets/animals/shark.png";
import whaleImg from "@/assets/animals/whale.png";
import crocodileImg from "@/assets/animals/crocodile.png";
import foxImg from "@/assets/animals/fox.png";
import duckImg from "@/assets/animals/duck.png";
import octopusImg from "@/assets/animals/octopus.png";
import tigerImg from "@/assets/animals/tiger.png";

export const Cat: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={catImg} alt="Gato" />;
export const Dog: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={dogImg} alt="Cachorro" />;
export const Elephant: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={elephantImg} alt="Elefante" />;
export const Rabbit: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={rabbitImg} alt="Coelho" />;
export const Bird: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={birdImg} alt="Pássaro" />;
export const Fish: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={fishImg} alt="Peixe" />;
export const Lion: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={lionImg} alt="Leão" />;
export const Turtle: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={turtleImg} alt="Tartaruga" />;
export const Butterfly: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={butterflyImg} alt="Borboleta" />;
export const Frog: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={frogImg} alt="Sapo" />;
export const Horse: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={horseImg} alt="Cavalo" />;
export const Owl: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={owlImg} alt="Coruja" />;
export const Penguin: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={penguinImg} alt="Pinguim" />;
export const Monkey: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={monkeyImg} alt="Macaco" />;
export const Giraffe: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={giraffeImg} alt="Girafa" />;
export const Bear: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={bearImg} alt="Urso" />;
export const Dolphin: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={dolphinImg} alt="Golfinho" />;
export const Snake: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={snakeImg} alt="Cobra" />;
export const Bee: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={beeImg} alt="Abelha" />;
export const Pig: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={pigImg} alt="Porco" />;
export const Panda: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={pandaImg} alt="Panda" />;
export const Koala: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={koalaImg} alt="Coala" />;
export const Zebra: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={zebraImg} alt="Zebra" />;
export const Shark: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={sharkImg} alt="Tubarão" />;
export const Whale: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={whaleImg} alt="Baleia" />;
export const Crocodile: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={crocodileImg} alt="Crocodilo" />;
export const Fox: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={foxImg} alt="Raposa" />;
export const Duck: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={duckImg} alt="Pato" />;
export const Octopus: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={octopusImg} alt="Polvo" />;
export const Tiger: React.FC<AnimalProps> = (props) => <AnimalImage {...props} src={tigerImg} alt="Tigre" />;
