import type { AnimalId } from "./animals";

export const animalFunFacts: Record<AnimalId, string[]> = {
  cat: [
    "Os gatos dormem até 16 horas por dia!",
    "Os gatos conseguem girar as orelhas em 180 graus!",
    "Um gato pode pular até 6 vezes o seu próprio tamanho!",
    "Os gatos têm mais de 20 tipos de miados diferentes!",
    "O nariz de cada gato é único, como a impressão digital humana!",
    "Os gatos conseguem enxergar no escuro!",
    "Os gatos passam 30% do dia se limpando!",
    "Um gato tem 230 ossos no corpo, mais do que os humanos!",
    "Os bigodes do gato servem para medir se ele cabe em lugares apertados!",
    "Os gatos ronronam quando estão felizes, mas também quando querem se curar!",
    "Gatos conseguem correr a 48 quilômetros por hora!",
    "Os gatos domésticos existem há mais de 10 mil anos!",
    "Um gato consegue ouvir sons que nós não conseguimos!",
    "Os gatos caem sempre de pé por causa do equilíbrio incrível!",
    "Gatos esfregam o rosto nas coisas para marcar território!",
    "O gato mais velho do mundo viveu 38 anos!",
    "Os gatos têm uma terceira pálpebra escondida!",
    "Gatos preferem água corrente do que parada!",
    "Os gatos conseguem sentir terremotos antes dos humanos!",
    "Um grupo de gatos se chama colônia!",
  ],
  dog: [
    "O faro do cachorro é 40 vezes melhor que o dos humanos!",
    "Cachorros conseguem aprender mais de 100 palavras!",
    "O cachorro mais rápido do mundo corre a 70 km por hora!",
    "Cachorros sonham enquanto dormem, igualzinho a gente!",
    "O nariz do cachorro é úmido para captar melhor os cheiros!",
    "Cachorros abanam o rabo para a direita quando estão felizes!",
    "Cachorros enxergam em tons de azul e amarelo!",
    "A audição dos cachorros é 4 vezes melhor que a nossa!",
    "O cachorro mais velho do mundo viveu 30 anos!",
    "Cachorros bocejam quando veem alguém bocejando, por empatia!",
    "Um cachorro consegue sentir o humor do dono pelo cheiro!",
    "Existem mais de 340 raças de cachorros no mundo!",
    "Os cachorros suam apenas pelas patinhas!",
    "Filhotes de cachorro nascem surdos e cegos!",
    "O Labrador é a raça mais popular do mundo!",
    "Cachorros conseguem farejar doenças nos humanos!",
    "Um cachorro adulto tem 42 dentes!",
    "Cachorros giram em círculos antes de deitar por instinto!",
    "Os cachorros conseguem ouvir sons a 225 metros de distância!",
    "Três cachorros sobreviveram ao naufrágio do Titanic!",
  ],
  elephant: [
    "Os elefantes são os maiores animais terrestres do mundo!",
    "Elefantes conseguem se reconhecer no espelho!",
    "Um elefante bebe até 200 litros de água por dia!",
    "Elefantes têm uma memória incrível e nunca esquecem um amigo!",
    "Os elefantes se comunicam com sons tão graves que nós não ouvimos!",
    "Elefantes adoram tomar banho de lama para se proteger do sol!",
    "Os elefantes podem pesar até 6 toneladas!",
    "Elefantes usam a tromba como um canudo para beber água!",
    "Um elefante bebê pesa cerca de 100 quilos ao nascer!",
    "Os elefantes andam na ponta dos dedos!",
    "Elefantes conseguem nadar muito bem!",
    "A tromba de um elefante tem mais de 40 mil músculos!",
    "Elefantes ficam tristes quando um amigo morre e fazem luto!",
    "Os elefantes africanos têm orelhas em formato de África!",
    "Elefantes comem até 150 quilos de comida por dia!",
    "Os elefantes vivem em famílias lideradas por uma fêmea!",
    "Elefantes se cumprimentam entrelaçando as trombas!",
    "A pele do elefante tem até 2,5 centímetros de espessura!",
    "Elefantes conseguem sentir vibrações no chão pelos pés!",
    "Os elefantes são um dos poucos animais que choram de emoção!",
  ],
  rabbit: [
    "Os coelhos podem girar as orelhas em qualquer direção!",
    "Coelhos são tão felizes que pulam e giram no ar! Isso se chama binky!",
    "Os dentes dos coelhos nunca param de crescer!",
    "Coelhos conseguem ver quase 360 graus ao redor deles!",
    "Um coelho pode correr a 55 km por hora!",
    "Coelhos ronronam quando estão felizes, igual aos gatos!",
    "Os coelhos têm mais de 28 dentes!",
    "Coelhos mexem o nariz até 120 vezes por minuto!",
    "Os coelhos são mais ativos de manhã cedo e ao entardecer!",
    "Coelhos podem dar pulos de até 1 metro de altura!",
    "Um grupo de coelhos se chama colônia!",
    "Os coelhos se limpam lambendo as patas, como os gatos!",
    "Coelhos vivem em tocas subterrâneas!",
    "Os coelhos podem ter até 12 filhotes de uma vez!",
    "Coelhos batem as patas no chão para avisar de perigo!",
    "Os coelhos adoram brincar com túneis e caixas!",
    "Coelhos dormem de olhos abertos às vezes!",
    "Os coelhos conseguem aprender truques e seu nome!",
    "Coelhos selvagens vivem em quase todos os continentes!",
    "Os coelhos podem viver até 12 anos!",
  ],
  bird: [
    "Alguns pássaros conseguem imitar a voz humana!",
    "O beija-flor é o único pássaro que voa para trás!",
    "Pássaros enxergam mais cores do que os humanos!",
    "O avestruz é o pássaro mais rápido correndo, a 70 km por hora!",
    "Pássaros cantam para se comunicar e marcar território!",
    "As penas dos pássaros são mais fortes do que parecem!",
    "Os papagaios podem viver até 80 anos!",
    "O beija-flor bate as asas até 80 vezes por segundo!",
    "Pássaros migram milhares de quilômetros todo ano!",
    "O ovo do avestruz é o maior ovo do mundo!",
    "Pássaros têm ossos ocos para ficarem mais leves para voar!",
    "Os corvos são tão inteligentes que usam ferramentas!",
    "O menor pássaro do mundo é o beija-flor-abelha, com 5 centímetros!",
    "Pássaros conseguem dormir com metade do cérebro acordada!",
    "Os flamingos são rosas por causa da comida que comem!",
    "Existem mais de 10 mil espécies de pássaros no mundo!",
    "Os pinguins são pássaros, mas não voam!",
    "Pássaros engolem pedrinhas para ajudar a digerir a comida!",
    "As corujas não conseguem mexer os olhos, só giram a cabeça!",
    "O albatroz pode voar por anos sem pousar em terra!",
  ],
  fish: [
    "Existem peixes que brilham no fundo do mar!",
    "Alguns peixes conseguem voar por cima da água!",
    "O peixe-palhaço vive dentro das anêmonas do mar!",
    "Peixes não têm pálpebras, eles dormem de olhos abertos!",
    "O tubarão-baleia é o maior peixe do mundo!",
    "Alguns peixes mudam de cor para se esconder dos predadores!",
    "Os peixes usam as brânquias para respirar debaixo d'água!",
    "Existem mais de 30 mil espécies de peixes no mundo!",
    "O cavalo-marinho é um dos poucos peixes onde o pai carrega os bebês!",
    "Peixes conseguem sentir vibrações na água com uma linha lateral!",
    "O peixe-espada pode nadar a 110 quilômetros por hora!",
    "Alguns peixes vivem nas profundezas mais escuras do oceano!",
    "Os peixes-dourados conseguem se lembrar de coisas por meses!",
    "O baiacu se enche de água para parecer maior e assustar predadores!",
    "Peixes viajam em cardumes para se proteger!",
    "Os tubarões existem há mais de 400 milhões de anos!",
    "Alguns peixes fazem ninhos para proteger seus ovos!",
    "O peixe-lua é o peixe ósseo mais pesado do mundo!",
    "Peixes podem sentir o gosto da água ao redor deles!",
    "O peixe-arqueiro cospe jatos de água para derrubar insetos!",
  ],
  lion: [
    "O rugido do leão pode ser ouvido a 8 quilômetros de distância!",
    "Os leões dormem até 20 horas por dia!",
    "Só os leões machos têm aquela juba enorme!",
    "As leoas são as caçadoras da família!",
    "Os leões vivem em grupos chamados de alcateias!",
    "Um leão pode correr a 80 km por hora em curtas distâncias!",
    "Os filhotes de leão nascem com manchas que somem quando crescem!",
    "Leões esfregam as cabeças uns nos outros para se cumprimentar!",
    "A juba do leão escurece conforme ele envelhece!",
    "Leões conseguem pular até 11 metros de distância!",
    "Os leões são chamados de Rei da Selva, mas vivem na savana!",
    "Um leão pode comer 40 quilos de carne de uma vez!",
    "Os bigodes do leão ajudam a sentir o que está ao redor!",
    "Leões descansam nas árvores para fugir do calor!",
    "Os filhotes de leão brincam de lutar para aprender a caçar!",
    "Leões machos protegem o território enquanto as fêmeas caçam!",
    "O leão é o segundo maior felino do mundo, depois do tigre!",
    "Leões podem viver até 15 anos na natureza!",
    "Os leões bebem água sempre que podem, mas aguentam dias sem beber!",
    "Um leão reconhece os membros da alcateia pelo rugido!",
  ],
  turtle: [
    "Algumas tartarugas podem viver mais de 100 anos!",
    "O casco da tartaruga faz parte do esqueleto dela!",
    "As tartarugas marinhas viajam milhares de quilômetros pelo oceano!",
    "As tartarugas existem há mais de 200 milhões de anos!",
    "Tartarugas não têm dentes, elas têm um bico como os pássaros!",
    "A tartaruga-de-couro é a maior tartaruga do mundo!",
    "Tartarugas conseguem sentir quando tocam no casco!",
    "As tartarugas marinhas voltam à mesma praia onde nasceram para botar ovos!",
    "Tartarugas podem prender a respiração por horas debaixo d'água!",
    "O sexo das tartarugas bebês depende da temperatura da areia!",
    "Tartarugas enxergam cores, inclusive ultravioleta!",
    "Algumas tartarugas hibernam no inverno enterradas na lama!",
    "A tartaruga-gigante-de-Galápagos pode pesar 400 quilos!",
    "Tartarugas têm um ótimo senso de direção!",
    "As tartarugas são répteis, parentes dos dinossauros!",
    "Tartarugas marinhas choram para eliminar o sal da água do mar!",
    "Algumas tartarugas conseguem respirar pelo bumbum!",
    "Tartarugas de estimação podem viver mais de 50 anos!",
    "As tartarugas são os répteis mais antigos que existem!",
    "Tartarugas bebês são do tamanho de uma moeda quando nascem!",
  ],
  butterfly: [
    "As borboletas provam a comida com os pés!",
    "Uma borboleta começa a vida como uma lagarta!",
    "Existem mais de 20 mil espécies de borboletas no mundo!",
    "As asas das borboletas são transparentes, as cores vêm de escamas minúsculas!",
    "Algumas borboletas migram milhares de quilômetros!",
    "Borboletas não conseguem voar se estiverem com frio!",
    "As borboletas bebem néctar das flores com uma tromba enrolada!",
    "A borboleta-monarca viaja do Canadá ao México todo ano!",
    "Borboletas vivem apenas algumas semanas!",
    "As borboletas precisam do sol para aquecer as asas e voar!",
    "Algumas borboletas parecem ter olhos nas asas para assustar predadores!",
    "A transformação de lagarta em borboleta se chama metamorfose!",
    "Borboletas enxergam cores que os humanos não conseguem ver!",
    "Dentro do casulo, a lagarta se transforma completamente em líquido!",
    "Algumas borboletas se alimentam de frutas podres!",
    "As borboletas batem as asas cerca de 5 vezes por segundo!",
    "Borboletas podem voar a até 20 quilômetros por hora!",
    "A maior borboleta do mundo tem 30 centímetros de envergadura!",
    "Borboletas se aquecem abrindo as asas ao sol como painéis solares!",
    "Algumas borboletas têm um gosto ruim para os predadores não comerem!",
  ],
  frog: [
    "Os sapos absorvem água pela pele, eles não bebem!",
    "Alguns sapos são tão venenosos que podem derrubar um elefante!",
    "Os sapos engolem a comida usando os olhos para empurrar!",
    "Existem sapos de todas as cores do arco-íris!",
    "Os sapos coaxam para atrair uma namorada!",
    "Alguns sapos conseguem congelar no inverno e descongelar na primavera!",
    "Os sapos começam a vida como girinos na água!",
    "Sapos conseguem pular até 20 vezes o tamanho do corpo!",
    "A pele dos sapos é sempre úmida!",
    "Existem sapos menores que uma unha!",
    "Os sapos venenosos são coloridos para avisar os predadores!",
    "Alguns sapos carregam os filhotes nas costas!",
    "Os sapos existem há mais de 200 milhões de anos!",
    "Sapos podem viver tanto na água quanto na terra!",
    "O maior sapo do mundo pesa mais de 3 quilos!",
    "Sapos mudam de pele regularmente e comem a pele velha!",
    "Os olhos dos sapos ficam em cima da cabeça para ver fora d'água!",
    "Sapos são muito importantes para controlar insetos!",
    "Existem mais de 7 mil espécies de sapos no mundo!",
    "Alguns sapos fazem sons que parecem pássaros cantando!",
  ],
  horse: [
    "Os cavalos conseguem dormir em pé!",
    "Um cavalo pode correr poucas horas depois de nascer!",
    "Os cavalos enxergam quase 360 graus ao redor deles!",
    "Os dentes dos cavalos ocupam mais espaço na cabeça do que o cérebro!",
    "Cavalos conseguem reconhecer emoções no rosto humano!",
    "O cavalo mais rápido do mundo atingiu 70 km por hora!",
    "Cavalos têm a maior visão de todos os mamíferos terrestres!",
    "Os cavalos se comunicam com as orelhas, olhos e expressões!",
    "Um cavalo adulto tem 40 dentes!",
    "Os cavalos podem viver até 30 anos!",
    "Cavalos dormem apenas 2 a 3 horas por dia!",
    "Os cascos dos cavalos são feitos do mesmo material das nossas unhas!",
    "Cavalos conseguem correr no mesmo dia em que nascem!",
    "Os cavalos são herbívoros e adoram cenouras e maçãs!",
    "Um cavalo bebe entre 30 e 50 litros de água por dia!",
    "Cavalos têm uma memória excelente!",
    "Os cavalos selvagens vivem em manadas lideradas por uma égua!",
    "Cavalos não conseguem vomitar!",
    "O menor cavalo do mundo tem apenas 44 centímetros de altura!",
    "Os cavalos existem há mais de 50 milhões de anos!",
  ],
  owl: [
    "As corujas conseguem girar a cabeça até 270 graus!",
    "Corujas têm uma audição tão boa que caçam no escuro total!",
    "Os olhos das corujas não se mexem, por isso elas giram a cabeça!",
    "As penas das corujas são silenciosas, elas voam sem fazer barulho!",
    "Algumas corujas são menores que a sua mão!",
    "Corujas engolem a presa inteira e depois cospem os ossos!",
    "As corujas têm três pálpebras em cada olho!",
    "Corujas conseguem ouvir um rato andando debaixo da neve!",
    "Os olhos das corujas são tão grandes que não cabem se mexer!",
    "Corujas são encontradas em todos os continentes, menos na Antártida!",
    "A coruja-buraqueira vive em buracos no chão!",
    "Corujas viram a cabeça porque não conseguem mexer os olhos!",
    "Existem mais de 200 espécies de corujas no mundo!",
    "As corujas são caçadoras noturnas incríveis!",
    "A coruja-das-neves é quase toda branca!",
    "Corujas têm garras superfortes para agarrar as presas!",
    "Um grupo de corujas se chama parlamento!",
    "As corujas bebês se chamam corujinhas ou ninhegos!",
    "Corujas podem girar a cabeça para os dois lados!",
    "A maior coruja do mundo tem quase 2 metros de envergadura!",
  ],
  penguin: [
    "Os pinguins não voam, mas são ótimos nadadores!",
    "Pinguins podem prender a respiração por até 20 minutos debaixo d'água!",
    "O pinguim-imperador é o maior de todos, com quase 1 metro de altura!",
    "Os pinguins vivem no frio, mas nem todos vivem na neve!",
    "Pinguins se aquecem ficando juntinhos em grupo!",
    "Os pais pinguins chocam os ovos nos próprios pés!",
    "Pinguins podem nadar a 35 quilômetros por hora!",
    "Existem 18 espécies de pinguins no mundo!",
    "Os pinguins bebem água salgada e filtram o sal!",
    "Pinguins reconhecem o parceiro pelo canto!",
    "O menor pinguim do mundo tem apenas 30 centímetros!",
    "Os pinguins trocam de penas uma vez por ano!",
    "Pinguins deslizam de barriga na neve para se locomover!",
    "Os pinguins são pretos e brancos para se camuflar na água!",
    "Pinguins podem mergulhar a mais de 500 metros de profundidade!",
    "Os pinguins-imperador suportam temperaturas de -60 graus!",
    "Pinguins são muito fiéis e reconhecem o parceiro todo ano!",
    "Os filhotes de pinguim ficam em creches enquanto os pais caçam!",
    "Pinguins comem peixes, lulas e krill!",
    "Os pinguins existem há mais de 60 milhões de anos!",
  ],
  monkey: [
    "Os macacos usam ferramentas como pedras para abrir frutas!",
    "Macacos se abraçam e fazem carinho para mostrar amizade!",
    "O macaco-aranha usa o rabo como uma mão extra!",
    "Existem mais de 260 espécies de macacos no mundo!",
    "Os macacos vivem em grupos e cuidam uns dos outros!",
    "Macacos conseguem reconhecer o próprio reflexo no espelho!",
    "Macacos catam piolhos uns dos outros para fortalecer a amizade!",
    "O menor macaco do mundo cabe na palma da mão!",
    "Macacos conseguem aprender linguagem de sinais!",
    "Os macacos bugios são ouvidos a 5 quilômetros de distância!",
    "Macacos japoneses tomam banho em fontes termais no inverno!",
    "Os macacos-prego são considerados os mais inteligentes das Américas!",
    "Macacos bocejam quando veem outro macaco bocejando!",
    "Os macacos noturnos são os únicos que enxergam bem no escuro!",
    "Macacos usam diferentes sons para avisar sobre tipos de predadores!",
    "O macaco-narigudo tem o maior nariz de todos os primatas!",
    "Macacos bebês se agarram à barriga da mãe para se locomover!",
    "Os macacos são nossos parentes mais próximos no reino animal!",
    "Macacos podem viver até 40 anos na natureza!",
    "Os macacos da América têm rabo que agarra, os da África não!",
  ],
  giraffe: [
    "A girafa é o animal mais alto do mundo, chegando a 6 metros!",
    "A língua da girafa tem até 50 centímetros de comprimento!",
    "Cada girafa tem um padrão de manchas único, como impressões digitais!",
    "As girafas dormem apenas 30 minutos por dia!",
    "O coração da girafa pesa 11 quilos!",
    "Os bebês girafa já nascem com quase 2 metros de altura!",
    "A língua da girafa é roxa para se proteger do sol!",
    "Girafas andam movendo as duas pernas do mesmo lado juntas!",
    "As girafas podem correr a 55 quilômetros por hora!",
    "O pescoço da girafa tem apenas 7 vértebras, igual ao nosso!",
    "Girafas raramente se deitam, até dormem em pé!",
    "As girafas bebem água abrindo bem as pernas da frente!",
    "Girafas machos lutam batendo pescoço, isso se chama necking!",
    "Os chifres da girafa se chamam ossicones!",
    "Girafas podem ficar dias sem beber água!",
    "As girafas são os mamíferos com a maior pressão sanguínea!",
    "Girafas fêmeas voltam ao lugar onde nasceram para ter seus filhotes!",
    "Girafas se comunicam com sons que humanos não conseguem ouvir!",
    "A girafa pode chutar tão forte que assusta até um leão!",
    "Existem 4 espécies diferentes de girafas!",
  ],
  bear: [
    "Os ursos polares têm a pele preta por baixo do pelo branco!",
    "Ursos conseguem sentir o cheiro de comida a 30 quilômetros!",
    "Alguns ursos dormem o inverno inteiro sem comer nem beber!",
    "Os ursos pandas comem bambu por até 14 horas por dia!",
    "Ursos são excelentes nadadores!",
    "O urso-pardo pode pesar mais de 600 quilos!",
    "Os ursos polares são os maiores carnívoros terrestres!",
    "Ursos conseguem correr a 55 quilômetros por hora!",
    "O pelo do urso polar é transparente, não branco!",
    "Ursos pandas bebês nascem do tamanho de uma barra de manteiga!",
    "Os ursos têm um olfato 7 vezes melhor que o de um cão!",
    "Ursos se coçam nas árvores para marcar território!",
    "O urso-de-óculos é o único urso da América do Sul!",
    "Ursos conseguem ficar em pé nas patas traseiras!",
    "Os ursos negros podem subir em árvores muito rápido!",
    "Existem 8 espécies de ursos no mundo!",
    "Ursos podem viver até 30 anos na natureza!",
    "Os filhotes de urso nascem cegos e sem pelo!",
    "Ursos adoram mel e não se importam com as picadas de abelha!",
    "O coração do urso bate apenas 8 vezes por minuto durante a hibernação!",
  ],
  dolphin: [
    "Os golfinhos dormem com um olho aberto!",
    "Golfinhos se comunicam com sons como cliques e assobios!",
    "Um golfinho pode nadar a 60 km por hora!",
    "Golfinhos são tão inteligentes que se reconhecem no espelho!",
    "Golfinhos vivem em grupos chamados de pods!",
    "Os golfinhos ajudam uns aos outros quando estão doentes!",
    "Cada golfinho tem um assobio único, como um nome próprio!",
    "Golfinhos conseguem prender a respiração por até 10 minutos!",
    "Os golfinhos brincam com ondas e surfam por diversão!",
    "Golfinhos usam ecolocalização para encontrar comida no escuro!",
    "O golfinho-nariz-de-garrafa é o mais conhecido do mundo!",
    "Golfinhos podem mergulhar a 300 metros de profundidade!",
    "Os golfinhos são mamíferos, não peixes!",
    "Golfinhos fêmeas cuidam dos filhotes por até 6 anos!",
    "Os golfinhos têm entre 80 e 100 dentes!",
    "Golfinhos já foram vistos ajudando pescadores a pescar!",
    "O cérebro do golfinho é um dos maiores do reino animal!",
    "Golfinhos conseguem saltar até 6 metros fora da água!",
    "Golfinhos podem viver até 50 anos!",
    "Os golfinhos cor-de-rosa vivem nos rios da Amazônia!",
  ],
  snake: [
    "As cobras sentem cheiros com a língua!",
    "Cobras não têm pálpebras, elas dormem de olhos abertos!",
    "Algumas cobras conseguem voar planando entre as árvores!",
    "As cobras trocam de pele várias vezes por ano!",
    "Existem cobras que podem comer presas maiores que a própria cabeça!",
    "A cobra mais longa do mundo pode chegar a 10 metros!",
    "Cobras não têm ouvidos externos, mas sentem vibrações no chão!",
    "Existem mais de 3 mil espécies de cobras no mundo!",
    "A maioria das cobras não é venenosa!",
    "Cobras conseguem abrir a boca até 150 graus!",
    "Algumas cobras cuidam dos ovos até eles chocarem!",
    "A cobra mais rápida do mundo é a mamba-negra!",
    "Cobras podem ficar meses sem comer depois de uma grande refeição!",
    "As cobras têm centenas de costelas flexíveis!",
    "Cobras são encontradas em todos os continentes, menos na Antártida!",
    "A cobra-rei é a maior cobra venenosa, chegando a 5 metros!",
    "Cobras se movem de várias formas: rastejando, ondulando e até pulando!",
    "Algumas cobras fingem de mortas para escapar de predadores!",
    "As cobras ajudam a controlar populações de ratos e insetos!",
    "A sucuri é a cobra mais pesada do mundo, podendo pesar 250 quilos!",
  ],
  bee: [
    "Uma abelha visita até 2 mil flores por dia!",
    "As abelhas dançam para mostrar onde tem comida!",
    "O mel nunca estraga, já encontraram mel de 3 mil anos!",
    "Uma colmeia pode ter até 60 mil abelhas!",
    "As abelhas são responsáveis por polinizar um terço da nossa comida!",
    "A abelha rainha pode viver até 5 anos!",
    "As abelhas batem as asas 200 vezes por segundo!",
    "Uma abelha produz apenas uma colher de chá de mel na vida toda!",
    "As abelhas se comunicam dançando em forma de oito!",
    "Abelhas conseguem reconhecer rostos humanos!",
    "O ferrão da abelha tem um formato de serra!",
    "As abelhas operárias são todas fêmeas!",
    "Abelhas precisam visitar 2 milhões de flores para fazer 1 quilo de mel!",
    "As abelhas mantêm a colmeia a 35 graus batendo as asas!",
    "Abelhas veem cores ultravioletas que nós não enxergamos!",
    "Uma abelha voa a 24 quilômetros por hora!",
    "As abelhas têm 5 olhos: 2 grandes e 3 pequenos!",
    "Abelhas carregam o pólen em cestinhas nas pernas traseiras!",
    "A rainha é a única que bota ovos na colmeia!",
    "Sem as abelhas, muitas frutas e vegetais deixariam de existir!",
  ],
  pig: [
    "Os porcos são tão inteligentes quanto os cachorros!",
    "Porcos não conseguem olhar para cima, para o céu!",
    "Os porcos tomam banho de lama para se refrescar, não porque são sujos!",
    "Porcos têm um olfato incrível e são usados para encontrar trufas!",
    "Os porquinhos recém-nascidos reconhecem a voz da mãe!",
    "Porcos conseguem aprender truques e jogar videogame simples!",
    "Porcos são animais muito limpos e organizam o espaço onde vivem!",
    "Os porcos se comunicam com mais de 20 sons diferentes!",
    "Porcos conseguem sonhar enquanto dormem!",
    "O porco-espinho na verdade não é um porco, é um roedor!",
    "Os porcos têm uma memória excelente!",
    "Porcos podem correr a 18 quilômetros por hora!",
    "Os porcos domésticos existem há mais de 9 mil anos!",
    "Porcos não suam, por isso precisam da lama para se refrescar!",
    "Os porquinhos nascem com os olhos abertos!",
    "Porcos reconhecem outros porcos e humanos pelo rosto!",
    "O porco mini-pig pode viver até 20 anos!",
    "Os porcos adoram receber carinho na barriga!",
    "Porcos selvagens são chamados de javalis!",
    "Os porcos têm 44 dentes, mais que os humanos!",
  ],
};

import { animalFunFactsEn } from "./animalFunFactsEn";
import { animalFunFactsEs } from "./animalFunFactsEs";
import { animalFunFactsFr } from "./animalFunFactsFr";
import { animalFunFactsIt } from "./animalFunFactsIt";
import type { Locale } from "@/i18n/translations";

const factsByLocale: Record<Locale, Record<AnimalId, string[]>> = {
  pt: animalFunFacts,
  en: animalFunFactsEn,
  es: animalFunFactsEs,
  fr: animalFunFactsFr,
  it: animalFunFactsIt,
};

export function getRandomFunFact(animalId: AnimalId, locale: Locale = "pt"): string {
  const facts = factsByLocale[locale][animalId];
  return facts[Math.floor(Math.random() * facts.length)];
}
