import type { AnimalId } from "./animals";

export const animalFunFactsEs: Record<AnimalId, string[]> = {
  cat: [
    "¡Los gatos duermen hasta 16 horas al día!",
    "¡Los gatos pueden girar sus orejas 180 grados!",
    "¡Un gato puede saltar hasta 6 veces su propia longitud!",
    "¡Los gatos tienen más de 20 tipos diferentes de maullidos!",
    "¡La nariz de cada gato es única, como una huella digital humana!",
    "¡Los gatos pueden ver en la oscuridad!",
    "¡Los gatos pasan el 30% del día acicalándose!",
    "¡Un gato tiene 230 huesos, más que los humanos!",
    "¡Los bigotes del gato le ayudan a medir si cabe en espacios estrechos!",
    "¡Los gatos ronronean cuando están felices, pero también para curarse!",
    "¡Los gatos pueden correr a 48 kilómetros por hora!",
    "¡Los gatos domésticos existen desde hace más de 10 mil años!",
    "¡Un gato puede escuchar sonidos que nosotros no podemos!",
    "¡Los gatos siempre caen de pie gracias a su increíble equilibrio!",
    "¡Los gatos frotan su cara en las cosas para marcar territorio!",
    "¡El gato más viejo del mundo vivió 38 años!",
    "¡Los gatos tienen un tercer párpado oculto!",
    "¡Los gatos prefieren el agua corriente al agua estancada!",
    "¡Los gatos pueden sentir terremotos antes que los humanos!",
    "¡Un grupo de gatos se llama colonia!",
  ],
  dog: [
    "¡El olfato de un perro es 40 veces mejor que el de los humanos!",
    "¡Los perros pueden aprender más de 100 palabras!",
    "¡El perro más rápido del mundo corre a 70 km por hora!",
    "¡Los perros sueñan mientras duermen, igual que nosotros!",
    "¡Los perros pueden sentir el estado de ánimo de sus dueños!",
    "¡Los perros tienen la nariz húmeda para captar mejor los olores!",
    "¡Existen más de 300 razas de perros en el mundo!",
    "¡Los perros ven los colores azul y amarillo!",
    "¡La cola de un perro cuenta cómo se siente!",
    "¡Los cachorros nacen sordos y ciegos!",
    "¡Los perros pueden oler enfermedades en las personas!",
    "¡Un perro puede entender hasta 250 palabras y gestos!",
    "¡Los perros tienen un sentido del tiempo y saben cuándo volverás!",
    "¡Las huellas de la nariz de cada perro son únicas!",
    "¡Los perros mueven la cola hacia la derecha cuando están felices!",
    "¡Los perros pueden oír sonidos 4 veces más lejos que los humanos!",
    "¡El perro más pequeño del mundo cabe en la palma de la mano!",
    "¡Los perros bostezan cuando ven a alguien bostezar!",
    "¡Los perros tienen tres párpados en cada ojo!",
    "¡Los perros son los mejores amigos de los humanos desde hace 15 mil años!",
  ],
  elephant: [
    "¡Los elefantes son los animales terrestres más grandes del mundo!",
    "¡Los elefantes pueden recordar lugares durante toda su vida!",
    "¡Un elefante bebe hasta 200 litros de agua al día!",
    "¡Los elefantes se comunican con sonidos que no podemos oír!",
    "¡Los elefantes usan su trompa como una mano!",
    "¡Los elefantes bebés se chupan la trompa como los bebés humanos el pulgar!",
    "¡Los elefantes pueden nadar largas distancias!",
    "¡La piel de un elefante puede tener hasta 3 centímetros de grosor!",
    "¡Los elefantes viven en familias lideradas por una abuela!",
    "¡Los elefantes son muy inteligentes y sienten emociones!",
    "¡Un elefante puede pesar tanto como un autobús escolar!",
    "¡Los elefantes se echan barro para protegerse del sol!",
    "¡Las orejas de los elefantes les ayudan a enfriarse!",
    "¡Los elefantes caminan de puntillas!",
    "¡Los elefantes pueden vivir hasta 70 años!",
    "¡Los elefantes ronronean como los gatos cuando están contentos!",
    "¡Un elefante come hasta 150 kilos de comida al día!",
    "¡Los elefantes tienen miedo de las abejas!",
    "¡Los elefantes se reconocen en el espejo!",
    "¡Los elefantes africanos tienen las orejas en forma de África!",
  ],
  rabbit: [
    "¡Los conejos pueden saltar hasta 3 metros de distancia!",
    "¡Los dientes de los conejos nunca dejan de crecer!",
    "¡Los conejos mueven la nariz hasta 120 veces por minuto!",
    "¡Los conejos pueden ver casi 360 grados a su alrededor!",
    "¡Los conejos ronronean cuando están contentos!",
    "¡Los conejos bebés se llaman gazapos!",
    "¡Los conejos pueden vivir hasta 12 años!",
    "¡Los conejos dan saltos de alegría llamados binkies!",
    "¡Los conejos tienen orejas que pueden girar en todas direcciones!",
    "¡Los conejos son más activos al amanecer y al atardecer!",
    "¡Existen más de 30 razas de conejos!",
    "¡Los conejos se comunican moviendo la cola!",
    "¡Los conejos pueden correr a 55 kilómetros por hora!",
    "¡Los conejos comen sus propias cacas especiales para absorber más nutrientes!",
    "¡Las orejas de los conejos les ayudan a regular la temperatura!",
    "¡Los conejos pueden dormir con los ojos abiertos!",
    "¡Los conejos tienen 28 dientes!",
    "¡Los conejos lamen a sus amigos para mostrar cariño!",
    "¡Un grupo de conejos se llama colonia!",
    "¡Los conejos pueden ser entrenados como los perros!",
  ],
  bird: [
    "¡Algunos pájaros pueden imitar la voz humana!",
    "¡El colibrí es el único pájaro que puede volar hacia atrás!",
    "¡Los pájaros tienen huesos huecos para ser más ligeros!",
    "¡El avestruz es el pájaro más grande del mundo!",
    "¡Los pingüinos son pájaros que no pueden volar!",
    "¡Los pájaros pueden ver colores que los humanos no pueden!",
    "¡Algunos pájaros migran miles de kilómetros cada año!",
    "¡Los pájaros cantan para comunicarse y marcar territorio!",
    "¡El pájaro más pequeño del mundo es el zunzuncito!",
    "¡Los loros pueden vivir más de 80 años!",
    "¡Los flamencos son rosas por lo que comen!",
    "¡Los cuervos son tan inteligentes como un niño de 7 años!",
    "¡Los pájaros carpinteros pueden picotear 20 veces por segundo!",
    "¡Las águilas pueden ver un conejo a 3 kilómetros de distancia!",
    "¡Los búhos pueden girar la cabeza casi completamente!",
    "¡Los pájaros descienden de los dinosaurios!",
    "¡Los pelícanos usan su bolsa para pescar!",
    "¡Los kiwis son pájaros que no pueden volar y viven en Nueva Zelanda!",
    "¡Los pájaros tienen un excelente sentido del equilibrio!",
    "¡Un grupo de flamencos se llama flamboyance!",
  ],
  fish: [
    "¡Los peces pueden sentir el movimiento del agua a su alrededor!",
    "¡Algunos peces pueden vivir más de 100 años!",
    "¡El pez más rápido es el pez vela, a 110 km por hora!",
    "¡Los peces payaso viven entre las anémonas sin ser picados!",
    "¡Los caballitos de mar machos son los que tienen a los bebés!",
    "¡El tiburón ballena es el pez más grande del mundo!",
    "¡Los peces globo se inflan para asustar a los depredadores!",
    "¡Algunos peces pueden volar saltando fuera del agua!",
    "¡Los peces tienen una línea lateral que detecta vibraciones!",
    "¡El pez más pequeño del mundo mide solo 7 milímetros!",
    "¡Algunos peces cambian de color para camuflarse!",
    "¡Los peces dorados pueden vivir hasta 40 años!",
    "¡Los delfines no son peces, son mamíferos!",
    "¡Los peces linterna producen su propia luz en el fondo del mar!",
    "¡Algunos peces pueden caminar sobre la tierra!",
    "¡Los peces tienen memoria de más de 5 meses!",
    "¡El pez luna puede pesar hasta 2 toneladas!",
    "¡Los peces duermen con los ojos abiertos porque no tienen párpados!",
    "¡Los peces se comunican con sonidos y vibraciones!",
    "¡Existen más de 30 mil especies de peces en el mundo!",
  ],
  lion: [
    "¡Los leones son conocidos como el Rey de la Selva!",
    "¡El rugido de un león se escucha a 8 kilómetros de distancia!",
    "¡Los leones duermen hasta 20 horas al día!",
    "¡Las leonas son las principales cazadoras de la manada!",
    "¡Los cachorros de león tienen manchas que desaparecen al crecer!",
    "¡Los leones viven en grupos llamados manadas!",
    "¡La melena del león lo protege en las peleas!",
    "¡Los leones pueden correr a 80 kilómetros por hora!",
    "¡Los leones se saludan frotando las cabezas!",
    "¡Un león puede comer 40 kilos de carne de una vez!",
    "¡Los leones pueden saltar hasta 11 metros de distancia!",
    "¡Los leones tienen garras retráctiles como los gatos!",
    "¡Los bigotes del león le ayudan a orientarse en la oscuridad!",
    "¡Los leones machos protegen el territorio de la manada!",
    "¡Los cachorros de león juegan para aprender a cazar!",
    "¡Los leones pueden vivir hasta 15 años en la naturaleza!",
    "¡Los leones blancos existen pero son muy raros!",
    "¡Los leones reconocen las voces de otros leones!",
    "¡Los leones se comunican con rugidos, gruñidos y maullidos!",
    "¡Los leones son los felinos más sociables del mundo!",
  ],
  turtle: [
    "¡Algunas tortugas pueden vivir más de 150 años!",
    "¡Las tortugas existen desde la época de los dinosaurios!",
    "¡El caparazón de la tortuga es parte de su esqueleto!",
    "¡Las tortugas marinas viajan miles de kilómetros para poner huevos!",
    "¡Las tortugas no tienen dientes, usan un pico!",
    "¡Las tortugas bebés encuentran el mar siguiendo la luz de la luna!",
    "¡Algunas tortugas pueden respirar por el trasero!",
    "¡Las tortugas esconden la cabeza cuando tienen miedo!",
    "¡Las tortugas pueden sentir cuando tocan su caparazón!",
    "¡La tortuga más grande del mundo es la tortuga laúd!",
    "¡Las tortugas de tierra comen frutas, flores y hojas!",
    "¡Las tortugas marinas pueden aguantar la respiración por horas!",
    "¡La tortuga más antigua conocida vivió 188 años!",
    "¡Las tortugas tienen un excelente sentido de la orientación!",
    "¡Algunas tortugas hibernan durante el invierno!",
    "¡Las tortugas pueden oír vibraciones aunque no oyen muy bien!",
    "¡Las tortugas marinas lloran para eliminar el exceso de sal!",
    "¡El sexo de las tortugas depende de la temperatura del nido!",
    "¡Las tortugas se calientan tomando el sol!",
    "¡Las tortugas son reptiles, no anfibios!",
  ],
  butterfly: [
    "¡Las mariposas prueban la comida con los pies!",
    "¡Algunas mariposas migran miles de kilómetros!",
    "¡Las alas de las mariposas están cubiertas de escamas diminutas!",
    "¡Las mariposas pueden ver colores que los humanos no pueden!",
    "¡Las mariposas beben néctar con una lengua en forma de espiral!",
    "¡Las orugas se transforman en mariposas dentro de un capullo!",
    "¡Existen más de 20 mil especies de mariposas!",
    "¡Las mariposas no pueden volar si tienen frío!",
    "¡La mariposa monarca viaja 4 mil kilómetros cada año!",
    "¡Las mariposas viven de 2 semanas a 11 meses!",
    "¡Algunas mariposas parecen tener ojos en las alas para asustar depredadores!",
    "¡Las mariposas huelen con sus antenas!",
    "¡Las mariposas son polinizadoras importantes de las flores!",
    "¡Las alas de las mariposas son transparentes, los colores vienen de las escamas!",
    "¡Las mariposas toman el sol para calentar sus alas!",
    "¡La mariposa más grande tiene una envergadura de 30 centímetros!",
    "¡Las mariposas pueden volar a 20 kilómetros por hora!",
    "¡Algunas mariposas imitan a otras venenosas para protegerse!",
    "¡Las mariposas adultas no crecen, nacen con su tamaño final!",
    "¡Las mariposas tienen cuatro alas, no dos!",
  ],
  frog: [
    "¡Las ranas pueden absorber agua a través de la piel!",
    "¡Algunas ranas son tan venenosas que pueden ser letales!",
    "¡Las ranas tragan la comida con los ojos, ¡los empujan hacia adentro!!",
    "¡Los renacuajos respiran bajo el agua como los peces!",
    "¡Algunas ranas pueden congelarse en invierno y revivir en primavera!",
    "¡Las ranas croaban antes de que existieran los dinosaurios!",
    "¡La rana más pequeña cabe en la uña del pulgar!",
    "¡Las ranas pueden saltar hasta 20 veces su propia longitud!",
    "¡Algunas ranas llevan a sus renacuajos en la espalda!",
    "¡Existen ranas de colores brillantes en la selva tropical!",
    "¡Las ranas mudan de piel y se la comen!",
    "¡Las ranas tienen dientes diminutos en el maxilar superior!",
    "¡El canto de las ranas es único para cada especie!",
    "¡Algunas ranas pueden planear entre los árboles!",
    "¡Las ranas tienen una lengua pegajosa que atrapa insectos en milisegundos!",
    "¡La rana gigante puede medir hasta 30 centímetros!",
    "¡Las ranas beben agua absorbida por un parche en la barriga!",
    "¡Algunas ranas cuidan sus huevos hasta que eclosionan!",
    "¡Las ranas pueden ver en casi todas las direcciones al mismo tiempo!",
    "¡Las ranas son indicadores de la salud del medio ambiente!",
  ],
  horse: [
    "¡Los caballos pueden dormir de pie!",
    "¡Los caballos pueden correr pocas horas después de nacer!",
    "¡Los ojos de los caballos son de los más grandes entre los mamíferos!",
    "¡Los caballos pueden ver casi 360 grados a su alrededor!",
    "¡Los caballos se comunican con las orejas y las expresiones faciales!",
    "¡Un caballo puede vivir hasta 30 años!",
    "¡Los caballos tienen una memoria increíble!",
    "¡Los cascos de los caballos están hechos del mismo material que nuestras uñas!",
    "¡Los caballos no pueden vomitar!",
    "¡Los caballos pueden correr a 70 kilómetros por hora!",
    "¡Los caballos beben hasta 40 litros de agua al día!",
    "¡Hay más de 300 razas de caballos en el mundo!",
    "¡Los caballos bebés se llaman potros!",
    "¡Los caballos tienen un campo de visión de casi 360 grados!",
    "¡Los caballos pueden sentir las emociones de las personas!",
    "¡Los dientes del caballo ocupan más espacio que su cerebro!",
    "¡Los caballos duermen solo 2 a 3 horas al día!",
    "¡Los caballos pueden mover cada oreja independientemente!",
    "¡Los caballos sonríen levantando el labio para oler mejor!",
    "¡Los caballos fueron domesticados hace más de 5 mil años!",
  ],
  owl: [
    "¡Los búhos pueden girar la cabeza hasta 270 grados!",
    "¡Los búhos tienen los ojos fijos, no pueden moverlos!",
    "¡Los búhos vuelan casi sin hacer ruido!",
    "¡Los búhos pueden escuchar un ratón bajo la nieve!",
    "¡Los búhos tienen tres párpados en cada ojo!",
    "¡Los búhos tragan la presa entera!",
    "¡Los búhos tienen plumas especiales que amortiguan el sonido!",
    "¡Un grupo de búhos se llama parlamento!",
    "¡Los búhos pueden ver muy bien en la oscuridad!",
    "¡El búho más pequeño del mundo mide solo 13 centímetros!",
    "¡Los búhos existen desde hace 60 millones de años!",
    "¡Los búhos no tienen orejas visibles, pero oyen increíblemente bien!",
    "¡Las crías de búho se llaman polluelos!",
    "¡Los búhos regurgitan bolitas con huesos de sus presas!",
    "¡Los búhos son símbolo de sabiduría en muchas culturas!",
    "¡Los búhos pueden detectar presas en completa oscuridad solo con el oído!",
    "¡Existen más de 200 especies de búhos!",
    "¡Los búhos nevados tienen plumas en las patas para no pasar frío!",
    "¡Los búhos parpadean cerrando el párpado de arriba hacia abajo!",
    "¡Los búhos son grandes cazadores nocturnos!",
  ],
  penguin: [
    "¡Los pingüinos no pueden volar, pero nadan increíblemente bien!",
    "¡Los pingüinos emperador pueden aguantar temperaturas de -60 grados!",
    "¡Los pingüinos se deslizan sobre la barriga en el hielo!",
    "¡Los pingüinos papá incuban el huevo sobre sus pies!",
    "¡Los pingüinos pueden beber agua salada!",
    "¡Los pingüinos se reconocen por su canto!",
    "¡Los pingüinos pueden nadar a 35 kilómetros por hora!",
    "¡Existen 18 especies de pingüinos en el mundo!",
    "¡Los pingüinos viven solo en el hemisferio sur!",
    "¡Los pingüinos tienen plumas impermeables!",
    "¡Los pingüinos se abrazan para mantener el calor!",
    "¡El pingüino más grande es el emperador, con casi 1,2 metros!",
    "¡Los pingüinos pueden bucear a más de 500 metros de profundidad!",
    "¡Los pingüinos dan piedras como regalo a su pareja!",
    "¡Los pingüinos mudan todas sus plumas una vez al año!",
    "¡Los pingüinos bebés tienen plumas suaves y esponjosas!",
    "¡Los pingüinos son muy sociables y viven en grandes colonias!",
    "¡Los pingüinos pueden aguantar la respiración hasta 20 minutos!",
    "¡Los pingüinos saltan fuera del agua como delfines!",
    "¡Los pingüinos Adelia construyen nidos con piedras!",
  ],
  monkey: [
    "¡Los monos usan herramientas como piedras para abrir nueces!",
    "¡Los monos viven en grupos con reglas sociales!",
    "¡Los monos aulladores se escuchan a 5 kilómetros de distancia!",
    "¡Los monos se acicalan unos a otros para hacer amigos!",
    "¡Los monos capuchinos son de los más inteligentes del mundo!",
    "¡Los monos pueden reconocerse en el espejo!",
    "¡Existen más de 260 especies de monos!",
    "¡Algunos monos tienen cola prensil que funciona como una mano extra!",
    "¡Los monos se comunican con sonidos, gestos y expresiones!",
    "¡Los monos tití son tan pequeños que caben en un dedo!",
    "¡Los monos pueden aprender lenguaje de señas!",
    "¡Los monos araña pueden columpiarse entre árboles a gran velocidad!",
    "¡Los monos bostezan cuando están nerviosos!",
    "¡Los monos narigudos tienen narices enormes que amplifican sus gritos!",
    "¡Los monos bebés se agarran a la barriga de su mamá!",
    "¡Los monos japoneses se bañan en aguas termales!",
    "¡Los monos tienen huellas dactilares como los humanos!",
    "¡Los monos pueden contar y entender cantidades!",
    "¡Los monos juegan entre ellos como los niños!",
    "¡Los monos viven en todos los continentes excepto Europa y Antártida!",
  ],
  giraffe: [
    "¡Las jirafas son los animales más altos del mundo!",
    "¡La lengua de la jirafa mide hasta 50 centímetros!",
    "¡Las jirafas duermen solo 30 minutos al día!",
    "¡Cada jirafa tiene un patrón de manchas único!",
    "¡Las jirafas bebés caen 2 metros al nacer y ya se ponen de pie!",
    "¡El corazón de una jirafa pesa 11 kilos!",
    "¡Las jirafas pueden correr a 55 kilómetros por hora!",
    "¡Las jirafas pelean golpeándose con el cuello!",
    "¡La lengua de la jirafa es azul oscuro!",
    "¡Las jirafas pueden pasar semanas sin beber agua!",
    "¡Las jirafas tienen la misma cantidad de vértebras en el cuello que nosotros: 7!",
    "¡Las jirafas comen hasta 35 kilos de hojas al día!",
    "¡Las jirafas bebés pueden caminar una hora después de nacer!",
    "¡Las jirafas se comunican con sonidos que no podemos oír!",
    "¡Las manchas de la jirafa le ayudan a regular la temperatura!",
    "¡Las jirafas tienen cuernos cubiertos de piel llamados osiconos!",
    "¡Las jirafas hembra eligen al macho más alto!",
    "¡Las jirafas pueden vivir hasta 25 años!",
    "¡Las jirafas se limpian las orejas con su propia lengua!",
    "¡Un grupo de jirafas se llama torre!",
  ],
  bear: [
    "¡Los osos pueden oler comida a 30 kilómetros de distancia!",
    "¡Los osos polares tienen la piel negra debajo del pelo blanco!",
    "¡Los osos hibernan durante el invierno!",
    "¡Los osos pueden correr a 55 kilómetros por hora!",
    "¡Los osos panda comen bambú casi todo el día!",
    "¡Los osos bebés nacen ciegos y sin pelo!",
    "¡Los osos son excelentes nadadores!",
    "¡Los osos pardos pueden pesar hasta 600 kilos!",
    "¡Los osos tienen un excelente sentido del olfato!",
    "¡Los osos polares pueden nadar durante días sin parar!",
    "¡Los koalas no son osos, son marsupiales!",
    "¡Los osos pueden caminar erguidos sobre dos patas!",
    "¡Los osos negros pueden trepar árboles fácilmente!",
    "¡Los osos viven en todos los continentes excepto África y Australia!",
    "¡Los osos tienen garras que pueden medir hasta 10 centímetros!",
    "¡Los osos son muy inteligentes y tienen buena memoria!",
    "¡Los osos se rascan contra los árboles para marcar territorio!",
    "¡Los osos polares son casi invisibles en las cámaras infrarrojas!",
    "¡Los cachorros de oso se quedan con su mamá hasta 3 años!",
    "¡Los osos pueden vivir hasta 30 años en la naturaleza!",
  ],
  dolphin: [
    "¡Los delfines duermen con un ojo abierto!",
    "¡Los delfines se comunican con clics y silbidos!",
    "¡Los delfines pueden nadar a 55 kilómetros por hora!",
    "¡Los delfines tienen nombres propios entre ellos!",
    "¡Los delfines son tan inteligentes como los primates!",
    "¡Los delfines pueden aguantar la respiración hasta 15 minutos!",
    "¡Los delfines viven en grupos llamados manadas!",
    "¡Los delfines ayudan a otros delfines heridos a llegar a la superficie!",
    "¡Los delfines usan la ecolocalización para encontrar comida!",
    "¡Los delfines saltan fuera del agua por diversión!",
    "¡Los delfines pueden reconocerse en el espejo!",
    "¡Existen más de 40 especies de delfines!",
    "¡Los delfines tienen hasta 250 dientes!",
    "¡Los delfines nariz de botella son los más conocidos!",
    "¡Los delfines pueden sentir los campos magnéticos de la tierra!",
    "¡Los delfines juegan con algas y otros objetos como juguetes!",
    "¡Los delfines tienen la piel suave como la goma!",
    "¡Los delfines bebés nacen con la cola primero!",
    "¡Los delfines pueden vivir hasta 50 años!",
    "¡Los delfines son mamíferos, no peces!",
  ],
  snake: [
    "¡Las serpientes huelen con la lengua!",
    "¡Algunas serpientes pueden volar planeando entre árboles!",
    "¡Las serpientes no tienen párpados!",
    "¡Las serpientes mudan de piel varias veces al año!",
    "¡Algunas serpientes pueden comer presas más grandes que su cabeza!",
    "¡Las serpientes sienten vibraciones en el suelo!",
    "¡Existen más de 3 mil especies de serpientes!",
    "¡La mayoría de las serpientes no son venenosas!",
    "¡Las serpientes no pueden masticar, tragan la comida entera!",
    "¡La serpiente más larga del mundo mide 10 metros!",
    "¡Las serpientes son sordas al sonido aéreo pero sienten las vibraciones!",
    "¡Algunas serpientes pueden pasar un año sin comer!",
    "¡Las serpientes tienen cientos de costillas!",
    "¡Las serpientes huelen en estéreo con su lengua bífida!",
    "¡Las serpientes se deslizan usando sus escamas!",
    "¡Algunas serpientes cuidan sus huevos hasta que eclosionan!",
    "¡Las serpientes no tienen patas, pero algunas tienen vestigios!",
    "¡Las serpientes pueden desencajar la mandíbula para tragar presas grandes!",
    "¡Las serpientes bebé ya son independientes al nacer!",
    "¡Las serpientes existen desde hace 100 millones de años!",
  ],
  bee: [
    "¡Las abejas visitan hasta 5 mil flores en un día!",
    "¡Las abejas danzan para decirle a las demás dónde hay flores!",
    "¡La miel nunca se echa a perder!",
    "¡Las abejas baten las alas 200 veces por segundo!",
    "¡La abeja reina puede poner hasta 2 mil huevos al día!",
    "¡Las abejas tienen cinco ojos!",
    "¡Las abejas producen cera para construir sus panales!",
    "¡Las abejas son responsables de polinizar un tercio de nuestra comida!",
    "¡Las abejas pueden reconocer caras humanas!",
    "¡Las abejas obreras viven solo 6 semanas!",
    "¡Las abejas se comunican con feromonas y danzas!",
    "¡Una colmena puede tener hasta 60 mil abejas!",
    "¡Las abejas necesitan visitar 2 millones de flores para hacer un kilo de miel!",
    "¡Las abejas pueden volar a 25 kilómetros por hora!",
    "¡Las abejas tienen pelos en los ojos para recoger polen!",
    "¡Las abejas regulan la temperatura de la colmena!",
    "¡Las abejas zumban en la nota de Do!",
    "¡Las abejas son los insectos más importantes para la agricultura!",
    "¡Las abejas hacen miel desde hace 150 millones de años!",
    "¡Las abejas duermen de 5 a 8 horas por noche!",
  ],
  pig: [
    "¡Los cerdos son tan inteligentes como los perros!",
    "¡Los cerdos no sudan, por eso se revuelcan en el barro!",
    "¡Los cerdos tienen un excelente sentido del olfato!",
    "¡Los cerdos pueden aprender trucos y jugar videojuegos!",
    "¡Los cerdos se comunican con más de 20 sonidos diferentes!",
    "¡Los cerdos sueñan mientras duermen!",
    "¡Los cerditos recién nacidos reconocen la voz de su mamá!",
    "¡Los cerdos pueden correr a 18 kilómetros por hora!",
    "¡Los cerdos tienen una memoria excelente!",
    "¡Los cerdos son animales muy limpios!",
    "¡Los cerdos pueden ser entrenados para buscar trufas!",
    "¡Los cerdos tienen hasta 44 dientes!",
    "¡Los cerdos pueden nadar muy bien!",
    "¡Los cerdos reconocen sus nombres!",
    "¡Los cerdos tienen la piel sensible y les gusta que les rasquen!",
    "¡Los cerdos viven en grupos llamados piaras!",
    "¡Los cerdos existen desde hace 40 millones de años!",
    "¡Los cerdos pueden aprender tan rápido como los chimpancés!",
    "¡A los cerdos les encanta que les rasquen la barriga!",
    "¡Los cerdos salvajes se llaman jabalíes!",
  ],
  panda: [
    "¡Los pandas gigantes comen bambú hasta 14 horas al día!",
    "¡Un panda adulto puede comer 38 kilos de bambú al día!",
    "¡Los pandas bebés nacen rosados y sin pelo!",
    "¡Los pandas tienen un hueso especial en la muñeca que funciona como pulgar!",
    "¡Los pandas gigantes viven en las montañas de China!",
    "¡Los pandas pasan la mayor parte del tiempo comiendo y durmiendo!",
    "¡Los pandas son excelentes nadadores!",
    "¡Los pandas marcan territorio frotándose contra los árboles!",
    "¡Un panda bebé pesa solo 100 gramos al nacer!",
    "¡Los pandas tienen una dieta casi 100% vegetariana!",
    "¡Los pandas viven entre 20 y 30 años en la naturaleza!",
    "¡Los pandas son excelentes trepadores de árboles!",
    "¡El pelaje blanco y negro del panda ayuda en el camuflaje!",
    "¡Los pandas tienen mandíbulas superfuertes para masticar bambú!",
    "¡Los pandas gigantes son solitarios y prefieren vivir solos!",
    "¡Los pandas bebés se quedan con su madre hasta 2 años!",
    "¡Los pandas fueron retirados de la lista de especies en peligro!",
    "¡Los pandas hacen sonidos como balidos de oveja para comunicarse!",
    "¡Los pandas tienen pupilas verticales, como los gatos!",
    "¡El panda es el símbolo de la conservación de la naturaleza!",
  ],
  koala: [
    "¡Los koalas duermen hasta 22 horas al día!",
    "¡Los koalas se alimentan casi exclusivamente de hojas de eucalipto!",
    "¡Las huellas digitales de los koalas son casi iguales a las humanas!",
    "¡Los koalas bebés se quedan en la bolsa de la mamá por 6 meses!",
    "¡Los koalas rara vez beben agua, se hidratan con las hojas!",
    "¡Los koalas tienen dos pulgares en cada mano para agarrarse mejor!",
    "¡Los koalas no son osos, son marsupiales!",
    "¡Los koalas solo viven en Australia!",
    "¡Los koalas tienen una nariz grande para oler las mejores hojas!",
    "¡Los koalas bebés comen una pasta especial que produce la mamá!",
    "¡Los koalas pueden vivir hasta 18 años en la naturaleza!",
    "¡Los koalas tienen pelaje grueso y suave que los protege de la lluvia!",
    "¡Los koalas se abrazan a los árboles para refrescarse!",
    "¡Los koalas machos marcan territorio frotando el pecho en los árboles!",
    "¡Los koalas tienen un cerebro pequeño en relación a su cuerpo!",
    "¡Los koalas hacen sonidos graves y fuertes para comunicarse!",
    "¡Los koalas comen cerca de 500 gramos de hojas al día!",
    "¡Los koalas son animales nocturnos, más activos de noche!",
    "¡Los koalas tienen garras afiladas para trepar árboles!",
    "¡Los koalas son uno de los animales más queridos de Australia!",
  ],
  zebra: [
    "¡Cada cebra tiene un patrón de rayas único, como huellas digitales!",
    "¡Las rayas de la cebra ayudan a confundir a los depredadores!",
    "¡Las cebras duermen de pie, como los caballos!",
    "¡Los potros de cebra pueden caminar minutos después de nacer!",
    "¡Las cebras viven en grupos llamados manadas!",
    "¡Las cebras pueden correr hasta 65 kilómetros por hora!",
    "¡Las cebras se saludan tocándose la nariz!",
    "¡Las cebras son parientes de los caballos y los burros!",
    "¡Las cebras migran cientos de kilómetros!",
    "¡Las rayas de las cebras pueden espantar moscas e insectos!",
    "¡Las cebras tienen una excelente visión nocturna!",
    "¡Los potros reconocen a su madre por el patrón de rayas!",
    "¡Las cebras se protegen quedándose en grupo!",
    "¡Las cebras pueden vivir hasta 25 años en la naturaleza!",
    "¡Las cebras usan las orejas para mostrar su estado de ánimo!",
    "¡Las cebras comen pasto y hierbas durante muchas horas al día!",
    "¡Las cebras beben agua al menos una vez al día!",
    "¡Las cebras pueden dar patadas poderosas para defenderse!",
    "¡Las cebras viven en las sabanas y llanuras de África!",
    "¡Existen tres especies de cebras en el mundo!",
  ],
  shark: [
    "¡Los tiburones existen desde hace más de 400 millones de años!",
    "¡Los tiburones tienen filas de dientes que se renuevan toda la vida!",
    "¡El tiburón ballena es el pez más grande y come plancton!",
    "¡Los tiburones pueden detectar una gota de sangre a kilómetros!",
    "¡Los tiburones no tienen huesos, su esqueleto es de cartílago!",
    "¡Existen más de 500 especies de tiburones en el mundo!",
    "¡Los tiburones necesitan nadar para respirar!",
    "¡Los tiburones tienen una visión excelente, incluso en la oscuridad!",
    "¡Los tiburones bebés ya nacen sabiendo nadar!",
    "¡El tiburón martillo tiene la cabeza en forma de T!",
    "¡Los tiburones pueden detectar campos eléctricos de otros animales!",
    "¡El gran tiburón blanco puede saltar fuera del agua para cazar!",
    "¡Algunos tiburones viven en aguas muy profundas del océano!",
    "¡Los tiburones ayudan a mantener el equilibrio de los océanos!",
    "¡Los tiburones tienen una piel áspera como lija!",
    "¡El tiburón linterna brilla en la oscuridad!",
    "¡Los tiburones pueden vivir hasta 70 años o más!",
    "¡Los tiburones nadan hasta 50 kilómetros por hora!",
    "¡Los tiburones pierden y reponen miles de dientes en su vida!",
    "¡La mayoría de los tiburones son inofensivos para los humanos!",
  ],
  whale: [
    "¡La ballena azul es el animal más grande que ha existido!",
    "¡El corazón de una ballena azul es del tamaño de un coche!",
    "¡Las ballenas se comunican con cantos que viajan miles de kilómetros!",
    "¡Las ballenas jorobadas hacen acrobacias saltando fuera del agua!",
    "¡Las ballenas pueden aguantar la respiración por más de una hora!",
    "¡Los ballenatos beben cientos de litros de leche al día!",
    "¡Las ballenas migran miles de kilómetros cada año!",
    "¡La lengua de una ballena azul pesa tanto como un elefante!",
    "¡Las ballenas duermen con la mitad del cerebro despierto!",
    "¡Los cachalotes bucean a más de 2.000 metros de profundidad!",
    "¡Las ballenas son mamíferos, no peces!",
    "¡Una ballena azul puede medir 30 metros de largo!",
    "¡Las ballenas tienen pelos en el cuerpo, generalmente en la barbilla!",
    "¡Los ballenatos nacen por la cola para no ahogarse!",
    "¡El canto de la ballena jorobada puede durar horas!",
    "¡Las ballenas viven en todos los océanos del mundo!",
    "¡Algunas ballenas pueden vivir hasta 200 años!",
    "¡Las ballenas lanzan chorros de agua por el espiráculo!",
    "¡Las ballenas forman lazos fuertes con sus crías!",
    "¡La ballena azul come hasta 4 toneladas de krill al día!",
  ],
  crocodile: [
    "¡Los cocodrilos existen desde hace más de 200 millones de años!",
    "¡Los cocodrilos pueden quedarse quietos horas esperando una presa!",
    "¡Los cocodrilos tienen la mordida más fuerte de todos los animales!",
    "¡Los cocodrilos lloran mientras comen, pero no de tristeza!",
    "¡Los cocodrilos pueden vivir hasta 70 años!",
    "¡El cocodrilo de agua salada es el reptil más grande del mundo!",
    "¡Los cocodrilos pueden nadar a 30 kilómetros por hora!",
    "¡Los bebés cocodrilos hacen sonidos dentro del huevo para avisar a la mamá!",
    "¡Los cocodrilos tragan piedras para ayudar en la digestión!",
    "¡La temperatura del nido determina el sexo de los bebés!",
    "¡Los cocodrilos pueden aguantar la respiración por más de una hora!",
    "¡Los cocodrilos tienen 80 dientes y los cambian toda la vida!",
    "¡Los cocodrilos viven en agua dulce y salada!",
    "¡La mamá cocodrilo lleva a los bebés en la boca con cuidado!",
    "¡Los ojos de los cocodrilos brillan en la oscuridad!",
    "¡Los cocodrilos regulan su temperatura tomando sol!",
    "¡Los cocodrilos son parientes de los dinosaurios!",
    "¡Los cocodrilos pueden correr rápido en tierra por cortas distancias!",
    "¡Los cocodrilos tienen una audición excelente!",
    "¡Los cocodrilos pueden pasar meses sin comer!",
  ],
  fox: [
    "¡Los zorros usan el campo magnético de la Tierra para cazar!",
    "¡Los zorros son parientes de los perros y los lobos!",
    "¡Los zorros tienen bigotes en las patas para orientarse!",
    "¡Los zorros pueden oír animales debajo de la nieve!",
    "¡Los zorros viven en todos los continentes excepto la Antártida!",
    "¡Los zorros son nocturnos y cazan de noche!",
    "¡El zorro ártico cambia de color según la estación!",
    "¡Los zorros hacen más de 40 sonidos diferentes!",
    "¡Los zorros son muy ágiles y pueden escalar cercas!",
    "¡Los zorros viven en madrigueras!",
    "¡Los cachorros de zorro nacen sordos y ciegos!",
    "¡Los zorros tienen pupilas verticales, como los gatos!",
    "¡Los zorros pueden correr a 50 kilómetros por hora!",
    "¡Los zorros son animales solitarios la mayor parte del tiempo!",
    "¡La cola del zorro sirve para mantener el equilibrio y el calor!",
    "¡Los zorros esconden comida para comerla después!",
    "¡Los cachorros de zorro juegan mucho de pequeños!",
    "¡Los zorros tienen un olfato increíble para encontrar comida!",
    "¡Los zorros pueden vivir hasta 14 años!",
    "¡El zorro fénec tiene las orejas más grandes en relación a su cuerpo!",
  ],
  duck: [
    "¡Los patos tienen plumas impermeables!",
    "¡Los patos pueden dormir con un ojo abierto!",
    "¡Los patitos siguen lo primero que ven al nacer!",
    "¡Los patos tienen 3 párpados en cada ojo!",
    "¡Los patos no sienten frío en los pies, incluso en agua helada!",
    "¡Los patos pueden volar hasta 80 kilómetros por hora!",
    "¡Los patos hacen cuac, pero el sonido no hace eco!",
    "¡Los patitos pueden nadar horas después de nacer!",
    "¡Los patos comen peces, insectos, plantas y semillas!",
    "¡Los patos migran a lugares más cálidos en invierno!",
    "¡Los patos machos son más coloridos que las hembras!",
    "¡Los patos nadan usando los pies como remos!",
    "¡Los patos pueden bucear para buscar comida en el fondo!",
    "¡Existen más de 120 especies de patos en el mundo!",
    "¡Los patos viven en todos los continentes excepto la Antártida!",
    "¡Los patos son aves muy sociales y viven en grupos!",
    "¡Los patos cambian todas las plumas una vez al año!",
    "¡Los patos ven los colores mejor que los humanos!",
    "¡Los patos pueden vivir hasta 20 años!",
    "¡Los patitos ya saben nadar en su primer día de vida!",
  ],
  octopus: [
    "¡Los pulpos tienen 3 corazones y sangre azul!",
    "¡Los pulpos pueden cambiar de color en menos de un segundo!",
    "¡Los pulpos son los invertebrados más inteligentes!",
    "¡Los pulpos tienen 8 brazos, cada uno con ventosas!",
    "¡Los pulpos pueden abrir frascos y resolver rompecabezas!",
    "¡Los pulpos no tienen huesos y pueden pasar por cualquier lugar!",
    "¡Los pulpos lanzan tinta para escapar de depredadores!",
    "¡Cada brazo del pulpo tiene su propio mini-cerebro!",
    "¡Los pulpos pueden regenerar brazos perdidos!",
    "¡El pulpo mimético imita la apariencia de otros animales!",
    "¡Los pulpos viven en el fondo del océano, en guaridas!",
    "¡Los pulpos son maestros del camuflaje!",
    "¡El pulpo de anillos azules es uno de los animales más venenosos!",
    "¡Las pulpos hembra cuidan los huevos sin comer hasta que nacen!",
    "¡Los pulpos tienen una visión excelente!",
    "¡Los pulpos usan conchas y cocos como refugio!",
    "¡Los pulpos nadan expulsando chorros de agua!",
    "¡Existen más de 300 especies de pulpos en el mundo!",
    "¡Los pulpos viven solo 1 a 2 años en promedio!",
    "¡Los pulpos prueban la comida con las ventosas de sus brazos!",
  ],
  tiger: [
    "¡El tigre es el felino más grande del mundo!",
    "¡Cada tigre tiene rayas únicas, como huellas digitales!",
    "¡A los tigres les encanta nadar y jugar en el agua!",
    "¡Los tigres pueden correr hasta 65 kilómetros por hora!",
    "¡Los tigres cazan solos, generalmente de noche!",
    "¡Un tigre puede comer 40 kilos de carne de una vez!",
    "¡Los cachorros de tigre se quedan con la madre hasta 3 años!",
    "¡Los tigres rugen tan fuerte que se oyen a 3 kilómetros!",
    "¡Existen 6 subespecies de tigres en el mundo!",
    "¡Los tigres marcan territorio con arañazos en los árboles!",
    "¡Los tigres tienen garras retráctiles que se esconden al caminar!",
    "¡El tigre siberiano es el más grande, puede pesar 300 kilos!",
    "¡Los tigres pueden saltar hasta 5 metros de altura!",
    "¡Los tigres tienen visión nocturna 6 veces mejor que la humana!",
    "¡Los tigres son animales solitarios y territoriales!",
    "¡Las rayas de los tigres también existen en la piel, no solo en el pelo!",
    "¡Los tigres blancos son raros y tienen rayas claras!",
    "¡Los tigres pueden nadar varios kilómetros!",
    "¡Los tigres se encuentran en Asia!",
    "¡Los tigres están en peligro de extinción y necesitan protección!",
  ],
};
