import type { AnimalId } from "./animals";

export const animalFunFactsDe: Record<AnimalId, string[]> = {
  cat: [
    "Katzen schlafen bis zu 16 Stunden am Tag!",
    "Katzen können ihre Ohren um 180 Grad drehen!",
    "Eine Katze kann bis zum Sechsfachen ihrer Körperlänge springen!",
    "Katzen haben über 20 verschiedene Arten zu miauen!",
    "Jeder Katzennasenabdruck ist einzigartig, wie ein menschlicher Fingerabdruck!",
    "Katzen können im Dunkeln sehen!",
    "Katzen verbringen 30% des Tages mit Fellpflege!",
    "Eine Katze hat 230 Knochen, mehr als Menschen!",
    "Die Schnurrhaare einer Katze helfen zu messen, ob sie in enge Räume passt!",
    "Katzen schnurren, wenn sie glücklich sind, aber auch um sich selbst zu heilen!",
    "Katzen können 48 Kilometer pro Stunde laufen!",
    "Hauskatzen gibt es seit über 10.000 Jahren!",
    "Eine Katze kann Geräusche hören, die wir nicht hören können!",
    "Katzen landen dank ihres erstaunlichen Gleichgewichts immer auf den Pfoten!",
    "Katzen reiben ihr Gesicht an Dingen, um ihr Revier zu markieren!",
    "Die älteste Katze der Welt wurde 38 Jahre alt!",
    "Katzen haben ein verstecktes drittes Augenlid!",
    "Katzen bevorzugen fließendes Wasser gegenüber stehendem Wasser!",
    "Katzen können Erdbeben spüren, bevor Menschen es können!",
    "Eine Gruppe von Katzen nennt man eine Kolonie!",
  ],
  dog: [
    "Der Geruchssinn eines Hundes ist 40-mal besser als der des Menschen!",
    "Hunde können über 100 Wörter lernen!",
    "Der schnellste Hund kann 70 km pro Stunde laufen!",
    "Hunde träumen im Schlaf, genau wie wir!",
    "Die Nase eines Hundes ist feucht, um Gerüche besser aufzunehmen!",
    "Hunde wedeln mit dem Schwanz nach rechts, wenn sie glücklich sind!",
    "Hunde sehen in Blau- und Gelbtönen!",
    "Das Gehör von Hunden ist viermal besser als unseres!",
    "Der älteste Hund der Welt wurde 30 Jahre alt!",
    "Hunde gähnen, wenn sie jemanden gähnen sehen, aus Empathie!",
    "Ein Hund kann die Stimmung seines Besitzers am Geruch erkennen!",
    "Es gibt über 340 Hunderassen auf der Welt!",
    "Hunde schwitzen nur über ihre Pfoten!",
    "Hundewelpen werden taub und blind geboren!",
    "Der Labrador ist die beliebteste Hunderasse der Welt!",
    "Hunde können Krankheiten bei Menschen erschnüffeln!",
    "Ein erwachsener Hund hat 42 Zähne!",
    "Hunde drehen sich im Kreis, bevor sie sich hinlegen, aus Instinkt!",
    "Hunde können Geräusche aus 225 Metern Entfernung hören!",
    "Drei Hunde überlebten den Untergang der Titanic!",
  ],
  elephant: [
    "Elefanten sind die größten Landtiere der Welt!",
    "Elefanten können sich im Spiegel erkennen!",
    "Ein Elefant trinkt bis zu 200 Liter Wasser am Tag!",
    "Elefanten haben ein unglaubliches Gedächtnis und vergessen nie einen Freund!",
    "Elefanten kommunizieren mit so tiefen Tönen, dass wir sie nicht hören können!",
    "Elefanten nehmen gerne Schlammbäder, um sich vor der Sonne zu schützen!",
    "Elefanten können bis zu 6 Tonnen wiegen!",
    "Elefanten benutzen ihren Rüssel wie einen Strohhalm zum Trinken!",
    "Ein Elefantenbaby wiegt bei der Geburt etwa 100 Kilogramm!",
    "Elefanten laufen auf Zehenspitzen!",
    "Elefanten können sehr gut schwimmen!",
    "Der Rüssel eines Elefanten hat über 40.000 Muskeln!",
    "Elefanten trauern, wenn ein Freund stirbt!",
    "Afrikanische Elefanten haben Ohren in Form von Afrika!",
    "Elefanten fressen bis zu 150 Kilogramm Futter am Tag!",
    "Elefanten leben in Familien, die von einem Weibchen angeführt werden!",
    "Elefanten begrüßen sich, indem sie ihre Rüssel verschlingen!",
    "Die Haut eines Elefanten ist bis zu 2,5 Zentimeter dick!",
    "Elefanten können Vibrationen im Boden durch ihre Füße spüren!",
    "Elefanten sind eines der wenigen Tiere, die vor Rührung weinen!",
  ],
  rabbit: [
    "Kaninchen können ihre Ohren in jede Richtung drehen!",
    "Kaninchen sind so glücklich, dass sie in die Luft springen und sich drehen! Das nennt man Binky!",
    "Die Zähne von Kaninchen hören nie auf zu wachsen!",
    "Kaninchen können fast 360 Grad um sich herum sehen!",
    "Ein Kaninchen kann 55 km pro Stunde laufen!",
    "Kaninchen schnurren, wenn sie glücklich sind, genau wie Katzen!",
    "Kaninchen haben mehr als 28 Zähne!",
    "Kaninchen bewegen ihre Nase bis zu 120 Mal pro Minute!",
    "Kaninchen sind morgens früh und abends am aktivsten!",
    "Kaninchen können bis zu 1 Meter hoch springen!",
    "Eine Gruppe von Kaninchen nennt man eine Kolonie!",
    "Kaninchen putzen sich, indem sie ihre Pfoten lecken, wie Katzen!",
    "Kaninchen leben in unterirdischen Bauten!",
    "Kaninchen können bis zu 12 Junge auf einmal bekommen!",
    "Kaninchen klopfen mit den Pfoten auf den Boden, um vor Gefahr zu warnen!",
    "Kaninchen lieben es, mit Tunneln und Kisten zu spielen!",
    "Kaninchen schlafen manchmal mit offenen Augen!",
    "Kaninchen können Tricks und ihren Namen lernen!",
    "Wildkaninchen leben auf fast allen Kontinenten!",
    "Kaninchen können bis zu 12 Jahre alt werden!",
  ],
  bird: [
    "Manche Vögel können die menschliche Stimme nachahmen!",
    "Der Kolibri ist der einzige Vogel, der rückwärts fliegen kann!",
    "Vögel sehen mehr Farben als Menschen!",
    "Der Strauß ist der schnellste laufende Vogel mit 70 km pro Stunde!",
    "Vögel singen, um zu kommunizieren und ihr Revier zu markieren!",
    "Die Federn von Vögeln sind stärker, als sie aussehen!",
    "Papageien können bis zu 80 Jahre alt werden!",
    "Der Kolibri schlägt seine Flügel bis zu 80 Mal pro Sekunde!",
    "Vögel ziehen jedes Jahr Tausende von Kilometern weit!",
    "Das Straußenei ist das größte Ei der Welt!",
    "Vögel haben hohle Knochen, damit sie leichter fliegen können!",
    "Krähen sind so intelligent, dass sie Werkzeuge benutzen!",
    "Der kleinste Vogel der Welt ist die Bienenelfe mit 5 Zentimetern!",
    "Vögel können mit einer Gehirnhälfte wach schlafen!",
    "Flamingos sind rosa wegen der Nahrung, die sie fressen!",
    "Es gibt über 10.000 Vogelarten auf der Welt!",
    "Pinguine sind Vögel, aber sie können nicht fliegen!",
    "Vögel schlucken kleine Steine, um die Verdauung zu unterstützen!",
    "Eulen können ihre Augen nicht bewegen, nur den Kopf drehen!",
    "Der Albatros kann jahrelang fliegen, ohne an Land zu gehen!",
  ],
  fish: [
    "Es gibt Fische, die in der Tiefsee leuchten!",
    "Manche Fische können über das Wasser fliegen!",
    "Der Clownfisch lebt in den Anemonen des Meeres!",
    "Fische haben keine Augenlider, sie schlafen mit offenen Augen!",
    "Der Walhai ist der größte Fisch der Welt!",
    "Manche Fische ändern ihre Farbe, um sich vor Feinden zu verstecken!",
    "Fische atmen unter Wasser mit Kiemen!",
    "Es gibt über 30.000 Fischarten auf der Welt!",
    "Das Seepferdchen ist einer der wenigen Fische, bei denen der Vater die Babys trägt!",
    "Fische können Vibrationen im Wasser mit einer Seitenlinie spüren!",
    "Der Schwertfisch kann 110 Kilometer pro Stunde schwimmen!",
    "Manche Fische leben in den dunkelsten Tiefen des Ozeans!",
    "Goldfische können sich monatelang an Dinge erinnern!",
    "Der Kugelfisch bläht sich mit Wasser auf, um größer zu wirken!",
    "Fische schwimmen in Schwärmen, um sich zu schützen!",
    "Haie gibt es seit über 400 Millionen Jahren!",
    "Manche Fische bauen Nester, um ihre Eier zu schützen!",
    "Der Mondfisch ist der schwerste Knochenfisch der Welt!",
    "Fische können das Wasser um sich herum schmecken!",
    "Der Schützenfisch spritzt Wasserstrahlen, um Insekten herunterzuschießen!",
  ],
  lion: [
    "Das Brüllen eines Löwen kann 8 Kilometer weit gehört werden!",
    "Löwen schlafen bis zu 20 Stunden am Tag!",
    "Nur männliche Löwen haben diese riesige Mähne!",
    "Die Löwinnen sind die Jägerinnen der Familie!",
    "Löwen leben in Gruppen, die man Rudel nennt!",
    "Ein Löwe kann auf kurze Distanz 80 km pro Stunde laufen!",
    "Löwenbabys werden mit Flecken geboren, die verschwinden, wenn sie wachsen!",
    "Löwen reiben ihre Köpfe aneinander, um sich zu begrüßen!",
    "Die Mähne des Löwen wird dunkler, je älter er wird!",
    "Löwen können bis zu 11 Meter weit springen!",
    "Löwen werden König des Dschungels genannt, leben aber in der Savanne!",
    "Ein Löwe kann 40 Kilogramm Fleisch auf einmal fressen!",
    "Die Schnurrhaare des Löwen helfen, die Umgebung zu spüren!",
    "Löwen ruhen in Bäumen, um der Hitze zu entkommen!",
    "Löwenbabys spielen kämpfen, um das Jagen zu lernen!",
    "Löwenmännchen beschützen das Revier, während die Weibchen jagen!",
    "Der Löwe ist die zweitgrößte Katze der Welt, nach dem Tiger!",
    "Löwen können in der Wildnis bis zu 15 Jahre alt werden!",
    "Löwen trinken Wasser, wann immer sie können, halten aber Tage ohne aus!",
    "Ein Löwe erkennt die Mitglieder seines Rudels am Brüllen!",
  ],
  turtle: [
    "Manche Schildkröten können über 100 Jahre alt werden!",
    "Der Panzer der Schildkröte ist Teil ihres Skeletts!",
    "Meeresschildkröten reisen Tausende von Kilometern durch den Ozean!",
    "Schildkröten gibt es seit über 200 Millionen Jahren!",
    "Schildkröten haben keine Zähne, sie haben einen Schnabel wie Vögel!",
    "Die Lederschildkröte ist die größte Schildkröte der Welt!",
    "Schildkröten können spüren, wenn man ihren Panzer berührt!",
    "Meeresschildkröten kehren zum Eierlegen an denselben Strand zurück, an dem sie geboren wurden!",
    "Schildkröten können stundenlang unter Wasser die Luft anhalten!",
    "Das Geschlecht von Schildkrötenbabys hängt von der Temperatur des Sandes ab!",
    "Schildkröten sehen Farben, sogar Ultraviolett!",
    "Manche Schildkröten halten Winterschlaf, im Schlamm vergraben!",
    "Die Galapagos-Riesenschildkröte kann 400 Kilogramm wiegen!",
    "Schildkröten haben einen ausgezeichneten Orientierungssinn!",
    "Schildkröten sind Reptilien, Verwandte der Dinosaurier!",
    "Meeresschildkröten weinen, um das Salz aus dem Meerwasser loszuwerden!",
    "Manche Schildkröten können durch ihren Po atmen!",
    "Haustier-Schildkröten können über 50 Jahre alt werden!",
    "Schildkröten sind die ältesten lebenden Reptilien!",
    "Schildkrötenbabys sind bei der Geburt so groß wie eine Münze!",
  ],
  butterfly: [
    "Schmetterlinge schmecken ihr Essen mit den Füßen!",
    "Ein Schmetterling beginnt sein Leben als Raupe!",
    "Es gibt über 20.000 Schmetterlingsarten auf der Welt!",
    "Die Flügel der Schmetterlinge sind durchsichtig, die Farben kommen von winzigen Schuppen!",
    "Manche Schmetterlinge wandern Tausende von Kilometern!",
    "Schmetterlinge können nicht fliegen, wenn ihnen kalt ist!",
    "Schmetterlinge trinken Nektar aus Blumen mit einem eingerollten Rüssel!",
    "Der Monarchfalter reist jedes Jahr von Kanada nach Mexiko!",
    "Schmetterlinge leben nur einige Wochen!",
    "Schmetterlinge brauchen die Sonne, um ihre Flügel aufzuwärmen und zu fliegen!",
    "Manche Schmetterlinge sehen aus, als hätten sie Augen auf den Flügeln, um Feinde abzuschrecken!",
    "Die Verwandlung von der Raupe zum Schmetterling heißt Metamorphose!",
    "Schmetterlinge sehen Farben, die Menschen nicht sehen können!",
    "Im Kokon verwandelt sich die Raupe komplett in Flüssigkeit!",
    "Manche Schmetterlinge fressen verfaulte Früchte!",
    "Schmetterlinge schlagen ihre Flügel etwa 5 Mal pro Sekunde!",
    "Schmetterlinge können bis zu 20 Kilometer pro Stunde fliegen!",
    "Der größte Schmetterling der Welt hat 30 Zentimeter Flügelspannweite!",
    "Schmetterlinge wärmen sich auf, indem sie ihre Flügel wie Sonnenkollektoren zur Sonne öffnen!",
    "Manche Schmetterlinge schmecken schlecht, damit Feinde sie nicht fressen!",
  ],
  frog: [
    "Frösche nehmen Wasser über die Haut auf, sie trinken nicht!",
    "Manche Frösche sind so giftig, dass sie einen Elefanten umwerfen könnten!",
    "Frösche schlucken ihr Essen, indem sie die Augen benutzen, um es hinunterzudrücken!",
    "Es gibt Frösche in allen Regenbogenfarben!",
    "Frösche quaken, um ein Weibchen anzulocken!",
    "Manche Frösche können im Winter einfrieren und im Frühling wieder auftauen!",
    "Frösche beginnen ihr Leben als Kaulquappen im Wasser!",
    "Frösche können bis zum 20-fachen ihrer Körpergröße springen!",
    "Die Haut von Fröschen ist immer feucht!",
    "Es gibt Frösche, die kleiner als ein Fingernagel sind!",
    "Giftige Frösche sind bunt gefärbt, um Feinde zu warnen!",
    "Manche Frösche tragen ihre Jungen auf dem Rücken!",
    "Frösche gibt es seit über 200 Millionen Jahren!",
    "Frösche können sowohl im Wasser als auch an Land leben!",
    "Der größte Frosch der Welt wiegt mehr als 3 Kilogramm!",
    "Frösche häuten sich regelmäßig und fressen die alte Haut!",
    "Die Augen der Frösche sitzen oben auf dem Kopf, um aus dem Wasser zu schauen!",
    "Frösche sind sehr wichtig für die Kontrolle von Insekten!",
    "Es gibt über 7.000 Froscharten auf der Welt!",
    "Manche Frösche machen Geräusche, die wie singende Vögel klingen!",
  ],
  horse: [
    "Pferde können im Stehen schlafen!",
    "Ein Pferd kann schon wenige Stunden nach der Geburt laufen!",
    "Pferde sehen fast 360 Grad um sich herum!",
    "Die Zähne der Pferde nehmen mehr Platz im Kopf ein als das Gehirn!",
    "Pferde können Emotionen im menschlichen Gesicht erkennen!",
    "Das schnellste Pferd der Welt erreichte 70 km pro Stunde!",
    "Pferde haben das größte Sehvermögen aller Landsäugetiere!",
    "Pferde kommunizieren mit Ohren, Augen und Gesichtsausdrücken!",
    "Ein erwachsenes Pferd hat 40 Zähne!",
    "Pferde können bis zu 30 Jahre alt werden!",
    "Pferde schlafen nur 2 bis 3 Stunden am Tag!",
    "Die Hufe der Pferde bestehen aus dem gleichen Material wie unsere Fingernägel!",
    "Pferde können am selben Tag laufen, an dem sie geboren werden!",
    "Pferde sind Pflanzenfresser und lieben Karotten und Äpfel!",
    "Ein Pferd trinkt zwischen 30 und 50 Liter Wasser am Tag!",
    "Pferde haben ein ausgezeichnetes Gedächtnis!",
    "Wildpferde leben in Herden, die von einer Stute angeführt werden!",
    "Pferde können sich nicht übergeben!",
    "Das kleinste Pferd der Welt ist nur 44 Zentimeter groß!",
    "Pferde gibt es seit über 50 Millionen Jahren!",
  ],
  owl: [
    "Eulen können ihren Kopf bis zu 270 Grad drehen!",
    "Eulen haben ein so gutes Gehör, dass sie in völliger Dunkelheit jagen!",
    "Die Augen der Eulen bewegen sich nicht, deshalb drehen sie den Kopf!",
    "Die Federn der Eulen sind lautlos, sie fliegen ohne Geräusch!",
    "Manche Eulen sind kleiner als deine Hand!",
    "Eulen verschlucken ihre Beute im Ganzen und spucken dann die Knochen aus!",
    "Eulen haben drei Augenlider an jedem Auge!",
    "Eulen können eine Maus hören, die unter dem Schnee läuft!",
    "Die Augen der Eulen sind so groß, dass sie sich nicht bewegen können!",
    "Eulen gibt es auf allen Kontinenten außer der Antarktis!",
    "Der Kaninchenkauz lebt in Erdlöchern!",
    "Eulen drehen den Kopf, weil sie ihre Augen nicht bewegen können!",
    "Es gibt über 200 Eulenarten auf der Welt!",
    "Eulen sind unglaubliche Nachtjäger!",
    "Die Schnee-Eule ist fast ganz weiß!",
    "Eulen haben superstarke Krallen, um Beute zu greifen!",
    "Eine Gruppe von Eulen nennt man ein Parlament!",
    "Eulenbabys nennt man Küken oder Nestlinge!",
    "Eulen können den Kopf in beide Richtungen drehen!",
    "Die größte Eule der Welt hat fast 2 Meter Flügelspannweite!",
  ],
  penguin: [
    "Pinguine fliegen nicht, aber sie sind hervorragende Schwimmer!",
    "Pinguine können bis zu 20 Minuten unter Wasser die Luft anhalten!",
    "Der Kaiserpinguin ist der größte von allen, fast 1 Meter groß!",
    "Pinguine leben in der Kälte, aber nicht alle leben im Schnee!",
    "Pinguine wärmen sich auf, indem sie sich in Gruppen zusammenkuscheln!",
    "Pinguineltern brüten die Eier auf ihren eigenen Füßen aus!",
    "Pinguine können 35 Kilometer pro Stunde schwimmen!",
    "Es gibt 18 Pinguinarten auf der Welt!",
    "Pinguine trinken Salzwasser und filtern das Salz heraus!",
    "Pinguine erkennen ihren Partner am Gesang!",
    "Der kleinste Pinguin der Welt ist nur 30 Zentimeter groß!",
    "Pinguine wechseln einmal im Jahr ihre Federn!",
    "Pinguine rutschen auf dem Bauch über den Schnee, um sich fortzubewegen!",
    "Pinguine sind schwarz und weiß zur Tarnung im Wasser!",
    "Pinguine können tiefer als 500 Meter tauchen!",
    "Kaiserpinguine halten Temperaturen von -60 Grad aus!",
    "Pinguine sind sehr treu und erkennen ihren Partner jedes Jahr!",
    "Pinguinküken bleiben in Krippen, während die Eltern jagen!",
    "Pinguine fressen Fische, Tintenfische und Krill!",
    "Pinguine gibt es seit über 60 Millionen Jahren!",
  ],
  monkey: [
    "Affen benutzen Werkzeuge wie Steine, um Früchte zu öffnen!",
    "Affen umarmen sich und streicheln sich, um Freundschaft zu zeigen!",
    "Der Klammeraffe benutzt seinen Schwanz wie eine zusätzliche Hand!",
    "Es gibt über 260 Affenarten auf der Welt!",
    "Affen leben in Gruppen und kümmern sich umeinander!",
    "Affen können ihr eigenes Spiegelbild erkennen!",
    "Affen lausen sich gegenseitig, um die Freundschaft zu stärken!",
    "Der kleinste Affe der Welt passt in eine Handfläche!",
    "Affen können Zeichensprache lernen!",
    "Brüllaffen kann man 5 Kilometer weit hören!",
    "Japanische Makaken baden im Winter in heißen Quellen!",
    "Kapuzineraffen gelten als die intelligentesten Affen Amerikas!",
    "Affen gähnen, wenn sie einen anderen Affen gähnen sehen!",
    "Nachtaffen sind die einzigen, die im Dunkeln gut sehen!",
    "Affen benutzen verschiedene Laute, um vor verschiedenen Feinden zu warnen!",
    "Der Nasenaffe hat die größte Nase aller Primaten!",
    "Affenbabys klammern sich am Bauch der Mutter fest, um sich fortzubewegen!",
    "Affen sind unsere nächsten Verwandten im Tierreich!",
    "Affen können in der Wildnis bis zu 40 Jahre alt werden!",
    "Affen in Amerika haben Greifschwänze, die in Afrika nicht!",
  ],
  giraffe: [
    "Die Giraffe ist das größte Tier der Welt, bis zu 6 Meter hoch!",
    "Die Zunge der Giraffe ist bis zu 50 Zentimeter lang!",
    "Jede Giraffe hat ein einzigartiges Fleckenmuster, wie Fingerabdrücke!",
    "Giraffen schlafen nur 30 Minuten am Tag!",
    "Das Herz einer Giraffe wiegt 11 Kilogramm!",
    "Giraffenbabys sind bei der Geburt schon fast 2 Meter groß!",
    "Die Zunge der Giraffe ist lila, um sie vor der Sonne zu schützen!",
    "Giraffen gehen, indem sie beide Beine der gleichen Seite gleichzeitig bewegen!",
    "Giraffen können 55 Kilometer pro Stunde laufen!",
    "Der Hals der Giraffe hat nur 7 Wirbel, genau wie unserer!",
    "Giraffen legen sich selten hin, sie schlafen sogar im Stehen!",
    "Giraffen trinken Wasser, indem sie die Vorderbeine weit spreizen!",
    "Giraffen kämpfen, indem sie ihre Hälse gegeneinander schwingen!",
    "Die Beine einer Giraffe sind allein schon 1,80 Meter lang!",
    "Giraffen haben keine Stimmbänder und sind fast lautlos!",
    "Giraffenbabys fallen bei der Geburt fast 2 Meter tief!",
    "Giraffen brauchen nur alle paar Tage Wasser zu trinken!",
    "Eine Giraffe kann mit einem einzigen Tritt einen Löwen vertreiben!",
    "Giraffen leben in Afrika, in Savannen und Wäldern!",
    "Die Hörner der Giraffe nennt man Ossikone!",
  ],
  bear: [
    "Bären können Essen auf 30 Kilometer Entfernung riechen!",
    "Eisbären haben schwarze Haut unter dem weißen Fell!",
    "Bären können auf Bäume klettern, obwohl sie sehr schwer sind!",
    "Braunbären schlafen den ganzen Winter im Winterschlaf!",
    "Bären können 55 Kilometer pro Stunde laufen!",
    "Der Pandabär frisst den ganzen Tag Bambus!",
    "Bären sind ausgezeichnete Schwimmer!",
    "Es gibt 8 Bärenarten auf der Welt!",
    "Der Eisbär ist das größte Landraubtier der Welt!",
    "Bärenbabys werden blind und fast haarlos geboren!",
    "Der Koala ist kein Bär, sondern ein Beuteltier!",
    "Braunbären können 2,5 Meter groß werden, wenn sie aufstehen!",
    "Bären haben einen besseren Geruchssinn als Hunde!",
    "Im Winterschlaf sinkt die Herzfrequenz des Bären auf 8 Schläge pro Minute!",
    "Der Brillenbär ist der einzige Bär in Südamerika!",
    "Bären können bis zu 30 Jahre alt werden!",
    "Der Malaienbär ist der kleinste Bär der Welt!",
    "Bären lieben es, im Fluss Fische zu fangen!",
    "Bären markieren Bäume mit ihren Krallen, um ihr Revier zu zeigen!",
    "Der Pandabär frisst bis zu 38 Kilogramm Bambus am Tag!",
  ],
  dolphin: [
    "Delfine schlafen mit einem offenen Auge!",
    "Delfine benutzen Geräusche, um miteinander zu sprechen!",
    "Delfine können 60 Kilometer pro Stunde schwimmen!",
    "Delfine leben in Gruppen, die Schulen genannt werden!",
    "Delfine springen aus dem Wasser, weil es Spaß macht!",
    "Delfine haben über 100 Zähne, kauen aber nicht!",
    "Delfine können mehr als 40 Jahre alt werden!",
    "Jeder Delfin hat seinen eigenen einzigartigen Pfeifton!",
    "Delfine helfen kranken Freunden, an die Oberfläche zu kommen, um zu atmen!",
    "Delfine benutzen Echoortung, um Beute zu finden!",
    "Der Flussdelfin lebt im Süßwasser!",
    "Delfine spielen mit Quallen wie mit einem Ball!",
    "Das Gehirn der Delfine ist größer als das des Menschen!",
    "Delfine können Tricks und Kommandos lernen!",
    "Delfine sind keine Fische, sie sind Säugetiere!",
    "Der Orca ist der größte Delfin der Welt!",
    "Delfine gebären ein einziges Baby auf einmal!",
    "Delfine benutzen Schwämme zum Schutz der Nase bei der Jagd!",
    "Delfine gibt es seit über 50 Millionen Jahren!",
    "Delfine können bis zu 300 Meter tief tauchen!",
  ],
  snake: [
    "Schlangen riechen mit der Zunge!",
    "Schlangen haben keine Augenlider, ihre Augen sind immer offen!",
    "Manche Schlangen können fliegen, indem sie sich durch die Luft schlängeln!",
    "Die Anakonda ist eine der größten Schlangen der Welt!",
    "Schlangen häuten sich mehrmals im Jahr!",
    "Es gibt über 3.000 Schlangenarten auf der Welt!",
    "Die meisten Schlangen sind nicht giftig!",
    "Schlangen spüren Vibrationen im Boden, um Beute zu finden!",
    "Die Königskobra ist die längste Giftschlange der Welt!",
    "Schlangen können Beute verschlucken, die größer ist als ihr Kopf!",
    "Schlangen haben keine Beine, aber ihre Vorfahren hatten welche!",
    "Manche Schlangen können monatelang ohne Essen auskommen!",
    "Die Blindschlange ist so klein wie ein Regenwurm!",
    "Schlangen gibt es auf allen Kontinenten außer der Antarktis!",
    "Die Schwarze Mamba kann 20 Kilometer pro Stunde schnell sein!",
    "Schlangen haben sehr flexible Kiefer, um große Beute zu fressen!",
    "Pythons umschlingen ihre Beute, um sie festzuhalten!",
    "Manche Schlangen kümmern sich um ihre Eier, bis sie schlüpfen!",
    "Schlangen gibt es seit über 100 Millionen Jahren!",
    "Die Korallenschlange hat die schönsten Farben!",
  ],
  bee: [
    "Bienen besuchen bis zu 5.000 Blumen an einem einzigen Tag!",
    "Bienen tanzen, um den anderen zu zeigen, wo es Blumen gibt!",
    "Eine Biene muss 2 Millionen Blumen besuchen, um 1 Kilo Honig zu machen!",
    "Die Bienenkönigin kann bis zu 2.000 Eier am Tag legen!",
    "Bienen haben 5 Augen!",
    "Honig wird niemals schlecht!",
    "Bienen schlagen ihre Flügel 200 Mal pro Sekunde!",
    "Bienen sind für die Bestäubung von Obst und Gemüse verantwortlich!",
    "Eine Biene lebt nur etwa 6 Wochen im Sommer!",
    "Bienen produzieren Wachs mit ihrem Körper!",
    "Bienen können Gesichter erkennen!",
    "Ein Bienenstock kann bis zu 80.000 Bienen haben!",
    "Bienen gibt es seit über 100 Millionen Jahren!",
    "Bienen kommunizieren durch Tanzen und Vibrieren!",
    "Die Drohne (männliche Biene) stirbt nach der Paarung!",
    "Bienen bevorzugen blaue und gelbe Blumen!",
    "Bienen können bis zu 30 Kilometer pro Stunde fliegen!",
    "Bienen sind die wichtigsten Bestäuber des Planeten!",
    "Die Bienenkönigin kann bis zu 5 Jahre alt werden!",
    "Bienen machen Honig als Nahrung für den Winter!",
  ],
  pig: [
    "Schweine sind schlauer als Hunde!",
    "Schweine können Videospiele mit der Schnauze spielen!",
    "Der Geruchssinn von Schweinen ist hervorragend!",
    "Schweine können keine Bäume hochschauen, weil ihr Hals zu steif ist!",
    "Schweine drehen sich im Schlamm, um sich abzukühlen, weil sie nicht schwitzen!",
    "Schweine haben ein ausgezeichnetes Langzeitgedächtnis!",
    "Schweine können ihren Namen lernen und darauf reagieren!",
    "Es gibt über 70 Schweinerassen auf der Welt!",
    "Schweine können Trüffel unter der Erde finden!",
    "Schweine kommunizieren mit mehr als 20 verschiedenen Geräuschen!",
    "Schweinchen sind sehr sauber und halten ihren Schlafplatz getrennt!",
    "Schweine können bis zu 18 km pro Stunde laufen!",
    "Schweine gibt es seit über 40 Millionen Jahren!",
    "Schweine haben ein Sichtfeld von fast 310 Grad!",
    "Minischweine können bis zu 20 Jahre alt werden!",
    "Schweine werden am liebsten am Bauch gekrault!",
    "Wildschweine nennt man auch Keiler und Bachen!",
    "Schweine haben 44 Zähne, mehr als Menschen!",
    "Schweine können schwimmen!",
    "Schweine träumen, genau wie Menschen!",
  ],
};
