import type { AnimalId } from "./animals";

export const animalFunFacts: Record<AnimalId, string[]> = {
  cat: [
    "Os gatos dormem até 16 horas por dia!",
    "Os gatos conseguem girar as orelhas em 180 graus!",
    "Um gato pode pular até 6 vezes o seu próprio tamanho!",
    "Os gatos têm mais de 20 tipos de miados diferentes!",
    "O nariz de cada gato é único, como a impressão digital humana!",
    "Os gatos conseguem enxergar no escuro!",
  ],
  dog: [
    "O faro do cachorro é 40 vezes melhor que o dos humanos!",
    "Cachorros conseguem aprender mais de 100 palavras!",
    "O cachorro mais rápido do mundo corre a 70 km por hora!",
    "Cachorros sonham enquanto dormem, igualzinho a gente!",
    "O nariz do cachorro é úmido para captar melhor os cheiros!",
    "Cachorros abanam o rabo para a direita quando estão felizes!",
  ],
  elephant: [
    "Os elefantes são os maiores animais terrestres do mundo!",
    "Elefantes conseguem se reconhecer no espelho!",
    "Um elefante bebe até 200 litros de água por dia!",
    "Elefantes têm uma memória incrível e nunca esquecem um amigo!",
    "Os elefantes se comunicam com sons tão graves que nós não ouvimos!",
    "Elefantes adoram tomar banho de lama para se proteger do sol!",
  ],
  rabbit: [
    "Os coelhos podem girar as orelhas em qualquer direção!",
    "Coelhos são tão felizes que pulam e giram no ar! Isso se chama binky!",
    "Os dentes dos coelhos nunca param de crescer!",
    "Coelhos conseguem ver quase 360 graus ao redor deles!",
    "Um coelho pode correr a 55 km por hora!",
    "Coelhos ronronam quando estão felizes, igual aos gatos!",
  ],
  bird: [
    "Alguns pássaros conseguem imitar a voz humana!",
    "O beija-flor é o único pássaro que voa para trás!",
    "Pássaros enxergam mais cores do que os humanos!",
    "O avestruz é o pássaro mais rápido correndo, a 70 km por hora!",
    "Pássaros cantam para se comunicar e marcar território!",
    "As penas dos pássaros são mais fortes do que parecem!",
  ],
  fish: [
    "Existem peixes que brilham no fundo do mar!",
    "Alguns peixes conseguem voar por cima da água!",
    "O peixe-palhaço vive dentro das anêmonas do mar!",
    "Peixes não têm pálpebras, eles dormem de olhos abertos!",
    "O tubarão-baleia é o maior peixe do mundo!",
    "Alguns peixes mudam de cor para se esconder dos predadores!",
  ],
  lion: [
    "O rugido do leão pode ser ouvido a 8 quilômetros de distância!",
    "Os leões dormem até 20 horas por dia!",
    "Só os leões machos têm aquela juba enorme!",
    "As leoas são as caçadoras da família!",
    "Os leões vivem em grupos chamados de alcateias!",
    "Um leão pode correr a 80 km por hora em curtas distâncias!",
  ],
  turtle: [
    "Algumas tartarugas podem viver mais de 100 anos!",
    "O casco da tartaruga faz parte do esqueleto dela!",
    "As tartarugas marinhas viajam milhares de quilômetros pelo oceano!",
    "As tartarugas existem há mais de 200 milhões de anos!",
    "Tartarugas não têm dentes, elas têm um bico como os pássaros!",
    "A tartaruga-de-couro é a maior tartaruga do mundo!",
  ],
  butterfly: [
    "As borboletas provam a comida com os pés!",
    "Uma borboleta começa a vida como uma lagarta!",
    "Existem mais de 20 mil espécies de borboletas no mundo!",
    "As asas das borboletas são transparentes, as cores vêm de escamas minúsculas!",
    "Algumas borboletas migram milhares de quilômetros!",
    "Borboletas não conseguem voar se estiverem com frio!",
  ],
  frog: [
    "Os sapos absorvem água pela pele, eles não bebem!",
    "Alguns sapos são tão venenosos que podem derrubar um elefante!",
    "Os sapos engolem a comida usando os olhos para empurrar!",
    "Existem sapos de todas as cores do arco-íris!",
    "Os sapos coaxam para atrair uma namorada!",
    "Alguns sapos conseguem congelar no inverno e descongelar na primavera!",
  ],
  horse: [
    "Os cavalos conseguem dormir em pé!",
    "Um cavalo pode correr poucas horas depois de nascer!",
    "Os cavalos enxergam quase 360 graus ao redor deles!",
    "Os dentes dos cavalos ocupam mais espaço na cabeça do que o cérebro!",
    "Cavalos conseguem reconhecer emoções no rosto humano!",
    "O cavalo mais rápido do mundo atingiu 70 km por hora!",
  ],
  owl: [
    "As corujas conseguem girar a cabeça até 270 graus!",
    "Corujas têm uma audição tão boa que caçam no escuro total!",
    "Os olhos das corujas não se mexem, por isso elas giram a cabeça!",
    "As penas das corujas são silenciosas, elas voam sem fazer barulho!",
    "Algumas corujas são menores que a sua mão!",
    "Corujas engolem a presa inteira e depois cospem os ossos!",
  ],
  penguin: [
    "Os pinguins não voam, mas são ótimos nadadores!",
    "Pinguins podem prender a respiração por até 20 minutos debaixo d'água!",
    "O pinguim-imperador é o maior de todos, com quase 1 metro de altura!",
    "Os pinguins vivem no frio, mas nem todos vivem na neve!",
    "Pinguins se aquecem ficando juntinhos em grupo!",
    "Os pais pinguins chocam os ovos nos próprios pés!",
  ],
  monkey: [
    "Os macacos usam ferramentas como pedras para abrir frutas!",
    "Macacos se abraçam e fazem carinho para mostrar amizade!",
    "O macaco-aranha usa o rabo como uma mão extra!",
    "Existem mais de 260 espécies de macacos no mundo!",
    "Os macacos vivem em grupos e cuidam uns dos outros!",
    "Macacos conseguem reconhecer o próprio reflexo no espelho!",
  ],
  giraffe: [
    "A girafa é o animal mais alto do mundo, chegando a 6 metros!",
    "A língua da girafa tem até 50 centímetros de comprimento!",
    "Cada girafa tem um padrão de manchas único, como impressões digitais!",
    "As girafas dormem apenas 30 minutos por dia!",
    "O coração da girafa pesa 11 quilos!",
    "Os bebês girafa já nascem com quase 2 metros de altura!",
  ],
  bear: [
    "Os ursos polares têm a pele preta por baixo do pelo branco!",
    "Ursos conseguem sentir o cheiro de comida a 30 quilômetros!",
    "Alguns ursos dormem o inverno inteiro sem comer nem beber!",
    "Os ursos pandas comem bambu por até 14 horas por dia!",
    "Ursos são excelentes nadadores!",
    "O urso-pardo pode pesar mais de 600 quilos!",
  ],
  dolphin: [
    "Os golfinhos dormem com um olho aberto!",
    "Golfinhos se comunicam com sons como cliques e assobios!",
    "Um golfinho pode nadar a 60 km por hora!",
    "Golfinhos são tão inteligentes que se reconhecem no espelho!",
    "Golfinhos vivem em grupos chamados de pods!",
    "Os golfinhos ajudam uns aos outros quando estão doentes!",
  ],
  snake: [
    "As cobras sentem cheiros com a língua!",
    "Cobras não têm pálpebras, elas dormem de olhos abertos!",
    "Algumas cobras conseguem voar planando entre as árvores!",
    "As cobras trocam de pele várias vezes por ano!",
    "Existem cobras que podem comer presas maiores que a própria cabeça!",
    "A cobra mais longa do mundo pode chegar a 10 metros!",
  ],
  bee: [
    "Uma abelha visita até 2 mil flores por dia!",
    "As abelhas dançam para mostrar onde tem comida!",
    "O mel nunca estraga, já encontraram mel de 3 mil anos!",
    "Uma colmeia pode ter até 60 mil abelhas!",
    "As abelhas são responsáveis por polinizar um terço da nossa comida!",
    "A abelha rainha pode viver até 5 anos!",
  ],
  pig: [
    "Os porcos são tão inteligentes quanto os cachorros!",
    "Porcos não conseguem olhar para cima, para o céu!",
    "Os porcos tomam banho de lama para se refrescar, não porque são sujos!",
    "Porcos têm um olfato incrível e são usados para encontrar trufas!",
    "Os porquinhos recém-nascidos reconhecem a voz da mãe!",
    "Porcos conseguem aprender truques e jogar videogame simples!",
  ],
};

export function getRandomFunFact(animalId: AnimalId): string {
  const facts = animalFunFacts[animalId];
  return facts[Math.floor(Math.random() * facts.length)];
}
