import type { AnimalId } from "./animals";

export const animalFunFactsFr: Record<AnimalId, string[]> = {
  cat: [
    "Les chats dorment jusqu'à 16 heures par jour !",
    "Les chats peuvent tourner leurs oreilles à 180 degrés !",
    "Un chat peut sauter jusqu'à 6 fois sa propre taille !",
    "Les chats ont plus de 20 types de miaulements différents !",
    "Le nez de chaque chat est unique, comme une empreinte digitale !",
    "Les chats peuvent voir dans le noir !",
    "Les chats passent 30% de la journée à se toiletter !",
    "Un chat a 230 os, plus que les humains !",
    "Les moustaches du chat l'aident à mesurer s'il passe dans les espaces étroits !",
    "Les chats ronronnent quand ils sont heureux, mais aussi pour se guérir !",
    "Les chats peuvent courir à 48 kilomètres par heure !",
    "Les chats domestiques existent depuis plus de 10 000 ans !",
    "Un chat peut entendre des sons que nous ne pouvons pas !",
    "Les chats retombent toujours sur leurs pattes grâce à un équilibre incroyable !",
    "Les chats frottent leur visage sur les choses pour marquer leur territoire !",
    "Le plus vieux chat du monde a vécu 38 ans !",
    "Les chats ont une troisième paupière cachée !",
    "Les chats préfèrent l'eau courante à l'eau stagnante !",
    "Les chats peuvent sentir les tremblements de terre avant les humains !",
    "Un groupe de chats s'appelle une colonie !",
  ],
  dog: [
    "L'odorat du chien est 40 fois meilleur que celui des humains !",
    "Les chiens peuvent apprendre plus de 100 mots !",
    "Le chien le plus rapide peut courir à 70 km par heure !",
    "Les chiens rêvent quand ils dorment, tout comme nous !",
    "Le nez du chien est humide pour mieux capter les odeurs !",
    "Les chiens remuent la queue vers la droite quand ils sont heureux !",
    "Les chiens voient en tons de bleu et de jaune !",
    "L'ouïe des chiens est 4 fois meilleure que la nôtre !",
    "Le plus vieux chien du monde a vécu 30 ans !",
    "Les chiens bâillent quand ils voient quelqu'un bâiller, par empathie !",
    "Un chien peut sentir l'humeur de son maître par l'odeur !",
    "Il existe plus de 340 races de chiens dans le monde !",
    "Les chiens ne transpirent que par les coussinets !",
    "Les chiots naissent sourds et aveugles !",
    "Le Labrador est la race la plus populaire au monde !",
    "Les chiens peuvent flairer des maladies chez les humains !",
    "Un chien adulte a 42 dents !",
    "Les chiens tournent en rond avant de se coucher par instinct !",
    "Les chiens peuvent entendre des sons à 225 mètres de distance !",
    "Trois chiens ont survécu au naufrage du Titanic !",
  ],
  elephant: [
    "Les éléphants sont les plus grands animaux terrestres du monde !",
    "Les éléphants peuvent se reconnaître dans un miroir !",
    "Un éléphant boit jusqu'à 200 litres d'eau par jour !",
    "Les éléphants ont une mémoire incroyable et n'oublient jamais un ami !",
    "Les éléphants communiquent avec des sons si graves que nous ne les entendons pas !",
    "Les éléphants adorent prendre des bains de boue pour se protéger du soleil !",
    "Les éléphants peuvent peser jusqu'à 6 tonnes !",
    "Les éléphants utilisent leur trompe comme une paille pour boire !",
    "Un bébé éléphant pèse environ 100 kilos à la naissance !",
    "Les éléphants marchent sur la pointe des doigts !",
    "Les éléphants savent très bien nager !",
    "La trompe d'un éléphant a plus de 40 000 muscles !",
    "Les éléphants sont tristes quand un ami meurt et font le deuil !",
    "Les éléphants d'Afrique ont des oreilles en forme d'Afrique !",
    "Les éléphants mangent jusqu'à 150 kilos de nourriture par jour !",
    "Les éléphants vivent en familles dirigées par une femelle !",
    "Les éléphants se saluent en entrelaçant leurs trompes !",
    "La peau de l'éléphant fait jusqu'à 2,5 centimètres d'épaisseur !",
    "Les éléphants peuvent sentir les vibrations du sol par leurs pieds !",
    "Les éléphants sont l'un des rares animaux qui pleurent d'émotion !",
  ],
  rabbit: [
    "Les lapins peuvent tourner leurs oreilles dans toutes les directions !",
    "Les lapins sont si heureux qu'ils sautent et tournent en l'air ! Ça s'appelle un binky !",
    "Les dents des lapins ne cessent jamais de pousser !",
    "Les lapins peuvent voir presque à 360 degrés autour d'eux !",
    "Un lapin peut courir à 55 km par heure !",
    "Les lapins ronronnent quand ils sont heureux, comme les chats !",
    "Les lapins ont plus de 28 dents !",
    "Les lapins bougent le nez jusqu'à 120 fois par minute !",
    "Les lapins sont plus actifs tôt le matin et en fin d'après-midi !",
    "Les lapins peuvent faire des bonds d'1 mètre de haut !",
    "Un groupe de lapins s'appelle une colonie !",
    "Les lapins se nettoient en se léchant les pattes, comme les chats !",
    "Les lapins vivent dans des terriers souterrains !",
    "Les lapins peuvent avoir jusqu'à 12 bébés à la fois !",
    "Les lapins tapent du pied pour avertir d'un danger !",
    "Les lapins adorent jouer avec des tunnels et des boîtes !",
    "Les lapins dorment parfois les yeux ouverts !",
    "Les lapins peuvent apprendre des tours et leur nom !",
    "Les lapins sauvages vivent sur presque tous les continents !",
    "Les lapins peuvent vivre jusqu'à 12 ans !",
  ],
  bird: [
    "Certains oiseaux peuvent imiter la voix humaine !",
    "Le colibri est le seul oiseau qui vole en arrière !",
    "Les oiseaux voient plus de couleurs que les humains !",
    "L'autruche est l'oiseau le plus rapide à la course, à 70 km/h !",
    "Les oiseaux chantent pour communiquer et marquer leur territoire !",
    "Les plumes des oiseaux sont plus résistantes qu'elles n'en ont l'air !",
    "Les perroquets peuvent vivre jusqu'à 80 ans !",
    "Le colibri bat des ailes jusqu'à 80 fois par seconde !",
    "Les oiseaux migrent sur des milliers de kilomètres chaque année !",
    "L'œuf d'autruche est le plus grand œuf du monde !",
    "Les oiseaux ont des os creux pour être plus légers en vol !",
    "Les corbeaux sont si intelligents qu'ils utilisent des outils !",
    "Le plus petit oiseau du monde est le colibri-abeille, avec 5 cm !",
    "Les oiseaux peuvent dormir avec la moitié du cerveau éveillée !",
    "Les flamants roses sont roses à cause de leur nourriture !",
    "Il existe plus de 10 000 espèces d'oiseaux dans le monde !",
    "Les manchots sont des oiseaux, mais ils ne volent pas !",
    "Les oiseaux avalent des cailloux pour aider à digérer !",
    "Les chouettes ne peuvent pas bouger les yeux, elles tournent la tête !",
    "L'albatros peut voler pendant des années sans se poser !",
  ],
  fish: [
    "Il existe des poissons qui brillent au fond de la mer !",
    "Certains poissons peuvent voler au-dessus de l'eau !",
    "Le poisson-clown vit dans les anémones de mer !",
    "Les poissons n'ont pas de paupières, ils dorment les yeux ouverts !",
    "Le requin-baleine est le plus grand poisson du monde !",
    "Certains poissons changent de couleur pour se cacher des prédateurs !",
    "Les poissons utilisent leurs branchies pour respirer sous l'eau !",
    "Il existe plus de 30 000 espèces de poissons dans le monde !",
    "L'hippocampe est l'un des rares poissons où le père porte les bébés !",
    "Les poissons sentent les vibrations dans l'eau avec une ligne latérale !",
    "L'espadon peut nager à 110 kilomètres par heure !",
    "Certains poissons vivent dans les profondeurs les plus sombres de l'océan !",
    "Les poissons rouges peuvent se souvenir de choses pendant des mois !",
    "Le poisson-globe se gonfle d'eau pour paraître plus gros !",
    "Les poissons voyagent en bancs pour se protéger !",
    "Les requins existent depuis plus de 400 millions d'années !",
    "Certains poissons font des nids pour protéger leurs œufs !",
    "Le poisson-lune est le poisson osseux le plus lourd du monde !",
    "Les poissons peuvent goûter l'eau autour d'eux !",
    "Le poisson-archer crache des jets d'eau pour faire tomber les insectes !",
  ],
  lion: [
    "Le rugissement du lion peut être entendu à 8 kilomètres !",
    "Les lions dorment jusqu'à 20 heures par jour !",
    "Seuls les lions mâles ont cette énorme crinière !",
    "Les lionnes sont les chasseuses de la famille !",
    "Les lions vivent en groupes appelés troupes !",
    "Un lion peut courir à 80 km/h sur de courtes distances !",
    "Les lionceaux naissent avec des taches qui disparaissent en grandissant !",
    "Les lions frottent leurs têtes pour se saluer !",
    "La crinière du lion fonce avec l'âge !",
    "Les lions peuvent sauter jusqu'à 11 mètres de distance !",
    "Les lions sont appelés Rois de la Jungle, mais vivent dans la savane !",
    "Un lion peut manger 40 kilos de viande d'un coup !",
    "Les moustaches du lion l'aident à sentir ce qui l'entoure !",
    "Les lions se reposent dans les arbres pour échapper à la chaleur !",
    "Les lionceaux jouent à se battre pour apprendre à chasser !",
    "Les mâles protègent le territoire pendant que les femelles chassent !",
    "Le lion est le deuxième plus grand félin, après le tigre !",
    "Les lions peuvent vivre jusqu'à 15 ans dans la nature !",
    "Les lions boivent de l'eau dès qu'ils peuvent, mais tiennent des jours sans !",
    "Un lion reconnaît les membres de sa troupe par le rugissement !",
  ],
  turtle: [
    "Certaines tortues peuvent vivre plus de 100 ans !",
    "La carapace de la tortue fait partie de son squelette !",
    "Les tortues marines parcourent des milliers de kilomètres dans l'océan !",
    "Les tortues existent depuis plus de 200 millions d'années !",
    "Les tortues n'ont pas de dents, elles ont un bec comme les oiseaux !",
    "La tortue luth est la plus grande tortue du monde !",
    "Les tortues peuvent sentir quand on touche leur carapace !",
    "Les tortues marines retournent sur la même plage pour pondre !",
    "Les tortues peuvent retenir leur souffle pendant des heures sous l'eau !",
    "Le sexe des bébés tortues dépend de la température du sable !",
    "Les tortues voient les couleurs, y compris l'ultraviolet !",
    "Certaines tortues hibernent en hiver enterrées dans la boue !",
    "La tortue géante des Galápagos peut peser 400 kilos !",
    "Les tortues ont un excellent sens de l'orientation !",
    "Les tortues sont des reptiles, parentes des dinosaures !",
    "Les tortues marines pleurent pour éliminer le sel de l'eau de mer !",
    "Certaines tortues peuvent respirer par le derrière !",
    "Les tortues domestiques peuvent vivre plus de 50 ans !",
    "Les tortues sont les reptiles les plus anciens qui existent !",
    "Les bébés tortues ont la taille d'une pièce de monnaie à la naissance !",
  ],
  butterfly: [
    "Les papillons goûtent la nourriture avec leurs pattes !",
    "Un papillon commence sa vie comme une chenille !",
    "Il existe plus de 20 000 espèces de papillons dans le monde !",
    "Les ailes des papillons sont transparentes, les couleurs viennent d'écailles minuscules !",
    "Certains papillons migrent sur des milliers de kilomètres !",
    "Les papillons ne peuvent pas voler s'ils ont froid !",
    "Les papillons boivent le nectar des fleurs avec une trompe enroulée !",
    "Le papillon monarque voyage du Canada au Mexique chaque année !",
    "Les papillons ne vivent que quelques semaines !",
    "Les papillons ont besoin du soleil pour réchauffer leurs ailes et voler !",
    "Certains papillons ont des motifs d'yeux sur les ailes pour effrayer les prédateurs !",
    "La transformation de chenille en papillon s'appelle la métamorphose !",
    "Les papillons voient des couleurs que les humains ne peuvent pas voir !",
    "Dans le cocon, la chenille se transforme complètement en liquide !",
    "Certains papillons se nourrissent de fruits pourris !",
    "Les papillons battent des ailes environ 5 fois par seconde !",
    "Les papillons peuvent voler jusqu'à 20 kilomètres par heure !",
    "Le plus grand papillon du monde a 30 centimètres d'envergure !",
    "Les papillons se réchauffent en ouvrant les ailes au soleil comme des panneaux solaires !",
    "Certains papillons ont un goût désagréable pour que les prédateurs ne les mangent pas !",
  ],
  frog: [
    "Les grenouilles absorbent l'eau par la peau, elles ne boivent pas !",
    "Certaines grenouilles sont si venimeuses qu'elles pourraient terrasser un éléphant !",
    "Les grenouilles avalent leur nourriture en utilisant les yeux pour pousser !",
    "Il existe des grenouilles de toutes les couleurs de l'arc-en-ciel !",
    "Les grenouilles coassent pour attirer une compagne !",
    "Certaines grenouilles gèlent en hiver et dégèlent au printemps !",
    "Les grenouilles commencent leur vie comme des têtards dans l'eau !",
    "Les grenouilles peuvent sauter 20 fois la taille de leur corps !",
    "La peau des grenouilles est toujours humide !",
    "Il existe des grenouilles plus petites qu'un ongle !",
    "Les grenouilles venimeuses sont colorées pour avertir les prédateurs !",
    "Certaines grenouilles portent leurs bébés sur le dos !",
    "Les grenouilles existent depuis plus de 200 millions d'années !",
    "Les grenouilles peuvent vivre dans l'eau et sur terre !",
    "La plus grande grenouille du monde pèse plus de 3 kilos !",
    "Les grenouilles changent de peau régulièrement et mangent l'ancienne !",
    "Les yeux des grenouilles sont sur le dessus de la tête pour voir hors de l'eau !",
    "Les grenouilles sont très importantes pour contrôler les insectes !",
    "Il existe plus de 7 000 espèces de grenouilles dans le monde !",
    "Certaines grenouilles font des sons qui ressemblent à des oiseaux qui chantent !",
  ],
  horse: [
    "Les chevaux peuvent dormir debout !",
    "Un cheval peut courir quelques heures après sa naissance !",
    "Les chevaux voient presque à 360 degrés autour d'eux !",
    "Les dents des chevaux prennent plus de place dans la tête que le cerveau !",
    "Les chevaux peuvent reconnaître les émotions sur le visage humain !",
    "Le cheval le plus rapide du monde a atteint 70 km/h !",
    "Les chevaux ont la plus grande vision de tous les mammifères terrestres !",
    "Les chevaux communiquent avec les oreilles, les yeux et les expressions !",
    "Un cheval adulte a 40 dents !",
    "Les chevaux peuvent vivre jusqu'à 30 ans !",
    "Les chevaux ne dorment que 2 à 3 heures par jour !",
    "Les sabots des chevaux sont faits du même matériau que nos ongles !",
    "Les chevaux peuvent courir le jour même de leur naissance !",
    "Les chevaux sont herbivores et adorent les carottes et les pommes !",
    "Un cheval boit entre 30 et 50 litres d'eau par jour !",
    "Les chevaux ont une excellente mémoire !",
    "Les chevaux sauvages vivent en troupeaux menés par une jument !",
    "Les chevaux ne peuvent pas vomir !",
    "Le plus petit cheval du monde ne fait que 44 centimètres de haut !",
    "Les chevaux existent depuis plus de 50 millions d'années !",
  ],
  owl: [
    "Les chouettes peuvent tourner la tête jusqu'à 270 degrés !",
    "Les chouettes ont une ouïe si fine qu'elles chassent dans le noir total !",
    "Les yeux des chouettes ne bougent pas, c'est pour ça qu'elles tournent la tête !",
    "Les plumes des chouettes sont silencieuses, elles volent sans bruit !",
    "Certaines chouettes sont plus petites que ta main !",
    "Les chouettes avalent leur proie entière puis recrachent les os !",
    "Les chouettes ont trois paupières sur chaque œil !",
    "Les chouettes peuvent entendre une souris marcher sous la neige !",
    "Les yeux des chouettes sont si grands qu'ils ne peuvent pas bouger !",
    "Les chouettes se trouvent sur tous les continents sauf l'Antarctique !",
    "La chevêche des terriers vit dans des trous dans le sol !",
    "Les chouettes tournent la tête car elles ne peuvent pas bouger les yeux !",
    "Il existe plus de 200 espèces de chouettes dans le monde !",
    "Les chouettes sont des chasseuses nocturnes incroyables !",
    "Le harfang des neiges est presque tout blanc !",
    "Les chouettes ont des serres super fortes pour attraper les proies !",
    "Un groupe de chouettes s'appelle un parlement !",
    "Les bébés chouettes s'appellent des poussins !",
    "Les chouettes peuvent tourner la tête des deux côtés !",
    "La plus grande chouette du monde a près de 2 mètres d'envergure !",
  ],
  penguin: [
    "Les manchots ne volent pas, mais ce sont d'excellents nageurs !",
    "Les manchots peuvent retenir leur souffle pendant 20 minutes sous l'eau !",
    "Le manchot empereur est le plus grand, mesurant presque 1 mètre !",
    "Les manchots vivent dans le froid, mais pas tous dans la neige !",
    "Les manchots se réchauffent en se serrant les uns contre les autres !",
    "Les papas manchots couvent les œufs sur leurs propres pattes !",
    "Les manchots peuvent nager à 35 kilomètres par heure !",
    "Il existe 18 espèces de manchots dans le monde !",
    "Les manchots boivent de l'eau salée et filtrent le sel !",
    "Les manchots reconnaissent leur partenaire par le chant !",
    "Le plus petit manchot du monde ne fait que 30 centimètres !",
    "Les manchots changent de plumes une fois par an !",
    "Les manchots glissent sur le ventre dans la neige pour se déplacer !",
    "Les manchots sont noirs et blancs pour se camoufler dans l'eau !",
    "Les manchots peuvent plonger à plus de 500 mètres de profondeur !",
    "Les manchots empereurs supportent des températures de -60 degrés !",
    "Les manchots sont très fidèles et reconnaissent leur partenaire chaque année !",
    "Les bébés manchots restent en crèche pendant que les parents chassent !",
    "Les manchots mangent des poissons, des calmars et du krill !",
    "Les manchots existent depuis plus de 60 millions d'années !",
  ],
  monkey: [
    "Les singes utilisent des outils comme des pierres pour ouvrir des fruits !",
    "Les singes se font des câlins pour montrer leur amitié !",
    "Le singe-araignée utilise sa queue comme une main supplémentaire !",
    "Il existe plus de 260 espèces de singes dans le monde !",
    "Les singes vivent en groupes et prennent soin les uns des autres !",
    "Les singes peuvent reconnaître leur propre reflet dans un miroir !",
    "Les singes s'épouillent mutuellement pour renforcer l'amitié !",
    "Le plus petit singe du monde tient dans la paume de la main !",
    "Les singes peuvent apprendre la langue des signes !",
    "Les singes hurleurs s'entendent à 5 kilomètres de distance !",
    "Les singes japonais prennent des bains dans les sources chaudes en hiver !",
    "Les capucins sont considérés comme les singes les plus intelligents des Amériques !",
    "Les singes bâillent quand ils voient un autre singe bâiller !",
    "Les singes nocturnes sont les seuls qui voient bien dans le noir !",
    "Les singes utilisent différents sons pour signaler les types de prédateurs !",
    "Le nasique a le plus grand nez de tous les primates !",
    "Les bébés singes s'accrochent au ventre de leur mère pour se déplacer !",
    "Les singes sont nos plus proches parents dans le règne animal !",
    "Les singes peuvent vivre jusqu'à 40 ans dans la nature !",
    "Les singes d'Amérique ont une queue préhensile, ceux d'Afrique non !",
  ],
  giraffe: [
    "La girafe est l'animal le plus grand du monde, mesurant jusqu'à 6 mètres !",
    "La langue de la girafe mesure jusqu'à 50 centimètres !",
    "Chaque girafe a un motif de taches unique, comme des empreintes digitales !",
    "Les girafes ne dorment que 30 minutes par jour !",
    "Le cœur de la girafe pèse 11 kilos !",
    "Les bébés girafes naissent déjà avec près de 2 mètres de haut !",
    "La langue de la girafe est violette pour se protéger du soleil !",
    "Les girafes marchent en bougeant les deux pattes du même côté ensemble !",
    "Les girafes peuvent courir à 55 kilomètres par heure !",
    "Le cou de la girafe n'a que 7 vertèbres, comme le nôtre !",
    "Les girafes se couchent rarement, elles dorment même debout !",
    "Les girafes boivent de l'eau en écartant bien les pattes avant !",
    "Les girafes se battent en se donnant des coups de cou !",
    "Les girafes vivent dans la savane africaine !",
    "La girafe peut voir à des kilomètres grâce à sa hauteur !",
    "Les girafes mangent jusqu'à 35 kilos de feuilles par jour !",
    "Les girafes sont les amies des oiseaux qui mangent les parasites sur leur peau !",
    "Le bébé girafe tombe de 2 mètres en naissant et se lève en 30 minutes !",
    "Les girafes n'ont pas de cordes vocales !",
    "Les girafes sont des animaux très pacifiques !",
  ],
  bear: [
    "Les ours peuvent sentir de la nourriture à 30 kilomètres de distance !",
    "Les ours polaires ont la peau noire sous la fourrure blanche !",
    "Les ours hibernent pendant l'hiver et ne mangent pas pendant des mois !",
    "L'ours est l'un des animaux les plus forts du monde !",
    "Le panda géant mange du bambou presque toute la journée !",
    "Les ours peuvent courir à 55 kilomètres par heure !",
    "Les bébés ours naissent aveugles et sans poils !",
    "Les ours savent très bien grimper aux arbres !",
    "L'ours polaire est le plus grand carnivore terrestre !",
    "Les ours bruns peuvent peser jusqu'à 600 kilos !",
    "Le panda géant mange 38 kilos de bambou par jour !",
    "Les ours se lèvent sur les pattes arrière pour mieux voir !",
    "L'ours à lunettes est le seul ours d'Amérique du Sud !",
    "Les ours polaires nagent sur des centaines de kilomètres !",
    "Le plus petit ours du monde est l'ours malais !",
    "Les ours ont un excellent sens de l'odorat !",
    "Les ours vivent sur tous les continents sauf l'Afrique et l'Australie !",
    "Les bébés pandas naissent de la taille d'un bâton de beurre !",
    "Les ours peuvent vivre jusqu'à 30 ans dans la nature !",
    "Les ours adorent le miel, ils supportent les piqûres d'abeilles !",
  ],
  dolphin: [
    "Les dauphins dorment avec un seul œil fermé et la moitié du cerveau !",
    "Les dauphins se donnent des noms entre eux avec des sifflements !",
    "Les dauphins peuvent nager à 60 kilomètres par heure !",
    "Les dauphins utilisent l'écholocation pour trouver les poissons !",
    "Les dauphins sont parmi les animaux les plus intelligents du monde !",
    "Les dauphins vivent en groupes appelés bancs !",
    "Un bébé dauphin nage dès sa naissance !",
    "Les dauphins peuvent sauter jusqu'à 6 mètres hors de l'eau !",
    "Les dauphins aident d'autres animaux blessés en les soutenant à la surface !",
    "Les dauphins ont plus de 100 dents mais avalent la nourriture sans mâcher !",
    "Les dauphins jouent avec les vagues comme les surfeurs !",
    "Les dauphins peuvent retenir leur souffle pendant 15 minutes !",
    "Les dauphins communiquent avec des clics et des sifflements !",
    "Les dauphins ont une peau super lisse qui se régénère très vite !",
    "Le plus grand dauphin est l'orque, qui est en fait un dauphin !",
    "Les dauphins se reconnaissent dans un miroir !",
    "Les dauphins peuvent vivre jusqu'à 50 ans !",
    "Les dauphins protègent les humains des requins !",
    "Les dauphins roses existent et vivent dans les rivières d'Amérique du Sud !",
    "Les dauphins sont des mammifères et allaitent leurs petits !",
  ],
  snake: [
    "Les serpents n'ont pas de paupières, ils dorment les yeux ouverts !",
    "Les serpents sentent les odeurs avec la langue !",
    "Certains serpents peuvent voler en planant d'arbre en arbre !",
    "Les serpents muent plusieurs fois par an en changeant de peau !",
    "Le plus grand serpent du monde peut mesurer 10 mètres !",
    "Les serpents n'ont pas d'oreilles mais sentent les vibrations du sol !",
    "Certains serpents peuvent manger des proies plus grandes que leur tête !",
    "Les serpents à sonnette secouent leur queue pour avertir du danger !",
    "Les serpents existent depuis plus de 100 millions d'années !",
    "Les serpents sont des reptiles à sang froid !",
    "Le cobra royal est le plus grand serpent venimeux du monde !",
    "Certains serpents prennent soin de leurs œufs jusqu'à l'éclosion !",
    "Les serpents peuvent nager très bien !",
    "Les boas et pythons étouffent leurs proies en s'enroulant !",
    "Il existe plus de 3 000 espèces de serpents dans le monde !",
    "La plupart des serpents sont inoffensifs pour les humains !",
    "Les serpents aident à contrôler la population de rongeurs !",
    "Le mamba noir est le serpent le plus rapide, à 20 km/h !",
    "Les serpents avalent leur nourriture entière !",
    "Certains serpents de mer peuvent retenir leur souffle pendant 2 heures !",
  ],
  bee: [
    "Les abeilles visitent jusqu'à 5 000 fleurs en une seule journée !",
    "Les abeilles dansent pour indiquer où se trouvent les fleurs !",
    "Une abeille reine peut pondre 2 000 œufs par jour !",
    "Le miel ne périme jamais, du miel de 3 000 ans est encore comestible !",
    "Les abeilles battent des ailes 200 fois par seconde !",
    "Les abeilles sont responsables de la pollinisation d'un tiers de notre nourriture !",
    "Une ruche peut abriter 80 000 abeilles !",
    "Les abeilles produisent du miel en régurgitant le nectar !",
    "Les abeilles ouvrières ne vivent que 6 semaines !",
    "Les abeilles voient les couleurs, y compris l'ultraviolet !",
    "Les abeilles savent compter jusqu'à 4 !",
    "Les abeilles communiquent par des danses et des phéromones !",
    "Pour faire 1 kilo de miel, les abeilles visitent 4 millions de fleurs !",
    "La reine des abeilles peut vivre jusqu'à 5 ans !",
    "Les abeilles ont 5 yeux : 2 grands et 3 petits !",
    "Le bourdonnement des abeilles vient du battement de leurs ailes !",
    "Les abeilles gardent la ruche à exactement 35 degrés !",
    "Les abeilles existent depuis plus de 100 millions d'années !",
    "Sans les abeilles, beaucoup de fruits et légumes disparaîtraient !",
    "Les faux-bourdons mâles ne piquent pas, seules les femelles piquent !",
  ],
  pig: [
    "Les cochons sont aussi intelligents que les chiens !",
    "Les cochons ne transpirent pas, c'est pour ça qu'ils se roulent dans la boue !",
    "Les cochons ont un odorat incroyable, ils trouvent des truffes sous terre !",
    "Les cochons peuvent apprendre des tours et jouer à des jeux vidéo !",
    "Les cochons communiquent avec plus de 20 sons différents !",
    "Les cochons rêvent quand ils dorment, comme nous !",
    "Le plus petit cochon du monde pèse seulement 6 kilos !",
    "Les cochons peuvent courir à 18 kilomètres par heure !",
    "Les cochons sont très propres et font caca loin de l'endroit où ils dorment !",
    "Les cochons adorent se gratter le dos contre les arbres !",
    "Les bébés cochons apprennent leur nom en seulement deux semaines !",
    "Les cochons se reconnaissent dans un miroir !",
    "Les cochons ont une excellente mémoire à long terme !",
    "Les cochons font la queue quand ils sont heureux, comme les chiens !",
    "Les cochons peuvent nager très bien !",
    "Les cochons vivent en groupes et sont très sociables !",
    "Les cochons existent depuis plus de 40 millions d'années !",
    "Les cochons adorent les gratouilles sur le ventre !",
    "Les cochons sauvages s'appellent des sangliers !",
    "Les cochons ont 44 dents, plus que les humains !",
  ],
  panda: [
    "Les pandas géants mangent du bambou jusqu'à 14 heures par jour !",
    "Un panda adulte peut manger 38 kg de bambou par jour !",
    "Les bébés pandas naissent roses et sans poils !",
    "Les pandas ont un os spécial au poignet qui sert de pouce !",
    "Les pandas géants vivent dans les montagnes de Chine !",
    "Les pandas passent la plupart de leur temps à manger et dormir !",
    "Les pandas sont d'excellents nageurs !",
    "Les pandas marquent leur territoire en se frottant aux arbres !",
    "Un bébé panda ne pèse que 100 grammes à la naissance !",
    "Les pandas ont un régime alimentaire presque 100 % végétarien !",
    "Les pandas vivent entre 20 et 30 ans dans la nature !",
    "Les pandas sont d'excellents grimpeurs d'arbres !",
    "Le pelage noir et blanc du panda l'aide à se camoufler !",
    "Les pandas ont des mâchoires super puissantes pour mâcher le bambou !",
    "Les pandas géants sont solitaires et préfèrent vivre seuls !",
    "Les bébés pandas restent avec leur mère jusqu'à 2 ans !",
    "Les pandas ont été retirés de la liste des espèces en danger !",
    "Les pandas font des sons comme des bêlements pour communiquer !",
    "Les pandas ont des pupilles verticales, comme les chats !",
    "Le panda est le symbole de la conservation de la nature !",
  ],
  koala: [
    "Les koalas dorment jusqu'à 22 heures par jour !",
    "Les koalas se nourrissent presque exclusivement de feuilles d'eucalyptus !",
    "Les empreintes digitales des koalas sont presque identiques à celles des humains !",
    "Les bébés koalas restent dans la poche de leur mère pendant 6 mois !",
    "Les koalas boivent rarement de l'eau, ils s'hydratent avec les feuilles !",
    "Les koalas ont deux pouces à chaque main pour mieux s'agripper !",
    "Les koalas ne sont pas des ours, ce sont des marsupiaux !",
    "Les koalas ne vivent qu'en Australie !",
    "Les koalas ont un grand nez pour sentir les meilleures feuilles !",
    "Les bébés koalas mangent une pâte spéciale produite par la mère !",
    "Les koalas peuvent vivre jusqu'à 18 ans dans la nature !",
    "Les koalas ont une fourrure épaisse et douce qui les protège de la pluie !",
    "Les koalas serrent les arbres pour se rafraîchir quand il fait chaud !",
    "Les koalas mâles marquent leur territoire en frottant leur poitrine !",
    "Les koalas ont un petit cerveau par rapport à leur corps !",
    "Les koalas font des sons graves et forts pour communiquer !",
    "Les koalas mangent environ 500 grammes de feuilles par jour !",
    "Les koalas sont des animaux nocturnes !",
    "Les koalas ont des griffes acérées pour grimper aux arbres !",
    "Les koalas sont l'un des animaux les plus aimés d'Australie !",
  ],
  zebra: [
    "Chaque zèbre a un motif de rayures unique, comme des empreintes digitales !",
    "Les rayures du zèbre aident à confondre les prédateurs !",
    "Les zèbres dorment debout, comme les chevaux !",
    "Les bébés zèbres peuvent marcher quelques minutes après la naissance !",
    "Les zèbres vivent en groupes appelés troupeaux !",
    "Les zèbres peuvent courir jusqu'à 65 km/h !",
    "Les zèbres se saluent en se touchant le nez !",
    "Les zèbres sont apparentés aux chevaux et aux ânes !",
    "Les zèbres migrent sur des centaines de kilomètres !",
    "Les rayures des zèbres peuvent repousser les mouches !",
    "Les zèbres ont une excellente vision nocturne !",
    "Les poulains reconnaissent leur mère par ses rayures !",
    "Les zèbres se protègent en restant en groupe !",
    "Les zèbres peuvent vivre jusqu'à 25 ans dans la nature !",
    "Les zèbres utilisent leurs oreilles pour montrer leur humeur !",
    "Les zèbres mangent de l'herbe pendant de nombreuses heures !",
    "Les zèbres boivent de l'eau au moins une fois par jour !",
    "Les zèbres peuvent donner des coups de pied puissants !",
    "Les zèbres vivent dans les savanes et les plaines d'Afrique !",
    "Il existe trois espèces de zèbres dans le monde !",
  ],
  shark: [
    "Les requins existent depuis plus de 400 millions d'années !",
    "Les requins ont des rangées de dents qui se renouvellent toute leur vie !",
    "Le requin-baleine est le plus grand poisson et mange du plancton !",
    "Les requins peuvent détecter une goutte de sang à des kilomètres !",
    "Les requins n'ont pas d'os, leur squelette est en cartilage !",
    "Il existe plus de 500 espèces de requins dans le monde !",
    "Les requins doivent nager pour respirer !",
    "Les requins ont une excellente vision, même dans le noir !",
    "Les bébés requins savent nager dès la naissance !",
    "Le requin-marteau a une tête en forme de T !",
    "Les requins peuvent détecter les champs électriques des autres animaux !",
    "Le grand requin blanc peut sauter hors de l'eau pour chasser !",
    "Certains requins vivent dans les profondeurs de l'océan !",
    "Les requins aident à maintenir l'équilibre des océans !",
    "Les requins ont une peau rugueuse comme du papier de verre !",
    "Le requin-lanterne brille dans le noir !",
    "Les requins peuvent vivre jusqu'à 70 ans ou plus !",
    "Les requins nagent jusqu'à 50 km/h !",
    "Les requins perdent et remplacent des milliers de dents !",
    "La plupart des requins sont inoffensifs pour les humains !",
  ],
  whale: [
    "La baleine bleue est le plus grand animal ayant jamais existé !",
    "Le cœur d'une baleine bleue est de la taille d'une voiture !",
    "Les baleines communiquent avec des chants qui voyagent sur des milliers de km !",
    "Les baleines à bosse font des acrobaties en sautant hors de l'eau !",
    "Les baleines peuvent retenir leur souffle pendant plus d'une heure !",
    "Les bébés baleines boivent des centaines de litres de lait par jour !",
    "Les baleines migrent sur des milliers de kilomètres chaque année !",
    "La langue d'une baleine bleue pèse autant qu'un éléphant !",
    "Les baleines dorment avec la moitié du cerveau éveillée !",
    "Les cachalots plongent à plus de 2 000 mètres de profondeur !",
    "Les baleines sont des mammifères, pas des poissons !",
    "Une baleine bleue peut mesurer 30 mètres de long !",
    "Les baleines ont des poils sur le corps, généralement sur le menton !",
    "Les bébés baleines naissent par la queue pour ne pas se noyer !",
    "Le chant de la baleine à bosse peut durer des heures !",
    "Les baleines vivent dans tous les océans du monde !",
    "Certaines baleines peuvent vivre jusqu'à 200 ans !",
    "Les baleines projettent de l'eau par leur évent !",
    "Les baleines forment des liens forts avec leurs petits !",
    "La baleine bleue mange jusqu'à 4 tonnes de krill par jour !",
  ],
  crocodile: [
    "Les crocodiles existent depuis plus de 200 millions d'années !",
    "Les crocodiles peuvent rester immobiles pendant des heures !",
    "Les crocodiles ont la morsure la plus puissante du règne animal !",
    "Les crocodiles pleurent en mangeant, mais pas de tristesse !",
    "Les crocodiles peuvent vivre jusqu'à 70 ans !",
    "Le crocodile marin est le plus grand reptile du monde !",
    "Les crocodiles nagent à 30 km/h !",
    "Les bébés crocodiles font des sons dans l'œuf pour prévenir la mère !",
    "Les crocodiles avalent des pierres pour aider la digestion !",
    "La température du nid détermine le sexe des bébés !",
    "Les crocodiles retiennent leur souffle pendant plus d'une heure !",
    "Les crocodiles ont 80 dents qu'ils remplacent toute leur vie !",
    "Les crocodiles vivent en eau douce et en eau salée !",
    "La mère crocodile porte ses bébés dans sa bouche avec douceur !",
    "Les yeux des crocodiles brillent dans le noir !",
    "Les crocodiles régulent leur température en prenant le soleil !",
    "Les crocodiles sont des parents des dinosaures !",
    "Les crocodiles courent vite sur terre sur de courtes distances !",
    "Les crocodiles ont une ouïe excellente !",
    "Les crocodiles peuvent rester des mois sans manger !",
  ],
  fox: [
    "Les renards utilisent le champ magnétique terrestre pour chasser !",
    "Les renards sont apparentés aux chiens et aux loups !",
    "Les renards ont des moustaches sur les pattes pour s'orienter !",
    "Les renards peuvent entendre des animaux sous la neige !",
    "Les renards vivent sur tous les continents sauf l'Antarctique !",
    "Les renards sont nocturnes et chassent la nuit !",
    "Le renard arctique change de couleur selon la saison !",
    "Les renards produisent plus de 40 sons différents !",
    "Les renards sont très agiles et peuvent escalader des clôtures !",
    "Les renards vivent dans des terriers !",
    "Les renardeaux naissent sourds et aveugles !",
    "Les renards ont des pupilles verticales, comme les chats !",
    "Les renards peuvent courir à 50 km/h !",
    "Les renards sont des animaux solitaires la plupart du temps !",
    "La queue du renard sert à l'équilibre et au réchauffement !",
    "Les renards cachent de la nourriture pour plus tard !",
    "Les renardeaux jouent beaucoup quand ils sont petits !",
    "Les renards ont un odorat incroyable !",
    "Les renards peuvent vivre jusqu'à 14 ans !",
    "Le fennec a les plus grandes oreilles par rapport à son corps !",
  ],
  duck: [
    "Les canards ont des plumes imperméables !",
    "Les canards peuvent dormir avec un œil ouvert !",
    "Les canetons suivent la première chose qu'ils voient à la naissance !",
    "Les canards ont 3 paupières par œil !",
    "Les canards ne sentent pas le froid dans leurs pattes !",
    "Les canards peuvent voler jusqu'à 80 km/h !",
    "Les canards font coin-coin, mais le son ne fait pas d'écho !",
    "Les canetons savent nager quelques heures après la naissance !",
    "Les canards mangent des poissons, insectes, plantes et graines !",
    "Les canards migrent vers des endroits plus chauds en hiver !",
    "Les canards mâles sont plus colorés que les femelles !",
    "Les canards nagent en utilisant leurs pattes comme des rames !",
    "Les canards peuvent plonger pour chercher de la nourriture !",
    "Il existe plus de 120 espèces de canards dans le monde !",
    "Les canards vivent sur tous les continents sauf l'Antarctique !",
    "Les canards sont des oiseaux très sociaux !",
    "Les canards perdent toutes leurs plumes une fois par an !",
    "Les canards voient les couleurs mieux que les humains !",
    "Les canards peuvent vivre jusqu'à 20 ans !",
    "Les canetons savent nager dès leur premier jour de vie !",
  ],
  octopus: [
    "Les pieuvres ont 3 cœurs et du sang bleu !",
    "Les pieuvres peuvent changer de couleur en moins d'une seconde !",
    "Les pieuvres sont les invertébrés les plus intelligents !",
    "Les pieuvres ont 8 bras, chacun avec des ventouses !",
    "Les pieuvres peuvent ouvrir des bocaux et résoudre des puzzles !",
    "Les pieuvres n'ont pas d'os et peuvent se faufiler partout !",
    "Les pieuvres projettent de l'encre pour échapper aux prédateurs !",
    "Chaque bras de pieuvre a son propre mini-cerveau !",
    "Les pieuvres peuvent régénérer leurs bras perdus !",
    "La pieuvre mimétique imite l'apparence d'autres animaux !",
    "Les pieuvres vivent au fond de l'océan, dans des tanières !",
    "Les pieuvres sont les maîtres du camouflage !",
    "La pieuvre à anneaux bleus est l'un des animaux les plus venimeux !",
    "Les pieuvres femelles gardent leurs œufs sans manger !",
    "Les pieuvres ont une excellente vision !",
    "Les pieuvres utilisent des coquilles et des noix de coco comme abri !",
    "Les pieuvres nagent en expulsant des jets d'eau !",
    "Il existe plus de 300 espèces de pieuvres dans le monde !",
    "Les pieuvres ne vivent que 1 à 2 ans en moyenne !",
    "Les pieuvres goûtent la nourriture avec les ventouses de leurs bras !",
  ],
  tiger: [
    "Le tigre est le plus grand félin du monde !",
    "Chaque tigre a des rayures uniques, comme des empreintes digitales !",
    "Les tigres adorent nager et jouer dans l'eau !",
    "Les tigres peuvent courir jusqu'à 65 km/h !",
    "Les tigres chassent seuls, généralement la nuit !",
    "Un tigre peut manger 40 kg de viande en une fois !",
    "Les tigreaux restent avec leur mère jusqu'à 3 ans !",
    "Les tigres rugissent si fort qu'on les entend à 3 km !",
    "Il existe 6 sous-espèces de tigres dans le monde !",
    "Les tigres marquent leur territoire avec des griffures sur les arbres !",
    "Les tigres ont des griffes rétractiles cachées quand ils marchent !",
    "Le tigre de Sibérie est le plus grand, pesant jusqu'à 300 kg !",
    "Les tigres peuvent sauter jusqu'à 5 mètres de haut !",
    "Les tigres ont une vision nocturne 6 fois meilleure que la nôtre !",
    "Les tigres sont des animaux solitaires et territoriaux !",
    "Les rayures des tigres existent aussi sur leur peau !",
    "Les tigres blancs sont rares et ont des rayures pâles !",
    "Les tigres peuvent nager sur plusieurs kilomètres !",
    "Les tigres se trouvent en Asie !",
    "Les tigres sont menacés d'extinction et ont besoin de protection !",
  ],
};
