import type { AnimalId } from "./animals";

export const animalFunFactsIt: Record<AnimalId, string[]> = {
  cat: [
    "I gatti dormono fino a 16 ore al giorno!",
    "I gatti possono ruotare le orecchie di 180 gradi!",
    "Un gatto può saltare fino a 6 volte la propria lunghezza!",
    "I gatti hanno più di 20 tipi diversi di miagolio!",
    "Il naso di ogni gatto è unico, come un'impronta digitale!",
    "I gatti possono vedere al buio!",
    "I gatti passano il 30% della giornata a pulirsi!",
    "Un gatto ha 230 ossa, più degli esseri umani!",
    "I baffi del gatto lo aiutano a capire se passa negli spazi stretti!",
    "I gatti fanno le fusa quando sono felici, ma anche per guarirsi!",
    "I gatti possono correre a 48 chilometri all'ora!",
    "I gatti domestici esistono da più di 10.000 anni!",
    "Un gatto può sentire suoni che noi non possiamo!",
    "I gatti atterrano sempre sulle zampe grazie a un equilibrio incredibile!",
    "I gatti strofinano il muso sulle cose per marcare il territorio!",
    "Il gatto più vecchio del mondo ha vissuto 38 anni!",
    "I gatti hanno una terza palpebra nascosta!",
    "I gatti preferiscono l'acqua corrente a quella ferma!",
    "I gatti possono sentire i terremoti prima degli umani!",
    "Un gruppo di gatti si chiama colonia!",
  ],
  dog: [
    "L'olfatto del cane è 40 volte migliore di quello degli umani!",
    "I cani possono imparare più di 100 parole!",
    "Il cane più veloce può correre a 70 km all'ora!",
    "I cani sognano mentre dormono, proprio come noi!",
    "Il naso del cane è umido per catturare meglio gli odori!",
    "I cani scodinzolano verso destra quando sono felici!",
    "I cani vedono in tonalità di blu e giallo!",
    "L'udito dei cani è 4 volte migliore del nostro!",
    "Il cane più vecchio del mondo ha vissuto 30 anni!",
    "I cani sbadigliano quando vedono qualcuno sbadigliare, per empatia!",
    "Un cane può sentire l'umore del padrone dall'odore!",
    "Esistono più di 340 razze di cani nel mondo!",
    "I cani sudano solo attraverso i cuscinetti delle zampe!",
    "I cuccioli nascono sordi e ciechi!",
    "Il Labrador è la razza più popolare al mondo!",
    "I cani possono fiutare malattie negli esseri umani!",
    "Un cane adulto ha 42 denti!",
    "I cani girano in cerchio prima di sdraiarsi per istinto!",
    "I cani possono sentire suoni a 225 metri di distanza!",
    "Tre cani sono sopravvissuti al naufragio del Titanic!",
  ],
  elephant: [
    "Gli elefanti sono i più grandi animali terrestri del mondo!",
    "Gli elefanti possono riconoscersi allo specchio!",
    "Un elefante beve fino a 200 litri d'acqua al giorno!",
    "Gli elefanti hanno una memoria incredibile e non dimenticano mai un amico!",
    "Gli elefanti comunicano con suoni così gravi che non li sentiamo!",
    "Gli elefanti adorano fare bagni di fango per proteggersi dal sole!",
    "Gli elefanti possono pesare fino a 6 tonnellate!",
    "Gli elefanti usano la proboscide come una cannuccia per bere!",
    "Un elefantino pesa circa 100 chili alla nascita!",
    "Gli elefanti camminano in punta di dita!",
    "Gli elefanti sanno nuotare molto bene!",
    "La proboscide di un elefante ha più di 40.000 muscoli!",
    "Gli elefanti sono tristi quando un amico muore e fanno il lutto!",
    "Gli elefanti africani hanno orecchie a forma di Africa!",
    "Gli elefanti mangiano fino a 150 chili di cibo al giorno!",
    "Gli elefanti vivono in famiglie guidate da una femmina!",
    "Gli elefanti si salutano intrecciando le proboscidi!",
    "La pelle dell'elefante può essere spessa fino a 2,5 centimetri!",
    "Gli elefanti possono sentire le vibrazioni del terreno attraverso i piedi!",
    "Gli elefanti sono uno dei pochi animali che piangono di emozione!",
  ],
  rabbit: [
    "I conigli possono girare le orecchie in qualsiasi direzione!",
    "I conigli sono così felici che saltano e girano in aria! Si chiama binky!",
    "I denti dei conigli non smettono mai di crescere!",
    "I conigli possono vedere quasi a 360 gradi intorno a loro!",
    "Un coniglio può correre a 55 km all'ora!",
    "I conigli fanno le fusa quando sono felici, come i gatti!",
    "I conigli hanno più di 28 denti!",
    "I conigli muovono il naso fino a 120 volte al minuto!",
    "I conigli sono più attivi la mattina presto e al tramonto!",
    "I conigli possono fare salti alti 1 metro!",
    "Un gruppo di conigli si chiama colonia!",
    "I conigli si puliscono leccandosi le zampe, come i gatti!",
    "I conigli vivono in tane sotterranee!",
    "I conigli possono avere fino a 12 cuccioli alla volta!",
    "I conigli battono le zampe per avvertire del pericolo!",
    "I conigli adorano giocare con tunnel e scatole!",
    "I conigli a volte dormono con gli occhi aperti!",
    "I conigli possono imparare trucchi e il loro nome!",
    "I conigli selvatici vivono in quasi tutti i continenti!",
    "I conigli possono vivere fino a 12 anni!",
  ],
  bird: [
    "Alcuni uccelli possono imitare la voce umana!",
    "Il colibrì è l'unico uccello che vola all'indietro!",
    "Gli uccelli vedono più colori degli esseri umani!",
    "Lo struzzo è l'uccello più veloce nella corsa, a 70 km/h!",
    "Gli uccelli cantano per comunicare e marcare il territorio!",
    "Le piume degli uccelli sono più resistenti di quanto sembrino!",
    "I pappagalli possono vivere fino a 80 anni!",
    "Il colibrì batte le ali fino a 80 volte al secondo!",
    "Gli uccelli migrano per migliaia di chilometri ogni anno!",
    "L'uovo di struzzo è il più grande uovo del mondo!",
    "Gli uccelli hanno ossa cave per essere più leggeri in volo!",
    "I corvi sono così intelligenti che usano strumenti!",
    "Il più piccolo uccello del mondo è il colibrì-ape, con 5 cm!",
    "Gli uccelli possono dormire con metà del cervello sveglio!",
    "I fenicotteri sono rosa per via del cibo che mangiano!",
    "Esistono più di 10.000 specie di uccelli nel mondo!",
    "I pinguini sono uccelli, ma non volano!",
    "Gli uccelli ingoiano sassolini per aiutare la digestione!",
    "I gufi non possono muovere gli occhi, girano solo la testa!",
    "L'albatros può volare per anni senza posarsi a terra!",
  ],
  lion: [
    "Il ruggito del leone può essere sentito a 8 chilometri di distanza!",
    "I leoni dormono fino a 20 ore al giorno!",
    "Solo i leoni maschi hanno quella enorme criniera!",
    "Le leonesse sono le cacciatrici della famiglia!",
    "I leoni vivono in gruppi chiamati branchi!",
    "Un leone può correre a 80 km/h per brevi distanze!",
    "I cuccioli di leone nascono con macchie che scompaiono crescendo!",
    "I leoni strofinano le teste per salutarsi!",
    "La criniera del leone scurisce con l'età!",
    "I leoni possono saltare fino a 11 metri di distanza!",
    "I leoni sono chiamati Re della Giungla, ma vivono nella savana!",
    "Un leone può mangiare 40 chili di carne in una volta!",
    "I baffi del leone lo aiutano a sentire cosa c'è intorno!",
    "I leoni riposano sugli alberi per sfuggire al caldo!",
    "I cuccioli di leone giocano a lottare per imparare a cacciare!",
    "I maschi proteggono il territorio mentre le femmine cacciano!",
    "Il leone è il secondo felino più grande, dopo la tigre!",
    "I leoni possono vivere fino a 15 anni in natura!",
    "I leoni bevono acqua quando possono, ma resistono giorni senza!",
    "Un leone riconosce i membri del branco dal ruggito!",
  ],
  turtle: [
    "Alcune tartarughe possono vivere più di 100 anni!",
    "Il guscio della tartaruga fa parte del suo scheletro!",
    "Le tartarughe marine percorrono migliaia di chilometri nell'oceano!",
    "Le tartarughe esistono da più di 200 milioni di anni!",
    "Le tartarughe non hanno denti, hanno un becco come gli uccelli!",
    "La tartaruga liuto è la più grande tartaruga del mondo!",
    "Le tartarughe possono sentire quando tocchi il loro guscio!",
    "Le tartarughe marine tornano sulla stessa spiaggia per deporre le uova!",
    "Le tartarughe possono trattenere il respiro per ore sott'acqua!",
    "Il sesso dei piccoli di tartaruga dipende dalla temperatura della sabbia!",
    "Le tartarughe vedono i colori, incluso l'ultravioletto!",
    "Alcune tartarughe vanno in letargo in inverno sepolte nel fango!",
    "La tartaruga gigante delle Galápagos può pesare 400 chili!",
    "Le tartarughe hanno un ottimo senso dell'orientamento!",
    "Le tartarughe sono rettili, parenti dei dinosauri!",
    "Le tartarughe marine piangono per eliminare il sale dell'acqua di mare!",
    "Alcune tartarughe possono respirare dal sedere!",
    "Le tartarughe domestiche possono vivere più di 50 anni!",
    "Le tartarughe sono i rettili più antichi esistenti!",
    "I piccoli di tartaruga sono grandi come una moneta alla nascita!",
  ],
  butterfly: [
    "Le farfalle assaggiano il cibo con i piedi!",
    "Una farfalla inizia la vita come un bruco!",
    "Esistono più di 20.000 specie di farfalle nel mondo!",
    "Le ali delle farfalle sono trasparenti, i colori vengono da scaglie minuscole!",
    "Alcune farfalle migrano per migliaia di chilometri!",
    "Le farfalle non possono volare se hanno freddo!",
    "Le farfalle bevono il nettare dai fiori con una proboscide arrotolata!",
    "La farfalla monarca viaggia dal Canada al Messico ogni anno!",
    "Le farfalle vivono solo poche settimane!",
    "Le farfalle hanno bisogno del sole per scaldare le ali e volare!",
    "Alcune farfalle hanno motivi a occhio sulle ali per spaventare i predatori!",
    "La trasformazione da bruco a farfalla si chiama metamorfosi!",
    "Le farfalle vedono colori che gli umani non possono vedere!",
    "Dentro il bozzolo, il bruco si trasforma completamente in liquido!",
    "Alcune farfalle si nutrono di frutta marcia!",
    "Le farfalle battono le ali circa 5 volte al secondo!",
    "Le farfalle possono volare fino a 20 chilometri all'ora!",
    "La farfalla più grande del mondo ha 30 centimetri di apertura alare!",
    "Le farfalle si riscaldano aprendo le ali al sole come pannelli solari!",
    "Alcune farfalle hanno un sapore sgradevole per non essere mangiate!",
  ],
  frog: [
    "Le rane assorbono l'acqua attraverso la pelle, non bevono!",
    "Alcune rane sono così velenose da poter abbattere un elefante!",
    "Le rane ingoiano il cibo usando gli occhi per spingere!",
    "Esistono rane di tutti i colori dell'arcobaleno!",
    "Le rane gracidano per attirare una compagna!",
    "Alcune rane si congelano in inverno e si scongelano in primavera!",
    "Le rane iniziano la vita come girini nell'acqua!",
    "Le rane possono saltare 20 volte la lunghezza del loro corpo!",
    "La pelle delle rane è sempre umida!",
    "Esistono rane più piccole di un'unghia!",
    "Le rane velenose sono colorate per avvertire i predatori!",
    "Alcune rane portano i piccoli sulla schiena!",
    "Le rane esistono da più di 200 milioni di anni!",
    "Le rane possono vivere sia nell'acqua che sulla terra!",
    "La rana più grande del mondo pesa più di 3 chili!",
    "Le rane cambiano pelle regolarmente e mangiano quella vecchia!",
    "Gli occhi delle rane sono in cima alla testa per vedere fuori dall'acqua!",
    "Le rane sono molto importanti per controllare gli insetti!",
    "Esistono più di 7.000 specie di rane nel mondo!",
    "Alcune rane emettono suoni che sembrano uccelli che cantano!",
  ],
  horse: [
    "I cavalli possono dormire in piedi!",
    "Un cavallo può correre poche ore dopo la nascita!",
    "I cavalli vedono quasi a 360 gradi intorno a loro!",
    "I denti dei cavalli occupano più spazio nella testa del cervello!",
    "I cavalli possono riconoscere le emozioni sul viso umano!",
    "Il cavallo più veloce del mondo ha raggiunto i 70 km/h!",
    "I cavalli hanno la visione più ampia di tutti i mammiferi terrestri!",
    "I cavalli comunicano con le orecchie, gli occhi e le espressioni!",
    "Un cavallo adulto ha 40 denti!",
    "I cavalli possono vivere fino a 30 anni!",
    "I cavalli dormono solo 2-3 ore al giorno!",
    "Gli zoccoli dei cavalli sono fatti dello stesso materiale delle nostre unghie!",
    "I cavalli possono correre il giorno stesso della nascita!",
    "I cavalli sono erbivori e adorano carote e mele!",
    "Un cavallo beve tra 30 e 50 litri d'acqua al giorno!",
    "I cavalli hanno un'eccellente memoria!",
    "I cavalli selvatici vivono in branchi guidati da una giumenta!",
    "I cavalli non possono vomitare!",
    "Il cavallo più piccolo del mondo è alto solo 44 centimetri!",
    "I cavalli esistono da più di 50 milioni di anni!",
  ],
  owl: [
    "I gufi possono girare la testa fino a 270 gradi!",
    "I gufi hanno un udito così fine che cacciano nel buio totale!",
    "Gli occhi dei gufi non si muovono, per questo girano la testa!",
    "Le piume dei gufi sono silenziose, volano senza fare rumore!",
    "Alcuni gufi sono più piccoli della tua mano!",
    "I gufi ingoiano la preda intera e poi rigurgitano le ossa!",
    "I gufi hanno tre palpebre su ogni occhio!",
    "I gufi possono sentire un topo camminare sotto la neve!",
    "Gli occhi dei gufi sono così grandi che non possono muoversi!",
    "I gufi si trovano in tutti i continenti tranne l'Antartide!",
    "La civetta delle tane vive in buchi nel terreno!",
    "I gufi girano la testa perché non possono muovere gli occhi!",
    "Esistono più di 200 specie di gufi nel mondo!",
    "I gufi sono incredibili cacciatori notturni!",
    "Il gufo delle nevi è quasi tutto bianco!",
    "I gufi hanno artigli super forti per afferrare le prede!",
    "Un gruppo di gufi si chiama parlamento!",
    "I piccoli di gufo si chiamano pulcini!",
    "I gufi possono girare la testa da entrambi i lati!",
    "Il gufo più grande del mondo ha quasi 2 metri di apertura alare!",
  ],
  penguin: [
    "I pinguini non volano, ma sono ottimi nuotatori!",
    "I pinguini possono trattenere il respiro per 20 minuti sott'acqua!",
    "Il pinguino imperatore è il più grande, alto quasi 1 metro!",
    "I pinguini vivono al freddo, ma non tutti nella neve!",
    "I pinguini si riscaldano stando stretti insieme!",
    "I papà pinguini covano le uova sui propri piedi!",
    "I pinguini possono nuotare a 35 chilometri all'ora!",
    "Esistono 18 specie di pinguini nel mondo!",
    "I pinguini bevono acqua salata e filtrano il sale!",
    "I pinguini riconoscono il partner dal canto!",
    "Il pinguino più piccolo del mondo è alto solo 30 centimetri!",
    "I pinguini cambiano le piume una volta all'anno!",
    "I pinguini scivolano sulla pancia nella neve per spostarsi!",
    "I pinguini sono bianchi e neri per mimetizzarsi nell'acqua!",
    "I pinguini possono immergersi a più di 500 metri di profondità!",
    "I pinguini imperatore sopportano temperature di -60 gradi!",
    "I pinguini sono molto fedeli e riconoscono il partner ogni anno!",
    "I piccoli di pinguino stanno in asilo mentre i genitori cacciano!",
    "I pinguini mangiano pesci, calamari e krill!",
    "I pinguini esistono da più di 60 milioni di anni!",
  ],
  monkey: [
    "Le scimmie usano strumenti come pietre per aprire la frutta!",
    "Le scimmie si abbracciano per mostrare amicizia!",
    "La scimmia ragno usa la coda come una mano extra!",
    "Esistono più di 260 specie di scimmie nel mondo!",
    "Le scimmie vivono in gruppi e si prendono cura l'una dell'altra!",
    "Le scimmie possono riconoscere il proprio riflesso nello specchio!",
    "Le scimmie si spulciano a vicenda per rafforzare l'amicizia!",
    "La scimmia più piccola del mondo sta nel palmo della mano!",
    "Le scimmie possono imparare il linguaggio dei segni!",
    "Le scimmie urlatrici si sentono a 5 chilometri di distanza!",
    "Le scimmie giapponesi fanno il bagno nelle sorgenti calde in inverno!",
    "I cebi sono considerati le scimmie più intelligenti delle Americhe!",
    "Le scimmie sbadigliano quando vedono un'altra scimmia sbadigliare!",
    "Le scimmie notturne sono le uniche che vedono bene al buio!",
    "Le scimmie usano suoni diversi per segnalare i tipi di predatori!",
    "La nasica ha il naso più grande di tutti i primati!",
    "I cuccioli di scimmia si aggrappano alla pancia della mamma per spostarsi!",
    "Le scimmie sono i nostri parenti più stretti nel regno animale!",
    "Le scimmie possono vivere fino a 40 anni in natura!",
    "Le scimmie americane hanno la coda prensile, quelle africane no!",
  ],
  giraffe: [
    "La giraffa è l'animale più alto del mondo, arrivando a 6 metri!",
    "La lingua della giraffa è lunga fino a 50 centimetri!",
    "Ogni giraffa ha un motivo di macchie unico, come le impronte digitali!",
    "Le giraffe dormono solo 30 minuti al giorno!",
    "Il cuore della giraffa pesa 11 chili!",
    "I cuccioli di giraffa nascono già alti quasi 2 metri!",
    "La lingua della giraffa è viola per proteggersi dal sole!",
    "Le giraffe camminano muovendo le due zampe dello stesso lato insieme!",
    "Le giraffe possono correre a 55 chilometri all'ora!",
    "Il collo della giraffa ha solo 7 vertebre, come il nostro!",
    "Le giraffe si sdraiano raramente, dormono anche in piedi!",
    "Le giraffe bevono acqua allargando bene le zampe anteriori!",
    "Le giraffe combattono colpendosi con il collo!",
    "Le giraffe vivono nella savana africana!",
    "La giraffa può vedere per chilometri grazie alla sua altezza!",
    "Le giraffe mangiano fino a 35 chili di foglie al giorno!",
    "Le giraffe sono amiche degli uccelli che mangiano i parassiti sulla loro pelle!",
    "Il cucciolo di giraffa cade da 2 metri alla nascita e si alza in 30 minuti!",
    "Le giraffe non hanno corde vocali!",
    "Le giraffe sono animali molto pacifici!",
  ],
  bear: [
    "Gli orsi possono sentire il cibo a 30 chilometri di distanza!",
    "Gli orsi polari hanno la pelle nera sotto la pelliccia bianca!",
    "Gli orsi vanno in letargo in inverno e non mangiano per mesi!",
    "L'orso è uno degli animali più forti del mondo!",
    "Il panda gigante mangia bambù quasi tutto il giorno!",
    "Gli orsi possono correre a 55 chilometri all'ora!",
    "I cuccioli di orso nascono ciechi e senza pelo!",
    "Gli orsi sono bravissimi ad arrampicarsi sugli alberi!",
    "L'orso polare è il più grande carnivoro terrestre!",
    "Gli orsi bruni possono pesare fino a 600 chili!",
    "Il panda gigante mangia 38 chili di bambù al giorno!",
    "Gli orsi si alzano sulle zampe posteriori per vedere meglio!",
    "L'orso dagli occhiali è l'unico orso del Sudamerica!",
    "Gli orsi polari nuotano per centinaia di chilometri!",
    "Il più piccolo orso del mondo è l'orso malese!",
    "Gli orsi hanno un eccellente senso dell'olfatto!",
    "Gli orsi vivono in tutti i continenti tranne Africa e Australia!",
    "I cuccioli di panda nascono grandi come un bastoncino di burro!",
    "Gli orsi possono vivere fino a 30 anni in natura!",
    "Gli orsi adorano il miele e sopportano le punture delle api!",
  ],
  snake: [
    "I serpenti non hanno palpebre, dormono con gli occhi aperti!",
    "I serpenti sentono gli odori con la lingua!",
    "Alcuni serpenti possono volare planando da un albero all'altro!",
    "I serpenti fanno la muta diverse volte all'anno cambiando pelle!",
    "Il serpente più grande del mondo può misurare 10 metri!",
    "I serpenti non hanno orecchie ma sentono le vibrazioni del terreno!",
    "Alcuni serpenti possono mangiare prede più grandi della loro testa!",
    "I serpenti a sonagli scuotono la coda per avvertire del pericolo!",
    "I serpenti esistono da più di 100 milioni di anni!",
    "I serpenti sono rettili a sangue freddo!",
    "Il cobra reale è il serpente velenoso più grande del mondo!",
    "Alcuni serpenti si prendono cura delle uova fino alla schiusa!",
    "I serpenti sanno nuotare molto bene!",
    "I boa e i pitoni soffocano le prede avvolgendosi!",
    "Esistono più di 3.000 specie di serpenti nel mondo!",
    "La maggior parte dei serpenti è innocua per gli esseri umani!",
    "I serpenti aiutano a controllare la popolazione dei roditori!",
    "Il mamba nero è il serpente più veloce, a 20 km/h!",
    "I serpenti ingoiano il cibo intero!",
    "Alcuni serpenti di mare possono trattenere il respiro per 2 ore!",
  ],
  bee: [
    "Le api visitano fino a 5.000 fiori in un solo giorno!",
    "Le api danzano per indicare dove si trovano i fiori!",
    "Un'ape regina può deporre 2.000 uova al giorno!",
    "Il miele non scade mai, miele di 3.000 anni è ancora commestibile!",
    "Le api battono le ali 200 volte al secondo!",
    "Le api sono responsabili dell'impollinazione di un terzo del nostro cibo!",
    "Un alveare può ospitare 80.000 api!",
    "Le api producono miele rigurgitando il nettare!",
    "Le api operaie vivono solo 6 settimane!",
    "Le api vedono i colori, incluso l'ultravioletto!",
    "Le api sanno contare fino a 4!",
    "Le api comunicano attraverso danze e feromoni!",
    "Per fare 1 chilo di miele, le api visitano 4 milioni di fiori!",
    "L'ape regina può vivere fino a 5 anni!",
    "Le api hanno 5 occhi: 2 grandi e 3 piccoli!",
    "Il ronzio delle api viene dal battito delle ali!",
    "Le api mantengono l'alveare esattamente a 35 gradi!",
    "Le api esistono da più di 100 milioni di anni!",
    "Senza le api, molti frutti e verdure scomparirebbero!",
    "I fuchi maschi non pungono, solo le femmine pungono!",
  ],
  pig: [
    "I maiali sono intelligenti quanto i cani!",
    "I maiali non sudano, per questo si rotolano nel fango!",
    "I maiali hanno un olfatto incredibile, trovano i tartufi sottoterra!",
    "I maiali possono imparare trucchi e giocare ai videogiochi!",
    "I maiali comunicano con più di 20 suoni diversi!",
    "I maiali sognano quando dormono, come noi!",
    "Il maiale più piccolo del mondo pesa solo 6 chili!",
    "I maiali possono correre a 18 chilometri all'ora!",
    "I maiali sono molto puliti e fanno i bisogni lontano da dove dormono!",
    "I maiali adorano grattarsi la schiena contro gli alberi!",
    "I maialini imparano il loro nome in sole due settimane!",
    "I maiali si riconoscono allo specchio!",
    "I maiali hanno un'eccellente memoria a lungo termine!",
    "I maiali scodinzolano quando sono felici, come i cani!",
    "I maiali sanno nuotare molto bene!",
    "I maiali vivono in gruppi e sono molto socievoli!",
    "I maiali esistono da più di 40 milioni di anni!",
    "I maiali adorano le grattine sulla pancia!",
    "I maiali selvatici si chiamano cinghiali!",
    "I maiali hanno 44 denti, più degli esseri umani!",
  ],
  panda: [
    "I panda giganti mangiano bambù fino a 14 ore al giorno!",
    "Un panda adulto può mangiare 38 kg di bambù al giorno!",
    "I cuccioli di panda nascono rosa e senza pelo!",
    "I panda hanno un osso speciale nel polso che funziona come un pollice!",
    "I panda giganti vivono nelle montagne della Cina!",
    "I panda passano la maggior parte del tempo a mangiare e dormire!",
    "I panda sono ottimi nuotatori!",
    "I panda marcano il territorio strofinandosi contro gli alberi!",
    "Un cucciolo di panda pesa solo 100 grammi alla nascita!",
    "I panda hanno una dieta quasi al 100% vegetariana!",
    "I panda vivono tra i 20 e i 30 anni in natura!",
    "I panda sono eccellenti arrampicatori di alberi!",
    "Il pelo bianco e nero del panda lo aiuta a mimetizzarsi!",
    "I panda hanno mascelle super forti per masticare il bambù!",
    "I panda giganti sono solitari e preferiscono vivere da soli!",
    "I cuccioli di panda restano con la mamma fino a 2 anni!",
    "I panda sono stati tolti dalla lista delle specie in pericolo!",
    "I panda emettono suoni simili a belati per comunicare!",
    "I panda hanno pupille verticali, come i gatti!",
    "Il panda è il simbolo della conservazione della natura!",
  ],
  koala: [
    "I koala dormono fino a 22 ore al giorno!",
    "I koala si nutrono quasi esclusivamente di foglie di eucalipto!",
    "Le impronte digitali dei koala sono quasi identiche a quelle umane!",
    "I cuccioli di koala restano nel marsupio della mamma per 6 mesi!",
    "I koala raramente bevono acqua, si idratano con le foglie!",
    "I koala hanno due pollici per mano per afferrarsi meglio!",
    "I koala non sono orsi, sono marsupiali!",
    "I koala vivono solo in Australia!",
    "I koala hanno un naso grande per sentire le foglie migliori!",
    "I cuccioli di koala mangiano una pappa speciale prodotta dalla mamma!",
    "I koala possono vivere fino a 18 anni in natura!",
    "I koala hanno una pelliccia spessa e morbida che li protegge dalla pioggia!",
    "I koala abbracciano gli alberi per rinfrescarsi!",
    "I koala maschi marcano il territorio strofinando il petto sugli alberi!",
    "I koala hanno un cervello piccolo rispetto al corpo!",
    "I koala emettono suoni gravi e forti per comunicare!",
    "I koala mangiano circa 500 grammi di foglie al giorno!",
    "I koala sono animali notturni, più attivi di notte!",
    "I koala hanno artigli affilati per arrampicarsi!",
    "I koala sono uno degli animali più amati dell'Australia!",
  ],
  zebra: [
    "Ogni zebra ha un disegno di strisce unico, come le impronte digitali!",
    "Le strisce della zebra aiutano a confondere i predatori!",
    "Le zebre dormono in piedi, come i cavalli!",
    "I puledri di zebra camminano pochi minuti dopo la nascita!",
    "Le zebre vivono in gruppi chiamati branchi!",
    "Le zebre possono correre fino a 65 km/h!",
    "Le zebre si salutano toccandosi il naso!",
    "Le zebre sono parenti dei cavalli e degli asini!",
    "Le zebre migrano per centinaia di chilometri!",
    "Le strisce delle zebre possono respingere mosche e insetti!",
    "Le zebre hanno un'eccellente visione notturna!",
    "I puledri riconoscono la mamma dal disegno delle strisce!",
    "Le zebre si proteggono restando in gruppo!",
    "Le zebre possono vivere fino a 25 anni in natura!",
    "Le zebre usano le orecchie per mostrare il loro umore!",
    "Le zebre mangiano erba per molte ore al giorno!",
    "Le zebre bevono acqua almeno una volta al giorno!",
    "Le zebre possono sferrare calci potenti per difendersi!",
    "Le zebre vivono nelle savane e pianure dell'Africa!",
    "Esistono tre specie di zebre nel mondo!",
  ],
  crocodile: [
    "I coccodrilli esistono da oltre 200 milioni di anni!",
    "I coccodrilli possono restare immobili per ore aspettando una preda!",
    "I coccodrilli hanno il morso più potente di tutti gli animali!",
    "I coccodrilli piangono mentre mangiano, ma non di tristezza!",
    "I coccodrilli possono vivere fino a 70 anni!",
    "Il coccodrillo marino è il rettile più grande del mondo!",
    "I coccodrilli possono nuotare a 30 km/h!",
    "I cuccioli di coccodrillo emettono suoni nell'uovo per avvisare la mamma!",
    "I coccodrilli ingoiano pietre per aiutare la digestione!",
    "La temperatura del nido determina il sesso dei cuccioli!",
    "I coccodrilli possono trattenere il respiro per più di un'ora!",
    "I coccodrilli hanno 80 denti e li cambiano per tutta la vita!",
    "I coccodrilli vivono sia in acqua dolce che salata!",
    "La mamma coccodrillo porta i cuccioli in bocca con delicatezza!",
    "Gli occhi dei coccodrilli brillano al buio!",
    "I coccodrilli regolano la temperatura prendendo il sole!",
    "I coccodrilli sono parenti dei dinosauri!",
    "I coccodrilli possono correre veloci sulla terra per brevi tratti!",
    "I coccodrilli hanno un udito eccellente!",
    "I coccodrilli possono restare mesi senza mangiare!",
  ],
  fox: [
    "Le volpi usano il campo magnetico terrestre per cacciare!",
    "Le volpi sono imparentate con i cani e i lupi!",
    "Le volpi hanno baffi sulle zampe per orientarsi!",
    "Le volpi possono sentire animali sotto la neve!",
    "Le volpi vivono in tutti i continenti tranne l'Antartide!",
    "Le volpi sono notturne e cacciano di notte!",
    "La volpe artica cambia colore con le stagioni!",
    "Le volpi producono più di 40 suoni diversi!",
    "Le volpi sono molto agili e possono scalare recinzioni!",
    "Le volpi vivono in tane!",
    "I cuccioli di volpe nascono sordi e ciechi!",
    "Le volpi hanno pupille verticali, come i gatti!",
    "Le volpi possono correre a 50 km/h!",
    "Le volpi sono animali solitari la maggior parte del tempo!",
    "La coda della volpe serve per l'equilibrio e il calore!",
    "Le volpi nascondono il cibo per mangiarlo dopo!",
    "I cuccioli di volpe giocano molto da piccoli!",
    "Le volpi hanno un olfatto incredibile!",
    "Le volpi possono vivere fino a 14 anni!",
    "Il fennec ha le orecchie più grandi in proporzione al corpo!",
  ],
  duck: [
    "Le anatre hanno piume impermeabili!",
    "Le anatre possono dormire con un occhio aperto!",
    "I anatroccoli seguono la prima cosa che vedono alla nascita!",
    "Le anatre hanno 3 palpebre per occhio!",
    "Le anatre non sentono freddo nelle zampe, anche in acqua gelata!",
    "Le anatre possono volare fino a 80 km/h!",
    "Le anatre fanno qua qua, ma il suono non fa eco!",
    "Gli anatroccoli sanno nuotare poche ore dopo la nascita!",
    "Le anatre mangiano pesci, insetti, piante e semi!",
    "Le anatre migrano verso luoghi più caldi in inverno!",
    "I maschi di anatra sono più colorati delle femmine!",
    "Le anatre nuotano usando le zampe come remi!",
    "Le anatre possono tuffarsi per cercare cibo sul fondo!",
    "Esistono più di 120 specie di anatre nel mondo!",
    "Le anatre vivono in tutti i continenti tranne l'Antartide!",
    "Le anatre sono uccelli molto sociali e vivono in gruppi!",
    "Le anatre cambiano tutte le piume una volta all'anno!",
    "Le anatre vedono i colori meglio degli esseri umani!",
    "Le anatre possono vivere fino a 20 anni!",
    "Gli anatroccoli sanno nuotare dal primo giorno di vita!",
  ],
  tiger: [
    "La tigre è il felino più grande del mondo!",
    "Ogni tigre ha strisce uniche, come impronte digitali!",
    "Le tigri adorano nuotare e giocare nell'acqua!",
    "Le tigri possono correre fino a 65 km/h!",
    "Le tigri cacciano da sole, di solito di notte!",
    "Una tigre può mangiare 40 kg di carne in una volta!",
    "I cuccioli di tigre restano con la mamma fino a 3 anni!",
    "Le tigri ruggiscono così forte che si sentono a 3 km!",
    "Esistono 6 sottospecie di tigri nel mondo!",
    "Le tigri marcano il territorio con graffi sugli alberi!",
    "Le tigri hanno artigli retrattili nascosti quando camminano!",
    "La tigre siberiana è la più grande, può pesare 300 kg!",
    "Le tigri possono saltare fino a 5 metri di altezza!",
    "Le tigri hanno visione notturna 6 volte migliore della nostra!",
    "Le tigri sono animali solitari e territoriali!",
    "Le strisce delle tigri esistono anche sulla pelle!",
    "Le tigri bianche sono rare e hanno strisce chiare!",
    "Le tigri possono nuotare per diversi chilometri!",
    "Le tigri si trovano in Asia!",
    "Le tigri sono in pericolo di estinzione e hanno bisogno di protezione!",
  ],
};
