import type { AnimalId } from "./animals";

export const animalFunFactsEn: Record<AnimalId, string[]> = {
  cat: [
    "Cats sleep up to 16 hours a day!",
    "Cats can rotate their ears 180 degrees!",
    "A cat can jump up to 6 times its own length!",
    "Cats have over 20 different types of meows!",
    "Every cat's nose print is unique, like a human fingerprint!",
    "Cats can see in the dark!",
    "Cats spend 30% of the day grooming themselves!",
    "A cat has 230 bones, more than humans!",
    "A cat's whiskers help measure if it fits in tight spaces!",
    "Cats purr when happy, but also to heal themselves!",
    "Cats can run at 48 kilometers per hour!",
    "Domestic cats have existed for over 10,000 years!",
    "A cat can hear sounds we can't!",
    "Cats always land on their feet thanks to amazing balance!",
    "Cats rub their face on things to mark territory!",
    "The oldest cat ever lived to be 38 years old!",
    "Cats have a hidden third eyelid!",
    "Cats prefer running water over still water!",
    "Cats can sense earthquakes before humans!",
    "A group of cats is called a clowder!",
  ],
  dog: [
    "A dog's sense of smell is 40 times better than humans!",
    "Dogs can learn over 100 words!",
    "The fastest dog can run at 70 km per hour!",
    "Dogs dream while they sleep, just like us!",
    "A dog's nose is wet to better capture scents!",
    "Dogs wag their tail to the right when happy!",
    "Dogs see in shades of blue and yellow!",
    "A dog's hearing is 4 times better than ours!",
    "The oldest dog ever lived to be 30 years old!",
    "Dogs yawn when they see someone yawning, out of empathy!",
    "A dog can sense its owner's mood by smell!",
    "There are over 340 dog breeds in the world!",
    "Dogs only sweat through their paw pads!",
    "Puppies are born deaf and blind!",
    "The Labrador is the most popular breed in the world!",
    "Dogs can sniff out diseases in humans!",
    "An adult dog has 42 teeth!",
    "Dogs spin in circles before lying down by instinct!",
    "Dogs can hear sounds from 225 meters away!",
    "Three dogs survived the sinking of the Titanic!",
  ],
  elephant: [
    "Elephants are the largest land animals in the world!",
    "Elephants can recognize themselves in a mirror!",
    "An elephant drinks up to 200 liters of water a day!",
    "Elephants have incredible memories and never forget a friend!",
    "Elephants communicate with sounds so low we can't hear them!",
    "Elephants love mud baths to protect from the sun!",
    "Elephants can weigh up to 6 tons!",
    "Elephants use their trunk like a straw to drink water!",
    "A baby elephant weighs about 100 kilograms at birth!",
    "Elephants walk on the tips of their toes!",
    "Elephants are great swimmers!",
    "An elephant's trunk has over 40,000 muscles!",
    "Elephants mourn when a friend dies!",
    "African elephants have ears shaped like Africa!",
    "Elephants eat up to 150 kilograms of food a day!",
    "Elephants live in families led by a female!",
    "Elephants greet each other by intertwining their trunks!",
    "An elephant's skin can be 2.5 centimeters thick!",
    "Elephants can sense vibrations through their feet!",
    "Elephants are one of the few animals that cry from emotion!",
  ],
  rabbit: [
    "Rabbits can turn their ears in any direction!",
    "Rabbits are so happy they jump and twist in the air! It's called a binky!",
    "Rabbit teeth never stop growing!",
    "Rabbits can see almost 360 degrees around them!",
    "A rabbit can run at 55 km per hour!",
    "Rabbits purr when happy, just like cats!",
    "Rabbits have more than 28 teeth!",
    "Rabbits wiggle their nose up to 120 times per minute!",
    "Rabbits are most active at dawn and dusk!",
    "Rabbits can jump up to 1 meter high!",
    "A group of rabbits is called a colony!",
    "Rabbits groom themselves by licking their paws, like cats!",
    "Rabbits live in underground burrows!",
    "Rabbits can have up to 12 babies at once!",
    "Rabbits thump their feet to warn of danger!",
    "Rabbits love playing with tunnels and boxes!",
    "Rabbits sometimes sleep with their eyes open!",
    "Rabbits can learn tricks and their own name!",
    "Wild rabbits live on almost every continent!",
    "Rabbits can live up to 12 years!",
  ],
  bird: [
    "Some birds can mimic the human voice!",
    "The hummingbird is the only bird that can fly backwards!",
    "Birds see more colors than humans!",
    "The ostrich is the fastest running bird at 70 km per hour!",
    "Birds sing to communicate and mark territory!",
    "Bird feathers are stronger than they look!",
    "Parrots can live up to 80 years!",
    "A hummingbird flaps its wings up to 80 times per second!",
    "Birds migrate thousands of kilometers every year!",
    "The ostrich egg is the largest egg in the world!",
    "Birds have hollow bones to be lighter for flying!",
    "Crows are so smart they use tools!",
    "The smallest bird is the bee hummingbird at 5 centimeters!",
    "Birds can sleep with half their brain awake!",
    "Flamingos are pink because of the food they eat!",
    "There are over 10,000 species of birds in the world!",
    "Penguins are birds, but they can't fly!",
    "Birds swallow small stones to help digest food!",
    "Owls can't move their eyes, they turn their whole head!",
    "The albatross can fly for years without landing!",
  ],
  fish: [
    "There are fish that glow in the deep sea!",
    "Some fish can fly above the water!",
    "The clownfish lives inside sea anemones!",
    "Fish don't have eyelids, they sleep with eyes open!",
    "The whale shark is the largest fish in the world!",
    "Some fish change color to hide from predators!",
    "Fish use gills to breathe underwater!",
    "There are over 30,000 species of fish in the world!",
    "The seahorse is one of the few fish where the dad carries the babies!",
    "Fish can sense vibrations in the water with a lateral line!",
    "The swordfish can swim at 110 kilometers per hour!",
    "Some fish live in the darkest depths of the ocean!",
    "Goldfish can remember things for months!",
    "The pufferfish fills with water to look bigger and scare predators!",
    "Fish travel in schools to protect themselves!",
    "Sharks have existed for over 400 million years!",
    "Some fish build nests to protect their eggs!",
    "The ocean sunfish is the heaviest bony fish in the world!",
    "Fish can taste the water around them!",
    "The archerfish spits jets of water to knock down insects!",
  ],
  lion: [
    "A lion's roar can be heard from 8 kilometers away!",
    "Lions sleep up to 20 hours a day!",
    "Only male lions have that huge mane!",
    "Lionesses are the hunters of the family!",
    "Lions live in groups called prides!",
    "A lion can run at 80 km per hour in short bursts!",
    "Lion cubs are born with spots that fade as they grow!",
    "Lions rub heads with each other to say hello!",
    "A lion's mane gets darker as it ages!",
    "Lions can leap up to 11 meters far!",
    "Lions are called King of the Jungle, but live in the savanna!",
    "A lion can eat 40 kilograms of meat in one sitting!",
    "A lion's whiskers help it sense its surroundings!",
    "Lions rest in trees to escape the heat!",
    "Lion cubs play-fight to learn how to hunt!",
    "Male lions protect the territory while females hunt!",
    "The lion is the second largest cat after the tiger!",
    "Lions can live up to 15 years in the wild!",
    "Lions drink water whenever they can, but survive days without it!",
    "A lion recognizes pride members by their roar!",
  ],
  turtle: [
    "Some turtles can live over 100 years!",
    "A turtle's shell is part of its skeleton!",
    "Sea turtles travel thousands of kilometers across the ocean!",
    "Turtles have existed for over 200 million years!",
    "Turtles don't have teeth, they have a beak like birds!",
    "The leatherback is the largest turtle in the world!",
    "Turtles can feel when you touch their shell!",
    "Sea turtles return to the same beach where they were born to lay eggs!",
    "Turtles can hold their breath for hours underwater!",
    "The sex of baby turtles depends on the sand temperature!",
    "Turtles can see colors, including ultraviolet!",
    "Some turtles hibernate in winter buried in mud!",
    "The giant Galápagos tortoise can weigh 400 kilograms!",
    "Turtles have an excellent sense of direction!",
    "Turtles are reptiles, relatives of dinosaurs!",
    "Sea turtles cry to get rid of salt from seawater!",
    "Some turtles can breathe through their rear end!",
    "Pet turtles can live over 50 years!",
    "Turtles are the oldest living reptiles!",
    "Baby turtles are the size of a coin when born!",
  ],
  butterfly: [
    "Butterflies taste food with their feet!",
    "A butterfly starts life as a caterpillar!",
    "There are over 20,000 species of butterflies in the world!",
    "Butterfly wings are transparent — the colors come from tiny scales!",
    "Some butterflies migrate thousands of kilometers!",
    "Butterflies can't fly if they're too cold!",
    "Butterflies drink nectar from flowers with a coiled tongue!",
    "The monarch butterfly travels from Canada to Mexico every year!",
    "Butterflies only live a few weeks!",
    "Butterflies need the sun to warm their wings to fly!",
    "Some butterflies have eye-like patterns on wings to scare predators!",
    "The transformation from caterpillar to butterfly is called metamorphosis!",
    "Butterflies can see colors that humans can't!",
    "Inside the cocoon, the caterpillar turns completely into liquid!",
    "Some butterflies feed on rotting fruit!",
    "Butterflies flap their wings about 5 times per second!",
    "Butterflies can fly at up to 20 kilometers per hour!",
    "The largest butterfly has a 30-centimeter wingspan!",
    "Butterflies warm up by opening their wings to the sun like solar panels!",
    "Some butterflies taste bad so predators won't eat them!",
  ],
  frog: [
    "Frogs absorb water through their skin — they don't drink!",
    "Some frogs are so poisonous they could knock out an elephant!",
    "Frogs swallow food using their eyes to push it down!",
    "There are frogs of every color of the rainbow!",
    "Frogs croak to attract a mate!",
    "Some frogs can freeze in winter and thaw in spring!",
    "Frogs start life as tadpoles in the water!",
    "Frogs can jump up to 20 times their body length!",
    "A frog's skin is always moist!",
    "There are frogs smaller than a fingernail!",
    "Poisonous frogs are colorful to warn predators!",
    "Some frogs carry their babies on their backs!",
    "Frogs have existed for over 200 million years!",
    "Frogs can live both in water and on land!",
    "The largest frog weighs over 3 kilograms!",
    "Frogs shed their skin regularly and eat the old skin!",
    "Frog eyes sit on top of their head to see above water!",
    "Frogs are very important for controlling insects!",
    "There are over 7,000 species of frogs in the world!",
    "Some frogs make sounds that sound like birds singing!",
  ],
  horse: [
    "Horses can sleep standing up!",
    "A horse can run just hours after being born!",
    "Horses can see almost 360 degrees around them!",
    "Horse teeth take up more space in the head than the brain!",
    "Horses can recognize emotions on a human face!",
    "The fastest horse reached 70 km per hour!",
    "Horses have the largest eyes of any land mammal!",
    "Horses communicate with their ears, eyes, and expressions!",
    "An adult horse has 40 teeth!",
    "Horses can live up to 30 years!",
    "Horses sleep only 2 to 3 hours a day!",
    "Horse hooves are made of the same material as our nails!",
    "Horses can run on the same day they are born!",
    "Horses are herbivores and love carrots and apples!",
    "A horse drinks between 30 and 50 liters of water a day!",
    "Horses have an excellent memory!",
    "Wild horses live in herds led by a mare!",
    "Horses can't vomit!",
    "The smallest horse is only 44 centimeters tall!",
    "Horses have existed for over 50 million years!",
  ],
  owl: [
    "Owls can turn their head up to 270 degrees!",
    "Owls have such good hearing they can hunt in total darkness!",
    "Owl eyes don't move, so they turn their whole head!",
    "Owl feathers are silent — they fly without making noise!",
    "Some owls are smaller than your hand!",
    "Owls swallow prey whole and later spit out the bones!",
    "Owls have three eyelids on each eye!",
    "Owls can hear a mouse walking under the snow!",
    "Owl eyes are so big they can't move inside the skull!",
    "Owls are found on every continent except Antarctica!",
    "The burrowing owl lives in holes in the ground!",
    "Owls turn their head because they can't move their eyes!",
    "There are over 200 species of owls in the world!",
    "Owls are incredible nocturnal hunters!",
    "The snowy owl is almost entirely white!",
    "Owls have super strong talons to grab prey!",
    "A group of owls is called a parliament!",
    "Baby owls are called owlets!",
    "Owls can turn their head both ways!",
    "The largest owl has nearly a 2-meter wingspan!",
  ],
  penguin: [
    "Penguins don't fly, but they're excellent swimmers!",
    "Penguins can hold their breath for up to 20 minutes underwater!",
    "The emperor penguin is the tallest, nearly 1 meter!",
    "Penguins live in the cold, but not all live in snow!",
    "Penguins keep warm by huddling together!",
    "Penguin dads incubate eggs on their own feet!",
    "Penguins can swim at 35 kilometers per hour!",
    "There are 18 species of penguins in the world!",
    "Penguins drink saltwater and filter out the salt!",
    "Penguins recognize their partner by their call!",
    "The smallest penguin is only 30 centimeters tall!",
    "Penguins molt once a year!",
    "Penguins slide on their bellies across the snow!",
    "Penguins are black and white for camouflage in water!",
    "Penguins can dive over 500 meters deep!",
    "Emperor penguins survive temperatures of -60 degrees!",
    "Penguins are very loyal and recognize their partner every year!",
    "Penguin chicks stay in groups while parents hunt!",
    "Penguins eat fish, squid, and krill!",
    "Penguins have existed for over 60 million years!",
  ],
  monkey: [
    "Monkeys use tools like stones to open fruit!",
    "Monkeys hug and groom each other to show friendship!",
    "The spider monkey uses its tail as an extra hand!",
    "There are over 260 species of monkeys in the world!",
    "Monkeys live in groups and look after each other!",
    "Monkeys can recognize their own reflection in a mirror!",
    "Monkeys groom each other to strengthen friendships!",
    "The smallest monkey fits in the palm of your hand!",
    "Monkeys can learn sign language!",
    "Howler monkeys can be heard from 5 kilometers away!",
    "Japanese macaques bathe in hot springs in winter!",
    "Capuchin monkeys are considered the smartest in the Americas!",
    "Monkeys yawn when they see another monkey yawning!",
    "Night monkeys are the only ones that see well in the dark!",
    "Monkeys use different sounds to warn about types of predators!",
    "The proboscis monkey has the largest nose of all primates!",
    "Baby monkeys cling to their mother's belly to get around!",
    "Monkeys are our closest relatives in the animal kingdom!",
    "Monkeys can live up to 40 years in the wild!",
    "American monkeys have grasping tails, African ones don't!",
  ],
  giraffe: [
    "The giraffe is the tallest animal, reaching 6 meters!",
    "A giraffe's tongue is up to 50 centimeters long!",
    "Each giraffe has a unique spot pattern, like fingerprints!",
    "Giraffes sleep only 30 minutes a day!",
    "A giraffe's heart weighs 11 kilograms!",
    "Baby giraffes are already almost 2 meters tall at birth!",
    "A giraffe's tongue is purple to protect it from the sun!",
    "Giraffes walk by moving both legs on the same side together!",
    "Giraffes can run at 55 kilometers per hour!",
    "A giraffe's neck has only 7 vertebrae, same as ours!",
    "Giraffes rarely lie down — they even sleep standing up!",
    "Giraffes drink water by spreading their front legs wide!",
    "A giraffe's kick can defeat a lion!",
    "Baby giraffes fall almost 2 meters when born!",
    "Giraffes hum to each other at night!",
    "No two giraffes have the same pattern of spots!",
    "A giraffe's tongue is tough enough to eat thorns!",
    "Giraffes can go weeks without drinking water!",
    "Female giraffes return to their birthplace to have babies!",
    "Giraffes have existed for over 8 million years!",
  ],
  bear: [
    "Bears can smell food from 30 kilometers away!",
    "Polar bears have black skin under white fur!",
    "Bears hibernate for months without eating or drinking!",
    "Grizzly bears can run at 55 km per hour!",
    "Bear cubs are born tiny, the size of a squirrel!",
    "Pandas eat up to 38 kilograms of bamboo a day!",
    "Bears are excellent swimmers!",
    "The polar bear is the largest land carnivore!",
    "Bears can stand up on two legs to see farther!",
    "Bears have an incredible sense of smell!",
    "Sun bears have the longest tongue of all bears!",
    "Bears can live up to 30 years in the wild!",
    "Koalas aren't bears, they're marsupials!",
    "Bear claws can be 10 centimeters long!",
    "Some bears eat up to 40 kilograms of food a day before hibernating!",
    "Bears love honey and aren't afraid of bee stings!",
    "There are 8 species of bears in the world!",
    "Spectacled bears are the only bears in South America!",
    "Bears are very smart and have great memory!",
    "Panda bears are black and white to camouflage in snow and shadows!",
  ],
  dolphin: [
    "Dolphins sleep with one eye open!",
    "Dolphins talk to each other using clicks and whistles!",
    "Dolphins can swim at 60 kilometers per hour!",
    "Each dolphin has a unique whistle, like a name!",
    "Dolphins can jump up to 6 meters high!",
    "Dolphins live in groups called pods!",
    "Dolphins help sick or injured members of the group!",
    "Dolphins are one of the smartest animals in the world!",
    "Dolphins can hold their breath for up to 10 minutes!",
    "Dolphins use echolocation to find food!",
    "Dolphins love to surf ocean waves!",
    "Baby dolphins are born tail-first!",
    "Dolphins can recognize themselves in a mirror!",
    "Dolphins barely sleep — just a few minutes at a time!",
    "Dolphins can live up to 50 years!",
    "Dolphins love to play with seaweed and other objects!",
    "Dolphins have over 100 teeth but don't chew!",
    "Dolphins can swim up to 100 kilometers in a day!",
    "Dolphins have smooth skin that renews every 2 hours!",
    "Dolphins have already saved humans from sharks!",
  ],
  snake: [
    "Snakes smell with their tongue!",
    "Snakes don't have eyelids, they sleep with eyes open!",
    "Some snakes can fly through the air between trees!",
    "The longest snake in the world is 10 meters long!",
    "Snakes shed their entire skin several times a year!",
    "Snakes don't have legs, but some have tiny hidden leg bones!",
    "Some snakes can eat animals larger than their own head!",
    "Snakes feel vibrations on the ground to sense prey!",
    "There are over 3,000 species of snakes in the world!",
    "Most snakes are not venomous!",
    "The king cobra is the largest venomous snake in the world!",
    "Snakes can go months without eating!",
    "Snakes have flexible jaws that open super wide!",
    "Some snakes take care of their eggs until they hatch!",
    "Anacondas are so big they can catch caimans!",
    "Sea snakes can hold their breath for up to 2 hours!",
    "Snakes are found on every continent except Antarctica!",
    "Some snakes pretend to be dead to fool predators!",
    "Snakes are important for controlling rats and mice!",
    "Snakes have existed for over 100 million years!",
  ],
  bee: [
    "Bees visit up to 5,000 flowers in a single day!",
    "Bees dance to tell others where to find flowers!",
    "Honey never spoils — it can last thousands of years!",
    "A bee flaps its wings 200 times per second!",
    "Bees are responsible for pollinating one-third of our food!",
    "The queen bee can lay 2,000 eggs a day!",
    "Bees produce honey by processing flower nectar!",
    "A bee travels 800 kilometers in its lifetime!",
    "Bees have 5 eyes — 2 large and 3 small!",
    "Bees communicate through vibrations and dances!",
    "A bee can fly at 25 kilometers per hour!",
    "Without bees, many fruits and vegetables would disappear!",
    "Bees make honey to eat during winter!",
    "The stinger of a worker bee falls off after stinging!",
    "Bees can recognize human faces!",
    "A hive can have up to 60,000 bees!",
    "Bees keep the hive at exactly 35 degrees!",
    "Worker bees live only 6 weeks in summer!",
    "Bees are the most important pollinators on the planet!",
    "The queen bee can live up to 5 years!",
  ],
  pig: [
    "Pigs are one of the smartest animals in the world!",
    "Pigs can learn their name and come when called!",
    "A pig's sense of smell is even better than a dog's!",
    "Pigs roll in mud to cool down and protect from the sun!",
    "Pigs can run at 18 kilometers per hour!",
    "Pigs dream while they sleep, just like us!",
    "Pigs have over 15,000 taste buds — more than humans!",
    "Pigs can play video games with a joystick!",
    "Pigs are very clean and keep their bathroom area separate!",
    "Pigs communicate with over 20 different sounds!",
    "A baby pig is called a piglet!",
    "Pigs can recognize themselves in a mirror!",
    "Pigs were domesticated over 9,000 years ago!",
    "A pig's squeal can reach 115 decibels — louder than a jet!",
    "Pigs have excellent long-term memory!",
    "Pigs can solve mazes and puzzles!",
    "Pigs love belly rubs and fall asleep when petted!",
    "Pigs can't look up at the sky while standing!",
    "Pigs have 44 teeth!",
    "Pigs are social animals and love company!",
  ],
  panda: [
    "Giant pandas eat bamboo for up to 14 hours a day!",
    "An adult panda can eat 38 kilograms of bamboo a day!",
    "Baby pandas are born pink and hairless!",
    "Pandas have a special wrist bone that works like a thumb!",
    "Giant pandas live in the mountains of China!",
    "Pandas spend most of their time eating and sleeping!",
    "Pandas are excellent swimmers!",
    "Pandas mark their territory by rubbing against trees!",
    "A baby panda weighs only 100 grams at birth!",
    "Pandas have an almost 100% vegetarian diet!",
    "Pandas live between 20 and 30 years in the wild!",
    "Pandas are excellent tree climbers!",
    "The black and white fur helps pandas camouflage!",
    "Pandas have super strong jaws to chew bamboo!",
    "Giant pandas are solitary and prefer to live alone!",
    "Baby pandas stay with their mother for up to 2 years!",
    "Pandas were removed from the endangered species list!",
    "Pandas make bleating sounds like sheep to communicate!",
    "Pandas have vertical pupils, like cats!",
    "The panda is the symbol of nature conservation worldwide!",
  ],
  koala: [
    "Koalas sleep up to 22 hours a day!",
    "Koalas feed almost exclusively on eucalyptus leaves!",
    "Koala fingerprints are almost identical to human fingerprints!",
    "Baby koalas stay in their mother's pouch for 6 months!",
    "Koalas rarely drink water, they get hydration from leaves!",
    "Koalas have two thumbs on each hand for a better grip!",
    "Koalas are not bears, they are marsupials!",
    "Koalas only live in Australia!",
    "Koalas have a big nose to smell which leaves are good!",
    "Baby koalas eat a special paste produced by their mother!",
    "Koalas can live up to 18 years in the wild!",
    "Koalas have thick, soft fur that protects them from rain!",
    "Koalas hug trees to cool down in the heat!",
    "Male koalas mark territory by rubbing their chest on trees!",
    "Koalas have a small brain relative to their body!",
    "Koalas make deep, loud sounds to communicate!",
    "Koalas eat about 500 grams of leaves per day!",
    "Koalas are nocturnal animals, most active at night!",
    "Koalas have sharp claws for climbing trees!",
    "Koalas are one of Australia's most beloved animals!",
  ],
  zebra: [
    "Every zebra has a unique stripe pattern, like fingerprints!",
    "Zebra stripes help confuse predators!",
    "Zebras sleep standing up, like horses!",
    "Baby zebras can walk minutes after being born!",
    "Zebras live in groups called herds!",
    "Zebras can run up to 65 kilometers per hour!",
    "Zebras greet each other by touching noses!",
    "Zebras are related to horses and donkeys!",
    "Zebras migrate hundreds of kilometers!",
    "Zebra stripes can repel flies and insects!",
    "Zebras have excellent night vision!",
    "Foals recognize their mother by her stripe pattern!",
    "Zebras protect themselves by staying in groups!",
    "Zebras can live up to 25 years in the wild!",
    "Zebras use their ears to show their mood!",
    "Zebras eat grass and herbs for many hours a day!",
    "Zebras drink water at least once a day!",
    "Zebras can deliver powerful kicks to defend themselves!",
    "Zebras live in the savannas and plains of Africa!",
    "There are three species of zebras in the world!",
  ],
  shark: [
    "Sharks have been around for over 400 million years!",
    "Sharks have rows of teeth that regrow throughout their lives!",
    "The whale shark is the largest fish and eats plankton!",
    "Sharks can detect a drop of blood in water from miles away!",
    "Sharks have no bones, their skeleton is made of cartilage!",
    "There are over 500 species of sharks in the world!",
    "Sharks need to keep swimming to breathe!",
    "Sharks have excellent vision, even in the dark!",
    "Baby sharks are born knowing how to swim!",
    "The hammerhead shark has a T-shaped head!",
    "Sharks can sense electrical fields of other animals!",
    "Great white sharks can leap out of the water to hunt!",
    "Some sharks live in very deep parts of the ocean!",
    "Sharks help maintain the balance of the oceans!",
    "Sharks have rough skin like sandpaper!",
    "The lantern shark glows in the dark!",
    "Sharks can live up to 70 years or more!",
    "Sharks swim up to 50 kilometers per hour!",
    "Sharks lose and replace thousands of teeth in their lifetime!",
    "Most sharks are harmless to humans!",
  ],
  whale: [
    "The blue whale is the largest animal that has ever lived!",
    "A blue whale's heart is the size of a car!",
    "Whales communicate with songs that travel thousands of kilometers!",
    "Humpback whales perform amazing acrobatics jumping out of the water!",
    "Whales can hold their breath for over an hour!",
    "Baby whales drink hundreds of liters of milk per day!",
    "Whales migrate thousands of kilometers every year!",
    "A blue whale's tongue weighs as much as an elephant!",
    "Whales sleep with half their brain awake!",
    "Sperm whales dive to more than 2,000 meters deep!",
    "Whales are mammals, not fish!",
    "A blue whale can be 30 meters long!",
    "Whales have hairs on their body, usually on the chin!",
    "Baby whales are born tail-first so they don't drown!",
    "A humpback whale's song can last for hours!",
    "Whales live in every ocean in the world!",
    "Some whales can live up to 200 years!",
    "Whales spray water through the blowhole on their head!",
    "Whales form strong bonds with their calves!",
    "A blue whale eats up to 4 tons of krill per day!",
  ],
  crocodile: [
    "Crocodiles have been around for over 200 million years!",
    "Crocodiles can stay still for hours, waiting for prey!",
    "Crocodiles have the strongest bite of any animal!",
    "Crocodiles cry while eating, but not from sadness!",
    "Crocodiles can live up to 70 years!",
    "The saltwater crocodile is the largest reptile in the world!",
    "Crocodiles can swim at 30 kilometers per hour!",
    "Baby crocodiles make sounds inside the egg to alert their mother!",
    "Crocodiles swallow stones to help with digestion!",
    "Nest temperature determines if babies will be male or female!",
    "Crocodiles can hold their breath for over an hour!",
    "Crocodiles have 80 teeth and replace them throughout life!",
    "Crocodiles live in both fresh and salt water!",
    "Mother crocodiles carefully carry babies in their mouth!",
    "Crocodile eyes glow in the dark!",
    "Crocodiles regulate their temperature by sunbathing!",
    "Crocodiles are relatives of dinosaurs!",
    "Crocodiles can run fast on land for short distances!",
    "Crocodiles have excellent hearing!",
    "Crocodiles can go months without eating!",
  ],
  fox: [
    "Foxes use Earth's magnetic field to hunt!",
    "Foxes are related to dogs and wolves!",
    "Foxes have whiskers on their legs to help navigate!",
    "Foxes can hear animals under the snow!",
    "Foxes live on every continent except Antarctica!",
    "Foxes are nocturnal and hunt at night!",
    "The Arctic fox changes color with the seasons!",
    "Foxes make over 40 different sounds!",
    "Foxes are very agile and can climb fences!",
    "Foxes live in dens called earths!",
    "Fox cubs are born deaf and blind!",
    "Foxes have vertical pupils, like cats!",
    "Foxes can run at 50 kilometers per hour!",
    "Foxes are solitary animals most of the time!",
    "A fox's tail helps with balance and warmth!",
    "Foxes hide food to eat later!",
    "Fox cubs play a lot when they're young!",
    "Foxes have an incredible sense of smell!",
    "Foxes can live up to 14 years!",
    "The fennec fox has the largest ears relative to its body!",
  ],
  duck: [
    "Ducks have waterproof feathers!",
    "Ducks can sleep with one eye open!",
    "Ducklings follow the first thing they see after hatching!",
    "Ducks have 3 eyelids on each eye!",
    "Ducks don't feel cold in their feet, even in icy water!",
    "Ducks can fly at up to 80 kilometers per hour!",
    "Ducks quack, but the sound doesn't echo!",
    "Ducklings can swim just hours after being born!",
    "Ducks eat fish, insects, plants, and seeds!",
    "Ducks migrate to warmer places in winter!",
    "Male ducks are more colorful than females!",
    "Ducks swim using their feet like paddles!",
    "Ducks can dive to find food at the bottom!",
    "There are over 120 species of ducks in the world!",
    "Ducks live on every continent except Antarctica!",
    "Ducks are very social birds and live in groups!",
    "Ducks shed all their feathers once a year!",
    "Ducks see colors better than humans!",
    "Ducks can live up to 20 years!",
    "Ducklings can swim on their very first day of life!",
  ],
  octopus: [
    "Octopuses have 3 hearts and blue blood!",
    "Octopuses can change color in less than a second!",
    "Octopuses are the most intelligent invertebrates!",
    "Octopuses have 8 arms, each with suckers!",
    "Octopuses can open jars and solve puzzles!",
    "Octopuses have no bones and can squeeze through anything!",
    "Octopuses release ink to escape predators!",
    "Each octopus arm has its own mini-brain!",
    "Octopuses can regenerate lost arms!",
    "The mimic octopus imitates the appearance of other animals!",
    "Octopuses live on the ocean floor, in dens!",
    "Octopuses are masters of camouflage!",
    "The blue-ringed octopus is one of the most venomous animals!",
    "Female octopuses guard their eggs without eating until they hatch!",
    "Octopuses have excellent vision!",
    "Octopuses use shells and coconuts as shelter!",
    "Octopuses swim by expelling jets of water!",
    "There are over 300 species of octopuses in the world!",
    "Octopuses live only 1 to 2 years on average!",
    "Octopuses taste food with the suckers on their arms!",
  ],
  tiger: [
    "The tiger is the largest cat in the world!",
    "Every tiger has unique stripes, like fingerprints!",
    "Tigers love swimming and playing in water!",
    "Tigers can run up to 65 kilometers per hour!",
    "Tigers hunt alone, usually at night!",
    "A tiger can eat 40 kilograms of meat at once!",
    "Tiger cubs stay with their mother for up to 3 years!",
    "Tigers roar so loudly it can be heard 3 kilometers away!",
    "There are 6 subspecies of tigers in the world!",
    "Tigers mark territory with scratches on trees!",
    "Tigers have retractable claws hidden when they walk!",
    "The Siberian tiger is the largest, weighing up to 300 kilos!",
    "Tigers can jump up to 5 meters high!",
    "Tigers have night vision 6 times better than humans!",
    "Tigers are solitary and territorial animals!",
    "Tiger stripes also exist on their skin, not just fur!",
    "White tigers are rare and have pale stripes!",
    "Tigers can swim for several kilometers!",
    "Tigers are found in Asia!",
    "Tigers are endangered and need protection!",
  ],
};
