import type { AquaticId } from "./aquatics";

export const aquaticFunFactsEn: Record<AquaticId, string[]> = {
  whale: [
    "The blue whale is the largest animal that ever lived on Earth!",
    "A blue whale's heart is the size of a small car!",
    "Whales sing to communicate across thousands of kilometers!",
    "Whales can hold their breath for up to 90 minutes!",
    "Baby whales are born almost 8 meters long!",
    "Whales migrate thousands of kilometers every year!",
    "A blue whale's tongue weighs as much as an elephant!",
    "Humpback whales do incredible acrobatics out of the water!",
    "Whales have lungs, not gills, and need to surface to breathe!",
    "Whales can live over 100 years!",
    "Whales produce milk to feed their calves!",
    "A whale's water spout can reach 9 meters high!",
    "Whales sleep with half their brain awake!",
    "A blue whale can weigh up to 150 tons!",
    "Whales are descended from animals that lived on land!",
    "Sperm whales dive over 2,000 meters deep!",
    "Each humpback whale has a unique tail, like a fingerprint!",
    "Whales communicate with deep sounds called songs!",
    "Gray whales make the longest migration of any mammal!",
    "Whales help fertilize the oceans with their waste!",
  ],
  dolphin: [
    "Dolphins sleep with one eye open!",
    "Dolphins call each other by unique names!",
    "Dolphins can swim at 60 kilometers per hour!",
    "Dolphins use echolocation to find fish!",
    "Dolphins are one of the smartest animals in the world!",
    "Dolphins live in groups called pods!",
    "Dolphins can hold their breath for up to 10 minutes!",
    "Dolphins play with waves and surf!",
    "Dolphins help other dolphins that are hurt!",
    "Dolphins can recognize their own reflection in a mirror!",
    "Baby dolphins stay with their mothers for up to 6 years!",
    "Dolphins can jump up to 6 meters out of the water!",
    "Dolphins communicate with clicks and whistles!",
    "Dolphins have been seen helping swimmers in danger!",
    "The bottlenose dolphin is the most well-known species!",
    "Dolphins have super smooth skin that helps them swim fast!",
    "Dolphins shed their skin every 2 hours!",
    "Dolphins can live up to 50 years!",
    "Dolphins use sponges on their snout for protection while digging!",
    "There are over 40 species of dolphins in the world!",
  ],
  shark: [
    "Sharks have been around for over 400 million years!",
    "Sharks have rows of teeth that replace themselves for life!",
    "The whale shark is the biggest fish in the world!",
    "Sharks can detect a drop of blood in water from miles away!",
    "Sharks have no bones, only cartilage!",
    "Some sharks must keep swimming to breathe!",
    "The hammerhead shark has eyes on the tips of its head!",
    "Sharks have a sixth sense that detects electric fields!",
    "Great white sharks can leap completely out of the water!",
    "Sharks can have up to 3,000 teeth at once!",
    "The smallest shark fits in the palm of your hand!",
    "Sharks live in every ocean in the world!",
    "The lantern shark glows in the dark!",
    "Sharks help keep the oceans balanced!",
    "Sharks have incredible hearing underwater!",
    "The whale shark is gentle and eats only plankton!",
    "Baby sharks are born knowing how to swim!",
    "Sharks can live up to 70 years!",
    "The Greenland shark can live over 400 years!",
    "Sharks are older than dinosaurs!",
  ],
  octopus: [
    "An octopus has three hearts!",
    "Octopuses have blue blood!",
    "Octopuses can change color in milliseconds!",
    "An octopus has eight arms, each with suckers!",
    "Octopuses are the smartest invertebrates!",
    "An octopus can squeeze through any hole the size of its beak!",
    "Octopuses release ink to escape predators!",
    "An octopus can open jars with its suckers!",
    "Octopuses have neurons in their arms and can think with them!",
    "The blue-ringed octopus is one of the most venomous in the world!",
    "Octopuses can regenerate lost arms!",
    "An octopus walks, swims, and jets water to move!",
    "Octopuses build gardens with shells and rocks!",
    "The mimic octopus can imitate other sea animals!",
    "Octopuses live alone, not in groups!",
    "The giant Pacific octopus can span 5 meters!",
    "Octopuses are color blind but see light polarization!",
    "The octopus has the largest brain of all invertebrates!",
    "Octopuses can solve mazes and puzzles!",
    "Octopuses have existed for over 300 million years!",
  ],
  fish: [
    "Some fish glow in the deep sea!",
    "Some fish can fly above the water!",
    "Fish don't have eyelids and sleep with their eyes open!",
    "The whale shark is the largest fish in the world!",
    "Some fish change color to hide!",
    "Fish use gills to breathe underwater!",
    "There are over 30,000 species of fish in the world!",
    "Fish can sense vibrations in the water!",
    "The swordfish can swim at 110 kilometers per hour!",
    "Goldfish can remember things for months!",
    "Pufferfish inflate with water to look bigger!",
    "Fish travel in schools for protection!",
    "Some fish build nests to protect their eggs!",
    "The ocean sunfish is the heaviest bony fish!",
    "Fish can taste the water around them!",
    "The archerfish spits jets of water to knock down insects!",
    "Some fish live in the darkest depths of the ocean!",
    "The clownfish lives inside sea anemones!",
    "Fish have existed for over 500 million years!",
    "Some fish have fins that look like wings!",
  ],
  seahorse: [
    "The seahorse is the only animal where the father gets pregnant!",
    "Seahorses swim upright, unlike all other fish!",
    "Seahorses hold onto things with their tail to avoid drifting!",
    "Seahorses don't have a stomach!",
    "Seahorses change color to camouflage!",
    "The pygmy seahorse is smaller than a fingernail!",
    "Seahorses eat all day because they have no stomach!",
    "Seahorses mate for life!",
    "Seahorses swim very slowly, they're the slowest fish!",
    "A father seahorse can have up to 2,000 babies at once!",
    "Seahorses have eyes that move independently!",
    "The seahorse uses its snout to suck up tiny shrimp!",
    "Seahorses dance together every morning to strengthen their bond!",
    "There are over 40 species of seahorses!",
    "Seahorses don't have scales, they have bony armor!",
    "Seahorses can be found in all tropical oceans!",
    "The pot-bellied seahorse is one of the largest species!",
    "Seahorses are related to pipefish!",
    "A seahorse can move its fins up to 50 times per second!",
    "Seahorses are masters of camouflage!",
  ],
  jellyfish: [
    "Jellyfish have existed for over 500 million years!",
    "Jellyfish have no brain, heart, or blood!",
    "Some jellyfish glow in the dark!",
    "The lion's mane jellyfish can have 30-meter tentacles!",
    "Jellyfish are 95% water!",
    "Some jellyfish are immortal and can rejuvenate!",
    "Jellyfish move by contracting their body like an umbrella!",
    "Jellyfish use venomous tentacles to catch prey!",
    "The box jellyfish is one of the most venomous creatures!",
    "Jellyfish are food for sea turtles!",
    "Some jellyfish are so small they're barely visible!",
    "Jellyfish live in every ocean in the world!",
    "A group of jellyfish is called a smack!",
    "Jellyfish don't choose where they swim, currents carry them!",
    "Some jellyfish have eyes that detect light!",
    "The moon jellyfish is one of the most common!",
    "Jellyfish are older than dinosaurs!",
    "Some jellyfish tentacles can sting even after death!",
    "Jellyfish are studied to create glowing materials!",
    "The immortal jellyfish can revert to a polyp and restart life!",
  ],
  stingray: [
    "Stingrays are related to sharks!",
    "Stingrays have no bones, only cartilage!",
    "Some stingrays have a venomous stinger on their tail!",
    "Stingrays bury themselves in sand to hide!",
    "Stingrays use electricity to sense hidden prey!",
    "The manta ray can span 7 meters wide!",
    "Stingrays swim by flapping their fins like wings!",
    "Stingrays eat mollusks, crustaceans, and small fish!",
    "Stingrays have their mouth on the bottom of their body!",
    "Electric rays can shock to defend themselves!",
    "Stingrays live in both shallow and deep waters!",
    "Manta rays are gentle giants that eat plankton!",
    "Stingrays can live up to 25 years!",
    "Stingrays have rough skin like sandpaper!",
    "Stingrays see from above but their mouth is below!",
    "Some stingrays live in freshwater!",
    "Manta rays are very intelligent and recognize reflections!",
    "Stingrays give birth to live young, not eggs!",
    "The flat shape of stingrays helps them hide on the ocean floor!",
    "Stingrays are found in every ocean in the world!",
  ],
  seal: [
    "Seals can hold their breath for up to 2 hours!",
    "Seals sleep underwater and surface to breathe without waking!",
    "Seals have whiskers that sense vibrations in water!",
    "Seals can swim at 35 kilometers per hour!",
    "Baby seals are born with fluffy white fur!",
    "Seals keep warm with a thick layer of blubber!",
    "Monk seals are one of the rarest species!",
    "Seals can dive to 600 meters deep!",
    "Leopard seals are fierce predators in Antarctica!",
    "Seals communicate with sounds underwater!",
    "Harp seals migrate thousands of kilometers!",
    "Seals have large eyes to see in deep water!",
    "Seals nurse their pups with super-rich milk!",
    "Seals can live up to 30 years!",
    "Elephant seals can weigh up to 4 tons!",
    "Seals close their nostrils when diving!",
    "Seals are found in every ocean!",
    "Seals bask on rocks and beaches to warm up!",
    "Seals have flipper-shaped hind feet!",
    "Seals are mammals and need to breathe air!",
  ],
  crab: [
    "Crabs walk sideways!",
    "Crabs have ten legs, including two pincers!",
    "The Japanese spider crab can span 4 meters!",
    "Crabs shed their shell to grow!",
    "Some crabs are hermits and use borrowed shells!",
    "Crabs can regenerate lost pincers!",
    "The coconut crab climbs palm trees!",
    "Crabs have blue blood!",
    "Some crabs live on land and only return to sea to lay eggs!",
    "Crabs use their pincers to eat and defend!",
    "Crabs can live up to 30 years!",
    "The horseshoe crab has existed for 450 million years!",
    "Crabs can see in all directions!",
    "Crabs communicate by clapping their pincers!",
    "Hermit crabs line up to swap shells!",
    "The smallest crab is only 1 centimeter!",
    "Crabs eat anything: algae, mollusks, and fish scraps!",
    "Female crabs carry eggs on their belly!",
    "Crabs can walk forward but prefer sideways!",
    "The boxer crab holds anemones in its pincers for defense!",
  ],
  lobster: [
    "Lobsters can live over 100 years!",
    "Lobsters have blue blood!",
    "Lobsters grow their entire lives and never stop!",
    "Lobsters communicate by peeing at each other's face!",
    "The largest lobster ever found weighed over 20 kilos!",
    "Lobsters shed their shell to grow!",
    "Lobsters have two stomachs!",
    "Lobsters can regenerate lost legs and claws!",
    "Lobsters smell with their antennae!",
    "Lobsters walk on the seafloor but swim backwards when scared!",
    "Lobsters have teeth in their stomach!",
    "Lobsters carry eggs for up to a year!",
    "Lobsters can be blue, yellow, or even white!",
    "Lobsters are cannibals and can eat other lobsters!",
    "Lobsters have compound eyes with thousands of lenses!",
    "Lobsters can travel great distances on the seafloor!",
    "Lobsters are crustaceans, related to crabs!",
    "Lobsters can crush shells with their powerful claws!",
    "Lobsters have taste receptors in their feet!",
    "A lobster can walk up to 160 kilometers along the seafloor!",
  ],
  starfish: [
    "Starfish are not fish, they're echinoderms!",
    "Starfish can regenerate lost arms!",
    "Some starfish have more than 5 arms!",
    "Starfish don't have a brain!",
    "Starfish eat by pushing their stomach out of their body!",
    "Starfish walk with hundreds of tiny tube feet!",
    "There are over 2,000 species of starfish!",
    "Starfish don't have blood, they use seawater!",
    "Some starfish glow on the ocean floor!",
    "The sunflower starfish has 24 arms!",
    "Starfish can live up to 35 years!",
    "Starfish have eyes at the tip of each arm!",
    "Starfish stick to rocks with suction cup feet!",
    "Some starfish eat coral!",
    "If you cut a starfish, each piece can become a new one!",
    "Starfish come in every color of the rainbow!",
    "Starfish live in every ocean in the world!",
    "Starfish are very slow, moving just centimeters per minute!",
    "The crown-of-thorns starfish is venomous!",
    "Starfish are important for ocean balance!",
  ],
  narwhal: [
    "The narwhal has a horn that's actually a giant canine tooth!",
    "A narwhal's tusk can be up to 3 meters long!",
    "Narwhals live in the icy waters of the Arctic!",
    "Narwhals are called the unicorns of the sea!",
    "Narwhals dive over 1,500 meters deep!",
    "A narwhal's tusk has millions of nerve endings!",
    "Narwhals live in groups of 15 to 20!",
    "Narwhals communicate with clicks and whistles!",
    "Narwhals can live up to 50 years!",
    "Narwhals eat fish, squid, and shrimp!",
    "A narwhal's tusk grows throughout its life!",
    "Narwhals change color as they age!",
    "Baby narwhals are born gray and get lighter!",
    "Narwhals can hold their breath for up to 25 minutes!",
    "The narwhal is related to the beluga!",
    "Narwhals have no dorsal fin for swimming under ice!",
    "Male narwhals rub tusks together as a greeting!",
    "Narwhals are one of the deepest-diving mammals!",
    "Narwhals are found in Canada, Greenland, and Russia!",
    "Narwhals inspired unicorn legends in the Middle Ages!",
  ],
  orca: [
    "Orcas are actually the largest member of the dolphin family!",
    "Orcas live in families called pods!",
    "Orcas can swim at 55 kilometers per hour!",
    "Each orca pod has its own dialect!",
    "Orcas hunt in groups with coordinated strategies!",
    "Orcas are found in every ocean in the world!",
    "Orcas can live up to 90 years!",
    "Orcas can knock seals off ice floes with waves!",
    "Orcas sleep with half their brain awake!",
    "Orcas teach hunting techniques to their young!",
    "A male orca's dorsal fin can be 1.8 meters tall!",
    "Orcas are called killer whales but are dolphins!",
    "Orcas communicate with complex sounds!",
    "Each orca has unique white patches behind its eyes!",
    "Orcas eat fish, seals, and even other whales!",
    "Baby orcas are born almost 2.5 meters long!",
    "Orcas have the second largest brain of all marine mammals!",
    "Orcas can dive to 300 meters deep!",
    "Orcas live in matriarchal societies!",
    "Orcas are one of the smartest predators in the ocean!",
  ],
  clownfish: [
    "Clownfish live inside venomous anemones without getting hurt!",
    "Clownfish have a mucus layer that protects from venom!",
    "All clownfish are born male!",
    "The most dominant clownfish in a group can become female!",
    "Clownfish clean and protect the anemone they live in!",
    "There are 30 species of clownfish!",
    "Clownfish became famous from the movie Finding Nemo!",
    "Clownfish are very territorial!",
    "Clownfish do a dance to introduce themselves to an anemone!",
    "Clownfish eat algae and small invertebrates!",
    "Clownfish can live up to 10 years!",
    "Clownfish communicate with pops and clicks!",
    "Clownfish rarely stray far from their anemone!",
    "Clownfish have white and orange stripes for camouflage!",
    "The female clownfish is always the largest in the group!",
    "Clownfish sleep inside the anemone at night!",
    "Clownfish lay eggs near the anemone!",
    "The father clownfish guards the eggs until they hatch!",
    "Clownfish live in tropical coral reefs!",
    "Clownfish are one of the most colorful fish in the ocean!",
  ],
  squid: [
    "Squid have three hearts, like octopuses!",
    "Squid have blue blood!",
    "Squid can swim backwards by jetting water!",
    "The giant squid can be up to 13 meters long!",
    "Squid have ten tentacles, two longer than the rest!",
    "Squid can change color instantly!",
    "Squid release ink to escape predators!",
    "The colossal squid has the largest eyes in the animal kingdom!",
    "Squid are very intelligent and can solve problems!",
    "Some squid glow in the dark with bioluminescence!",
    "Squid swim in groups called shoals!",
    "The vampire squid lives in the dark deep ocean!",
    "Squid eat fish, shrimp, and other squid!",
    "Squid have a hard beak like a parrot!",
    "The Humboldt squid can weigh up to 50 kilos!",
    "Squid can swim at up to 40 kilometers per hour!",
    "Squid have an internal shell called a gladius!",
    "Squid live in every ocean in the world!",
    "The giant squid was considered a sea monster for centuries!",
    "Squid can live from 1 to 5 years depending on species!",
  ],
  walrus: [
    "Walruses have tusks that can reach 1 meter!",
    "Walruses use their tusks to pull themselves out of the ice!",
    "Walruses can weigh up to 1,500 kilos!",
    "Walruses have super-sensitive whiskers to find food on the seafloor!",
    "Walruses live in the Arctic, in icy waters!",
    "Walruses stay warm with a thick layer of blubber!",
    "Walruses can hold their breath for up to 10 minutes!",
    "Walruses eat mollusks, especially clams!",
    "Walruses live in large groups on beaches!",
    "Walruses can sleep both in water and on land!",
    "Male walruses fight with their tusks over females!",
    "Walruses communicate with sounds like bells!",
    "Walruses can swim at 35 kilometers per hour!",
    "Baby walruses stay with their mother for up to 3 years!",
    "Walruses can live up to 40 years!",
    "Walrus skin changes color: pink in sun, gray in water!",
    "Walruses use their tusks as support to sleep on ice!",
    "Walruses are the largest pinnipeds after elephant seals!",
    "Walruses can eat up to 6,000 clams a day!",
    "Walruses have air sacs in their neck to float while sleeping!",
  ],
  sea_turtle: [
    "Sea turtles have existed for over 100 million years!",
    "Sea turtles travel thousands of kilometers across the ocean!",
    "Sea turtles return to the same beach where they were born to lay eggs!",
    "Sea turtles can hold their breath for up to 5 hours!",
    "The leatherback is the largest, weighing up to 700 kilos!",
    "Sea turtles cry to remove salt from seawater!",
    "Sea turtles use Earth's magnetic field to navigate!",
    "There are 7 species of sea turtles!",
    "Sea turtles eat jellyfish, algae, and sponges!",
    "Baby sea turtles race to the sea when they hatch!",
    "The sex of sea turtles depends on sand temperature!",
    "Sea turtles can live up to 80 years!",
    "Sea turtles swim using their flippers like wings!",
    "Sea turtles dive over 1,000 meters deep!",
    "Sea turtles are reptiles that live in the sea!",
    "Sea turtles can't hide inside their shell!",
    "Green sea turtles mainly eat seagrass and algae!",
    "Sea turtles are threatened by plastic pollution!",
    "Sea turtles have salt glands near their eyes!",
    "Sea turtles can swim at up to 35 kilometers per hour!",
  ],
  swordfish: [
    "The swordfish has a bill that can be 1 meter long!",
    "Swordfish can swim at 110 kilometers per hour!",
    "The swordfish uses its bill to stun prey!",
    "Adult swordfish have no scales!",
    "Swordfish can weigh up to 650 kilos!",
    "Swordfish can dive to 550 meters deep!",
    "Swordfish have an organ that heats their eyes and brain!",
    "Swordfish swim alone, not in schools!",
    "Swordfish can measure up to 4.5 meters!",
    "Swordfish eat squid, fish, and crustaceans!",
    "Swordfish migrate to warmer waters in winter!",
    "Swordfish can leap completely out of the water!",
    "The swordfish bill is flat, unlike a marlin's!",
    "Swordfish grow very fast in their first year!",
    "Swordfish can live up to 15 years!",
    "Swordfish have few natural predators!",
    "The swordfish is one of the fastest fish in the ocean!",
    "Baby swordfish have teeth and scales they lose as they grow!",
    "Swordfish swim in waters of every ocean!",
    "Swordfish are top predators in the food chain!",
  ],
  manatee: [
    "The manatee is a herbivorous mammal that lives in water!",
    "Manatees can eat up to 50 kilos of plants a day!",
    "Manatees are called sea cows!",
    "Manatees can hold their breath for up to 20 minutes!",
    "Manatees swim slowly, at just 8 kilometers per hour!",
    "Manatees can weigh up to 600 kilos!",
    "Manatees are distant relatives of elephants!",
    "Manatees live in warm, shallow waters!",
    "Manatees have flexible lips to pull plants!",
    "Manatees can live up to 60 years!",
    "Manatees replace their teeth throughout life, like sharks!",
    "Manatees are very gentle and calm animals!",
    "Manatees have nails on their flippers from their ancestors!",
    "Manatees can be found in rivers and seas!",
    "The Amazonian manatee lives only in freshwater!",
    "Baby manatees nurse underwater!",
    "Manatees were mistaken for mermaids by ancient sailors!",
    "Manatees communicate with high-pitched sounds underwater!",
    "Manatees have very dense bones that help them sink!",
    "Manatees are endangered and protected by law!",
  ],
};
