import type { AquaticId } from "./aquatics";

export const aquaticFunFactsEs: Record<AquaticId, string[]> = {
  whale: [
    "¡La ballena azul es el animal más grande que ha existido!",
    "¡El corazón de la ballena azul es del tamaño de un auto pequeño!",
    "¡Las ballenas cantan para comunicarse a miles de kilómetros!",
    "¡Las ballenas pueden aguantar la respiración hasta 90 minutos!",
    "¡Las crías de ballena nacen con casi 8 metros de largo!",
    "¡Las ballenas migran miles de kilómetros cada año!",
    "¡La lengua de la ballena azul pesa tanto como un elefante!",
    "¡Las ballenas jorobadas hacen acrobacias increíbles fuera del agua!",
    "¡Las ballenas tienen pulmones y necesitan subir a respirar!",
    "¡Las ballenas pueden vivir más de 100 años!",
    "¡Las ballenas producen leche para alimentar a sus crías!",
    "¡El chorro de agua de la ballena puede alcanzar 9 metros!",
    "¡Las ballenas duermen con la mitad del cerebro despierta!",
    "¡La ballena azul puede pesar hasta 150 toneladas!",
    "¡Las ballenas descienden de animales que vivían en tierra!",
    "¡Los cachalotes se sumergen a más de 2 mil metros!",
    "¡Cada ballena jorobada tiene una cola única!",
    "¡Las ballenas se comunican con sonidos graves llamados cantos!",
    "¡Las ballenas grises hacen la migración más larga de todos los mamíferos!",
    "¡Las ballenas ayudan a fertilizar los océanos!",
  ],
  dolphin: [
    "¡Los delfines duermen con un ojo abierto!",
    "¡Los delfines se llaman entre sí por nombres únicos!",
    "¡Los delfines pueden nadar a 60 kilómetros por hora!",
    "¡Los delfines usan ecolocalización para encontrar peces!",
    "¡Los delfines son uno de los animales más inteligentes!",
    "¡Los delfines viven en grupos llamados manadas!",
    "¡Los delfines pueden aguantar la respiración 10 minutos!",
    "¡Los delfines juegan con las olas y surfean!",
    "¡Los delfines ayudan a otros delfines heridos!",
    "¡Los delfines reconocen su reflejo en el espejo!",
    "¡Las crías de delfín se quedan con la madre hasta 6 años!",
    "¡Los delfines pueden saltar hasta 6 metros fuera del agua!",
    "¡Los delfines se comunican con clics y silbidos!",
    "¡Los delfines han sido vistos ayudando a nadadores en peligro!",
    "¡El delfín nariz de botella es la especie más conocida!",
    "¡Los delfines tienen una piel súper lisa!",
    "¡Los delfines renuevan su piel cada 2 horas!",
    "¡Los delfines pueden vivir hasta 50 años!",
    "¡Los delfines usan esponjas en el hocico para protegerse!",
    "¡Existen más de 40 especies de delfines!",
  ],
  shark: [
    "¡Los tiburones existen desde hace más de 400 millones de años!",
    "¡Los tiburones tienen filas de dientes que se reemplazan toda la vida!",
    "¡El tiburón ballena es el pez más grande del mundo!",
    "¡Los tiburones detectan una gota de sangre a kilómetros!",
    "¡Los tiburones no tienen huesos, solo cartílago!",
    "¡Algunos tiburones deben nadar sin parar para respirar!",
    "¡El tiburón martillo tiene ojos en las puntas de la cabeza!",
    "¡Los tiburones tienen un sexto sentido que detecta campos eléctricos!",
    "¡El tiburón blanco puede saltar completamente fuera del agua!",
    "¡Los tiburones pueden tener hasta 3 mil dientes a la vez!",
    "¡El tiburón más pequeño cabe en la palma de la mano!",
    "¡Los tiburones viven en todos los océanos del mundo!",
    "¡El tiburón linterna brilla en la oscuridad!",
    "¡Los tiburones ayudan a mantener el equilibrio de los océanos!",
    "¡Los tiburones tienen una audición increíble bajo el agua!",
    "¡El tiburón ballena es gentil y solo come plancton!",
    "¡Las crías de tiburón nacen sabiendo nadar!",
    "¡Los tiburones pueden vivir hasta 70 años!",
    "¡El tiburón de Groenlandia puede vivir más de 400 años!",
    "¡Los tiburones son más antiguos que los dinosaurios!",
  ],
  octopus: [
    "¡El pulpo tiene tres corazones!",
    "¡Los pulpos tienen sangre azul!",
    "¡Los pulpos pueden cambiar de color en milisegundos!",
    "¡El pulpo tiene ocho brazos con ventosas!",
    "¡Los pulpos son los invertebrados más inteligentes!",
    "¡Un pulpo puede pasar por cualquier agujero del tamaño de su pico!",
    "¡Los pulpos sueltan tinta para escapar de depredadores!",
    "¡Un pulpo puede abrir frascos con sus ventosas!",
    "¡Los pulpos tienen neuronas en los brazos!",
    "¡El pulpo de anillos azules es uno de los más venenosos!",
    "¡Los pulpos pueden regenerar brazos perdidos!",
    "¡El pulpo camina, nada y se impulsa con chorros de agua!",
    "¡Los pulpos construyen jardines con conchas y piedras!",
    "¡El pulpo mimo puede imitar a otros animales marinos!",
    "¡Los pulpos viven solos, no en grupos!",
    "¡El pulpo gigante del Pacífico puede medir 5 metros!",
    "¡Los pulpos son daltónicos pero ven la polarización de la luz!",
    "¡El pulpo tiene el cerebro más grande de los invertebrados!",
    "¡Los pulpos pueden resolver laberintos y puzzles!",
    "¡Los pulpos existen desde hace más de 300 millones de años!",
  ],
  fish: [
    "¡Existen peces que brillan en el fondo del mar!",
    "¡Algunos peces pueden volar sobre el agua!",
    "¡Los peces no tienen párpados, duermen con los ojos abiertos!",
    "¡El tiburón ballena es el pez más grande del mundo!",
    "¡Algunos peces cambian de color para esconderse!",
    "¡Los peces usan branquias para respirar bajo el agua!",
    "¡Existen más de 30 mil especies de peces en el mundo!",
    "¡Los peces pueden sentir vibraciones en el agua!",
    "¡El pez espada puede nadar a 110 kilómetros por hora!",
    "¡Los peces dorados pueden recordar cosas por meses!",
    "¡El pez globo se infla con agua para parecer más grande!",
    "¡Los peces viajan en bancos para protegerse!",
    "¡Algunos peces hacen nidos para proteger sus huevos!",
    "¡El pez luna es el pez óseo más pesado del mundo!",
    "¡Los peces pueden sentir el sabor del agua a su alrededor!",
    "¡El pez arquero escupe chorros de agua para derribar insectos!",
    "¡Algunos peces viven en las profundidades más oscuras del océano!",
    "¡El pez payaso vive dentro de las anémonas de mar!",
    "¡Los peces existen desde hace más de 500 millones de años!",
    "¡Algunos peces tienen aletas que parecen alas!",
  ],
  seahorse: [
    "¡El caballito de mar es el único animal donde el padre se embaraza!",
    "¡Los caballitos de mar nadan en posición vertical!",
    "¡Los caballitos de mar se sujetan con la cola para no ser arrastrados!",
    "¡Los caballitos de mar no tienen estómago!",
    "¡Los caballitos de mar cambian de color para camuflarse!",
    "¡El caballito de mar pigmeo es más pequeño que una uña!",
    "¡Los caballitos de mar comen todo el día porque no tienen estómago!",
    "¡Los caballitos de mar forman parejas de por vida!",
    "¡Los caballitos de mar nadan muy despacio, son los peces más lentos!",
    "¡Un padre caballito de mar puede tener hasta 2 mil crías!",
    "¡Los caballitos de mar tienen ojos que se mueven independientemente!",
    "¡El caballito de mar usa su trompa para aspirar pequeños crustáceos!",
    "¡Los caballitos de mar bailan juntos cada mañana!",
    "¡Existen más de 40 especies de caballitos de mar!",
    "¡Los caballitos de mar no tienen escamas, tienen armadura ósea!",
    "¡Los caballitos de mar se encuentran en todos los océanos tropicales!",
    "¡El caballito de mar barrigudo es una de las especies más grandes!",
    "¡Los caballitos de mar son parientes de los peces pipa!",
    "¡Un caballito de mar mueve sus aletas hasta 50 veces por segundo!",
    "¡Los caballitos de mar son maestros del camuflaje!",
  ],
  jellyfish: [
    "¡Las medusas existen desde hace más de 500 millones de años!",
    "¡Las medusas no tienen cerebro, corazón ni sangre!",
    "¡Algunas medusas brillan en la oscuridad!",
    "¡La medusa melena de león puede tener tentáculos de 30 metros!",
    "¡Las medusas son 95% agua!",
    "¡Algunas medusas son inmortales y pueden rejuvenecer!",
    "¡Las medusas se mueven contrayendo su cuerpo como un paraguas!",
    "¡Las medusas usan tentáculos venenosos para capturar presas!",
    "¡La medusa caja es una de las criaturas más venenosas!",
    "¡Las medusas son alimento para las tortugas marinas!",
    "¡Algunas medusas son tan pequeñas que apenas se ven!",
    "¡Las medusas viven en todos los océanos del mundo!",
    "¡Un grupo de medusas se llama enjambre!",
    "¡Las medusas no eligen hacia dónde nadan, las corrientes las llevan!",
    "¡Algunas medusas tienen ojos que detectan la luz!",
    "¡La medusa luna es una de las más comunes!",
    "¡Las medusas son más antiguas que los dinosaurios!",
    "¡Algunos tentáculos pueden picar incluso después de muertas!",
    "¡Las medusas se estudian para crear materiales brillantes!",
    "¡La medusa inmortal puede volver a pólipo y reiniciar su vida!",
  ],
  stingray: [
    "¡Las rayas son parientes de los tiburones!",
    "¡Las rayas no tienen huesos, solo cartílago!",
    "¡Algunas rayas tienen un aguijón venenoso en la cola!",
    "¡Las rayas se entierran en la arena para esconderse!",
    "¡Las rayas usan electricidad para detectar presas!",
    "¡La mantarraya puede tener 7 metros de envergadura!",
    "¡Las rayas nadan batiendo sus aletas como alas!",
    "¡Las rayas comen moluscos, crustáceos y peces pequeños!",
    "¡Las rayas tienen la boca debajo del cuerpo!",
    "¡La raya eléctrica puede dar descargas para defenderse!",
    "¡Las rayas viven en aguas poco profundas y profundas!",
    "¡Las mantarrayas son gigantes gentiles que comen plancton!",
    "¡Las rayas pueden vivir hasta 25 años!",
    "¡Las rayas tienen piel áspera como papel de lija!",
    "¡Las rayas ven desde arriba pero la boca está abajo!",
    "¡Algunas rayas viven en agua dulce!",
    "¡Las mantarrayas son muy inteligentes y reconocen su reflejo!",
    "¡Las rayas dan a luz crías vivas!",
    "¡La forma aplanada de la raya le ayuda a esconderse en el fondo!",
    "¡Las rayas se encuentran en todos los océanos!",
  ],
  seal: [
    "¡Las focas pueden aguantar la respiración hasta 2 horas!",
    "¡Las focas duermen bajo el agua y suben a respirar sin despertar!",
    "¡Las focas tienen bigotes que sienten vibraciones en el agua!",
    "¡Las focas pueden nadar a 35 kilómetros por hora!",
    "¡Las crías de foca nacen con pelaje blanco y suave!",
    "¡Las focas se calientan con una capa gruesa de grasa!",
    "¡Las focas monje son una de las especies más raras!",
    "¡Las focas pueden sumergirse a 600 metros!",
    "¡Las focas leopardo son depredadoras feroces en la Antártida!",
    "¡Las focas se comunican con sonidos bajo el agua!",
    "¡Las focas arpa migran miles de kilómetros!",
    "¡Las focas tienen ojos grandes para ver en el fondo del mar!",
    "¡Las focas amamantan con leche súper grasa!",
    "¡Las focas pueden vivir hasta 30 años!",
    "¡Los elefantes marinos pueden pesar hasta 4 toneladas!",
    "¡Las focas cierran las fosas nasales al bucear!",
    "¡Las focas se encuentran en todos los océanos!",
    "¡Las focas toman sol en rocas y playas para calentarse!",
    "¡Las focas tienen patas traseras en forma de aleta!",
    "¡Las focas son mamíferos y necesitan respirar aire!",
  ],
  crab: [
    "¡Los cangrejos caminan de lado!",
    "¡Los cangrejos tienen diez patas, incluyendo dos pinzas!",
    "¡El cangrejo araña japonés puede medir 4 metros!",
    "¡Los cangrejos cambian de caparazón para crecer!",
    "¡Algunos cangrejos son ermitaños y usan conchas prestadas!",
    "¡Los cangrejos pueden regenerar pinzas perdidas!",
    "¡El cangrejo cocotero escala palmeras!",
    "¡Los cangrejos tienen sangre azul!",
    "¡Algunos cangrejos viven en tierra y solo van al mar a poner huevos!",
    "¡Los cangrejos usan las pinzas para comer y defenderse!",
    "¡Los cangrejos pueden vivir hasta 30 años!",
    "¡El cangrejo herradura existe desde hace 450 millones de años!",
    "¡Los cangrejos ven en todas las direcciones!",
    "¡Los cangrejos se comunican golpeando las pinzas!",
    "¡Los cangrejos ermitaños hacen fila para cambiar de concha!",
    "¡El cangrejo más pequeño mide solo 1 centímetro!",
    "¡Los cangrejos comen de todo: algas, moluscos y restos de peces!",
    "¡Las hembras de cangrejo cargan los huevos en el abdomen!",
    "¡Los cangrejos pueden caminar hacia adelante pero prefieren de lado!",
    "¡El cangrejo boxeador sostiene anémonas en sus pinzas para defenderse!",
  ],
  lobster: [
    "¡Las langostas pueden vivir más de 100 años!",
    "¡Las langostas tienen sangre azul!",
    "¡Las langostas crecen toda su vida y nunca paran!",
    "¡Las langostas se comunican orinándose en la cara!",
    "¡La langosta más grande pesaba más de 20 kilos!",
    "¡Las langostas cambian de caparazón para crecer!",
    "¡Las langostas tienen dos estómagos!",
    "¡Las langostas pueden regenerar patas y pinzas perdidas!",
    "¡Las langostas huelen con las antenas!",
    "¡Las langostas caminan por el fondo pero nadan hacia atrás cuando se asustan!",
    "¡Las langostas tienen dientes en el estómago!",
    "¡Las langostas cargan los huevos hasta un año!",
    "¡Las langostas pueden ser azules, amarillas o blancas!",
    "¡Las langostas son caníbales!",
    "¡Las langostas tienen ojos compuestos con miles de lentes!",
    "¡Las langostas recorren grandes distancias por el fondo del mar!",
    "¡Las langostas son crustáceos, parientes de los cangrejos!",
    "¡Las langostas pueden triturar conchas con sus pinzas!",
    "¡Las langostas tienen receptores de sabor en las patas!",
    "¡Una langosta puede caminar hasta 160 kilómetros por el fondo!",
  ],
  starfish: [
    "¡Las estrellas de mar no son peces, son equinodermos!",
    "¡Las estrellas de mar pueden regenerar brazos perdidos!",
    "¡Algunas estrellas de mar tienen más de 5 brazos!",
    "¡Las estrellas de mar no tienen cerebro!",
    "¡Las estrellas de mar comen sacando el estómago fuera del cuerpo!",
    "¡Las estrellas de mar caminan con cientos de pies tubulares!",
    "¡Existen más de 2 mil especies de estrellas de mar!",
    "¡Las estrellas de mar no tienen sangre, usan agua de mar!",
    "¡Algunas estrellas de mar brillan en el fondo del mar!",
    "¡La estrella de mar girasol tiene 24 brazos!",
    "¡Las estrellas de mar pueden vivir hasta 35 años!",
    "¡Las estrellas de mar tienen ojos en la punta de cada brazo!",
    "¡Las estrellas de mar se fijan a las rocas con ventosas!",
    "¡Algunas estrellas de mar comen corales!",
    "¡Si cortas una estrella de mar, cada pedazo puede ser una nueva!",
    "¡Las estrellas de mar existen en todos los colores del arcoíris!",
    "¡Las estrellas de mar viven en todos los océanos!",
    "¡Las estrellas de mar son muy lentas!",
    "¡La estrella de mar corona de espinas es venenosa!",
    "¡Las estrellas de mar son importantes para el equilibrio del océano!",
  ],
  narwhal: [
    "¡El narval tiene un cuerno que en realidad es un diente canino gigante!",
    "¡El colmillo del narval puede medir hasta 3 metros!",
    "¡Los narvales viven en las aguas heladas del Ártico!",
    "¡Los narvales son llamados los unicornios del mar!",
    "¡Los narvales se sumergen a más de 1500 metros!",
    "¡El colmillo del narval tiene millones de terminaciones nerviosas!",
    "¡Los narvales viven en grupos de 15 a 20 individuos!",
    "¡Los narvales se comunican con clics y silbidos!",
    "¡Los narvales pueden vivir hasta 50 años!",
    "¡Los narvales comen peces, calamares y camarones!",
    "¡El colmillo del narval crece toda su vida!",
    "¡Los narvales cambian de color al envejecer!",
    "¡Las crías de narval nacen grises y se aclaran!",
    "¡Los narvales pueden aguantar la respiración hasta 25 minutos!",
    "¡El narval es pariente de la beluga!",
    "¡Los narvales no tienen aleta dorsal para nadar bajo el hielo!",
    "¡Los narvales machos frotan sus colmillos como saludo!",
    "¡Los narvales son uno de los mamíferos que más profundo se sumergen!",
    "¡Los narvales se encuentran en Canadá, Groenlandia y Rusia!",
    "¡Los narvales inspiraron leyendas de unicornios en la Edad Media!",
  ],
  orca: [
    "¡Las orcas son en realidad el miembro más grande de la familia de los delfines!",
    "¡Las orcas viven en familias llamadas pods!",
    "¡Las orcas pueden nadar a 55 kilómetros por hora!",
    "¡Cada grupo de orcas tiene su propio dialecto!",
    "¡Las orcas cazan en grupo con estrategias coordinadas!",
    "¡Las orcas se encuentran en todos los océanos!",
    "¡Las orcas pueden vivir hasta 90 años!",
    "¡Las orcas pueden derribar focas de bloques de hielo con olas!",
    "¡Las orcas duermen con la mitad del cerebro despierta!",
    "¡Las orcas enseñan técnicas de caza a sus crías!",
    "¡La aleta dorsal del macho puede medir 1,8 metros!",
    "¡Las orcas se llaman ballenas asesinas pero son delfines!",
    "¡Las orcas se comunican con sonidos complejos!",
    "¡Cada orca tiene manchas blancas únicas detrás de los ojos!",
    "¡Las orcas comen peces, focas e incluso otras ballenas!",
    "¡Las crías de orca nacen con casi 2,5 metros!",
    "¡Las orcas tienen el segundo cerebro más grande de los mamíferos marinos!",
    "¡Las orcas pueden sumergirse a 300 metros!",
    "¡Las orcas viven en sociedades matriarcales!",
    "¡Las orcas son uno de los depredadores más inteligentes del océano!",
  ],
  clownfish: [
    "¡El pez payaso vive dentro de anémonas venenosas sin hacerse daño!",
    "¡El pez payaso tiene una capa de moco que lo protege del veneno!",
    "¡Todos los peces payaso nacen machos!",
    "¡El pez payaso más dominante del grupo puede volverse hembra!",
    "¡Los peces payaso limpian y protegen la anémona donde viven!",
    "¡Existen 30 especies de peces payaso!",
    "¡El pez payaso se hizo famoso con la película Buscando a Nemo!",
    "¡Los peces payaso son muy territoriales!",
    "¡El pez payaso hace una danza para presentarse a la anémona!",
    "¡Los peces payaso comen algas y pequeños invertebrados!",
    "¡El pez payaso puede vivir hasta 10 años!",
    "¡Los peces payaso se comunican con chasquidos!",
    "¡El pez payaso raramente se aleja de su anémona!",
    "¡Los peces payaso tienen rayas blancas y naranjas!",
    "¡La hembra del pez payaso es siempre la más grande del grupo!",
    "¡Los peces payaso duermen dentro de la anémona por la noche!",
    "¡El pez payaso pone huevos cerca de la anémona!",
    "¡El padre pez payaso cuida los huevos hasta que eclosionan!",
    "¡Los peces payaso viven en arrecifes de coral tropicales!",
    "¡El pez payaso es uno de los peces más coloridos del océano!",
  ],
  squid: [
    "¡Los calamares tienen tres corazones, como los pulpos!",
    "¡Los calamares tienen sangre azul!",
    "¡Los calamares pueden nadar hacia atrás expulsando agua!",
    "¡El calamar gigante puede medir hasta 13 metros!",
    "¡Los calamares tienen diez tentáculos, dos más largos!",
    "¡Los calamares pueden cambiar de color instantáneamente!",
    "¡Los calamares sueltan tinta para escapar de depredadores!",
    "¡El calamar colosal tiene los ojos más grandes del reino animal!",
    "¡Los calamares son muy inteligentes y resuelven problemas!",
    "¡Algunos calamares brillan en la oscuridad!",
    "¡Los calamares nadan en grupos llamados cardúmenes!",
    "¡El calamar vampiro vive en las profundidades oscuras del océano!",
    "¡Los calamares comen peces, camarones y otros calamares!",
    "¡Los calamares tienen un pico duro como el de un loro!",
    "¡El calamar de Humboldt puede pesar hasta 50 kilos!",
    "¡Los calamares pueden nadar a 40 kilómetros por hora!",
    "¡Los calamares tienen una concha interna llamada gladius!",
    "¡Los calamares viven en todos los océanos del mundo!",
    "¡El calamar gigante fue considerado un monstruo marino por siglos!",
    "¡Los calamares pueden vivir de 1 a 5 años!",
  ],
  walrus: [
    "¡Las morsas tienen colmillos que pueden llegar a 1 metro!",
    "¡Las morsas usan los colmillos para salir del hielo!",
    "¡Las morsas pueden pesar hasta 1500 kilos!",
    "¡Las morsas tienen bigotes súper sensibles para encontrar comida!",
    "¡Las morsas viven en el Ártico, en aguas heladas!",
    "¡Las morsas se calientan con una gruesa capa de grasa!",
    "¡Las morsas pueden aguantar la respiración hasta 10 minutos!",
    "¡Las morsas comen moluscos, especialmente almejas!",
    "¡Las morsas viven en grandes grupos en las playas!",
    "¡Las morsas pueden dormir tanto en el agua como en tierra!",
    "¡Los machos luchan con los colmillos por las hembras!",
    "¡Las morsas se comunican con sonidos como campanas!",
    "¡Las morsas pueden nadar a 35 kilómetros por hora!",
    "¡Las crías de morsa se quedan con la madre hasta 3 años!",
    "¡Las morsas pueden vivir hasta 40 años!",
    "¡La piel de la morsa cambia de color: rosa al sol y gris en el agua!",
    "¡Las morsas usan los colmillos como apoyo para dormir en el hielo!",
    "¡Las morsas son los pinnípedos más grandes después de los elefantes marinos!",
    "¡Las morsas pueden comer hasta 6 mil almejas al día!",
    "¡Las morsas tienen bolsas de aire en el cuello para flotar!",
  ],
  sea_turtle: [
    "¡Las tortugas marinas existen desde hace más de 100 millones de años!",
    "¡Las tortugas marinas viajan miles de kilómetros por el océano!",
    "¡Las tortugas marinas vuelven a la misma playa donde nacieron para poner huevos!",
    "¡Las tortugas marinas pueden aguantar la respiración hasta 5 horas!",
    "¡La tortuga laúd es la más grande y puede pesar 700 kilos!",
    "¡Las tortugas marinas lloran para eliminar la sal del agua de mar!",
    "¡Las tortugas marinas usan el campo magnético de la Tierra para navegar!",
    "¡Existen 7 especies de tortugas marinas!",
    "¡Las tortugas marinas comen medusas, algas y esponjas!",
    "¡Las crías de tortuga marina corren al mar al nacer!",
    "¡El sexo de las tortugas marinas depende de la temperatura de la arena!",
    "¡Las tortugas marinas pueden vivir hasta 80 años!",
    "¡Las tortugas marinas nadan usando las aletas como alas!",
    "¡Las tortugas marinas se sumergen a más de 1000 metros!",
    "¡Las tortugas marinas son reptiles que viven en el mar!",
    "¡Las tortugas marinas no pueden esconderse dentro del caparazón!",
    "¡La tortuga verde come principalmente algas y hierbas marinas!",
    "¡Las tortugas marinas están amenazadas por la contaminación plástica!",
    "¡Las tortugas marinas tienen glándulas de sal cerca de los ojos!",
    "¡Las tortugas marinas nadan a hasta 35 kilómetros por hora!",
  ],
  swordfish: [
    "¡El pez espada tiene un pico de hasta 1 metro!",
    "¡El pez espada puede nadar a 110 kilómetros por hora!",
    "¡El pez espada usa su pico para aturdir a las presas!",
    "¡El pez espada adulto no tiene escamas!",
    "¡El pez espada puede pesar hasta 650 kilos!",
    "¡El pez espada puede sumergirse a 550 metros!",
    "¡El pez espada tiene un órgano que calienta sus ojos y cerebro!",
    "¡El pez espada nada solo, no en cardúmenes!",
    "¡El pez espada puede medir hasta 4,5 metros!",
    "¡El pez espada come calamares, peces y crustáceos!",
    "¡El pez espada migra a aguas más cálidas en invierno!",
    "¡El pez espada puede saltar completamente fuera del agua!",
    "¡El pico del pez espada es aplanado, diferente del marlín!",
    "¡El pez espada crece muy rápido en su primer año!",
    "¡El pez espada puede vivir hasta 15 años!",
    "¡El pez espada tiene pocos depredadores naturales!",
    "¡El pez espada es uno de los peces más rápidos del océano!",
    "¡Los peces espada bebé tienen dientes y escamas que pierden al crecer!",
    "¡El pez espada nada en aguas de todos los océanos!",
    "¡El pez espada es un depredador tope en la cadena alimentaria!",
  ],
  manatee: [
    "¡El manatí es un mamífero herbívoro que vive en el agua!",
    "¡Los manatíes pueden comer hasta 50 kilos de plantas al día!",
    "¡Los manatíes son llamados vacas marinas!",
    "¡Los manatíes pueden aguantar la respiración hasta 20 minutos!",
    "¡Los manatíes nadan despacio, a solo 8 kilómetros por hora!",
    "¡Los manatíes pueden pesar hasta 600 kilos!",
    "¡Los manatíes son parientes lejanos de los elefantes!",
    "¡Los manatíes viven en aguas cálidas y poco profundas!",
    "¡Los manatíes tienen labios flexibles para arrancar plantas!",
    "¡Los manatíes pueden vivir hasta 60 años!",
    "¡Los manatíes cambian dientes toda su vida, como los tiburones!",
    "¡Los manatíes son animales muy gentiles y tranquilos!",
    "¡Los manatíes tienen uñas en las aletas, herencia de sus ancestros!",
    "¡Los manatíes pueden encontrarse en ríos y en el mar!",
    "¡El manatí amazónico vive exclusivamente en agua dulce!",
    "¡Las crías de manatí maman bajo el agua!",
    "¡Los manatíes fueron confundidos con sirenas por marineros antiguos!",
    "¡Los manatíes se comunican con sonidos agudos bajo el agua!",
    "¡Los manatíes tienen huesos muy densos que les ayudan a hundirse!",
    "¡Los manatíes están en peligro de extinción y protegidos por ley!",
  ],
};
