import type { AquaticId } from "./aquatics";

export const aquaticFunFacts: Record<AquaticId, string[]> = {
  whale: [
    "A baleia-azul é o maior animal que já existiu na Terra!",
    "O coração da baleia-azul é do tamanho de um carro pequeno!",
    "As baleias cantam para se comunicar a milhares de quilômetros!",
    "As baleias podem prender a respiração por até 90 minutos!",
    "As baleias bebês nascem com quase 8 metros de comprimento!",
    "As baleias migram milhares de quilômetros todo ano!",
    "A língua da baleia-azul pesa tanto quanto um elefante!",
    "As baleias jubarte fazem acrobacias incríveis fora da água!",
    "As baleias têm pulmões, não brânquias, e precisam subir para respirar!",
    "As baleias podem viver mais de 100 anos!",
    "As baleias produzem leite para alimentar seus filhotes!",
    "O jato d'água da baleia pode chegar a 9 metros de altura!",
    "As baleias dormem com metade do cérebro acordada!",
    "A baleia-azul pode pesar até 150 toneladas!",
    "As baleias são descendentes de animais que viviam na terra!",
    "As baleias cachalote mergulham a mais de 2 mil metros de profundidade!",
    "Cada baleia jubarte tem uma cauda única, como uma impressão digital!",
    "As baleias se comunicam com sons graves chamados de cantos!",
    "As baleias cinzentas fazem a migração mais longa de todos os mamíferos!",
    "As baleias ajudam a fertilizar os oceanos com seus dejetos!",
  ],
  dolphin: [
    "Os golfinhos dormem com um olho aberto!",
    "Golfinhos se chamam uns aos outros por nomes únicos!",
    "Os golfinhos conseguem nadar a 60 quilômetros por hora!",
    "Golfinhos usam ecolocalização para encontrar peixes!",
    "Os golfinhos são um dos animais mais inteligentes do mundo!",
    "Golfinhos vivem em grupos chamados de manadas!",
    "Os golfinhos podem prender a respiração por até 10 minutos!",
    "Golfinhos brincam com ondas e surfam!",
    "Os golfinhos ajudam outros golfinhos que estão machucados!",
    "Golfinhos reconhecem o próprio reflexo no espelho!",
    "Os golfinhos bebês ficam junto da mãe por até 6 anos!",
    "Golfinhos conseguem pular até 6 metros fora da água!",
    "Os golfinhos se comunicam com cliques e assobios!",
    "Golfinhos já foram vistos ajudando nadadores em perigo!",
    "O golfinho-nariz-de-garrafa é a espécie mais conhecida!",
    "Golfinhos têm uma pele super lisa que ajuda a nadar rápido!",
    "Os golfinhos trocam de pele a cada 2 horas!",
    "Golfinhos podem viver até 50 anos!",
    "Os golfinhos usam esponjas no focinho para proteger ao cavar no fundo do mar!",
    "Existem mais de 40 espécies de golfinhos no mundo!",
  ],
  shark: [
    "Os tubarões existem há mais de 400 milhões de anos!",
    "Tubarões têm fileiras de dentes que se substituem a vida toda!",
    "O tubarão-baleia é o maior peixe do mundo!",
    "Tubarões conseguem sentir uma gota de sangue na água a quilômetros!",
    "Tubarões não têm ossos, só cartilagem!",
    "Alguns tubarões precisam nadar sem parar para respirar!",
    "O tubarão-martelo tem olhos nas pontas da cabeça!",
    "Tubarões têm um sexto sentido que detecta campos elétricos!",
    "O tubarão-branco pode saltar completamente para fora da água!",
    "Tubarões podem ter até 3 mil dentes ao mesmo tempo!",
    "O menor tubarão do mundo cabe na palma da mão!",
    "Tubarões vivem em todos os oceanos do mundo!",
    "O tubarão-lanterna brilha no escuro!",
    "Tubarões ajudam a manter o equilíbrio dos oceanos!",
    "Os tubarões têm uma audição incrível debaixo d'água!",
    "O tubarão-baleia é gentil e come apenas plâncton!",
    "Filhotes de tubarão já nascem sabendo nadar!",
    "Tubarões podem viver até 70 anos!",
    "O tubarão-da-Groenlândia pode viver mais de 400 anos!",
    "Os tubarões são mais antigos que os dinossauros!",
  ],
  octopus: [
    "O polvo tem três corações!",
    "Os polvos têm sangue azul!",
    "Polvos podem mudar de cor em milissegundos!",
    "O polvo tem oito braços, cada um com ventosas!",
    "Polvos são os invertebrados mais inteligentes!",
    "O polvo pode se espremer por qualquer buraco do tamanho do seu bico!",
    "Polvos soltam tinta para escapar dos predadores!",
    "O polvo consegue abrir potes com as ventosas!",
    "Polvos têm neurônios nos braços e pensam com eles!",
    "O polvo-de-anéis-azuis é um dos mais venenosos do mundo!",
    "Polvos podem regenerar braços perdidos!",
    "O polvo caminha, nada e até jatos de água para se mover!",
    "Polvos constroem jardins com conchas e pedras!",
    "O polvo-mimico pode imitar outros animais do mar!",
    "Polvos vivem sozinhos, não em grupos!",
    "O polvo gigante do Pacífico pode ter 5 metros de envergadura!",
    "Polvos são daltônicos mas veem a polarização da luz!",
    "O polvo tem o maior cérebro de todos os invertebrados!",
    "Polvos podem resolver labirintos e puzzles!",
    "Os polvos existem há mais de 300 milhões de anos!",
  ],
  fish: [
    "Existem peixes que brilham no fundo do mar!",
    "Alguns peixes conseguem voar por cima da água!",
    "Peixes não têm pálpebras, dormem de olhos abertos!",
    "O tubarão-baleia é o maior peixe do mundo!",
    "Alguns peixes mudam de cor para se esconder!",
    "Os peixes usam brânquias para respirar debaixo d'água!",
    "Existem mais de 30 mil espécies de peixes no mundo!",
    "Peixes conseguem sentir vibrações na água!",
    "O peixe-espada pode nadar a 110 quilômetros por hora!",
    "Os peixes-dourados se lembram de coisas por meses!",
    "O baiacu se enche de água para parecer maior!",
    "Peixes viajam em cardumes para se proteger!",
    "Alguns peixes fazem ninhos para proteger seus ovos!",
    "O peixe-lua é o peixe ósseo mais pesado do mundo!",
    "Peixes podem sentir o gosto da água ao redor deles!",
    "O peixe-arqueiro cospe jatos de água para derrubar insetos!",
    "Alguns peixes vivem nas profundezas mais escuras do oceano!",
    "O peixe-palhaço vive dentro das anêmonas do mar!",
    "Os peixes existem há mais de 500 milhões de anos!",
    "Peixes podem ter barbatanas que parecem asas!",
  ],
  seahorse: [
    "O cavalo-marinho é o único animal onde o pai fica grávido!",
    "Os cavalos-marinhos nadam em pé, diferente de todos os peixes!",
    "Cavalos-marinhos se seguram em coisas com a cauda para não serem levados!",
    "Os cavalos-marinhos não têm estômago!",
    "Cavalos-marinhos mudam de cor para se camuflar!",
    "O cavalo-marinho-pigmeu é menor que uma unha!",
    "Cavalos-marinhos comem o dia todo porque não têm estômago!",
    "Os cavalos-marinhos formam casais para a vida toda!",
    "Cavalos-marinhos nadam muito devagar, são os peixes mais lentos!",
    "O pai cavalo-marinho pode ter até 2 mil filhotes de uma vez!",
    "Cavalos-marinhos têm olhos que se movem independentemente!",
    "O cavalo-marinho usa a tromba para sugar pequenos crustáceos!",
    "Cavalos-marinhos dançam juntos toda manhã para fortalecer o laço do casal!",
    "Existem mais de 40 espécies de cavalos-marinhos!",
    "Os cavalos-marinhos não têm escamas, têm uma armadura óssea!",
    "Cavalos-marinhos podem ser encontrados em todos os oceanos tropicais!",
    "O cavalo-marinho barrigudo é uma das maiores espécies!",
    "Cavalos-marinhos são parentes dos peixes-cachimbo!",
    "O cavalo-marinho consegue mover as barbatanas até 50 vezes por segundo!",
    "Cavalos-marinhos são mestres da camuflagem!",
  ],
  jellyfish: [
    "As águas-vivas existem há mais de 500 milhões de anos!",
    "Águas-vivas não têm cérebro, coração nem sangue!",
    "Algumas águas-vivas brilham no escuro!",
    "A água-viva-juba-de-leão pode ter tentáculos de 30 metros!",
    "Águas-vivas são compostas de 95% de água!",
    "Algumas águas-vivas são imortais e podem rejuvenescer!",
    "As águas-vivas se movem contraindo o corpo como um guarda-chuva!",
    "Águas-vivas usam tentáculos com veneno para capturar presas!",
    "A água-viva-caixa é uma das criaturas mais venenosas do mundo!",
    "Águas-vivas são alimento para tartarugas marinhas!",
    "Algumas águas-vivas são tão pequenas que mal se veem!",
    "Águas-vivas vivem em todos os oceanos do mundo!",
    "Um grupo de águas-vivas se chama enxame!",
    "Águas-vivas não escolhem para onde nadam, são levadas pelas correntes!",
    "Algumas águas-vivas têm olhos que detectam luz!",
    "A água-viva-lua é uma das mais comuns nos oceanos!",
    "Águas-vivas são mais antigas que os dinossauros!",
    "Algumas águas-vivas podem ter tentáculos venenosos mesmo depois de mortas!",
    "Águas-vivas são estudadas para criar materiais brilhantes!",
    "A água-viva-imortal pode voltar ao estágio de pólipo e recomeçar a vida!",
  ],
  stingray: [
    "As arraias são parentes dos tubarões!",
    "Arraias não têm ossos, só cartilagem!",
    "Algumas arraias têm um ferrão venenoso na cauda!",
    "As arraias se enterram na areia para se esconder!",
    "Arraias usam eletricidade para sentir presas escondidas!",
    "A arraia-manta pode ter 7 metros de envergadura!",
    "Arraias nadam batendo as nadadeiras como asas!",
    "As arraias comem moluscos, crustáceos e peixes pequenos!",
    "Arraias têm a boca embaixo do corpo!",
    "A arraia-elétrica pode dar choques para se defender!",
    "Arraias vivem em águas rasas e profundas!",
    "As arraias-manta são gigantes gentis que comem plâncton!",
    "Arraias podem viver até 25 anos!",
    "As arraias têm pele áspera como lixa!",
    "Arraias veem de cima mas a boca fica embaixo!",
    "Algumas arraias vivem em água doce!",
    "As arraias-manta são muito inteligentes e reconhecem o reflexo!",
    "Arraias dão à luz filhotes vivos, não botam ovos!",
    "O formato achatado da arraia ajuda a se esconder no fundo do mar!",
    "Arraias são encontradas em todos os oceanos do mundo!",
  ],
  seal: [
    "As focas podem prender a respiração por até 2 horas!",
    "Focas dormem debaixo d'água e sobem para respirar sem acordar!",
    "As focas têm bigodes que sentem vibrações na água!",
    "Focas podem nadar a 35 quilômetros por hora!",
    "As focas bebês nascem com uma pelagem branca e fofa!",
    "Focas se aquecem com uma camada grossa de gordura!",
    "As focas-monge são uma das espécies mais raras!",
    "Focas podem mergulhar a 600 metros de profundidade!",
    "As focas-leopardo são predadoras ferozes na Antártida!",
    "Focas se comunicam com sons debaixo d'água!",
    "As focas-harpa migram milhares de quilômetros!",
    "Focas têm olhos grandes para enxergar no fundo do mar!",
    "As focas amamentam os filhotes com leite super gordo!",
    "Focas podem viver até 30 anos!",
    "As focas-elefante podem pesar até 4 toneladas!",
    "Focas fecham as narinas quando mergulham!",
    "As focas são encontradas em todos os oceanos!",
    "Focas tomam sol em rochas e praias para se aquecer!",
    "As focas têm patas traseiras em forma de nadadeira!",
    "Focas são mamíferos e precisam respirar ar!",
  ],
  crab: [
    "Os caranguejos andam de lado!",
    "Caranguejos têm dez patas, incluindo duas pinças!",
    "O caranguejo-aranha-japonês pode ter 4 metros de envergadura!",
    "Caranguejos trocam de casca para crescer!",
    "Alguns caranguejos são ermitões e usam conchas emprestadas!",
    "Caranguejos podem regenerar pinças perdidas!",
    "O caranguejo-dos-coqueiros escala palmeiras!",
    "Caranguejos têm sangue azul!",
    "Alguns caranguejos vivem na terra e só voltam ao mar para botar ovos!",
    "Os caranguejos usam as pinças para comer e se defender!",
    "Caranguejos podem viver até 30 anos!",
    "O caranguejo-ferradura existe há 450 milhões de anos!",
    "Caranguejos veem em todas as direções!",
    "Os caranguejos se comunicam batendo as pinças!",
    "Caranguejos-ermitões fazem fila para trocar de concha!",
    "O menor caranguejo do mundo tem apenas 1 centímetro!",
    "Caranguejos comem de tudo: algas, moluscos e restos de peixes!",
    "As fêmeas de caranguejo carregam os ovos na barriga!",
    "Caranguejos podem andar para frente, mas preferem de lado!",
    "O caranguejo-boxeador segura anêmonas nas pinças para se defender!",
  ],
  lobster: [
    "As lagostas podem viver mais de 100 anos!",
    "Lagostas têm sangue azul!",
    "As lagostas crescem a vida toda e nunca param!",
    "Lagostas se comunicam fazendo xixi na cara umas das outras!",
    "A maior lagosta já encontrada pesava mais de 20 quilos!",
    "Lagostas trocam de casca para crescer!",
    "As lagostas têm dois estômagos!",
    "Lagostas conseguem regenerar patas e pinças perdidas!",
    "As lagostas sentem cheiro com as antenas!",
    "Lagostas andam no fundo do mar, mas nadam para trás quando assustadas!",
    "As lagostas têm dentes no estômago!",
    "Lagostas carregam os ovos por até um ano!",
    "As lagostas podem ser azuis, amarelas ou até brancas!",
    "Lagostas são canibais e podem comer outras lagostas!",
    "As lagostas têm um olho composto com milhares de lentes!",
    "Lagostas podem percorrer grandes distâncias no fundo do mar!",
    "As lagostas são crustáceos, parentes dos caranguejos!",
    "Lagostas podem esmagar conchas com suas pinças poderosas!",
    "As lagostas têm receptores de sabor nas patas!",
    "Uma lagosta pode caminhar até 160 quilômetros pelo fundo do mar!",
  ],
  starfish: [
    "As estrelas-do-mar não são peixes, são equinodermos!",
    "Estrelas-do-mar podem regenerar braços perdidos!",
    "Algumas estrelas-do-mar têm mais de 5 braços!",
    "As estrelas-do-mar não têm cérebro!",
    "Estrelas-do-mar comem empurrando o estômago para fora do corpo!",
    "As estrelas-do-mar andam com centenas de pezinhos em forma de tubo!",
    "Existem mais de 2 mil espécies de estrelas-do-mar!",
    "Estrelas-do-mar não têm sangue, usam água do mar!",
    "Algumas estrelas-do-mar brilham no fundo do mar!",
    "A estrela-do-mar-girassol tem 24 braços!",
    "Estrelas-do-mar podem viver até 35 anos!",
    "As estrelas-do-mar têm olhos na ponta de cada braço!",
    "Estrelas-do-mar se fixam em rochas com as ventosas dos pés!",
    "Algumas estrelas-do-mar comem corais!",
    "Se cortar uma estrela-do-mar, cada pedaço pode virar uma nova!",
    "Estrelas-do-mar existem em todas as cores do arco-íris!",
    "As estrelas-do-mar vivem em todos os oceanos do mundo!",
    "Estrelas-do-mar são muito lentas, andam poucos centímetros por minuto!",
    "A estrela-do-mar-coroa-de-espinhos é venenosa!",
    "Estrelas-do-mar são importantes para o equilíbrio do oceano!",
  ],
  narwhal: [
    "O narval tem um chifre que na verdade é um dente canino gigante!",
    "O chifre do narval pode ter até 3 metros de comprimento!",
    "Narvais vivem nas águas geladas do Ártico!",
    "Os narvais são chamados de unicórnios do mar!",
    "Narvais mergulham a mais de 1500 metros de profundidade!",
    "O chifre do narval tem milhões de terminações nervosas!",
    "Narvais vivem em grupos de 15 a 20 indivíduos!",
    "Os narvais se comunicam com cliques e assobios!",
    "Narvais podem viver até 50 anos!",
    "Os narvais comem peixes, lulas e camarões!",
    "O chifre do narval cresce a vida toda!",
    "Narvais mudam de cor conforme envelhecem!",
    "Os bebês narval nascem cinzentos e ficam mais claros!",
    "Narvais podem prender a respiração por até 25 minutos!",
    "O narval é parente da beluga!",
    "Narvais não têm barbatana dorsal para nadar sob o gelo!",
    "Os narvais machos esfregam os chifres como cumprimento!",
    "Narvais são um dos mamíferos que mergulham mais fundo!",
    "Os narvais são encontrados no Canadá, Groenlândia e Rússia!",
    "Narvais inspiraram lendas de unicórnios na Idade Média!",
  ],
  orca: [
    "As orcas são na verdade o maior membro da família dos golfinhos!",
    "Orcas vivem em famílias chamadas de pods!",
    "As orcas podem nadar a 55 quilômetros por hora!",
    "Cada grupo de orcas tem seu próprio dialeto!",
    "As orcas caçam em grupo com estratégias coordenadas!",
    "Orcas são encontradas em todos os oceanos do mundo!",
    "As orcas podem viver até 90 anos!",
    "Orcas conseguem derrubar focas de blocos de gelo com ondas!",
    "As orcas dormem com metade do cérebro acordada!",
    "Orcas ensinam técnicas de caça para os filhotes!",
    "A nadadeira dorsal do macho pode ter 1,8 metro de altura!",
    "Orcas são chamadas de baleias assassinas, mas são golfinhos!",
    "As orcas se comunicam com sons complexos!",
    "Cada orca tem manchas brancas únicas atrás dos olhos!",
    "Orcas comem peixes, focas, e até outras baleias!",
    "Os filhotes de orca nascem com quase 2,5 metros!",
    "As orcas têm o segundo maior cérebro de todos os mamíferos marinhos!",
    "Orcas podem mergulhar a 300 metros de profundidade!",
    "As orcas vivem em sociedades matriarcais!",
    "Orcas são um dos predadores mais inteligentes do oceano!",
  ],
  clownfish: [
    "O peixe-palhaço vive dentro de anêmonas venenosas sem se machucar!",
    "Peixe-palhaço tem uma camada de muco que protege do veneno!",
    "Todos os peixes-palhaço nascem machos!",
    "O peixe-palhaço mais dominante do grupo pode virar fêmea!",
    "Peixes-palhaço limpam e protegem a anêmona onde vivem!",
    "Existem 30 espécies de peixes-palhaço!",
    "O peixe-palhaço ficou famoso com o filme Procurando Nemo!",
    "Peixes-palhaço são muito territorialistas!",
    "O peixe-palhaço faz uma dança para se apresentar à anêmona!",
    "Peixes-palhaço comem algas e pequenos invertebrados!",
    "O peixe-palhaço pode viver até 10 anos!",
    "Peixes-palhaço se comunicam com estalos e sons!",
    "O peixe-palhaço raramente se afasta da sua anêmona!",
    "Peixes-palhaço têm listras brancas e laranja para se camuflar!",
    "A fêmea do peixe-palhaço é sempre a maior do grupo!",
    "Peixes-palhaço dormem dentro da anêmona à noite!",
    "O peixe-palhaço bota ovos perto da anêmona!",
    "O pai peixe-palhaço cuida dos ovos até eclodirem!",
    "Peixes-palhaço vivem em recifes de coral tropicais!",
    "O peixe-palhaço é um dos peixes mais coloridos do oceano!",
  ],
  squid: [
    "Lulas têm três corações, como os polvos!",
    "As lulas têm sangue azul!",
    "Lulas podem nadar para trás jatando água!",
    "A lula-gigante pode ter até 13 metros de comprimento!",
    "Lulas têm dez tentáculos, dois mais longos que os outros!",
    "Lulas podem mudar de cor instantaneamente!",
    "As lulas soltam tinta para escapar de predadores!",
    "A lula-colossal tem os maiores olhos do reino animal!",
    "Lulas são muito inteligentes e podem resolver problemas!",
    "Algumas lulas brilham no escuro com bioluminescência!",
    "Lulas nadam em grupos chamados de cardumes!",
    "A lula-vampiro vive nas profundezas escuras do oceano!",
    "Lulas comem peixes, camarões e outras lulas!",
    "Lulas têm um bico duro como o de um papagaio!",
    "A lula-de-Humboldt pode pesar até 50 quilos!",
    "Lulas podem nadar a até 40 quilômetros por hora!",
    "As lulas têm uma concha interna chamada gladius!",
    "Lulas vivem em todos os oceanos do mundo!",
    "A lula-gigante foi considerada um monstro marinho por séculos!",
    "Lulas podem viver de 1 a 5 anos dependendo da espécie!",
  ],
  walrus: [
    "As morsas têm presas que podem chegar a 1 metro!",
    "Morsas usam as presas para se puxar para fora do gelo!",
    "As morsas podem pesar até 1500 quilos!",
    "Morsas têm bigodes super sensíveis para encontrar comida no fundo do mar!",
    "As morsas vivem no Ártico, em águas geladas!",
    "Morsas se aquecem com uma camada grossa de gordura!",
    "As morsas podem prender a respiração por até 10 minutos!",
    "Morsas comem moluscos, especialmente amêijoas!",
    "As morsas vivem em grandes grupos nas praias!",
    "Morsas podem dormir tanto na água quanto em terra!",
    "As morsas machos lutam com as presas para disputar fêmeas!",
    "Morsas se comunicam com sons que parecem sinos!",
    "As morsas podem nadar a 35 quilômetros por hora!",
    "Morsas bebês ficam com a mãe por até 3 anos!",
    "As morsas podem viver até 40 anos!",
    "A pele da morsa muda de cor: fica rosa no sol e cinza na água!",
    "Morsas usam as presas como apoio para dormir no gelo!",
    "As morsas são os maiores pinípedes depois dos elefantes-marinhos!",
    "Morsas podem comer até 6 mil amêijoas por dia!",
    "As morsas têm bolsas de ar no pescoço para flutuar enquanto dormem!",
  ],
  sea_turtle: [
    "As tartarugas-marinhas existem há mais de 100 milhões de anos!",
    "Tartarugas-marinhas viajam milhares de quilômetros pelo oceano!",
    "As tartarugas-marinhas voltam à mesma praia onde nasceram para botar ovos!",
    "Tartarugas-marinhas podem prender a respiração por até 5 horas!",
    "A tartaruga-de-couro é a maior e pode pesar até 700 quilos!",
    "Tartarugas-marinhas choram para eliminar o sal da água do mar!",
    "As tartarugas-marinhas usam o campo magnético da Terra para navegar!",
    "Existem 7 espécies de tartarugas-marinhas!",
    "Tartarugas-marinhas comem águas-vivas, algas e esponjas!",
    "As tartarugas-marinhas bebês correm para o mar ao nascer!",
    "O sexo das tartarugas-marinhas depende da temperatura da areia!",
    "Tartarugas-marinhas podem viver até 80 anos!",
    "As tartarugas-marinhas nadam usando as nadadeiras como asas!",
    "Tartarugas-marinhas mergulham a mais de 1000 metros!",
    "As tartarugas-marinhas são répteis que vivem no mar!",
    "Tartarugas-marinhas não conseguem se esconder dentro do casco!",
    "A tartaruga-verde come principalmente algas e ervas marinhas!",
    "Tartarugas-marinhas são ameaçadas por poluição plástica!",
    "As tartarugas-marinhas têm glândulas de sal perto dos olhos!",
    "Tartarugas-marinhas nadam a até 35 quilômetros por hora!",
  ],
  swordfish: [
    "O peixe-espada tem um bico que pode ter 1 metro de comprimento!",
    "Peixe-espada pode nadar a 110 quilômetros por hora!",
    "O peixe-espada usa o bico para atordoar as presas!",
    "Peixe-espada não tem escamas quando adulto!",
    "O peixe-espada pode pesar até 650 quilos!",
    "Peixe-espada pode mergulhar a 550 metros de profundidade!",
    "O peixe-espada tem um órgão que aquece os olhos e o cérebro!",
    "Peixe-espada nada sozinho, não em cardumes!",
    "O peixe-espada pode medir até 4,5 metros!",
    "Peixe-espada come lulas, peixes e crustáceos!",
    "O peixe-espada migra para águas mais quentes no inverno!",
    "Peixe-espada pode saltar completamente fora da água!",
    "O bico do peixe-espada é achatado, diferente do marlim!",
    "Peixe-espada cresce muito rápido no primeiro ano de vida!",
    "O peixe-espada pode viver até 15 anos!",
    "Peixe-espada tem poucos predadores naturais!",
    "O peixe-espada é um dos peixes mais rápidos do oceano!",
    "Peixe-espada bebê tem dentes e escamas que perdem ao crescer!",
    "O peixe-espada nada em águas de todos os oceanos!",
    "Peixe-espada é um predador de topo na cadeia alimentar!",
  ],
  manatee: [
    "O peixe-boi é um mamífero herbívoro que vive na água!",
    "Peixe-boi pode comer até 50 quilos de plantas por dia!",
    "O peixe-boi é chamado de vaca marinha!",
    "Peixe-boi pode prender a respiração por até 20 minutos!",
    "O peixe-boi nada devagar, a apenas 8 quilômetros por hora!",
    "Peixe-boi pode pesar até 600 quilos!",
    "O peixe-boi é parente distante do elefante!",
    "Peixe-boi vive em águas mornas e rasas!",
    "O peixe-boi tem lábios flexíveis para arrancar plantas!",
    "Peixe-boi pode viver até 60 anos!",
    "O peixe-boi troca de dentes a vida toda, como tubarões!",
    "Peixe-boi é um animal muito gentil e calmo!",
    "O peixe-boi tem unhas nas nadadeiras, herança dos ancestrais!",
    "Peixe-boi pode ser encontrado em rios e no mar!",
    "O peixe-boi-da-Amazônia vive exclusivamente em água doce!",
    "Peixe-boi bebê mama debaixo d'água!",
    "O peixe-boi foi confundido com sereias por marinheiros antigos!",
    "Peixe-boi se comunica com sons agudos debaixo d'água!",
    "O peixe-boi tem ossos muito densos que ajudam a afundar!",
    "Peixe-boi está ameaçado de extinção e é protegido por lei!",
  ],
};

import { aquaticFunFactsEn } from "./aquaticFunFactsEn";
import { aquaticFunFactsEs } from "./aquaticFunFactsEs";
import { aquaticFunFactsFr } from "./aquaticFunFactsFr";
import { aquaticFunFactsIt } from "./aquaticFunFactsIt";
import { aquaticFunFactsDe } from "./aquaticFunFactsDe";
import type { Locale } from "@/i18n/translations";

const factsByLocale: Record<Locale, Record<AquaticId, string[]>> = {
  pt: aquaticFunFacts,
  en: aquaticFunFactsEn,
  es: aquaticFunFactsEs,
  fr: aquaticFunFactsFr,
  it: aquaticFunFactsIt,
  de: aquaticFunFactsDe,
};

export function getRandomAquaticFunFact(aquaticId: AquaticId, locale: Locale = "pt"): string {
  const facts = factsByLocale[locale][aquaticId];
  return facts[Math.floor(Math.random() * facts.length)];
}
