import type { DinoId } from "./dinosaurs";

export const dinoFunFactsIt: Record<DinoId, string[]> = {
  trex: [
    "Il T-Rex aveva denti grandi come banane!",
    "Il T-Rex poteva sentire le vibrazioni del terreno con i piedi!",
    "Le piccole braccia del T-Rex erano in realtà super forti!",
    "Il T-Rex è vissuto 68 milioni di anni fa!",
    "Il T-Rex poteva mangiare 230 chili di carne in un morso!",
    "T-Rex significa Re dei Lucertoloni Tiranni!",
    "Il T-Rex poteva correre a 40 chilometri all'ora!",
    "Il T-Rex aveva il morso più potente di tutti gli animali terrestri!",
    "Il cervello del T-Rex era più grande di quello della maggior parte dei dinosauri!",
    "Il T-Rex aveva una vista migliore di un'aquila!",
    "Gli scienziati hanno trovato più di 50 scheletri di T-Rex!",
    "Il T-Rex era lungo fino a 12 metri!",
    "I cuccioli di T-Rex nascevano coperti di piume!",
    "Il T-Rex viveva in quello che oggi sono gli Stati Uniti e il Canada!",
    "La coda del T-Rex lo aiutava a mantenere l'equilibrio mentre correva!",
    "Il T-Rex è parente delle galline di oggi!",
    "Il T-Rex poteva sentire suoni molto gravi, come i terremoti!",
    "Il cranio del T-Rex poteva essere lungo 1,5 metri!",
    "Il T-Rex sostituiva i denti per tutta la vita, come gli squali!",
    "Il T-Rex fu uno degli ultimi dinosauri prima dell'estinzione!",
  ],
  triceratops: [
    "Il Triceratopo aveva tre corna sul muso!",
    "Lo scudo del Triceratopo proteggeva il suo collo!",
    "Il Triceratopo era erbivoro e mangiava piante tutto il giorno!",
    "Il Triceratopo poteva pesare fino a 12 tonnellate!",
    "Triceratopo significa faccia con tre corna!",
    "Il Triceratopo viveva in branchi per proteggersi!",
    "Il becco del Triceratopo assomigliava a quello di un pappagallo!",
    "Il Triceratopo è vissuto nella stessa epoca del T-Rex!",
    "Lo scudo del Triceratopo cambiava colore per attirare i partner!",
    "Il Triceratopo era lungo fino a 9 metri!",
    "Il cranio del Triceratopo è uno dei più grandi di tutti gli animali terrestri!",
    "Il Triceratopo aveva più di 400 denti per masticare le piante!",
    "Scienziati hanno trovato Triceratopi con segni di morsi di T-Rex!",
    "Il Triceratopo camminava a quattro zampe, come un rinoceronte!",
    "Il Triceratopo è vissuto circa 68 milioni di anni fa!",
    "Le corna del Triceratopo potevano essere lunghe 1 metro!",
    "Il Triceratopo è uno dei dinosauri più famosi al mondo!",
    "Il Triceratopo è stato scoperto nel 1887!",
    "I cuccioli di Triceratopo avevano corna piccolissime!",
    "Il Triceratopo probabilmente usava le corna per lottare con i rivali!",
  ],
  stegosaurus: [
    "Lo Stegosauro aveva placche sul dorso che regolavano la temperatura!",
    "La coda dello Stegosauro aveva spine per difendersi!",
    "Il cervello dello Stegosauro era grande come una noce!",
    "Lo Stegosauro era lungo fino a 9 metri!",
    "Lo Stegosauro è vissuto 155 milioni di anni fa!",
    "Stegosauro significa lucertola con tetto!",
    "Lo Stegosauro era erbivoro e mangiava felci!",
    "Le placche dello Stegosauro diventavano rosse quando era arrabbiato!",
    "Lo Stegosauro poteva pesare fino a 5 tonnellate!",
    "Lo Stegosauro aveva 17 placche sul dorso!",
    "Le spine della coda erano lunghe fino a 60 centimetri!",
    "Lo Stegosauro camminava lentamente a quattro zampe!",
    "Lo Stegosauro è stato scoperto nel 1877 negli Stati Uniti!",
    "Le zampe posteriori dello Stegosauro erano più grandi di quelle anteriori!",
    "Lo Stegosauro è vissuto molto prima del T-Rex!",
    "Lo Stegosauro è il dinosauro ufficiale dello stato del Colorado!",
    "Le placche dello Stegosauro non servivano come armatura!",
    "Lo Stegosauro aveva guance per conservare il cibo!",
    "I cuccioli di Stegosauro nascevano già con piccole placche!",
    "Lo Stegosauro è uno dei dinosauri più facili da riconoscere!",
  ],
  brachiosaurus: [
    "Il Brachiosauro era alto quanto un palazzo di 4 piani!",
    "Il Brachiosauro mangiava fino a 400 chili di piante al giorno!",
    "Il collo del Brachiosauro era lungo 9 metri!",
    "Il Brachiosauro poteva pesare fino a 80 tonnellate!",
    "Il Brachiosauro aveva le narici sulla cima della testa!",
    "Brachiosauro significa lucertola con braccia!",
    "Il Brachiosauro è vissuto 154 milioni di anni fa!",
    "Le zampe anteriori del Brachiosauro erano più grandi di quelle posteriori!",
    "Il Brachiosauro non masticava, ingoiava le piante intere!",
    "Il Brachiosauro era lungo fino a 26 metri!",
    "Il cuore del Brachiosauro era enorme per pompare il sangue fino alla testa!",
    "Il Brachiosauro viveva nel Giurassico!",
    "Il Brachiosauro appare nel film Jurassic Park!",
    "Il Brachiosauro probabilmente viveva in gruppi!",
    "I cuccioli di Brachiosauro crescevano molto velocemente!",
    "Il Brachiosauro era uno dei più grandi animali mai esistiti!",
    "Il Brachiosauro non poteva correre a causa del peso!",
    "Il Brachiosauro è stato scoperto nel 1900!",
    "Il Brachiosauro mangiava le foglie in cima agli alberi più alti!",
    "I denti del Brachiosauro erano come cucchiai per strappare le foglie!",
  ],
  velociraptor: [
    "Il Velociraptor era grande quanto un grosso tacchino!",
    "Il Velociraptor aveva piume su tutto il corpo!",
    "Il Velociraptor aveva un enorme artiglio ricurvo su ogni piede!",
    "Velociraptor significa ladro veloce!",
    "Il Velociraptor è vissuto 75 milioni di anni fa in Mongolia!",
    "Il Velociraptor era molto intelligente per un dinosauro!",
    "Il Velociraptor cacciava in gruppo per catturare prede più grandi!",
    "Il Velociraptor poteva correre a 60 chilometri all'ora!",
    "L'artiglio del Velociraptor era lungo 6 centimetri!",
    "Il Velociraptor era carnivoro e cacciava altri dinosauri!",
    "Il Velociraptor nel film Jurassic Park è molto più grande di quello reale!",
    "Il Velociraptor era lungo solo 2 metri!",
    "Il Velociraptor pesava solo 15 chili!",
    "Il Velociraptor aveva più di 80 denti affilati!",
    "Scienziati hanno trovato un Velociraptor che combatteva con un Protoceratopo!",
    "Il Velociraptor usava la coda per equilibrarsi mentre correva!",
    "Il Velociraptor aveva una vista eccellente per cacciare!",
    "Il Velociraptor viveva nel deserto del Gobi!",
    "Le piume del Velociraptor non servivano per volare!",
    "Il Velociraptor è uno dei dinosauri più studiati al mondo!",
  ],
  pteranodon: [
    "Lo Pteranodonte non era un dinosauro, era un rettile volante!",
    "L'apertura alare dello Pteranodonte arrivava a 7 metri!",
    "Lo Pteranodonte non aveva denti!",
    "Lo Pteranodonte mangiava pesci che pescava in mare!",
    "La cresta dello Pteranodonte aiutava a stabilizzare il volo!",
    "Pteranodonte significa ala senza denti!",
    "Lo Pteranodonte è vissuto 86 milioni di anni fa!",
    "Lo Pteranodonte pesava solo 25 chili nonostante le dimensioni!",
    "Lo Pteranodonte aveva ossa cave, come gli uccelli di oggi!",
    "Lo Pteranodonte planava per lunghe distanze sull'oceano!",
    "I maschi avevano creste più grandi delle femmine!",
    "Lo Pteranodonte viveva in Nord America!",
    "Lo Pteranodonte camminava a quattro zampe a terra!",
    "Lo Pteranodonte era uno dei più grandi animali volanti!",
    "Le ali dello Pteranodonte erano fatte di pelle tesa!",
    "Lo Pteranodonte poteva tuffarsi in acqua per prendere i pesci!",
    "Lo Pteranodonte si prendeva cura dei piccoli nel nido!",
    "I fossili dello Pteranodonte sono stati trovati in Kansas!",
    "Lo Pteranodonte è stato scoperto nel 1876!",
    "Lo Pteranodonte volava a 50 chilometri all'ora!",
  ],
  ankylosaurus: [
    "L'Anchilosauro era un carro armato vivente!",
    "La coda dell'Anchilosauro aveva un'enorme mazza ossea!",
    "L'Anchilosauro aveva un'armatura fatta di placche ossee!",
    "L'Anchilosauro poteva spezzare le zampe del T-Rex con la coda!",
    "Anchilosauro significa lucertola rigida!",
    "L'Anchilosauro è vissuto 68 milioni di anni fa!",
    "L'Anchilosauro era lungo fino a 10 metri!",
    "L'Anchilosauro era erbivoro e mangiava piante basse!",
    "L'Anchilosauro poteva pesare fino a 6 tonnellate!",
    "Perfino le palpebre dell'Anchilosauro avevano l'armatura!",
    "L'Anchilosauro aveva un cervello piccolo!",
    "La mazza della coda poteva pesare 30 chili!",
    "L'Anchilosauro camminava lentamente a quattro zampe!",
    "L'Anchilosauro viveva da solo, diversamente da altri erbivori!",
    "L'Anchilosauro è stato scoperto nel 1908!",
    "L'Anchilosauro non aveva bisogno di fuggire perché era molto protetto!",
    "La pancia dell'Anchilosauro era la parte più vulnerabile!",
    "L'Anchilosauro viveva in Nord America!",
    "I denti dell'Anchilosauro erano piccoli e a forma di foglia!",
    "L'Anchilosauro è uno dei dinosauri più corazzati mai esistiti!",
  ],
  spinosaurus: [
    "Lo Spinosauro era più grande del T-Rex!",
    "Lo Spinosauro aveva un'enorme vela sul dorso!",
    "Lo Spinosauro è stato il primo dinosauro nuotatore!",
    "Lo Spinosauro mangiava pesci giganti!",
    "Il muso dello Spinosauro assomigliava a quello di un coccodrillo!",
    "Spinosauro significa lucertola con spine!",
    "Lo Spinosauro è vissuto 95 milioni di anni fa in Africa!",
    "Lo Spinosauro era lungo fino a 15 metri!",
    "La vela sul dorso poteva essere alta 1,8 metri!",
    "Lo Spinosauro aveva enormi artigli sulle mani!",
    "Lo Spinosauro poteva respirare sott'acqua per poco tempo!",
    "Lo Spinosauro aveva sensori sul muso per rilevare prede nell'acqua!",
    "Lo Spinosauro poteva pesare fino a 7 tonnellate!",
    "Lo Spinosauro camminava sia su due che su quattro zampe!",
    "Lo Spinosauro è stato scoperto nel 1912 in Egitto!",
    "Il primo fossile dello Spinosauro è stato distrutto nella Seconda Guerra Mondiale!",
    "Lo Spinosauro aveva denti conici, diversi dal T-Rex!",
    "La coda dello Spinosauro era piatta come quella di un pesce!",
    "Lo Spinosauro è il più grande carnivoro terrestre mai esistito!",
    "Lo Spinosauro appare nel film Jurassic Park 3!",
  ],
  parasaurolophus: [
    "Il Parasaurolofo aveva una cresta cava che faceva suoni come una tromba!",
    "Il Parasaurolofo usava la cresta per comunicare con il gruppo!",
    "Il Parasaurolofo era erbivoro e mangiava foglie e frutti!",
    "Il Parasaurolofo poteva camminare su due o quattro zampe!",
    "Parasaurolofo significa lucertola con cresta vicina!",
    "Il Parasaurolofo è vissuto 76 milioni di anni fa!",
    "La cresta del Parasaurolofo poteva essere lunga 1 metro!",
    "Il Parasaurolofo era lungo fino a 10 metri!",
    "Il Parasaurolofo viveva in grandi branchi!",
    "Il Parasaurolofo poteva pesare fino a 5 tonnellate!",
    "Il suono della cresta del Parasaurolofo era grave come una tromba!",
    "Il Parasaurolofo aveva centinaia di denti per masticare!",
    "Il Parasaurolofo è stato scoperto nel 1922 in Canada!",
    "I cuccioli avevano creste più piccole che crescevano col tempo!",
    "Il Parasaurolofo aveva un buon olfatto per fiutare i predatori!",
    "Il Parasaurolofo è uno dei dinosauri più musicali!",
    "La cresta poteva essere colorata per attirare i partner!",
    "Il Parasaurolofo viveva in Nord America!",
    "Il Parasaurolofo correva fino a 40 chilometri all'ora!",
    "Il Parasaurolofo è conosciuto come il dinosauro tromba!",
  ],
  diplodocus: [
    "Il Diplodoco era uno dei dinosauri più lunghi, con 27 metri!",
    "La coda del Diplodoco poteva schioccare come una frusta!",
    "Il Diplodoco aveva un collo di 6 metri!",
    "Il Diplodoco era erbivoro e mangiava foglie tutto il giorno!",
    "Diplodoco significa doppia trave!",
    "Il Diplodoco è vissuto 154 milioni di anni fa!",
    "Il Diplodoco poteva pesare fino a 16 tonnellate!",
    "Il Diplodoco aveva denti solo nella parte anteriore della bocca, come un pettine!",
    "Il Diplodoco ingoiava pietre per aiutare la digestione!",
    "Il Diplodoco viveva in grandi branchi!",
    "Il Diplodoco fu uno dei primi dinosauri giganti scoperti!",
    "Il Diplodoco non masticava, strappava le foglie e ingoiava!",
    "Il Diplodoco aveva 15 vertebre nel collo!",
    "Il Diplodoco è stato scoperto nel 1878!",
    "La coda del Diplodoco aveva più di 70 ossa!",
    "Il Diplodoco poteva alzarsi sulle zampe posteriori per raggiungere gli alberi!",
    "Il cuore del Diplodoco era gigantesco per pompare il sangue in tutto il corpo!",
    "Il Diplodoco viveva in Nord America!",
    "I cuccioli di Diplodoco crescevano molto velocemente!",
    "Il Diplodoco è uno dei dinosauri più esposti nei musei!",
  ],
  pachycephalosaurus: [
    "Il Pachicefalosauro aveva un cranio spesso 25 centimetri!",
    "Il Pachicefalosauro usava la testa dura per dare testate!",
    "Pachicefalosauro significa lucertola dalla testa spessa!",
    "Il Pachicefalosauro è vissuto 70 milioni di anni fa!",
    "Il Pachicefalosauro era lungo fino a 5 metri!",
    "Il Pachicefalosauro era bipede e camminava su due zampe!",
    "Il Pachicefalosauro era erbivoro e onnivoro!",
    "La cupola della testa era decorata con spine e noduli!",
    "Il Pachicefalosauro viveva in Nord America!",
    "Il Pachicefalosauro pesava circa 450 chili!",
    "I maschi si davano testate per conquistare le femmine!",
    "Il Pachicefalosauro è stato scoperto nel 1931!",
    "Il cranio del Pachicefalosauro è uno dei più spessi di tutti gli animali!",
    "Il Pachicefalosauro aveva denti piccoli e appuntiti!",
    "Il Pachicefalosauro è vissuto nella stessa epoca del T-Rex!",
    "Il Pachicefalosauro poteva correre veloce su due zampe!",
    "Gli occhi del Pachicefalosauro erano ai lati della testa!",
    "Il Pachicefalosauro è il dinosauro testa dura!",
    "Gli scienziati discutono se le testate non danneggiassero il cervello!",
    "La cupola cranica cresceva con l'età dell'animale!",
  ],
  iguanodon: [
    "L'Iguanodonte è stato il secondo dinosauro a essere nominato nella storia!",
    "L'Iguanodonte aveva uno sperone sul pollice per difendersi!",
    "Iguanodonte significa dente di iguana!",
    "L'Iguanodonte è vissuto 125 milioni di anni fa!",
    "L'Iguanodonte era lungo fino a 10 metri!",
    "L'Iguanodonte poteva camminare su due o quattro zampe!",
    "L'Iguanodonte era erbivoro e masticava come una mucca!",
    "L'Iguanodonte è stato scoperto nel 1825 in Inghilterra!",
    "L'Iguanodonte poteva pesare fino a 4 tonnellate!",
    "Lo sperone del pollice è stato scambiato per un corno sul naso!",
    "L'Iguanodonte viveva in grandi gruppi!",
    "L'Iguanodonte aveva centinaia di denti per triturare le piante!",
    "L'Iguanodonte viveva in Europa, Nord America e Asia!",
    "L'Iguanodonte è uno dei dinosauri più studiati!",
    "I denti dell'Iguanodonte si sostituivano per tutta la vita!",
    "L'Iguanodonte aveva una lingua lunga per tirare le foglie!",
    "L'Iguanodonte correva fino a 35 chilometri all'ora!",
    "L'Iguanodonte aveva mani molto flessibili!",
    "Più di 30 scheletri sono stati trovati insieme in una miniera in Belgio!",
    "L'Iguanodonte ha aiutato gli scienziati a capire come vivevano i dinosauri!",
  ],
  compsognathus: [
    "Il Compsognato era uno dei dinosauri più piccoli, grande come una gallina!",
    "Il Compsognato pesava solo 3 chili!",
    "Il Compsognato era un cacciatore veloce e agile!",
    "Compsognato significa mascella elegante!",
    "Il Compsognato è vissuto 150 milioni di anni fa!",
    "Il Compsognato mangiava insetti e lucertole!",
    "Il Compsognato fu uno dei primi dinosauri completi trovati!",
    "Il Compsognato era lungo solo 1 metro!",
    "Il Compsognato correva molto veloce su due zampe!",
    "Il Compsognato viveva in Europa, nell'odierna Germania e Francia!",
    "Il Compsognato è stato scoperto nel 1859!",
    "Gli scienziati hanno trovato una lucertola nello stomaco di un fossile!",
    "Il Compsognato aveva piume sottili sul corpo!",
    "Il Compsognato era un lontano parente del Velociraptor!",
    "Il Compsognato aveva grandi occhi per vedere bene!",
    "Il Compsognato è uno dei dinosauri più carini!",
    "Il Compsognato cacciava da solo, non in gruppo!",
    "Il Compsognato aveva tre dita per mano!",
    "Il Compsognato viveva nello stesso periodo dell'Archaeopteryx!",
    "Il Compsognato appare nel film Jurassic Park come piccolo dinosauro!",
  ],
  carnotaurus: [
    "Il Carnotauro aveva corna sopra gli occhi, come un toro!",
    "Il Carnotauro aveva braccia ancora più piccole del T-Rex!",
    "Carnotauro significa toro carnivoro!",
    "Il Carnotauro è vissuto 72 milioni di anni fa in Argentina!",
    "Il Carnotauro poteva correre a 56 chilometri all'ora!",
    "Il Carnotauro era lungo fino a 8 metri!",
    "Il Carnotauro aveva la pelle con squame e protuberanze!",
    "Il Carnotauro era uno dei predatori più veloci!",
    "Il Carnotauro pesava circa 1,5 tonnellate!",
    "Il Carnotauro è stato scoperto nel 1985!",
    "Il Carnotauro è uno dei pochi dinosauri con pelle fossilizzata!",
    "Le corna del Carnotauro servivano per le lotte tra maschi!",
    "Il Carnotauro aveva un muso corto e una mascella debole!",
    "Il Carnotauro compensava la mascella debole con la velocità!",
    "Il Carnotauro viveva in Sud America!",
    "Il Carnotauro aveva gli occhi rivolti in avanti per la visione profonda!",
    "Le braccia del Carnotauro erano praticamente inutili!",
    "Il Carnotauro probabilmente cacciava dinosauri erbivori!",
    "Il Carnotauro appare nel film Jurassic World!",
    "Il Carnotauro è il dinosauro con corna più famoso tra i carnivori!",
  ],
  dilophosaurus: [
    "Il Dilofosauro aveva due belle creste sulla testa!",
    "Il Dilofosauro NON sputava veleno, è un'invenzione del film!",
    "Dilofosauro significa lucertola con due creste!",
    "Il Dilofosauro è vissuto 193 milioni di anni fa!",
    "Il Dilofosauro era lungo fino a 7 metri!",
    "Il Dilofosauro era uno dei più grandi carnivori del suo tempo!",
    "Il Dilofosauro pesava circa 400 chili!",
    "Le creste servivano per attirare i partner!",
    "Il Dilofosauro non aveva il collare che si vede nel film!",
    "Il Dilofosauro viveva nell'odierno Arizona!",
    "Il Dilofosauro è stato scoperto nel 1942!",
    "Il Dilofosauro era bipede e correva veloce!",
    "Il Dilofosauro aveva denti lunghi e sottili!",
    "Il Dilofosauro aveva mani con quattro dita!",
    "Il Dilofosauro è uno dei primi grandi carnivori della storia!",
    "Il Dilofosauro viveva all'inizio del Giurassico!",
    "Le creste del Dilofosauro erano molto fragili!",
    "Il Dilofosauro poteva essere alto 2 metri!",
    "Il Dilofosauro cacciava piccoli animali e pesci!",
    "Il Dilofosauro è diventato famoso grazie al film Jurassic Park!",
  ],
  apatosaurus: [
    "L'Apatosauro era uno dei dinosauri più grandi!",
    "L'Apatosauro poteva pesare fino a 35 tonnellate!",
    "Apatosauro significa lucertola ingannevole!",
    "L'Apatosauro è vissuto 152 milioni di anni fa!",
    "L'Apatosauro era lungo fino a 23 metri!",
    "L'Apatosauro era erbivoro e mangiava piante!",
    "L'Apatosauro si chiamava prima Brontosauro!",
    "L'Apatosauro aveva un collo e una coda lunghissimi!",
    "L'Apatosauro ingoiava pietre per aiutare la digestione!",
    "L'Apatosauro viveva in grandi branchi!",
    "L'Apatosauro poteva alzarsi sulle zampe posteriori!",
    "La coda dell'Apatosauro schioccava come una frusta!",
    "L'Apatosauro è stato scoperto nel 1877!",
    "L'Apatosauro viveva in Nord America!",
    "I cuccioli di Apatosauro crescevano molto velocemente!",
    "L'Apatosauro aveva un cervello piccolo rispetto al corpo!",
    "L'Apatosauro non masticava il cibo!",
    "L'Apatosauro poteva vivere fino a 100 anni!",
    "L'Apatosauro era uno dei più grandi erbivori!",
    "L'Apatosauro è uno dei dinosauri più conosciuti al mondo!",
  ],
  plesiosaurus: [
    "Il Plesiosauro non era un dinosauro, era un rettile marino!",
    "Il Plesiosauro aveva un collo lunghissimo e un corpo piccolo!",
    "Il Plesiosauro nuotava con quattro pinne come remi!",
    "Il Plesiosauro è vissuto 200 milioni di anni fa!",
    "Il Plesiosauro mangiava pesci e calamari!",
    "Plesiosauro significa vicino alla lucertola!",
    "Il Plesiosauro era lungo fino a 15 metri!",
    "Il Plesiosauro ha ispirato la leggenda del mostro di Loch Ness!",
    "Il Plesiosauro doveva risalire in superficie per respirare!",
    "Il Plesiosauro è stato uno dei primi rettili marini scoperti!",
    "Il collo del Plesiosauro aveva più di 40 vertebre!",
    "Il Plesiosauro viveva nei mari di tutto il mondo!",
    "Il Plesiosauro è stato scoperto nel 1823 in Inghilterra!",
    "Il Plesiosauro ingoiava pietre per controllare il galleggiamento!",
    "Il Plesiosauro nuotava lentamente ma con eleganza!",
    "Il Plesiosauro catturava i pesci con il suo lungo collo!",
    "Il Plesiosauro aveva denti appuntiti per afferrare prede scivolose!",
    "I cuccioli di Plesiosauro nascevano vivi, non dalle uova!",
    "Il Plesiosauro viveva in gruppi nell'oceano!",
    "Il Plesiosauro si è estinto con i dinosauri 66 milioni di anni fa!",
  ],
  mosasaurus: [
    "Il Mosasauro era uno dei più grandi predatori marini!",
    "Il Mosasauro poteva essere lungo fino a 17 metri!",
    "Il Mosasauro non era un dinosauro, era una lucertola marina gigante!",
    "Il Mosasauro è vissuto 70 milioni di anni fa!",
    "Il Mosasauro aveva due file di denti sul palato!",
    "Mosasauro significa lucertola della Mosa!",
    "Il Mosasauro mangiava pesci, tartarughe e persino squali!",
    "Il Mosasauro nuotava ondulando il corpo come un serpente!",
    "Il Mosasauro doveva risalire in superficie per respirare!",
    "Il Mosasauro era il predatore supremo dei mari del Cretaceo!",
    "Il Mosasauro poteva pesare fino a 15 tonnellate!",
    "Il Mosasauro aveva un corpo idrodinamico per nuotare veloce!",
    "Il primo fossile di Mosasauro è stato trovato nei Paesi Bassi nel 1764!",
    "Il Mosasauro è parente dei varani di oggi!",
    "Il Mosasauro aveva gli occhi ai lati della testa!",
    "Il Mosasauro poteva aprire la bocca molto ampiamente!",
    "Il Mosasauro partoriva piccoli vivi!",
    "Il Mosasauro appare nel film Jurassic World!",
    "Il Mosasauro aveva una coda piatta per nuotare!",
    "Il Mosasauro si è estinto nell'estinzione di massa 66 milioni di anni fa!",
  ],
  dimetrodon: [
    "Il Dimetrodonte non era un dinosauro ma un rettile pre-dinosauro!",
    "Il Dimetrodonte aveva una grande vela sul dorso!",
    "La vela del Dimetrodonte lo aiutava a regolare la temperatura!",
    "Il Dimetrodonte è vissuto 280 milioni di anni fa!",
    "Il Dimetrodonte è vissuto prima dei dinosauri!",
    "Dimetrodonte significa due misure di denti!",
    "Il Dimetrodonte aveva denti di dimensioni diverse!",
    "Il Dimetrodonte era carnivoro e un predatore temibile!",
    "Il Dimetrodonte era lungo fino a 4 metri!",
    "Il Dimetrodonte è più parente dei mammiferi che dei rettili!",
    "La vela del Dimetrodonte era fatta di pelle tesa su spine ossee!",
    "Il Dimetrodonte viveva nell'odierno Nord America!",
    "Il Dimetrodonte si scaldava girando la vela verso il sole!",
    "Il Dimetrodonte poteva pesare fino a 250 chili!",
    "Il Dimetrodonte è stato scoperto nel 1878!",
    "Il Dimetrodonte viene spesso confuso con un dinosauro!",
    "Il Dimetrodonte viveva in zone paludose!",
    "Il Dimetrodonte aveva zampe corte e allargate ai lati!",
    "Il Dimetrodonte è uno dei più famosi animali preistorici!",
    "Il Dimetrodonte si è estinto 40 milioni di anni prima dei dinosauri!",
  ],
  archaeopteryx: [
    "L'Archaeopteryx è considerato il primo uccello della storia!",
    "L'Archaeopteryx aveva piume come un uccello e denti come un dinosauro!",
    "L'Archaeopteryx è vissuto 150 milioni di anni fa!",
    "L'Archaeopteryx era grande come un corvo!",
    "Archaeopteryx significa ala antica!",
    "L'Archaeopteryx aveva artigli sulle ali!",
    "L'Archaeopteryx probabilmente non volava molto bene!",
    "L'Archaeopteryx viveva nell'odierna Germania!",
    "L'Archaeopteryx aveva una lunga coda ossea con piume!",
    "L'Archaeopteryx è stato scoperto nel 1861!",
    "L'Archaeopteryx collega i dinosauri agli uccelli!",
    "L'Archaeopteryx pesava meno di un chilo!",
    "L'Archaeopteryx aveva denti piccoli e appuntiti!",
    "L'Archaeopteryx mangiava insetti e piccole lucertole!",
    "Le piume dell'Archaeopteryx erano simili a quelle degli uccelli moderni!",
    "L'Archaeopteryx probabilmente planava più che volare!",
    "L'Archaeopteryx viveva in isole tropicali!",
    "Sono stati trovati solo 12 fossili di Archaeopteryx!",
    "L'Archaeopteryx non volava bene come gli uccelli moderni!",
    "L'Archaeopteryx è il fossile di transizione più famoso al mondo!",
  ],
};
