import type { DinoId } from "./dinosaurs";

export const dinoFunFacts: Record<DinoId, string[]> = {
  trex: [
    "O T-Rex tinha dentes do tamanho de bananas!",
    "O T-Rex podia sentir vibrações no chão com os pés!",
    "Os bracinhos do T-Rex eram super fortes, apesar de pequenos!",
    "O T-Rex viveu há 68 milhões de anos!",
    "O T-Rex podia comer 230 quilos de carne de uma vez!",
    "O nome T-Rex significa Rei dos Lagartos Tiranos!",
    "O T-Rex podia correr a 40 quilômetros por hora!",
    "O T-Rex tinha a mordida mais forte de todos os animais terrestres!",
    "O cérebro do T-Rex era maior que o de muitos dinossauros!",
    "O T-Rex tinha visão muito boa, melhor que a de uma águia!",
    "Cientistas já encontraram mais de 50 esqueletos de T-Rex!",
    "O T-Rex media até 12 metros de comprimento!",
    "Os filhotes de T-Rex nasciam cobertos de penas!",
    "O T-Rex viveu no que hoje são Estados Unidos e Canadá!",
    "A cauda do T-Rex ajudava ele a manter o equilíbrio ao correr!",
    "O T-Rex é parente das galinhas de hoje!",
    "O T-Rex podia ouvir sons muito graves, como terremotos!",
    "O crânio do T-Rex podia ter até 1,5 metro de comprimento!",
    "O T-Rex trocava de dentes a vida toda, como os tubarões!",
    "O T-Rex foi um dos últimos dinossauros antes da extinção!",
  ],
  triceratops: [
    "O Tricerátops tinha três chifres no rosto!",
    "O escudo do Tricerátops protegia seu pescoço!",
    "O Tricerátops era herbívoro e comia plantas o dia todo!",
    "O Tricerátops podia pesar até 12 toneladas!",
    "O nome Tricerátops significa rosto com três chifres!",
    "O Tricerátops vivia em manadas para se proteger!",
    "O bico do Tricerátops era parecido com o de um papagaio!",
    "O Tricerátops viveu na mesma época do T-Rex!",
    "O escudo do Tricerátops mudava de cor para atrair parceiros!",
    "O Tricerátops media até 9 metros de comprimento!",
    "O crânio do Tricerátops é um dos maiores de qualquer animal terrestre!",
    "O Tricerátops tinha mais de 400 dentes para mastigar plantas!",
    "Cientistas já encontraram Tricerátops com marcas de mordida de T-Rex!",
    "O Tricerátops andava em quatro patas, como um rinoceronte!",
    "O Tricerátops viveu há cerca de 68 milhões de anos!",
    "Os chifres do Tricerátops podiam ter 1 metro de comprimento!",
    "O Tricerátops é um dos dinossauros mais famosos do mundo!",
    "O Tricerátops foi descoberto em 1887!",
    "Os filhotes de Tricerátops tinham chifres pequeninos!",
    "O Tricerátops provavelmente usava os chifres para lutar com rivais!",
  ],
  stegosaurus: [
    "O Estegossauro tinha placas nas costas que regulavam sua temperatura!",
    "A cauda do Estegossauro tinha espinhos para se defender!",
    "O cérebro do Estegossauro era do tamanho de uma noz!",
    "O Estegossauro media até 9 metros de comprimento!",
    "O Estegossauro viveu há 155 milhões de anos!",
    "O nome Estegossauro significa lagarto com telhado!",
    "O Estegossauro era herbívoro e comia samambaias!",
    "As placas do Estegossauro ficavam vermelhas quando ele estava bravo!",
    "O Estegossauro podia pesar até 5 toneladas!",
    "O Estegossauro tinha 17 placas nas costas!",
    "Os espinhos da cauda tinham até 60 centímetros!",
    "O Estegossauro andava devagar em quatro patas!",
    "O Estegossauro foi descoberto em 1877 nos Estados Unidos!",
    "As patas traseiras do Estegossauro eram maiores que as dianteiras!",
    "O Estegossauro viveu antes do T-Rex, há muito mais tempo!",
    "O Estegossauro é o dinossauro oficial do estado do Colorado!",
    "As placas do Estegossauro não serviam como armadura!",
    "O Estegossauro tinha bochechas para guardar comida!",
    "Os filhotes de Estegossauro já nasciam com pequenas placas!",
    "O Estegossauro é um dos dinossauros mais fáceis de reconhecer!",
  ],
  brachiosaurus: [
    "O Braquiossauro era tão alto quanto um prédio de 4 andares!",
    "O Braquiossauro comia até 400 quilos de plantas por dia!",
    "O pescoço do Braquiossauro tinha 9 metros de comprimento!",
    "O Braquiossauro podia pesar até 80 toneladas!",
    "O Braquiossauro tinha narinas no topo da cabeça!",
    "O nome Braquiossauro significa lagarto com braços!",
    "O Braquiossauro viveu há 154 milhões de anos!",
    "As patas dianteiras do Braquiossauro eram maiores que as traseiras!",
    "O Braquiossauro não mastigava, engolia as plantas inteiras!",
    "O Braquiossauro media até 26 metros de comprimento!",
    "O coração do Braquiossauro era enorme para bombear sangue até a cabeça!",
    "O Braquiossauro viveu no período Jurássico!",
    "O Braquiossauro aparece no filme Jurassic Park!",
    "O Braquiossauro provavelmente vivia em grupos!",
    "Os filhotes de Braquiossauro cresciam muito rápido!",
    "O Braquiossauro era um dos maiores animais que já existiu!",
    "O Braquiossauro não conseguia correr por causa do peso!",
    "O Braquiossauro foi descoberto em 1900!",
    "O Braquiossauro comia folhas no topo das árvores mais altas!",
    "Os dentes do Braquiossauro eram como colheres para arrancar folhas!",
  ],
  velociraptor: [
    "O Velociraptor era do tamanho de um peru grande!",
    "O Velociraptor tinha penas por todo o corpo!",
    "O Velociraptor tinha uma garra curva enorme em cada pé!",
    "O nome Velociraptor significa ladrão veloz!",
    "O Velociraptor viveu há 75 milhões de anos na Mongólia!",
    "O Velociraptor era muito inteligente para um dinossauro!",
    "O Velociraptor caçava em grupo para pegar presas maiores!",
    "O Velociraptor podia correr a 60 quilômetros por hora!",
    "A garra do Velociraptor tinha 6 centímetros de comprimento!",
    "O Velociraptor era carnívoro e caçava outros dinossauros!",
    "O Velociraptor no filme Jurassic Park é muito maior que o real!",
    "O Velociraptor media apenas 2 metros de comprimento!",
    "O Velociraptor pesava apenas 15 quilos!",
    "O Velociraptor tinha mais de 80 dentes afiados!",
    "Cientistas encontraram fósseis de Velociraptor lutando com Protoceratops!",
    "O Velociraptor usava a cauda para se equilibrar ao correr!",
    "O Velociraptor tinha visão excelente para caçar!",
    "O Velociraptor viveu no deserto de Gobi!",
    "As penas do Velociraptor não serviam para voar!",
    "O Velociraptor é um dos dinossauros mais estudados do mundo!",
  ],
  pteranodon: [
    "O Pteranodonte não era um dinossauro, era um réptil voador!",
    "A envergadura do Pteranodonte chegava a 7 metros!",
    "O Pteranodonte não tinha dentes!",
    "O Pteranodonte comia peixes que pescava no mar!",
    "A crista do Pteranodonte ajudava a estabilizar o voo!",
    "O nome Pteranodonte significa asa sem dentes!",
    "O Pteranodonte viveu há 86 milhões de anos!",
    "O Pteranodonte pesava apenas 25 quilos apesar do tamanho!",
    "O Pteranodonte tinha ossos ocos, como as aves de hoje!",
    "O Pteranodonte planava longas distâncias sobre o oceano!",
    "Os machos tinham cristas maiores que as fêmeas!",
    "O Pteranodonte viveu na América do Norte!",
    "O Pteranodonte andava de quatro no chão!",
    "O Pteranodonte foi um dos maiores animais voadores!",
    "As asas do Pteranodonte eram feitas de pele esticada!",
    "O Pteranodonte podia mergulhar na água para pegar peixes!",
    "O Pteranodonte cuidava dos filhotes no ninho!",
    "Os fósseis do Pteranodonte foram encontrados no Kansas!",
    "O Pteranodonte foi descoberto em 1876!",
    "O Pteranodonte voava a até 50 quilômetros por hora!",
  ],
  ankylosaurus: [
    "O Anquilossauro era um tanque de guerra vivo!",
    "A cauda do Anquilossauro tinha uma bola óssea enorme!",
    "O Anquilossauro tinha armadura feita de placas de osso!",
    "O Anquilossauro podia quebrar as pernas do T-Rex com a cauda!",
    "O nome Anquilossauro significa lagarto rígido!",
    "O Anquilossauro viveu há 68 milhões de anos!",
    "O Anquilossauro media até 10 metros de comprimento!",
    "O Anquilossauro era herbívoro e comia plantas baixas!",
    "O Anquilossauro podia pesar até 6 toneladas!",
    "Até as pálpebras do Anquilossauro tinham armadura!",
    "O Anquilossauro tinha um cérebro pequeno!",
    "A bola da cauda podia pesar 30 quilos!",
    "O Anquilossauro andava devagar em quatro patas!",
    "O Anquilossauro vivia sozinho, diferente de outros herbívoros!",
    "O Anquilossauro foi descoberto em 1908!",
    "O Anquilossauro não precisava fugir porque era muito protegido!",
    "A barriga do Anquilossauro era a parte mais vulnerável!",
    "O Anquilossauro viveu no que hoje é a América do Norte!",
    "Os dentes do Anquilossauro eram pequenos em forma de folha!",
    "O Anquilossauro é um dos dinossauros mais blindados que existiu!",
  ],
  spinosaurus: [
    "O Espinossauro era maior que o T-Rex!",
    "O Espinossauro tinha uma vela enorme nas costas!",
    "O Espinossauro era o primeiro dinossauro que nadava!",
    "O Espinossauro comia peixes gigantes!",
    "O focinho do Espinossauro era parecido com o de um crocodilo!",
    "O nome Espinossauro significa lagarto com espinhos!",
    "O Espinossauro viveu há 95 milhões de anos na África!",
    "O Espinossauro media até 15 metros de comprimento!",
    "A vela nas costas podia ter 1,8 metro de altura!",
    "O Espinossauro tinha garras enormes nas mãos!",
    "O Espinossauro podia respirar debaixo d'água por pouco tempo!",
    "O Espinossauro tinha sensores no focinho para detectar presas na água!",
    "O Espinossauro podia pesar até 7 toneladas!",
    "O Espinossauro andava tanto em duas quanto em quatro patas!",
    "O Espinossauro foi descoberto em 1912 no Egito!",
    "O primeiro fóssil do Espinossauro foi destruído na Segunda Guerra!",
    "O Espinossauro tinha dentes cônicos, diferentes do T-Rex!",
    "A cauda do Espinossauro era achatada como a de um peixe!",
    "O Espinossauro é o maior carnívoro terrestre que já existiu!",
    "O Espinossauro aparece no filme Jurassic Park 3!",
  ],
  parasaurolophus: [
    "O Parassaurolofo tinha uma crista oca que fazia sons como uma trombeta!",
    "O Parassaurolofo usava a crista para se comunicar com o grupo!",
    "O Parassaurolofo era herbívoro e comia folhas e frutas!",
    "O Parassaurolofo podia andar em duas ou quatro patas!",
    "O nome Parassaurolofo significa lagarto com crista próxima!",
    "O Parassaurolofo viveu há 76 milhões de anos!",
    "A crista do Parassaurolofo podia ter 1 metro de comprimento!",
    "O Parassaurolofo media até 10 metros de comprimento!",
    "O Parassaurolofo vivia em grandes manadas!",
    "O Parassaurolofo podia pesar até 5 toneladas!",
    "O som da crista do Parassaurolofo era grave como um trompete!",
    "O Parassaurolofo tinha centenas de dentes para mastigar!",
    "O Parassaurolofo foi descoberto em 1922 no Canadá!",
    "Os filhotes tinham cristas menores que cresciam com o tempo!",
    "O Parassaurolofo tinha bom olfato para sentir predadores!",
    "O Parassaurolofo é um dos dinossauros mais musicais!",
    "A crista pode ter sido colorida para atrair parceiros!",
    "O Parassaurolofo viveu na América do Norte!",
    "O Parassaurolofo corria a até 40 quilômetros por hora!",
    "O Parassaurolofo é conhecido como o dinossauro trombeta!",
  ],
  diplodocus: [
    "O Diplódoco era um dos dinossauros mais compridos, com 27 metros!",
    "A cauda do Diplódoco podia estalar como um chicote!",
    "O Diplódoco tinha um pescoço de 6 metros!",
    "O Diplódoco era herbívoro e comia folhas o dia todo!",
    "O nome Diplódoco significa viga dupla!",
    "O Diplódoco viveu há 154 milhões de anos!",
    "O Diplódoco podia pesar até 16 toneladas!",
    "O Diplódoco tinha dentes só na frente da boca, como um pente!",
    "O Diplódoco engolia pedras para ajudar a digerir a comida!",
    "O Diplódoco vivia em grandes manadas!",
    "O Diplódoco foi um dos primeiros dinossauros gigantes descobertos!",
    "O Diplódoco não mastigava, arrancava as folhas e engolia!",
    "O Diplódoco tinha 15 vértebras no pescoço!",
    "O Diplódoco foi descoberto em 1878!",
    "A cauda do Diplódoco tinha mais de 70 ossos!",
    "O Diplódoco podia se levantar nas patas traseiras para alcançar árvores!",
    "O coração do Diplódoco era gigante para bombear sangue pelo corpo todo!",
    "O Diplódoco viveu no que hoje é a América do Norte!",
    "Os filhotes de Diplódoco cresciam muito rápido!",
    "O Diplódoco é um dos dinossauros mais exibidos em museus!",
  ],
  pachycephalosaurus: [
    "O Paquicefalossauro tinha um crânio de 25 centímetros de espessura!",
    "O Paquicefalossauro usava a cabeça dura para dar cabeçadas!",
    "O nome Paquicefalossauro significa lagarto de cabeça grossa!",
    "O Paquicefalossauro viveu há 70 milhões de anos!",
    "O Paquicefalossauro media até 5 metros de comprimento!",
    "O Paquicefalossauro era bípede e andava em duas patas!",
    "O Paquicefalossauro era herbívoro e onívoro!",
    "O domo da cabeça era decorado com espinhos e nódulos!",
    "O Paquicefalossauro vivia na América do Norte!",
    "O Paquicefalossauro pesava cerca de 450 quilos!",
    "Machos davam cabeçadas para disputar fêmeas!",
    "O Paquicefalossauro foi descoberto em 1931!",
    "O crânio do Paquicefalossauro é um dos mais grossos de todos os animais!",
    "O Paquicefalossauro tinha dentes pequenos e pontiagudos!",
    "O Paquicefalossauro viveu na mesma época do T-Rex!",
    "O Paquicefalossauro podia correr rápido em duas patas!",
    "Os olhos do Paquicefalossauro ficavam na lateral da cabeça!",
    "O Paquicefalossauro é o dinossauro cabeça-dura!",
    "Cientistas debatem se as cabeçadas não machucariam o cérebro!",
    "O domo craniano crescia com a idade do animal!",
  ],
  iguanodon: [
    "O Iguanodonte foi o segundo dinossauro a ser nomeado na história!",
    "O Iguanodonte tinha um espigão no polegar para se defender!",
    "O nome Iguanodonte significa dente de iguana!",
    "O Iguanodonte viveu há 125 milhões de anos!",
    "O Iguanodonte media até 10 metros de comprimento!",
    "O Iguanodonte podia andar em duas ou quatro patas!",
    "O Iguanodonte era herbívoro e mastigava como uma vaca!",
    "O Iguanodonte foi descoberto em 1825 na Inglaterra!",
    "O Iguanodonte podia pesar até 4 toneladas!",
    "O espigão do polegar foi confundido com um chifre de nariz!",
    "O Iguanodonte vivia em grandes grupos!",
    "O Iguanodonte tinha centenas de dentes para moer plantas!",
    "O Iguanodonte viveu na Europa, América do Norte e Ásia!",
    "O Iguanodonte é um dos dinossauros mais bem estudados!",
    "Os dentes do Iguanodonte se substituíam a vida toda!",
    "O Iguanodonte tinha uma língua longa para puxar folhas!",
    "O Iguanodonte corria a até 35 quilômetros por hora!",
    "O Iguanodonte tinha mãos muito flexíveis!",
    "Foram encontrados mais de 30 esqueletos juntos numa mina na Bélgica!",
    "O Iguanodonte ajudou cientistas a entender como dinossauros viviam!",
  ],
  compsognathus: [
    "O Compsognato era um dos menores dinossauros, do tamanho de uma galinha!",
    "O Compsognato pesava apenas 3 quilos!",
    "O Compsognato era um caçador rápido e ágil!",
    "O nome Compsognato significa mandíbula elegante!",
    "O Compsognato viveu há 150 milhões de anos!",
    "O Compsognato comia insetos e lagartos!",
    "O Compsognato foi um dos primeiros dinossauros completos encontrados!",
    "O Compsognato media apenas 1 metro de comprimento!",
    "O Compsognato corria muito rápido em duas patas!",
    "O Compsognato viveu na Europa, onde hoje é a Alemanha e França!",
    "O Compsognato foi descoberto em 1859!",
    "Cientistas encontraram um lagarto dentro do estômago de um fóssil!",
    "O Compsognato tinha penas finas no corpo!",
    "O Compsognato era parente distante do Velociraptor!",
    "O Compsognato tinha olhos grandes para enxergar bem!",
    "O Compsognato é um dos dinossauros mais fofos!",
    "O Compsognato caçava sozinho, não em grupo!",
    "O Compsognato tinha três dedos em cada mão!",
    "O Compsognato viveu no mesmo período que o Archaeopteryx!",
    "O Compsognato aparece no filme Jurassic Park como dinossauro pequenino!",
  ],
  carnotaurus: [
    "O Carnotauro tinha chifres acima dos olhos, como um touro!",
    "O Carnotauro tinha os bracinhos ainda menores que o T-Rex!",
    "O nome Carnotauro significa touro carnívoro!",
    "O Carnotauro viveu há 72 milhões de anos na Argentina!",
    "O Carnotauro podia correr a 56 quilômetros por hora!",
    "O Carnotauro media até 8 metros de comprimento!",
    "O Carnotauro tinha pele com escamas e protuberâncias!",
    "O Carnotauro era um dos predadores mais rápidos!",
    "O Carnotauro pesava cerca de 1,5 tonelada!",
    "O Carnotauro foi descoberto em 1985!",
    "O Carnotauro é um dos poucos dinossauros com pele fossilizada!",
    "Os chifres do Carnotauro serviam para disputas entre machos!",
    "O Carnotauro tinha focinho curto e mandíbula fraca!",
    "O Carnotauro compensava a mandíbula fraca com velocidade!",
    "O Carnotauro viveu na América do Sul!",
    "O Carnotauro tinha olhos voltados para frente para ver profundidade!",
    "Os braços do Carnotauro eram praticamente inúteis!",
    "O Carnotauro provavelmente caçava dinossauros herbívoros!",
    "O Carnotauro aparece no filme Jurassic World!",
    "O Carnotauro é o dinossauro com chifres mais famoso entre os carnívoros!",
  ],
  dilophosaurus: [
    "O Dilofossauro tinha duas cristas bonitas na cabeça!",
    "O Dilofossauro NÃO cuspia veneno, isso foi invenção do filme!",
    "O nome Dilofossauro significa lagarto com duas cristas!",
    "O Dilofossauro viveu há 193 milhões de anos!",
    "O Dilofossauro media até 7 metros de comprimento!",
    "O Dilofossauro era um dos maiores carnívoros do seu tempo!",
    "O Dilofossauro pesava cerca de 400 quilos!",
    "As cristas serviam para atrair parceiros!",
    "O Dilofossauro não tinha aquela gola que aparece no filme!",
    "O Dilofossauro viveu no que hoje é o Arizona, nos Estados Unidos!",
    "O Dilofossauro foi descoberto em 1942!",
    "O Dilofossauro era bípede e corria rápido!",
    "O Dilofossauro tinha mãos com garras afiadas!",
    "O Dilofossauro provavelmente caçava em grupo!",
    "O Dilofossauro é um dos carnívoros mais antigos de grande porte!",
    "O Dilofossauro viveu logo após a extinção dos dinossauros triássicos!",
    "O Dilofossauro tinha dentes longos mas frágeis!",
    "O Dilofossauro era mais rápido que a maioria das suas presas!",
    "Pegadas de Dilofossauro foram encontradas em vários lugares do mundo!",
    "O Dilofossauro ficou famoso por causa do filme Jurassic Park!",
  ],
  apatosaurus: [
    "O Apatossauro é o que antes chamávamos de Brontossauro!",
    "O Apatossauro media até 23 metros de comprimento!",
    "O Apatossauro podia pesar até 35 toneladas!",
    "O nome Apatossauro significa lagarto enganoso!",
    "O Apatossauro viveu há 150 milhões de anos!",
    "A cauda do Apatossauro podia estalar como um chicote!",
    "O Apatossauro era herbívoro e comia toneladas de plantas!",
    "O Apatossauro engolia pedras para ajudar na digestão!",
    "O Apatossauro viveu no período Jurássico!",
    "O Apatossauro foi descoberto em 1877!",
    "O Apatossauro tinha um pescoço muito longo e flexível!",
    "O Apatossauro vivia em manadas para se proteger!",
    "Os filhotes de Apatossauro cresciam muito rápido!",
    "O Apatossauro não mastigava a comida, engolia inteiro!",
    "O coração do Apatossauro era do tamanho de uma TV!",
    "O Apatossauro viveu na América do Norte!",
    "O Apatossauro tinha garras nos pés para se defender!",
    "A confusão entre Brontossauro e Apatossauro durou 100 anos!",
    "O Apatossauro podia se levantar nas patas traseiras!",
    "O Apatossauro é um dos dinossauros mais queridos pelas crianças!",
  ],
  plesiosaurus: [
    "O Plesiossauro vivia no mar, não na terra!",
    "O Plesiossauro tinha um pescoço super longo!",
    "O Plesiossauro não era um dinossauro, era um réptil marinho!",
    "O Plesiossauro comia peixes e lulas!",
    "O nome Plesiossauro significa lagarto próximo!",
    "O Plesiossauro viveu há 200 milhões de anos!",
    "O Plesiossauro nadava usando quatro nadadeiras!",
    "O Plesiossauro media até 15 metros de comprimento!",
    "O Plesiossauro precisava subir à superfície para respirar!",
    "O Plesiossauro inspirou a lenda do Monstro do Lago Ness!",
    "O Plesiossauro foi um dos primeiros fósseis encontrados!",
    "O Plesiossauro engolia pedras para ajudar a mergulhar!",
    "O Plesiossauro tinha dentes longos e finos para pegar peixes!",
    "O Plesiossauro foi descoberto por Mary Anning em 1823!",
    "O Plesiossauro viveu nos oceanos do mundo todo!",
    "O Plesiossauro dava à luz filhotes vivos, como os golfinhos!",
    "O Plesiossauro tinha olhos grandes para ver no fundo do mar!",
    "O pescoço do Plesiossauro tinha mais de 40 vértebras!",
    "O Plesiossauro nadava graciosamente como uma tartaruga!",
    "Alguns Plesiossauros chegavam a pesar 20 toneladas!",
  ],
  mosasaurus: [
    "O Mosassauro era o maior predador dos oceanos antigos!",
    "O Mosassauro podia medir até 17 metros!",
    "O Mosassauro não era um dinossauro, era um réptil marinho!",
    "O nome Mosassauro vem do Rio Mosa, onde foi encontrado!",
    "O Mosassauro viveu há 70 milhões de anos!",
    "O Mosassauro tinha mandíbulas enormes para engolir presas!",
    "O Mosassauro comia tubarões, peixes e até outros répteis!",
    "O Mosassauro nadava ondulando o corpo como uma cobra!",
    "O Mosassauro podia pesar até 15 toneladas!",
    "O Mosassauro foi descoberto em 1764 na Holanda!",
    "O Mosassauro era parente dos lagartos monitores de hoje!",
    "O Mosassauro respirava ar e subia à superfície!",
    "O Mosassauro tinha duas fileiras de dentes no céu da boca!",
    "O Mosassauro aparece no filme Jurassic World!",
    "O Mosassauro era um nadador muito rápido!",
    "O Mosassauro dava à luz filhotes no oceano!",
    "O Mosassauro viveu em todos os oceanos do mundo!",
    "O Mosassauro tinha visão excelente para caçar!",
    "O Mosassauro foi um dos últimos grandes répteis marinhos!",
    "O Mosassauro foi extinto junto com os dinossauros há 66 milhões de anos!",
  ],
  dimetrodon: [
    "O Dimetrodonte viveu antes dos dinossauros!",
    "O Dimetrodonte tinha uma vela enorme nas costas!",
    "O Dimetrodonte não era um dinossauro, era um sinapsídeo!",
    "O Dimetrodonte é mais parente dos mamíferos que dos dinossauros!",
    "O nome Dimetrodonte significa dentes de duas medidas!",
    "O Dimetrodonte viveu há 290 milhões de anos!",
    "A vela do Dimetrodonte servia para regular a temperatura!",
    "O Dimetrodonte era um predador do topo da cadeia!",
    "O Dimetrodonte media até 4 metros de comprimento!",
    "O Dimetrodonte podia pesar até 250 quilos!",
    "O Dimetrodonte foi um dos primeiros grandes predadores terrestres!",
    "O Dimetrodonte tinha dentes de tamanhos diferentes!",
    "A vela era sustentada por espinhos ósseos da coluna vertebral!",
    "O Dimetrodonte viveu no que hoje são Estados Unidos e Europa!",
    "O Dimetrodonte andava em quatro patas com as pernas para os lados!",
    "O Dimetrodonte foi descoberto em 1878!",
    "O Dimetrodonte comia peixes e outros animais!",
    "O Dimetrodonte viveu no período Permiano!",
    "A vela do Dimetrodonte pode ter sido colorida!",
    "O Dimetrodonte é confundido com dinossauro, mas não é!",
  ],
  archaeopteryx: [
    "O Arqueoptérix é considerado o primeiro pássaro da história!",
    "O Arqueoptérix tinha dentes, garras e penas!",
    "O Arqueoptérix é metade dinossauro, metade ave!",
    "O nome Arqueoptérix significa asa antiga!",
    "O Arqueoptérix viveu há 150 milhões de anos!",
    "O Arqueoptérix era do tamanho de um corvo!",
    "O Arqueoptérix provavelmente planava mais do que voava!",
    "O Arqueoptérix tinha garras nas asas para escalar árvores!",
    "O Arqueoptérix pesava apenas 1 quilo!",
    "O Arqueoptérix comia insetos e pequenos animais!",
    "O Arqueoptérix foi descoberto em 1861 na Alemanha!",
    "O fóssil do Arqueoptérix é um dos mais importantes já encontrados!",
    "O Arqueoptérix tinha uma cauda longa com penas!",
    "O Arqueoptérix prova que aves evoluíram dos dinossauros!",
    "O Arqueoptérix viveu na mesma época dos grandes dinossauros!",
    "O Arqueoptérix tinha visão excelente!",
    "O Arqueoptérix viveu em ilhas tropicais na Europa!",
    "Apenas 12 fósseis de Arqueoptérix foram encontrados!",
    "O Arqueoptérix não voava tão bem quanto as aves modernas!",
    "O Arqueoptérix é o fóssil de transição mais famoso do mundo!",
  ],
};

import { dinoFunFactsEn } from "./dinoFunFactsEn";
import { dinoFunFactsEs } from "./dinoFunFactsEs";
import { dinoFunFactsFr } from "./dinoFunFactsFr";
import { dinoFunFactsIt } from "./dinoFunFactsIt";
import { dinoFunFactsDe } from "./dinoFunFactsDe";
import type { Locale } from "@/i18n/translations";

const factsByLocale: Record<Locale, Record<DinoId, string[]>> = {
  pt: dinoFunFacts,
  en: dinoFunFactsEn,
  es: dinoFunFactsEs,
  fr: dinoFunFactsFr,
  it: dinoFunFactsIt,
  de: dinoFunFactsDe,
};

export function getRandomDinoFunFact(id: DinoId, locale: Locale = "pt"): string {
  const facts = factsByLocale[locale][id];
  return facts[Math.floor(Math.random() * facts.length)];
}
