import type { DinoId } from "./dinosaurs";

export const dinoFunFactsEs: Record<DinoId, string[]> = {
  trex: [
    "¡El T-Rex tenía dientes del tamaño de plátanos!",
    "¡El T-Rex podía sentir vibraciones en el suelo con sus pies!",
    "¡Los bracitos del T-Rex eran súper fuertes a pesar de ser pequeños!",
    "¡El T-Rex vivió hace 68 millones de años!",
    "¡El T-Rex podía comer 230 kilos de carne de una vez!",
    "¡El nombre T-Rex significa Rey de los Lagartos Tiranos!",
    "¡El T-Rex podía correr a 40 kilómetros por hora!",
    "¡El T-Rex tenía la mordida más fuerte de todos los animales terrestres!",
    "¡El cerebro del T-Rex era más grande que el de muchos dinosaurios!",
    "¡El T-Rex tenía una visión muy buena, mejor que la de un águila!",
    "¡Los científicos han encontrado más de 50 esqueletos de T-Rex!",
    "¡El T-Rex medía hasta 12 metros de largo!",
    "¡Los bebés de T-Rex nacían cubiertos de plumas!",
    "¡El T-Rex vivía en lo que hoy son Estados Unidos y Canadá!",
    "¡La cola del T-Rex lo ayudaba a mantener el equilibrio al correr!",
    "¡El T-Rex es pariente de las gallinas de hoy!",
    "¡El T-Rex podía oír sonidos muy graves, como terremotos!",
    "¡El cráneo del T-Rex podía medir hasta 1,5 metros de largo!",
    "¡El T-Rex cambiaba de dientes toda su vida, como los tiburones!",
    "¡El T-Rex fue uno de los últimos dinosaurios antes de la extinción!",
  ],
  triceratops: [
    "¡El Triceratops tenía tres cuernos en la cara!",
    "¡El escudo del Triceratops protegía su cuello!",
    "¡El Triceratops era herbívoro y comía plantas todo el día!",
    "¡El Triceratops podía pesar hasta 12 toneladas!",
    "¡El Triceratops vivió hace 68 millones de años!",
    "¡El nombre Triceratops significa cara con tres cuernos!",
    "¡El Triceratops tenía un pico como el de un loro!",
    "¡El Triceratops medía hasta 9 metros de largo!",
    "¡El Triceratops tenía hasta 800 dientes!",
    "¡El Triceratops usaba sus cuernos para defenderse del T-Rex!",
    "¡El cráneo del Triceratops podía medir 2 metros!",
    "¡El Triceratops caminaba en cuatro patas!",
    "¡El Triceratops vivía en manadas para protegerse!",
    "¡El escudo del Triceratops también servía para regular su temperatura!",
    "¡El Triceratops es uno de los dinosaurios más reconocidos!",
    "¡Los fósiles de Triceratops se encontraron en América del Norte!",
    "¡El Triceratops era tan grande como un camión!",
    "¡El Triceratops comía helechos y palmeras!",
    "¡El Triceratops tenía la piel gruesa y rugosa!",
    "¡El Triceratops fue uno de los últimos dinosaurios que existieron!",
  ],
  stegosaurus: [
    "¡El Estegosaurio tenía placas en la espalda del tamaño de platos!",
    "¡El cerebro del Estegosaurio era del tamaño de una nuez!",
    "¡El Estegosaurio tenía pinchos en la cola para defenderse!",
    "¡El Estegosaurio vivió hace 155 millones de años!",
    "¡Las placas del Estegosaurio le ayudaban a regular la temperatura!",
    "¡El Estegosaurio medía hasta 9 metros de largo!",
    "¡El Estegosaurio era herbívoro y comía plantas bajas!",
    "¡El nombre Estegosaurio significa lagarto con techo!",
    "¡El Estegosaurio tenía 17 placas en la espalda!",
    "¡El Estegosaurio podía pesar hasta 5 toneladas!",
    "¡Los pinchos de la cola del Estegosaurio se llaman thagomizer!",
    "¡El Estegosaurio tenía las patas traseras más largas que las delanteras!",
    "¡El Estegosaurio no podía correr rápido!",
    "¡Las placas del Estegosaurio podían cambiar de color!",
    "¡El Estegosaurio vivía en lo que hoy es América del Norte!",
    "¡El Estegosaurio fue descubierto en 1877!",
    "¡El Estegosaurio tenía un cuerpo grande pero una cabeza muy pequeña!",
    "¡El Estegosaurio comía helechos y musgos!",
    "¡El Estegosaurio es uno de los dinosaurios más famosos!",
    "¡El Estegosaurio vivió antes que el T-Rex!",
  ],
  brachiosaurus: [
    "¡El Braquiosaurio era tan alto como un edificio de 4 pisos!",
    "¡El Braquiosaurio comía hojas de las copas de los árboles!",
    "¡El Braquiosaurio podía pesar hasta 80 toneladas!",
    "¡El Braquiosaurio tenía las patas delanteras más largas que las traseras!",
    "¡El nombre Braquiosaurio significa lagarto con brazos!",
    "¡El Braquiosaurio vivió hace 154 millones de años!",
    "¡El Braquiosaurio medía hasta 26 metros de largo!",
    "¡El Braquiosaurio tenía el cuello de hasta 9 metros!",
    "¡El Braquiosaurio comía hasta 400 kilos de plantas al día!",
    "¡El corazón del Braquiosaurio pesaba unos 400 kilos!",
    "¡El Braquiosaurio tenía dientes en forma de cuchara!",
    "¡El Braquiosaurio era uno de los dinosaurios más grandes!",
    "¡El Braquiosaurio vivía en manadas!",
    "¡Los bebés de Braquiosaurio nacían de huevos!",
    "¡El Braquiosaurio no podía correr, caminaba lento!",
    "¡El Braquiosaurio fue descubierto en 1903!",
    "¡El Braquiosaurio tenía fosas nasales en la parte alta de la cabeza!",
    "¡El Braquiosaurio tragaba piedras para ayudar a digerir!",
    "¡El Braquiosaurio aparece en la película Jurassic Park!",
    "¡El Braquiosaurio podía alcanzar hojas a 13 metros de altura!",
  ],
  velociraptor: [
    "¡El Velociraptor era del tamaño de un pavo grande!",
    "¡El Velociraptor tenía plumas como las aves!",
    "¡El Velociraptor tenía una garra gigante en cada pie!",
    "¡El Velociraptor era muy inteligente para un dinosaurio!",
    "¡El Velociraptor cazaba en manada!",
    "¡El nombre Velociraptor significa ladrón veloz!",
    "¡El Velociraptor vivió hace 75 millones de años!",
    "¡El Velociraptor podía correr a 65 kilómetros por hora!",
    "¡El Velociraptor medía hasta 2 metros de largo!",
    "¡El Velociraptor pesaba solo 15 kilos!",
    "¡La garra del Velociraptor medía hasta 9 centímetros!",
    "¡El Velociraptor vivía en lo que hoy es Mongolia!",
    "¡El Velociraptor tenía hasta 80 dientes afilados!",
    "¡El Velociraptor en las películas es mucho más grande que el real!",
    "¡Se encontró un fósil de Velociraptor peleando con un Protoceratops!",
    "¡El Velociraptor tenía excelente visión!",
    "¡El Velociraptor es pariente de las aves modernas!",
    "¡El Velociraptor usaba la cola para mantener el equilibrio!",
    "¡El Velociraptor fue descubierto en 1924!",
    "¡El Velociraptor podía saltar sobre sus presas!",
  ],
  pteranodon: [
    "¡El Pteranodonte no era un dinosaurio, era un reptil volador!",
    "¡El Pteranodonte tenía una envergadura de hasta 7 metros!",
    "¡El Pteranodonte no tenía dientes!",
    "¡El Pteranodonte pescaba volando sobre el mar!",
    "¡La cresta del Pteranodonte servía para estabilizar el vuelo!",
    "¡El Pteranodonte vivió hace 85 millones de años!",
    "¡El nombre Pteranodonte significa ala sin dientes!",
    "¡El Pteranodonte podía planear grandes distancias!",
    "¡El Pteranodonte pesaba solo unos 25 kilos!",
    "¡El Pteranodonte vivía cerca de océanos y mares!",
    "¡El Pteranodonte caminaba en cuatro patas!",
    "¡La cresta del Pteranodonte era más grande en los machos!",
    "¡El Pteranodonte tenía huesos huecos como las aves!",
    "¡El Pteranodonte es uno de los reptiles voladores más conocidos!",
    "¡El Pteranodonte comía peces y calamares!",
    "¡El Pteranodonte fue descubierto en 1876!",
    "¡Los fósiles de Pteranodonte se encontraron en Kansas, EE.UU.!",
    "¡El Pteranodonte probablemente tenía piel, no plumas!",
    "¡El Pteranodonte podía volar a grandes alturas!",
    "¡Los bebés de Pteranodonte podían volar poco después de nacer!",
  ],
  ankylosaurus: [
    "¡El Anquilosaurio tenía una armadura natural de hueso!",
    "¡El Anquilosaurio tenía una maza en la cola para defenderse!",
    "¡El Anquilosaurio era como un tanque viviente!",
    "¡El Anquilosaurio vivió hace 68 millones de años!",
    "¡El nombre Anquilosaurio significa lagarto acorazado!",
    "¡El Anquilosaurio medía hasta 10 metros de largo!",
    "¡El Anquilosaurio podía pesar hasta 6 toneladas!",
    "¡La maza de la cola podía romper huesos de depredadores!",
    "¡El Anquilosaurio tenía hasta párpados acorazados!",
    "¡El Anquilosaurio era herbívoro!",
    "¡El Anquilosaurio tenía dientes pequeños para comer plantas!",
    "¡El Anquilosaurio caminaba lentamente en cuatro patas!",
    "¡La armadura del Anquilosaurio estaba hecha de osteodermos!",
    "¡El Anquilosaurio tenía un cerebro pequeño!",
    "¡El Anquilosaurio vivía en América del Norte!",
    "¡El Anquilosaurio fue descubierto en 1908!",
    "¡El Anquilosaurio era casi imposible de voltear!",
    "¡Ni siquiera el T-Rex podía morder la armadura del Anquilosaurio!",
    "¡El Anquilosaurio tenía un amplio hocico para comer plantas bajas!",
    "¡El Anquilosaurio fue uno de los últimos dinosaurios acorazados!",
  ],
  spinosaurus: [
    "¡El Espinosaurio era el dinosaurio carnívoro más grande!",
    "¡El Espinosaurio tenía una vela en la espalda!",
    "¡El Espinosaurio comía peces gigantes!",
    "¡El Espinosaurio podía nadar y cazar bajo el agua!",
    "¡El Espinosaurio era más grande que el T-Rex!",
    "¡El Espinosaurio vivió hace 95 millones de años!",
    "¡El nombre Espinosaurio significa lagarto con espinas!",
    "¡La vela del Espinosaurio podía medir hasta 1,8 metros!",
    "¡El Espinosaurio medía hasta 15 metros de largo!",
    "¡El Espinosaurio tenía un hocico parecido al del cocodrilo!",
    "¡El Espinosaurio tenía dientes cónicos para atrapar peces!",
    "¡El Espinosaurio vivía cerca de ríos y lagos!",
    "¡El Espinosaurio podía caminar en dos o cuatro patas!",
    "¡El Espinosaurio pesaba hasta 20 toneladas!",
    "¡El Espinosaurio fue descubierto en Egipto en 1912!",
    "¡El Espinosaurio es el único dinosaurio que sabemos que nadaba!",
    "¡La cola del Espinosaurio era plana como la de un pez!",
    "¡El Espinosaurio vivía en lo que hoy es el norte de África!",
    "¡El Espinosaurio tenía sensores en el hocico para detectar presas!",
    "¡El primer fósil de Espinosaurio fue destruido en la Segunda Guerra Mundial!",
  ],
  parasaurolophus: [
    "¡El Parasaurolofo tenía una cresta tubular en la cabeza!",
    "¡La cresta del Parasaurolofo funcionaba como una trompeta!",
    "¡El Parasaurolofo usaba la cresta para comunicarse!",
    "¡El Parasaurolofo era herbívoro y comía plantas!",
    "¡El Parasaurolofo vivió hace 76 millones de años!",
    "¡El nombre Parasaurolofo significa cercano al lagarto con cresta!",
    "¡El Parasaurolofo medía hasta 10 metros de largo!",
    "¡El Parasaurolofo podía caminar en dos o cuatro patas!",
    "¡La cresta del Parasaurolofo podía medir más de 1 metro!",
    "¡El Parasaurolofo tenía cientos de dientes!",
    "¡El Parasaurolofo pesaba hasta 5 toneladas!",
    "¡El Parasaurolofo vivía en manadas!",
    "¡El sonido de la cresta del Parasaurolofo era grave como una tuba!",
    "¡El Parasaurolofo pertenece al grupo de los hadrosaurios!",
    "¡El Parasaurolofo tenía una cola larga y fuerte!",
    "¡El Parasaurolofo vivía en América del Norte!",
    "¡El Parasaurolofo fue descubierto en 1922!",
    "¡Los científicos reconstruyeron el sonido de la cresta!",
    "¡El Parasaurolofo probablemente tenía piel colorida!",
    "¡El Parasaurolofo es uno de los dinosaurios más melodiosos!",
  ],
  diplodocus: [
    "¡El Diplódoco era uno de los dinosaurios más largos!",
    "¡El Diplódoco tenía una cola como un látigo!",
    "¡El Diplódoco medía hasta 27 metros de largo!",
    "¡El Diplódoco tenía un cuello muy largo pero liviano!",
    "¡El Diplódoco vivió hace 154 millones de años!",
    "¡El nombre Diplódoco significa doble viga!",
    "¡El Diplódoco era herbívoro y comía helechos!",
    "¡El Diplódoco tenía dientes en forma de lápiz!",
    "¡El Diplódoco podía usar la cola para defenderse!",
    "¡El Diplódoco pesaba hasta 16 toneladas!",
    "¡El Diplódoco tragaba piedras para digerir la comida!",
    "¡El Diplódoco vivía en manadas grandes!",
    "¡El Diplódoco ponía huevos mientras caminaba!",
    "¡El chasquido de la cola del Diplódoco sonaba como un trueno!",
    "¡El Diplódoco tenía las patas delanteras más cortas que las traseras!",
    "¡El Diplódoco vivía en América del Norte!",
    "¡El Diplódoco fue descubierto en 1878!",
    "¡El Diplódoco tenía un cerebro diminuto para su tamaño!",
    "¡El Diplódoco podía alcanzar hojas a gran altura!",
    "¡El Diplódoco es uno de los dinosaurios más populares en los museos!",
  ],
  pachycephalosaurus: [
    "¡El Paquicefalosaurio tenía un cráneo de 25 centímetros de grosor!",
    "¡El Paquicefalosaurio se daba cabezazos con otros dinosaurios!",
    "¡El nombre Paquicefalosaurio significa lagarto de cabeza gruesa!",
    "¡El Paquicefalosaurio vivió hace 70 millones de años!",
    "¡El Paquicefalosaurio era del tamaño de un coche!",
    "¡El Paquicefalosaurio era herbívoro y omnívoro!",
    "¡El Paquicefalosaurio caminaba en dos patas!",
    "¡El cráneo del Paquicefalosaurio tenía bultos y espinas!",
    "¡El Paquicefalosaurio medía hasta 5 metros de largo!",
    "¡Los machos de Paquicefalosaurio competían chocando cabezas!",
    "¡El Paquicefalosaurio pesaba hasta 450 kilos!",
    "¡El Paquicefalosaurio tenía dientes pequeños y afilados!",
    "¡El Paquicefalosaurio vivía en América del Norte!",
    "¡El Paquicefalosaurio tenía buena visión!",
    "¡El Paquicefalosaurio fue descubierto en 1943!",
    "¡El Paquicefalosaurio tenía patas traseras fuertes para correr!",
    "¡La cúpula del cráneo estaba rodeada de espinas decorativas!",
    "¡Algunos científicos creen que los cabezazos eran solo rituales!",
    "¡El Paquicefalosaurio comía plantas, frutas e insectos!",
    "¡El Paquicefalosaurio fue uno de los últimos dinosaurios!",
  ],
  iguanodon: [
    "¡El Iguanodonte tenía un pulgar en forma de pincho!",
    "¡El Iguanodonte fue uno de los primeros dinosaurios descubiertos!",
    "¡El nombre Iguanodonte significa diente de iguana!",
    "¡El Iguanodonte podía caminar en dos o cuatro patas!",
    "¡El Iguanodonte vivió hace 125 millones de años!",
    "¡El Iguanodonte era herbívoro y comía muchas plantas!",
    "¡El Iguanodonte medía hasta 10 metros de largo!",
    "¡El Iguanodonte pesaba hasta 3 toneladas!",
    "¡El pulgar del Iguanodonte servía para defenderse!",
    "¡El Iguanodonte tenía un pico sin dientes en la punta!",
    "¡El Iguanodonte vivía en manadas!",
    "¡Los dientes del Iguanodonte se parecen a los de una iguana!",
    "¡El Iguanodonte fue descubierto en 1825!",
    "¡El Iguanodonte vivió en Europa, América del Norte y Asia!",
    "¡El Iguanodonte podía correr bastante rápido!",
    "¡El Iguanodonte masticaba la comida con sus dientes traseros!",
    "¡Primero pensaron que el pulgar era un cuerno en la nariz!",
    "¡El Iguanodonte tenía una cola larga y rígida!",
    "¡El Iguanodonte es uno de los dinosaurios más estudiados!",
    "¡Se encontraron más de 30 esqueletos de Iguanodonte juntos!",
  ],
  compsognathus: [
    "¡El Compsognato era del tamaño de un pollo!",
    "¡El Compsognato fue uno de los dinosaurios más pequeños!",
    "¡El Compsognato era un cazador rápido!",
    "¡El Compsognato comía lagartos e insectos!",
    "¡El Compsognato vivió hace 150 millones de años!",
    "¡El nombre Compsognato significa mandíbula elegante!",
    "¡El Compsognato medía solo 1 metro de largo!",
    "¡El Compsognato pesaba solo 3 kilos!",
    "¡El Compsognato tenía patas traseras largas para correr rápido!",
    "¡El Compsognato fue descubierto en 1859!",
    "¡El Compsognato tenía ojos grandes para cazar!",
    "¡Se encontró un lagarto en el estómago de un Compsognato!",
    "¡El Compsognato vivía en lo que hoy es Europa!",
    "¡El Compsognato es pariente del Velociraptor!",
    "¡El Compsognato probablemente tenía plumas!",
    "¡El Compsognato podía correr a gran velocidad!",
    "¡El Compsognato tenía manos con dos dedos!",
    "¡El Compsognato tenía una cola larga para equilibrarse!",
    "¡El Compsognato aparece en la película Jurassic Park!",
    "¡Solo se encontraron dos fósiles de Compsognato!",
  ],
  carnotaurus: [
    "¡El Carnotauro tenía cuernos sobre los ojos!",
    "¡El Carnotauro tenía brazos aún más pequeños que el T-Rex!",
    "¡El nombre Carnotauro significa toro carnívoro!",
    "¡El Carnotauro podía correr a 55 kilómetros por hora!",
    "¡El Carnotauro vivió hace 70 millones de años!",
    "¡El Carnotauro tenía una cabeza pequeña pero mandíbula fuerte!",
    "¡El Carnotauro medía hasta 9 metros de largo!",
    "¡El Carnotauro tenía piel con escamas y protuberancias!",
    "¡El Carnotauro fue descubierto en Argentina!",
    "¡El Carnotauro pesaba hasta 2 toneladas!",
    "¡El Carnotauro tenía ojos que miraban hacia adelante!",
    "¡Los cuernos del Carnotauro probablemente eran para pelear!",
    "¡El Carnotauro era uno de los depredadores más rápidos!",
    "¡Solo se encontró un esqueleto casi completo de Carnotauro!",
    "¡El Carnotauro vivía en lo que hoy es América del Sur!",
    "¡El Carnotauro tenía una cola larga y muscular!",
    "¡El Carnotauro cazaba dinosaurios herbívoros!",
    "¡El Carnotauro tenía un cuello corto y fuerte!",
    "¡La piel del Carnotauro se conservó en el fósil!",
    "¡El Carnotauro es uno de los dinosaurios más impresionantes!",
  ],
  dilophosaurus: [
    "¡El Dilofosaurio tenía dos crestas en la cabeza!",
    "¡El Dilofosaurio no escupía veneno como en las películas!",
    "¡El nombre Dilofosaurio significa lagarto con dos crestas!",
    "¡El Dilofosaurio vivió hace 193 millones de años!",
    "¡El Dilofosaurio fue uno de los primeros grandes depredadores!",
    "¡El Dilofosaurio medía hasta 7 metros de largo!",
    "¡El Dilofosaurio pesaba hasta 400 kilos!",
    "¡Las crestas del Dilofosaurio probablemente eran para exhibición!",
    "¡El Dilofosaurio vivía en lo que hoy es América del Norte!",
    "¡El Dilofosaurio caminaba en dos patas!",
    "¡El Dilofosaurio tenía mandíbulas delgadas con dientes afilados!",
    "¡El Dilofosaurio era mucho más grande que en Jurassic Park!",
    "¡No hay evidencia de que el Dilofosaurio tuviera collar!",
    "¡El Dilofosaurio fue descubierto en 1942!",
    "¡El Dilofosaurio tenía manos con tres dedos!",
    "¡El Dilofosaurio vivió en el período Jurásico!",
    "¡El Dilofosaurio probablemente cazaba en grupo!",
    "¡El Dilofosaurio tenía patas traseras fuertes!",
    "¡Los fósiles de Dilofosaurio se encontraron en Arizona!",
    "¡El Dilofosaurio es uno de los dinosaurios más antiguos conocidos!",
  ],
  apatosaurus: [
    "¡El Apatosaurio era uno de los dinosaurios más grandes!",
    "¡El Apatosaurio antes se llamaba Brontosaurio!",
    "¡El nombre Apatosaurio significa lagarto engañoso!",
    "¡El Apatosaurio medía hasta 23 metros de largo!",
    "¡El Apatosaurio vivió hace 152 millones de años!",
    "¡El Apatosaurio pesaba hasta 35 toneladas!",
    "¡El Apatosaurio era herbívoro y comía plantas todo el día!",
    "¡El Apatosaurio tenía un cuello muy largo!",
    "¡El Apatosaurio podía usar la cola como un látigo!",
    "¡El Apatosaurio tragaba piedras para digerir la comida!",
    "¡El Apatosaurio vivía en manadas!",
    "¡Los bebés de Apatosaurio crecían muy rápido!",
    "¡El Apatosaurio no podía levantar mucho el cuello!",
    "¡El Apatosaurio caminaba lentamente en cuatro patas!",
    "¡El Apatosaurio tenía un cerebro muy pequeño!",
    "¡El Apatosaurio vivía en América del Norte!",
    "¡El Apatosaurio fue descubierto en 1877!",
    "¡El corazón del Apatosaurio era enorme!",
    "¡El Apatosaurio se alimentaba de helechos y coníferas!",
    "¡El chasquido de la cola del Apatosaurio rompía la barrera del sonido!",
  ],
  plesiosaurus: [
    "¡El Plesiosauro no era un dinosaurio, era un reptil marino!",
    "¡El Plesiosauro tenía un cuello muy largo!",
    "¡El Plesiosauro nadaba con cuatro aletas!",
    "¡El Plesiosauro comía peces y calamares!",
    "¡El Plesiosauro vivió hace 200 millones de años!",
    "¡El nombre Plesiosauro significa cercano a lagarto!",
    "¡El Plesiosauro medía hasta 15 metros de largo!",
    "¡El Plesiosauro inspiró la leyenda del monstruo del Lago Ness!",
    "¡El Plesiosauro necesitaba salir a la superficie para respirar!",
    "¡El Plesiosauro tenía dientes afilados para atrapar peces!",
    "¡El Plesiosauro nadaba moviendo las aletas como un pingüino!",
    "¡El Plesiosauro fue descubierto por Mary Anning en 1823!",
    "¡El Plesiosauro daba a luz crías vivas!",
    "¡El Plesiosauro podía girar rápidamente en el agua!",
    "¡El Plesiosauro vivía en mares de todo el mundo!",
    "¡El Plesiosauro tenía un cuerpo ancho y aplanado!",
    "¡El Plesiosauro tenía ojos grandes para ver bajo el agua!",
    "¡El Plesiosauro tragaba piedras para ayudar a sumergirse!",
    "¡El cuello del Plesiosauro tenía hasta 40 vértebras!",
    "¡El Plesiosauro se extinguió junto con los dinosaurios!",
  ],
  mosasaurus: [
    "¡El Mosasaurio era el depredador más temido de los mares!",
    "¡El Mosasaurio no era un dinosaurio, era un lagarto marino gigante!",
    "¡El Mosasaurio podía medir hasta 17 metros de largo!",
    "¡El Mosasaurio tenía mandíbulas enormes con dientes curvos!",
    "¡El Mosasaurio vivió hace 70 millones de años!",
    "¡El nombre Mosasaurio significa lagarto del río Mosa!",
    "¡El Mosasaurio era pariente de los lagartos actuales!",
    "¡El Mosasaurio comía peces, tortugas y otros reptiles!",
    "¡El Mosasaurio nadaba moviendo la cola como una anguila!",
    "¡El Mosasaurio pesaba hasta 15 toneladas!",
    "¡El Mosasaurio respiraba aire y subía a la superficie!",
    "¡El Mosasaurio tenía una doble fila de dientes en el paladar!",
    "¡El Mosasaurio fue descubierto en 1764!",
    "¡El Mosasaurio podía abrir la boca muy ampliamente!",
    "¡El Mosasaurio vivía en todos los océanos del mundo!",
    "¡El Mosasaurio daba a luz crías vivas!",
    "¡El Mosasaurio tenía aletas en vez de patas!",
    "¡El Mosasaurio aparece en Jurassic World!",
    "¡El Mosasaurio era de sangre fría!",
    "¡El Mosasaurio se extinguió con los dinosaurios!",
  ],
  dimetrodon: [
    "¡El Dimetrodonte no era un dinosaurio, vivió antes que ellos!",
    "¡El Dimetrodonte tenía una gran vela en la espalda!",
    "¡La vela del Dimetrodonte le servía para calentarse!",
    "¡El Dimetrodonte vivió hace 280 millones de años!",
    "¡El Dimetrodonte era un depredador temible!",
    "¡El nombre Dimetrodonte significa dientes de dos medidas!",
    "¡El Dimetrodonte medía hasta 4 metros de largo!",
    "¡El Dimetrodonte es más cercano a los mamíferos que a los reptiles!",
    "¡El Dimetrodonte tenía dientes grandes y pequeños!",
    "¡La vela del Dimetrodonte era sostenida por espinas de la columna!",
    "¡El Dimetrodonte vivía en lo que hoy es América del Norte!",
    "¡El Dimetrodonte pesaba hasta 250 kilos!",
    "¡El Dimetrodonte era el mayor depredador de su época!",
    "¡El Dimetrodonte caminaba con las patas hacia los lados!",
    "¡El Dimetrodonte vivió 50 millones de años antes de los dinosaurios!",
    "¡El Dimetrodonte comía peces y animales pequeños!",
    "¡El Dimetrodonte fue descubierto en 1878!",
    "¡La vela del Dimetrodonte también servía para atraer pareja!",
    "¡El Dimetrodonte tenía una cola larga!",
    "¡El Dimetrodonte se confunde con dinosaurio pero es un sinápsido!",
  ],
  archaeopteryx: [
    "¡El Arqueoptérix es considerado la primera ave conocida!",
    "¡El Arqueoptérix tenía plumas como las aves actuales!",
    "¡El Arqueoptérix tenía dientes como un dinosaurio!",
    "¡El Arqueoptérix vivió hace 150 millones de años!",
    "¡El Arqueoptérix tenía garras en las alas!",
    "¡El nombre Arqueoptérix significa ala antigua!",
    "¡El Arqueoptérix era del tamaño de un cuervo!",
    "¡El Arqueoptérix tenía cola larga con plumas!",
    "¡El Arqueoptérix podía volar distancias cortas!",
    "¡El Arqueoptérix comía insectos y lagartos pequeños!",
    "¡El Arqueoptérix es el enlace entre dinosaurios y aves!",
    "¡El Arqueoptérix vivía en lo que hoy es Alemania!",
    "¡El primer fósil de Arqueoptérix se encontró en 1861!",
    "¡El Arqueoptérix tenía tres dedos con garras en cada ala!",
    "¡El Arqueoptérix pesaba menos de un kilo!",
    "¡El Arqueoptérix probablemente no volaba tan bien como las aves modernas!",
    "¡Las plumas del Arqueoptérix eran asimétricas, ideales para volar!",
    "¡Solo se han encontrado 12 fósiles de Arqueoptérix!",
    "¡El Arqueoptérix no volaba tan bien como las aves modernas!",
    "¡El Arqueoptérix es el fósil de transición más famoso del mundo!",
  ],
};
