import type { DinoId } from "./dinosaurs";

export const dinoFunFactsFr: Record<DinoId, string[]> = {
  trex: [
    "Le T-Rex avait des dents de la taille de bananes !",
    "Le T-Rex pouvait sentir les vibrations du sol avec ses pieds !",
    "Les petits bras du T-Rex étaient en fait super forts !",
    "Le T-Rex a vécu il y a 68 millions d'années !",
    "Le T-Rex pouvait manger 230 kilos de viande en une bouchée !",
    "T-Rex signifie Roi des Lézards Tyrans !",
    "Le T-Rex pouvait courir à 40 kilomètres par heure !",
    "Le T-Rex avait la morsure la plus puissante de tous les animaux terrestres !",
    "Le cerveau du T-Rex était plus gros que celui de la plupart des dinosaures !",
    "Le T-Rex avait une meilleure vue qu'un aigle !",
    "Les scientifiques ont trouvé plus de 50 squelettes de T-Rex !",
    "Le T-Rex mesurait jusqu'à 12 mètres de long !",
    "Les bébés T-Rex naissaient couverts de plumes !",
    "Le T-Rex vivait dans ce qui est aujourd'hui les États-Unis et le Canada !",
    "La queue du T-Rex l'aidait à garder l'équilibre en courant !",
    "Le T-Rex est parent des poules d'aujourd'hui !",
    "Le T-Rex pouvait entendre des sons très graves, comme les tremblements de terre !",
    "Le crâne du T-Rex pouvait mesurer 1,5 mètre de long !",
    "Le T-Rex remplaçait ses dents toute sa vie, comme les requins !",
    "Le T-Rex fut l'un des derniers dinosaures avant l'extinction !",
  ],
  triceratops: [
    "Le Tricératops avait trois cornes sur le visage !",
    "La collerette du Tricératops protégeait son cou !",
    "Le Tricératops était herbivore et mangeait des plantes toute la journée !",
    "Le Tricératops pouvait peser jusqu'à 12 tonnes !",
    "Tricératops signifie visage à trois cornes !",
    "Le Tricératops vivait en troupeaux pour se protéger !",
    "Le bec du Tricératops ressemblait à celui d'un perroquet !",
    "Le Tricératops a vécu à la même époque que le T-Rex !",
    "La collerette du Tricératops changeait de couleur pour attirer les partenaires !",
    "Le Tricératops mesurait jusqu'à 9 mètres de long !",
    "Le crâne du Tricératops est l'un des plus grands de tous les animaux terrestres !",
    "Le Tricératops avait plus de 400 dents pour mâcher les plantes !",
    "Des scientifiques ont trouvé des Tricératops avec des marques de morsure de T-Rex !",
    "Le Tricératops marchait à quatre pattes, comme un rhinocéros !",
    "Le Tricératops a vécu il y a environ 68 millions d'années !",
    "Les cornes du Tricératops pouvaient mesurer 1 mètre de long !",
    "Le Tricératops est l'un des dinosaures les plus célèbres au monde !",
    "Le Tricératops a été découvert en 1887 !",
    "Les bébés Tricératops avaient de toutes petites cornes !",
    "Le Tricératops utilisait probablement ses cornes pour se battre avec des rivaux !",
  ],
  stegosaurus: [
    "Le Stégosaure avait des plaques sur le dos qui régulaient sa température !",
    "La queue du Stégosaure avait des pointes pour se défendre !",
    "Le cerveau du Stégosaure était de la taille d'une noix !",
    "Le Stégosaure mesurait jusqu'à 9 mètres de long !",
    "Le Stégosaure a vécu il y a 155 millions d'années !",
    "Stégosaure signifie lézard à toit !",
    "Le Stégosaure était herbivore et mangeait des fougères !",
    "Les plaques du Stégosaure devenaient rouges quand il était en colère !",
    "Le Stégosaure pouvait peser jusqu'à 5 tonnes !",
    "Le Stégosaure avait 17 plaques sur le dos !",
    "Les pointes de la queue mesuraient jusqu'à 60 centimètres !",
    "Le Stégosaure marchait lentement à quatre pattes !",
    "Le Stégosaure a été découvert en 1877 aux États-Unis !",
    "Les pattes arrière du Stégosaure étaient plus grandes que les avant !",
    "Le Stégosaure a vécu bien avant le T-Rex !",
    "Le Stégosaure est le dinosaure officiel de l'État du Colorado !",
    "Les plaques du Stégosaure ne servaient pas d'armure !",
    "Le Stégosaure avait des joues pour stocker la nourriture !",
    "Les bébés Stégosaure naissaient déjà avec de petites plaques !",
    "Le Stégosaure est l'un des dinosaures les plus faciles à reconnaître !",
  ],
  brachiosaurus: [
    "Le Brachiosaure était aussi grand qu'un immeuble de 4 étages !",
    "Le Brachiosaure mangeait jusqu'à 400 kilos de plantes par jour !",
    "Le cou du Brachiosaure mesurait 9 mètres de long !",
    "Le Brachiosaure pouvait peser jusqu'à 80 tonnes !",
    "Le Brachiosaure avait des narines au sommet de la tête !",
    "Brachiosaure signifie lézard à bras !",
    "Le Brachiosaure a vécu il y a 154 millions d'années !",
    "Les pattes avant du Brachiosaure étaient plus grandes que les arrière !",
    "Le Brachiosaure ne mâchait pas, il avalait les plantes entières !",
    "Le Brachiosaure mesurait jusqu'à 26 mètres de long !",
    "Le cœur du Brachiosaure était énorme pour pomper le sang jusqu'à la tête !",
    "Le Brachiosaure vivait au Jurassique !",
    "Le Brachiosaure apparaît dans le film Jurassic Park !",
    "Le Brachiosaure vivait probablement en groupes !",
    "Les bébés Brachiosaure grandissaient très vite !",
    "Le Brachiosaure était l'un des plus grands animaux ayant jamais existé !",
    "Le Brachiosaure ne pouvait pas courir à cause de son poids !",
    "Le Brachiosaure a été découvert en 1900 !",
    "Le Brachiosaure mangeait les feuilles en haut des plus grands arbres !",
    "Les dents du Brachiosaure étaient comme des cuillères pour arracher les feuilles !",
  ],
  velociraptor: [
    "Le Vélociraptor avait la taille d'une grosse dinde !",
    "Le Vélociraptor avait des plumes sur tout le corps !",
    "Le Vélociraptor avait une énorme griffe courbe sur chaque pied !",
    "Vélociraptor signifie voleur rapide !",
    "Le Vélociraptor a vécu il y a 75 millions d'années en Mongolie !",
    "Le Vélociraptor était très intelligent pour un dinosaure !",
    "Le Vélociraptor chassait en groupe pour attraper de plus grosses proies !",
    "Le Vélociraptor pouvait courir à 60 kilomètres par heure !",
    "La griffe du Vélociraptor mesurait 6 centimètres de long !",
    "Le Vélociraptor était carnivore et chassait d'autres dinosaures !",
    "Le Vélociraptor dans Jurassic Park est bien plus grand que le vrai !",
    "Le Vélociraptor ne mesurait que 2 mètres de long !",
    "Le Vélociraptor ne pesait que 15 kilos !",
    "Le Vélociraptor avait plus de 80 dents aiguisées !",
    "Des scientifiques ont trouvé un Vélociraptor en combat avec un Protocératops !",
    "Le Vélociraptor utilisait sa queue pour s'équilibrer en courant !",
    "Le Vélociraptor avait une excellente vision pour chasser !",
    "Le Vélociraptor vivait dans le désert de Gobi !",
    "Les plumes du Vélociraptor ne servaient pas à voler !",
    "Le Vélociraptor est l'un des dinosaures les plus étudiés au monde !",
  ],
  pteranodon: [
    "Le Ptéranodon n'était pas un dinosaure, c'était un reptile volant !",
    "L'envergure du Ptéranodon atteignait 7 mètres !",
    "Le Ptéranodon n'avait pas de dents !",
    "Le Ptéranodon mangeait des poissons qu'il pêchait en mer !",
    "La crête du Ptéranodon aidait à stabiliser le vol !",
    "Ptéranodon signifie aile sans dents !",
    "Le Ptéranodon a vécu il y a 86 millions d'années !",
    "Le Ptéranodon ne pesait que 25 kilos malgré sa taille !",
    "Le Ptéranodon avait des os creux, comme les oiseaux d'aujourd'hui !",
    "Le Ptéranodon planait sur de longues distances au-dessus de l'océan !",
    "Les mâles avaient des crêtes plus grandes que les femelles !",
    "Le Ptéranodon vivait en Amérique du Nord !",
    "Le Ptéranodon marchait à quatre pattes au sol !",
    "Le Ptéranodon était l'un des plus grands animaux volants !",
    "Les ailes du Ptéranodon étaient faites de peau tendue !",
    "Le Ptéranodon pouvait plonger dans l'eau pour attraper des poissons !",
    "Le Ptéranodon s'occupait de ses petits dans le nid !",
    "Les fossiles du Ptéranodon ont été trouvés au Kansas !",
    "Le Ptéranodon a été découvert en 1876 !",
    "Le Ptéranodon volait à 50 kilomètres par heure !",
  ],
  ankylosaurus: [
    "L'Ankylosaure était un char d'assaut vivant !",
    "La queue de l'Ankylosaure avait une énorme masse osseuse !",
    "L'Ankylosaure avait une armure faite de plaques d'os !",
    "L'Ankylosaure pouvait casser les pattes du T-Rex avec sa queue !",
    "Ankylosaure signifie lézard rigide !",
    "L'Ankylosaure a vécu il y a 68 millions d'années !",
    "L'Ankylosaure mesurait jusqu'à 10 mètres de long !",
    "L'Ankylosaure était herbivore et mangeait des plantes basses !",
    "L'Ankylosaure pouvait peser jusqu'à 6 tonnes !",
    "Même les paupières de l'Ankylosaure avaient une armure !",
    "L'Ankylosaure avait un petit cerveau !",
    "La masse de la queue pouvait peser 30 kilos !",
    "L'Ankylosaure marchait lentement à quatre pattes !",
    "L'Ankylosaure vivait seul, contrairement à d'autres herbivores !",
    "L'Ankylosaure a été découvert en 1908 !",
    "L'Ankylosaure n'avait pas besoin de fuir car il était très protégé !",
    "Le ventre de l'Ankylosaure était la partie la plus vulnérable !",
    "L'Ankylosaure vivait en Amérique du Nord !",
    "Les dents de l'Ankylosaure étaient petites et en forme de feuille !",
    "L'Ankylosaure est l'un des dinosaures les plus blindés qui ait existé !",
  ],
  spinosaurus: [
    "Le Spinosaure était plus grand que le T-Rex !",
    "Le Spinosaure avait une énorme voile sur le dos !",
    "Le Spinosaure était le premier dinosaure qui nageait !",
    "Le Spinosaure mangeait des poissons géants !",
    "Le museau du Spinosaure ressemblait à celui d'un crocodile !",
    "Spinosaure signifie lézard à épines !",
    "Le Spinosaure a vécu il y a 95 millions d'années en Afrique !",
    "Le Spinosaure mesurait jusqu'à 15 mètres de long !",
    "La voile sur le dos pouvait mesurer 1,8 mètre de haut !",
    "Le Spinosaure avait d'énormes griffes sur les mains !",
    "Le Spinosaure pouvait respirer sous l'eau pendant un court moment !",
    "Le Spinosaure avait des capteurs sur le museau pour détecter les proies dans l'eau !",
    "Le Spinosaure pouvait peser jusqu'à 7 tonnes !",
    "Le Spinosaure marchait sur deux ou quatre pattes !",
    "Le Spinosaure a été découvert en 1912 en Égypte !",
    "Le premier fossile du Spinosaure a été détruit pendant la Seconde Guerre mondiale !",
    "Le Spinosaure avait des dents coniques, différentes du T-Rex !",
    "La queue du Spinosaure était aplatie comme celle d'un poisson !",
    "Le Spinosaure est le plus grand carnivore terrestre ayant jamais existé !",
    "Le Spinosaure apparaît dans le film Jurassic Park 3 !",
  ],
  parasaurolophus: [
    "Le Parasaurolophus avait une crête creuse qui faisait des sons comme une trompette !",
    "Le Parasaurolophus utilisait sa crête pour communiquer avec le groupe !",
    "Le Parasaurolophus était herbivore et mangeait des feuilles et des fruits !",
    "Le Parasaurolophus pouvait marcher sur deux ou quatre pattes !",
    "Parasaurolophus signifie lézard à crête proche !",
    "Le Parasaurolophus a vécu il y a 76 millions d'années !",
    "La crête du Parasaurolophus pouvait mesurer 1 mètre !",
    "Le Parasaurolophus mesurait jusqu'à 10 mètres de long !",
    "Le Parasaurolophus vivait en grands troupeaux !",
    "Le Parasaurolophus pouvait peser jusqu'à 5 tonnes !",
    "Le son de la crête du Parasaurolophus était grave comme une trompette !",
    "Le Parasaurolophus avait des centaines de dents pour mâcher !",
    "Le Parasaurolophus a été découvert en 1922 au Canada !",
    "Les bébés avaient des crêtes plus petites qui grandissaient avec le temps !",
    "Le Parasaurolophus avait un bon odorat pour sentir les prédateurs !",
    "Le Parasaurolophus est l'un des dinosaures les plus musicaux !",
    "La crête était peut-être colorée pour attirer les partenaires !",
    "Le Parasaurolophus vivait en Amérique du Nord !",
    "Le Parasaurolophus courait jusqu'à 40 kilomètres par heure !",
    "Le Parasaurolophus est connu comme le dinosaure trompette !",
  ],
  diplodocus: [
    "Le Diplodocus était l'un des dinosaures les plus longs, avec 27 mètres !",
    "La queue du Diplodocus pouvait claquer comme un fouet !",
    "Le Diplodocus avait un cou de 6 mètres !",
    "Le Diplodocus était herbivore et mangeait des feuilles toute la journée !",
    "Diplodocus signifie double poutre !",
    "Le Diplodocus a vécu il y a 154 millions d'années !",
    "Le Diplodocus pouvait peser jusqu'à 16 tonnes !",
    "Le Diplodocus n'avait des dents qu'à l'avant de la bouche, comme un peigne !",
    "Le Diplodocus avalait des pierres pour aider à digérer !",
    "Le Diplodocus vivait en grands troupeaux !",
    "Le Diplodocus fut l'un des premiers dinosaures géants découverts !",
    "Le Diplodocus ne mâchait pas, il arrachait les feuilles et avalait !",
    "Le Diplodocus avait 15 vertèbres dans le cou !",
    "Le Diplodocus a été découvert en 1878 !",
    "La queue du Diplodocus avait plus de 70 os !",
    "Le Diplodocus pouvait se dresser sur ses pattes arrière pour atteindre les arbres !",
    "Le cœur du Diplodocus était gigantesque pour pomper le sang dans tout le corps !",
    "Le Diplodocus vivait en Amérique du Nord !",
    "Les bébés Diplodocus grandissaient très vite !",
    "Le Diplodocus est l'un des dinosaures les plus exposés dans les musées !",
  ],
  pachycephalosaurus: [
    "Le Pachycéphalosaure avait un crâne de 25 centimètres d'épaisseur !",
    "Le Pachycéphalosaure utilisait sa tête dure pour donner des coups de tête !",
    "Pachycéphalosaure signifie lézard à tête épaisse !",
    "Le Pachycéphalosaure a vécu il y a 70 millions d'années !",
    "Le Pachycéphalosaure mesurait jusqu'à 5 mètres de long !",
    "Le Pachycéphalosaure était bipède et marchait sur deux pattes !",
    "Le Pachycéphalosaure était herbivore et omnivore !",
    "Le dôme de la tête était décoré de pointes et de nodules !",
    "Le Pachycéphalosaure vivait en Amérique du Nord !",
    "Le Pachycéphalosaure pesait environ 450 kilos !",
    "Les mâles se donnaient des coups de tête pour les femelles !",
    "Le Pachycéphalosaure a été découvert en 1931 !",
    "Le crâne du Pachycéphalosaure est l'un des plus épais de tous les animaux !",
    "Le Pachycéphalosaure avait de petites dents pointues !",
    "Le Pachycéphalosaure vivait à la même époque que le T-Rex !",
    "Le Pachycéphalosaure pouvait courir vite sur deux pattes !",
    "Les yeux du Pachycéphalosaure étaient sur le côté de la tête !",
    "Le Pachycéphalosaure est le dinosaure tête dure !",
    "Les scientifiques débattent si les coups de tête ne blessaient pas le cerveau !",
    "Le dôme crânien grandissait avec l'âge de l'animal !",
  ],
  iguanodon: [
    "L'Iguanodon a été le deuxième dinosaure nommé dans l'histoire !",
    "L'Iguanodon avait un éperon sur le pouce pour se défendre !",
    "Iguanodon signifie dent d'iguane !",
    "L'Iguanodon a vécu il y a 125 millions d'années !",
    "L'Iguanodon mesurait jusqu'à 10 mètres de long !",
    "L'Iguanodon pouvait marcher sur deux ou quatre pattes !",
    "L'Iguanodon était herbivore et mâchait comme une vache !",
    "L'Iguanodon a été découvert en 1825 en Angleterre !",
    "L'Iguanodon pouvait peser jusqu'à 4 tonnes !",
    "L'éperon du pouce a été confondu avec une corne de nez !",
    "L'Iguanodon vivait en grands groupes !",
    "L'Iguanodon avait des centaines de dents pour broyer les plantes !",
    "L'Iguanodon vivait en Europe, Amérique du Nord et Asie !",
    "L'Iguanodon est l'un des dinosaures les mieux étudiés !",
    "Les dents de l'Iguanodon se remplaçaient toute la vie !",
    "L'Iguanodon avait une longue langue pour tirer les feuilles !",
    "L'Iguanodon courait jusqu'à 35 kilomètres par heure !",
    "L'Iguanodon avait des mains très flexibles !",
    "Plus de 30 squelettes ont été trouvés ensemble dans une mine en Belgique !",
    "L'Iguanodon a aidé les scientifiques à comprendre comment vivaient les dinosaures !",
  ],
  compsognathus: [
    "Le Compsognathus était l'un des plus petits dinosaures, de la taille d'une poule !",
    "Le Compsognathus ne pesait que 3 kilos !",
    "Le Compsognathus était un chasseur rapide et agile !",
    "Compsognathus signifie mâchoire élégante !",
    "Le Compsognathus a vécu il y a 150 millions d'années !",
    "Le Compsognathus mangeait des insectes et des lézards !",
    "Le Compsognathus fut l'un des premiers dinosaures complets trouvés !",
    "Le Compsognathus ne mesurait qu'un mètre de long !",
    "Le Compsognathus courait très vite sur deux pattes !",
    "Le Compsognathus vivait en Europe, en Allemagne et en France !",
    "Le Compsognathus a été découvert en 1859 !",
    "Des scientifiques ont trouvé un lézard dans l'estomac d'un fossile !",
    "Le Compsognathus avait de fines plumes sur le corps !",
    "Le Compsognathus était un parent éloigné du Vélociraptor !",
    "Le Compsognathus avait de grands yeux pour bien voir !",
    "Le Compsognathus est l'un des dinosaures les plus mignons !",
    "Le Compsognathus chassait seul, pas en groupe !",
    "Le Compsognathus avait trois doigts à chaque main !",
    "Le Compsognathus vivait à la même époque que l'Archaeopteryx !",
    "Le Compsognathus apparaît dans Jurassic Park comme un petit dinosaure !",
  ],
  carnotaurus: [
    "Le Carnotaure avait des cornes au-dessus des yeux, comme un taureau !",
    "Le Carnotaure avait des bras encore plus petits que le T-Rex !",
    "Carnotaure signifie taureau carnivore !",
    "Le Carnotaure a vécu il y a 72 millions d'années en Argentine !",
    "Le Carnotaure pouvait courir à 56 kilomètres par heure !",
    "Le Carnotaure mesurait jusqu'à 8 mètres de long !",
    "Le Carnotaure avait une peau avec des écailles et des bosses !",
    "Le Carnotaure était l'un des prédateurs les plus rapides !",
    "Le Carnotaure pesait environ 1,5 tonne !",
    "Le Carnotaure a été découvert en 1985 !",
    "Le Carnotaure est l'un des rares dinosaures avec de la peau fossilisée !",
    "Les cornes du Carnotaure servaient pour les combats entre mâles !",
    "Le Carnotaure avait un museau court et une mâchoire faible !",
    "Le Carnotaure compensait sa mâchoire faible par la vitesse !",
    "Le Carnotaure vivait en Amérique du Sud !",
    "Le Carnotaure avait les yeux tournés vers l'avant pour voir en profondeur !",
    "Les bras du Carnotaure étaient pratiquement inutiles !",
    "Le Carnotaure chassait probablement des dinosaures herbivores !",
    "Le Carnotaure apparaît dans le film Jurassic World !",
    "Le Carnotaure est le dinosaure à cornes le plus célèbre parmi les carnivores !",
  ],
  dilophosaurus: [
    "Le Dilophosaure avait deux belles crêtes sur la tête !",
    "Le Dilophosaure ne crachait PAS de venin, c'est une invention du film !",
    "Dilophosaure signifie lézard à deux crêtes !",
    "Le Dilophosaure a vécu il y a 193 millions d'années !",
    "Le Dilophosaure mesurait jusqu'à 7 mètres de long !",
    "Le Dilophosaure était l'un des plus grands carnivores de son époque !",
    "Le Dilophosaure pesait environ 400 kilos !",
    "Les crêtes servaient à attirer les partenaires !",
    "Le Dilophosaure n'avait pas la collerette qu'on voit dans le film !",
    "Le Dilophosaure vivait dans ce qui est aujourd'hui l'Arizona !",
    "Le Dilophosaure a été découvert en 1942 !",
    "Le Dilophosaure était bipède et courait vite !",
    "Le Dilophosaure avait des dents longues et fines !",
    "Le Dilophosaure avait des mains à quatre doigts !",
    "Le Dilophosaure est l'un des premiers grands carnivores de l'histoire !",
    "Le Dilophosaure vivait au début du Jurassique !",
    "Les crêtes du Dilophosaure étaient très fragiles !",
    "Le Dilophosaure pouvait mesurer 2 mètres de haut !",
    "Le Dilophosaure chassait de petits animaux et des poissons !",
    "Le Dilophosaure est devenu célèbre grâce au film Jurassic Park !",
  ],
  apatosaurus: [
    "L'Apatosaure était l'un des plus grands dinosaures !",
    "L'Apatosaure pouvait peser jusqu'à 35 tonnes !",
    "Apatosaure signifie lézard trompeur !",
    "L'Apatosaure a vécu il y a 152 millions d'années !",
    "L'Apatosaure mesurait jusqu'à 23 mètres de long !",
    "L'Apatosaure était herbivore et mangeait des plantes !",
    "L'Apatosaure s'appelait autrefois Brontosaure !",
    "L'Apatosaure avait un très long cou et une très longue queue !",
    "L'Apatosaure avalait des pierres pour aider à digérer !",
    "L'Apatosaure vivait en grands troupeaux !",
    "L'Apatosaure pouvait se dresser sur ses pattes arrière !",
    "La queue de l'Apatosaure claquait comme un fouet !",
    "L'Apatosaure a été découvert en 1877 !",
    "L'Apatosaure vivait en Amérique du Nord !",
    "Les bébés Apatosaure grandissaient très vite !",
    "L'Apatosaure avait un petit cerveau par rapport à son corps !",
    "L'Apatosaure ne mâchait pas sa nourriture !",
    "L'Apatosaure pouvait vivre jusqu'à 100 ans !",
    "L'Apatosaure était l'un des plus grands herbivores !",
    "L'Apatosaure est l'un des dinosaures les plus connus au monde !",
  ],
  plesiosaurus: [
    "Le Plésiosaure n'était pas un dinosaure, c'était un reptile marin !",
    "Le Plésiosaure avait un très long cou et un petit corps !",
    "Le Plésiosaure nageait avec quatre nageoires comme des rames !",
    "Le Plésiosaure a vécu il y a 200 millions d'années !",
    "Le Plésiosaure mangeait des poissons et des calmars !",
    "Plésiosaure signifie proche du lézard !",
    "Le Plésiosaure mesurait jusqu'à 15 mètres de long !",
    "Le Plésiosaure a inspiré la légende du monstre du Loch Ness !",
    "Le Plésiosaure devait remonter à la surface pour respirer !",
    "Le Plésiosaure a été l'un des premiers reptiles marins découverts !",
    "Le cou du Plésiosaure avait plus de 40 vertèbres !",
    "Le Plésiosaure vivait dans les mers du monde entier !",
    "Le Plésiosaure a été découvert en 1823 en Angleterre !",
    "Le Plésiosaure avalait des pierres pour contrôler la flottabilité !",
    "Le Plésiosaure nageait lentement mais avec élégance !",
    "Le Plésiosaure attrapait les poissons avec son long cou !",
    "Le Plésiosaure avait des dents pointues pour attraper les proies glissantes !",
    "Les bébés Plésiosaure naissaient vivants, pas dans des œufs !",
    "Le Plésiosaure vivait en groupes dans l'océan !",
    "Le Plésiosaure a disparu avec les dinosaures il y a 66 millions d'années !",
  ],
  mosasaurus: [
    "Le Mosasaure était l'un des plus grands prédateurs marins !",
    "Le Mosasaure pouvait mesurer jusqu'à 17 mètres de long !",
    "Le Mosasaure n'était pas un dinosaure, c'était un lézard marin géant !",
    "Le Mosasaure a vécu il y a 70 millions d'années !",
    "Le Mosasaure avait deux rangées de dents sur le palais !",
    "Mosasaure signifie lézard de la Meuse !",
    "Le Mosasaure mangeait des poissons, tortues et même des requins !",
    "Le Mosasaure nageait en ondulant le corps comme un serpent !",
    "Le Mosasaure devait remonter à la surface pour respirer !",
    "Le Mosasaure était le prédateur suprême des mers du Crétacé !",
    "Le Mosasaure pouvait peser jusqu'à 15 tonnes !",
    "Le Mosasaure avait un corps hydrodynamique pour nager vite !",
    "Le premier fossile de Mosasaure a été trouvé aux Pays-Bas en 1764 !",
    "Le Mosasaure est parent des varans actuels !",
    "Le Mosasaure avait des yeux sur les côtés de la tête !",
    "Le Mosasaure pouvait ouvrir très grand la gueule !",
    "Le Mosasaure donnait naissance à des petits vivants !",
    "Le Mosasaure apparaît dans le film Jurassic World !",
    "Le Mosasaure avait une queue aplatie pour nager !",
    "Le Mosasaure a disparu lors de l'extinction massive il y a 66 millions d'années !",
  ],
  dimetrodon: [
    "Le Dimétrodon n'était pas un dinosaure mais un reptile pré-dinosaure !",
    "Le Dimétrodon avait une grande voile sur le dos !",
    "La voile du Dimétrodon l'aidait à réguler sa température !",
    "Le Dimétrodon a vécu il y a 280 millions d'années !",
    "Le Dimétrodon a vécu avant les dinosaures !",
    "Dimétrodon signifie deux tailles de dents !",
    "Le Dimétrodon avait des dents de tailles différentes !",
    "Le Dimétrodon était carnivore et un prédateur redoutable !",
    "Le Dimétrodon mesurait jusqu'à 4 mètres de long !",
    "Le Dimétrodon est plus proche parent des mammifères que des reptiles !",
    "La voile du Dimétrodon était faite de peau tendue sur des épines osseuses !",
    "Le Dimétrodon vivait dans ce qui est aujourd'hui l'Amérique du Nord !",
    "Le Dimétrodon se réchauffait en tournant sa voile vers le soleil !",
    "Le Dimétrodon pouvait peser jusqu'à 250 kilos !",
    "Le Dimétrodon a été découvert en 1878 !",
    "Le Dimétrodon est souvent confondu avec un dinosaure !",
    "Le Dimétrodon vivait dans des zones marécageuses !",
    "Le Dimétrodon avait des pattes courtes et étalées sur les côtés !",
    "Le Dimétrodon est l'un des plus célèbres animaux préhistoriques !",
    "Le Dimétrodon a disparu 40 millions d'années avant l'apparition des dinosaures !",
  ],
  archaeopteryx: [
    "L'Archéoptéryx est considéré comme le premier oiseau de l'histoire !",
    "L'Archéoptéryx avait des plumes comme un oiseau et des dents comme un dinosaure !",
    "L'Archéoptéryx a vécu il y a 150 millions d'années !",
    "L'Archéoptéryx avait la taille d'un corbeau !",
    "Archéoptéryx signifie aile ancienne !",
    "L'Archéoptéryx avait des griffes sur les ailes !",
    "L'Archéoptéryx ne volait probablement pas très bien !",
    "L'Archéoptéryx vivait dans ce qui est aujourd'hui l'Allemagne !",
    "L'Archéoptéryx avait une longue queue osseuse avec des plumes !",
    "L'Archéoptéryx a été découvert en 1861 !",
    "L'Archéoptéryx fait le lien entre les dinosaures et les oiseaux !",
    "L'Archéoptéryx pesait moins d'un kilo !",
    "L'Archéoptéryx avait des dents petites et pointues !",
    "L'Archéoptéryx mangeait des insectes et de petits lézards !",
    "Les plumes de l'Archéoptéryx étaient similaires à celles des oiseaux modernes !",
    "L'Archéoptéryx planait probablement plus qu'il ne volait !",
    "L'Archéoptéryx vivait dans des îles tropicales !",
    "Seulement 12 fossiles d'Archéoptéryx ont été trouvés !",
    "L'Archéoptéryx ne volait pas aussi bien que les oiseaux modernes !",
    "L'Archéoptéryx est le fossile de transition le plus célèbre au monde !",
  ],
};
