import type { DinoId } from "./dinosaurs";

export const dinoFunFactsDe: Record<DinoId, string[]> = {
  trex: [
    "Der T-Rex hatte Zähne so groß wie Bananen!",
    "Der T-Rex konnte Vibrationen im Boden durch seine Füße spüren!",
    "Die kleinen Arme des T-Rex waren tatsächlich superrrstark!",
    "Der T-Rex lebte vor 68 Millionen Jahren!",
    "Der T-Rex konnte 230 Kilogramm Fleisch auf einmal fressen!",
    "T-Rex bedeutet Tyrannenkönig der Eidechsen!",
    "Der T-Rex konnte 40 Kilometer pro Stunde laufen!",
    "Der T-Rex hatte den stärksten Biss aller Landtiere!",
    "Das Gehirn des T-Rex war größer als das vieler anderer Dinosaurier!",
    "Der T-Rex hatte bessere Augen als ein Adler!",
    "Wissenschaftler haben über 50 T-Rex-Skelette gefunden!",
    "Der T-Rex war bis zu 12 Meter lang!",
    "Baby-T-Rexe wurden mit Federn bedeckt geboren!",
    "Der T-Rex lebte in dem Gebiet, das heute die USA und Kanada sind!",
    "Der Schwanz des T-Rex half ihm beim Laufen das Gleichgewicht zu halten!",
    "Der T-Rex ist mit den heutigen Hühnern verwandt!",
    "Der T-Rex konnte sehr tiefe Geräusche hören, wie Erdbeben!",
    "Der Schädel des T-Rex konnte bis zu 1,5 Meter lang sein!",
    "Der T-Rex ersetzte seine Zähne ein Leben lang, wie Haie!",
    "Der T-Rex war einer der letzten Dinosaurier vor dem Aussterben!",
  ],
  triceratops: [
    "Der Triceratops hatte drei Hörner im Gesicht!",
    "Der Nackenschild des Triceratops schützte seinen Hals!",
    "Der Triceratops war ein Pflanzenfresser und fraß den ganzen Tag Pflanzen!",
    "Der Triceratops konnte bis zu 12 Tonnen wiegen!",
    "Triceratops bedeutet Gesicht mit drei Hörnern!",
    "Der Triceratops lebte in Herden zum Schutz!",
    "Der Schnabel des Triceratops sah aus wie der eines Papageis!",
    "Der Triceratops lebte zur gleichen Zeit wie der T-Rex!",
    "Der Nackenschild des Triceratops änderte die Farbe, um Partner anzulocken!",
    "Der Triceratops war bis zu 9 Meter lang!",
    "Der Schädel des Triceratops ist einer der größten aller Landtiere!",
    "Der Triceratops hatte über 400 Zähne zum Kauen von Pflanzen!",
    "Wissenschaftler fanden Triceratops mit Bissspuren vom T-Rex!",
    "Der Triceratops lief auf vier Beinen, wie ein Nashorn!",
    "Der Triceratops lebte vor etwa 68 Millionen Jahren!",
    "Die Hörner des Triceratops konnten 1 Meter lang werden!",
    "Der Triceratops ist einer der berühmtesten Dinosaurier der Welt!",
    "Der Triceratops wurde 1887 entdeckt!",
    "Baby-Triceratops hatten winzige Hörner!",
    "Der Triceratops benutzte wahrscheinlich seine Hörner, um mit Rivalen zu kämpfen!",
  ],
  stegosaurus: [
    "Der Stegosaurus hatte Platten auf dem Rücken, die seine Temperatur regulierten!",
    "Der Schwanz des Stegosaurus hatte Stacheln zur Verteidigung!",
    "Das Gehirn des Stegosaurus war so groß wie eine Walnuss!",
    "Der Stegosaurus war bis zu 9 Meter lang!",
    "Der Stegosaurus lebte vor 155 Millionen Jahren!",
    "Stegosaurus bedeutet Dacheidechse!",
    "Der Stegosaurus war ein Pflanzenfresser und fraß Farne!",
    "Die Platten des Stegosaurus wurden rot, wenn er wütend war!",
    "Der Stegosaurus konnte bis zu 5 Tonnen wiegen!",
    "Der Stegosaurus hatte 17 Platten auf dem Rücken!",
    "Die Schwanzstacheln waren bis zu 60 Zentimeter lang!",
    "Der Stegosaurus lief langsam auf vier Beinen!",
    "Der Stegosaurus wurde 1877 in den USA entdeckt!",
    "Die Hinterbeine des Stegosaurus waren größer als die Vorderbeine!",
    "Der Stegosaurus lebte lange vor dem T-Rex!",
    "Der Stegosaurus ist der offizielle Dinosaurier des Bundesstaates Colorado!",
    "Die Platten des Stegosaurus dienten nicht als Rüstung!",
    "Der Stegosaurus hatte Backentaschen, um Futter zu speichern!",
    "Baby-Stegosaurier wurden schon mit kleinen Platten geboren!",
    "Der Stegosaurus ist einer der am leichtesten erkennbaren Dinosaurier!",
  ],
  brachiosaurus: [
    "Der Brachiosaurus war so hoch wie ein vierstöckiges Gebäude!",
    "Der Brachiosaurus fraß bis zu 400 Kilogramm Pflanzen am Tag!",
    "Der Hals des Brachiosaurus war 9 Meter lang!",
    "Der Brachiosaurus konnte bis zu 80 Tonnen wiegen!",
    "Der Brachiosaurus hatte Nasenlöcher oben auf dem Kopf!",
    "Brachiosaurus bedeutet Armeidechse!",
    "Der Brachiosaurus lebte vor 154 Millionen Jahren!",
    "Die Vorderbeine des Brachiosaurus waren länger als die Hinterbeine!",
    "Der Brachiosaurus kaute nicht, er schluckte die Pflanzen ganz!",
    "Der Brachiosaurus war bis zu 26 Meter lang!",
    "Das Herz des Brachiosaurus war riesig, um Blut bis zum Kopf zu pumpen!",
    "Der Brachiosaurus lebte in der Jurazeit!",
    "Der Brachiosaurus kommt im Film Jurassic Park vor!",
    "Der Brachiosaurus lebte wahrscheinlich in Gruppen!",
    "Baby-Brachiosaurier wuchsen sehr schnell!",
    "Der Brachiosaurus war eines der größten Tiere, die je gelebt haben!",
    "Der Brachiosaurus konnte wegen seines Gewichts nicht rennen!",
    "Der Brachiosaurus wurde 1900 entdeckt!",
    "Der Brachiosaurus fraß Blätter von den höchsten Bäumen!",
    "Die Zähne des Brachiosaurus waren wie Löffel zum Blätterabreißen!",
  ],
  velociraptor: [
    "Der Velociraptor war so groß wie ein großer Truthahn!",
    "Der Velociraptor hatte Federn am ganzen Körper!",
    "Der Velociraptor hatte eine riesige gebogene Kralle an jedem Fuß!",
    "Velociraptor bedeutet schneller Räuber!",
    "Der Velociraptor lebte vor 75 Millionen Jahren in der Mongolei!",
    "Der Velociraptor war für einen Dinosaurier sehr intelligent!",
    "Der Velociraptor jagte in Gruppen, um größere Beute zu fangen!",
    "Der Velociraptor konnte 60 Kilometer pro Stunde laufen!",
    "Die Kralle des Velociraptors war 6 Zentimeter lang!",
    "Der Velociraptor war ein Fleischfresser und jagte andere Dinosaurier!",
    "Der Velociraptor im Film Jurassic Park ist viel größer als in Wirklichkeit!",
    "Der Velociraptor war nur 2 Meter lang!",
    "Der Velociraptor wog nur 15 Kilogramm!",
    "Der Velociraptor hatte über 80 scharfe Zähne!",
    "Wissenschaftler fanden Fossilien eines Velociraptors im Kampf mit einem Protoceratops!",
    "Der Velociraptor benutzte seinen Schwanz zum Balancieren beim Laufen!",
    "Der Velociraptor hatte ausgezeichnete Augen zum Jagen!",
    "Der Velociraptor lebte in der Wüste Gobi!",
    "Die Federn des Velociraptors dienten nicht zum Fliegen!",
    "Der Velociraptor ist einer der am besten erforschten Dinosaurier der Welt!",
  ],
  pteranodon: [
    "Der Pteranodon war kein Dinosaurier, sondern ein fliegendes Reptil!",
    "Die Flügelspannweite des Pteranodon erreichte 7 Meter!",
    "Der Pteranodon hatte keine Zähne!",
    "Der Pteranodon fraß Fische, die er aus dem Meer fischte!",
    "Der Kamm des Pteranodon half, den Flug zu stabilisieren!",
    "Pteranodon bedeutet Flügel ohne Zähne!",
    "Der Pteranodon lebte vor 86 Millionen Jahren!",
    "Der Pteranodon wog trotz seiner Größe nur 25 Kilogramm!",
    "Der Pteranodon hatte hohle Knochen, wie die heutigen Vögel!",
    "Der Pteranodon glitt über lange Strecken über dem Ozean!",
    "Die Männchen hatten größere Kämme als die Weibchen!",
    "Der Pteranodon lebte in Nordamerika!",
    "Der Pteranodon lief auf allen Vieren am Boden!",
    "Der Pteranodon war eines der größten fliegenden Tiere!",
    "Die Flügel des Pteranodon bestanden aus gespannter Haut!",
    "Der Pteranodon konnte ins Wasser tauchen, um Fische zu fangen!",
    "Der Pteranodon kümmerte sich um seine Jungen im Nest!",
    "Fossilien des Pteranodon wurden in Kansas gefunden!",
    "Der Pteranodon wurde 1876 entdeckt!",
    "Der Pteranodon flog mit bis zu 50 Kilometern pro Stunde!",
  ],
  ankylosaurus: [
    "Der Ankylosaurus war ein lebender Panzer!",
    "Der Schwanz des Ankylosaurus hatte eine riesige Knochenkeule!",
    "Der Ankylosaurus hatte eine Rüstung aus Knochenplatten!",
    "Der Ankylosaurus konnte dem T-Rex mit dem Schwanz die Beine brechen!",
    "Ankylosaurus bedeutet starre Eidechse!",
    "Der Ankylosaurus lebte vor 68 Millionen Jahren!",
    "Der Ankylosaurus war bis zu 10 Meter lang!",
    "Der Ankylosaurus war ein Pflanzenfresser und fraß niedrige Pflanzen!",
    "Der Ankylosaurus konnte bis zu 6 Tonnen wiegen!",
    "Sogar die Augenlider des Ankylosaurus hatten eine Rüstung!",
    "Der Ankylosaurus hatte ein kleines Gehirn!",
    "Die Schwanzkeule konnte 30 Kilogramm wiegen!",
    "Der Ankylosaurus lief langsam auf vier Beinen!",
    "Der Ankylosaurus lebte allein, anders als andere Pflanzenfresser!",
    "Der Ankylosaurus wurde 1908 entdeckt!",
    "Der Ankylosaurus musste nicht fliehen, weil er so gut geschützt war!",
    "Der Bauch des Ankylosaurus war die verletzlichste Stelle!",
    "Der Ankylosaurus lebte in dem Gebiet, das heute Nordamerika ist!",
    "Die Zähne des Ankylosaurus waren klein und blattförmig!",
    "Der Ankylosaurus ist einer der am stärksten gepanzerten Dinosaurier!",
  ],
  spinosaurus: [
    "Der Spinosaurus war größer als der T-Rex!",
    "Der Spinosaurus hatte ein riesiges Segel auf dem Rücken!",
    "Der Spinosaurus war der erste Dinosaurier, der schwimmen konnte!",
    "Der Spinosaurus fraß riesige Fische!",
    "Die Schnauze des Spinosaurus sah aus wie die eines Krokodils!",
    "Spinosaurus bedeutet Stacheleidechse!",
    "Der Spinosaurus lebte vor 95 Millionen Jahren in Afrika!",
    "Der Spinosaurus war bis zu 15 Meter lang!",
    "Das Rückensegel konnte 1,8 Meter hoch werden!",
    "Der Spinosaurus hatte riesige Krallen an den Händen!",
    "Der Spinosaurus konnte kurze Zeit unter Wasser atmen!",
    "Der Spinosaurus hatte Sensoren in der Schnauze, um Beute im Wasser zu orten!",
    "Der Spinosaurus konnte bis zu 7 Tonnen wiegen!",
    "Der Spinosaurus lief sowohl auf zwei als auch auf vier Beinen!",
    "Der Spinosaurus wurde 1912 in Ägypten entdeckt!",
    "Das erste Spinosaurus-Fossil wurde im Zweiten Weltkrieg zerstört!",
    "Der Spinosaurus hatte kegelförmige Zähne, anders als der T-Rex!",
    "Der Schwanz des Spinosaurus war flach wie der eines Fisches!",
    "Der Spinosaurus ist das größte landbewohnende Raubtier, das je gelebt hat!",
    "Der Spinosaurus kommt im Film Jurassic Park 3 vor!",
  ],
  parasaurolophus: [
    "Der Parasaurolophus hatte einen hohlen Kamm, der Töne wie eine Trompete machte!",
    "Der Parasaurolophus benutzte den Kamm, um mit der Gruppe zu kommunizieren!",
    "Der Parasaurolophus war ein Pflanzenfresser und fraß Blätter und Früchte!",
    "Der Parasaurolophus konnte auf zwei oder vier Beinen laufen!",
    "Parasaurolophus bedeutet Eidechse mit Kamm in der Nähe!",
    "Der Parasaurolophus lebte vor 76 Millionen Jahren!",
    "Der Kamm des Parasaurolophus konnte 1 Meter lang werden!",
    "Der Parasaurolophus war bis zu 10 Meter lang!",
    "Der Parasaurolophus lebte in großen Herden!",
    "Der Parasaurolophus konnte bis zu 5 Tonnen wiegen!",
    "Der Ton des Kamms war tief wie eine Trompete!",
    "Der Parasaurolophus hatte Hunderte von Zähnen zum Kauen!",
    "Der Parasaurolophus wurde 1922 in Kanada entdeckt!",
    "Die Jungen hatten kleinere Kämme, die mit der Zeit wuchsen!",
    "Der Parasaurolophus hatte einen guten Geruchssinn, um Raubtiere zu bemerken!",
    "Der Parasaurolophus ist einer der musikalischsten Dinosaurier!",
    "Der Kamm war möglicherweise bunt gefärbt, um Partner anzulocken!",
    "Der Parasaurolophus lebte in Nordamerika!",
    "Der Parasaurolophus konnte bis zu 40 Kilometer pro Stunde laufen!",
    "Der Parasaurolophus wird auch Trompeten-Dinosaurier genannt!",
  ],
  diplodocus: [
    "Der Diplodocus war einer der längsten Dinosaurier mit 27 Metern!",
    "Der Schwanz des Diplodocus konnte wie eine Peitsche knallen!",
    "Der Diplodocus hatte einen 6 Meter langen Hals!",
    "Der Diplodocus war ein Pflanzenfresser und fraß den ganzen Tag Blätter!",
    "Diplodocus bedeutet Doppelbalken!",
    "Der Diplodocus lebte vor 154 Millionen Jahren!",
    "Der Diplodocus konnte bis zu 16 Tonnen wiegen!",
    "Der Diplodocus hatte Zähne nur vorne im Mund, wie ein Kamm!",
    "Der Diplodocus schluckte Steine, um die Verdauung zu unterstützen!",
    "Der Diplodocus lebte in großen Herden!",
    "Der Diplodocus war einer der ersten entdeckten Riesendinosaurier!",
    "Der Diplodocus kaute nicht, er riss Blätter ab und schluckte sie!",
    "Der Diplodocus hatte 15 Halswirbel!",
    "Der Diplodocus wurde 1878 entdeckt!",
    "Der Schwanz des Diplodocus hatte über 70 Knochen!",
    "Der Diplodocus konnte sich auf die Hinterbeine stellen, um Bäume zu erreichen!",
    "Das Herz des Diplodocus war riesig, um Blut durch den ganzen Körper zu pumpen!",
    "Der Diplodocus lebte in dem Gebiet, das heute Nordamerika ist!",
    "Baby-Diplodocusse wuchsen sehr schnell!",
    "Der Diplodocus ist einer der am häufigsten in Museen ausgestellten Dinosaurier!",
  ],
  pachycephalosaurus: [
    "Der Pachycephalosaurus hatte einen 25 Zentimeter dicken Schädel!",
    "Der Pachycephalosaurus benutzte seinen harten Kopf für Kopfstöße!",
    "Pachycephalosaurus bedeutet Dickschädelechse!",
    "Der Pachycephalosaurus lebte vor 70 Millionen Jahren!",
    "Der Pachycephalosaurus war bis zu 5 Meter lang!",
    "Der Pachycephalosaurus war ein Zweibeiner!",
    "Der Pachycephalosaurus war Pflanzenfresser und Allesfresser!",
    "Die Schädelkuppel war mit Stacheln und Höckern verziert!",
    "Der Pachycephalosaurus lebte in Nordamerika!",
    "Der Pachycephalosaurus wog etwa 450 Kilogramm!",
    "Männchen stießen die Köpfe zusammen, um um Weibchen zu kämpfen!",
    "Der Pachycephalosaurus wurde 1931 entdeckt!",
    "Der Schädel des Pachycephalosaurus ist einer der dicksten aller Tiere!",
    "Der Pachycephalosaurus hatte kleine, spitze Zähne!",
    "Der Pachycephalosaurus lebte zur gleichen Zeit wie der T-Rex!",
    "Der Pachycephalosaurus konnte schnell auf zwei Beinen laufen!",
    "Die Augen des Pachycephalosaurus saßen an der Seite des Kopfes!",
    "Der Pachycephalosaurus ist der Dickkopf-Dinosaurier!",
    "Wissenschaftler diskutieren, ob die Kopfstöße das Gehirn verletzen konnten!",
    "Die Schädelkuppel wuchs mit dem Alter des Tieres!",
  ],
  iguanodon: [
    "Der Iguanodon war der zweite Dinosaurier, der jemals benannt wurde!",
    "Der Iguanodon hatte einen Daumenstachel zur Verteidigung!",
    "Iguanodon bedeutet Iguanzahn!",
    "Der Iguanodon lebte vor 125 Millionen Jahren!",
    "Der Iguanodon war bis zu 10 Meter lang!",
    "Der Iguanodon konnte auf zwei oder vier Beinen laufen!",
    "Der Iguanodon war ein Pflanzenfresser und kaute wie eine Kuh!",
    "Der Iguanodon wurde 1825 in England entdeckt!",
    "Der Iguanodon konnte bis zu 4 Tonnen wiegen!",
    "Der Daumenstachel wurde mit einem Nasenhorn verwechselt!",
    "Der Iguanodon lebte in großen Gruppen!",
    "Der Iguanodon hatte Hunderte von Zähnen zum Zermalmen von Pflanzen!",
    "Der Iguanodon lebte in Europa, Nordamerika und Asien!",
    "Der Iguanodon ist einer der am besten erforschten Dinosaurier!",
    "Die Zähne des Iguanodon wurden ein Leben lang ersetzt!",
    "Der Iguanodon hatte eine lange Zunge, um Blätter zu greifen!",
    "Der Iguanodon konnte bis zu 35 Kilometer pro Stunde laufen!",
    "Der Iguanodon hatte sehr flexible Hände!",
    "In einer Mine in Belgien wurden über 30 Skelette zusammen gefunden!",
    "Der Iguanodon half Wissenschaftlern zu verstehen, wie Dinosaurier lebten!",
  ],
  compsognathus: [
    "Der Compsognathus war einer der kleinsten Dinosaurier, so groß wie ein Huhn!",
    "Der Compsognathus wog nur 3 Kilogramm!",
    "Der Compsognathus war ein schneller und wendiger Jäger!",
    "Compsognathus bedeutet eleganter Kiefer!",
    "Der Compsognathus lebte vor 150 Millionen Jahren!",
    "Der Compsognathus fraß Insekten und Eidechsen!",
    "Der Compsognathus war einer der ersten vollständig gefundenen Dinosaurier!",
    "Der Compsognathus war nur 1 Meter lang!",
    "Der Compsognathus lief sehr schnell auf zwei Beinen!",
    "Der Compsognathus lebte in Europa, im heutigen Deutschland und Frankreich!",
    "Der Compsognathus wurde 1859 entdeckt!",
    "Wissenschaftler fanden eine Eidechse im Magen eines Fossils!",
    "Der Compsognathus hatte feine Federn am Körper!",
    "Der Compsognathus war ein entfernter Verwandter des Velociraptors!",
    "Der Compsognathus hatte große Augen, um gut sehen zu können!",
    "Der Compsognathus ist einer der niedlichsten Dinosaurier!",
    "Der Compsognathus jagte allein, nicht in Gruppen!",
    "Der Compsognathus hatte drei Finger an jeder Hand!",
    "Der Compsognathus lebte in der gleichen Zeit wie der Archaeopteryx!",
    "Der Compsognathus kommt im Film Jurassic Park als kleiner Dinosaurier vor!",
  ],
  carnotaurus: [
    "Der Carnotaurus hatte Hörner über den Augen, wie ein Stier!",
    "Der Carnotaurus hatte noch kleinere Arme als der T-Rex!",
    "Carnotaurus bedeutet fleischfressender Stier!",
    "Der Carnotaurus lebte vor 72 Millionen Jahren in Argentinien!",
    "Der Carnotaurus konnte 56 Kilometer pro Stunde laufen!",
    "Der Carnotaurus war bis zu 8 Meter lang!",
    "Der Carnotaurus hatte Haut mit Schuppen und Höckern!",
    "Der Carnotaurus war einer der schnellsten Raubtiere!",
    "Der Carnotaurus wog etwa 1,5 Tonnen!",
    "Der Carnotaurus wurde 1985 entdeckt!",
    "Der Carnotaurus ist einer der wenigen Dinosaurier mit fossilisierter Haut!",
    "Die Hörner des Carnotaurus dienten für Kämpfe zwischen Männchen!",
    "Der Carnotaurus hatte eine kurze Schnauze und einen schwachen Kiefer!",
    "Der Carnotaurus glich den schwachen Kiefer durch Geschwindigkeit aus!",
    "Der Carnotaurus lebte in Südamerika!",
    "Der Carnotaurus hatte nach vorne gerichtete Augen für Tiefenwahrnehmung!",
    "Die Arme des Carnotaurus waren praktisch nutzlos!",
    "Der Carnotaurus jagte wahrscheinlich pflanzenfressende Dinosaurier!",
    "Der Carnotaurus kommt im Film Jurassic World vor!",
    "Der Carnotaurus ist der berühmteste gehörnte Fleischfresser!",
  ],
  dilophosaurus: [
    "Der Dilophosaurus hatte zwei schöne Kämme auf dem Kopf!",
    "Der Dilophosaurus spuckte KEIN Gift, das war eine Filmerfindung!",
    "Dilophosaurus bedeutet Eidechse mit zwei Kämmen!",
    "Der Dilophosaurus lebte vor 193 Millionen Jahren!",
    "Der Dilophosaurus war bis zu 7 Meter lang!",
    "Der Dilophosaurus war einer der größten Fleischfresser seiner Zeit!",
    "Der Dilophosaurus wog etwa 400 Kilogramm!",
    "Die Kämme dienten dazu, Partner anzulocken!",
    "Der Dilophosaurus hatte nicht die Halskrause aus dem Film!",
    "Der Dilophosaurus lebte im heutigen Arizona in den USA!",
    "Der Dilophosaurus wurde 1942 entdeckt!",
    "Der Dilophosaurus war ein Zweibeiner und lief schnell!",
    "Der Dilophosaurus hatte scharfe Zähne und Krallen!",
    "Der Dilophosaurus war einer der ersten großen Raubtiere!",
    "Der Dilophosaurus lebte in der frühen Jurazeit!",
    "Der Dilophosaurus konnte wahrscheinlich gut schwimmen!",
    "Der Dilophosaurus hatte lange, starke Hinterbeine!",
    "Der Dilophosaurus jagte kleine Dinosaurier und andere Tiere!",
    "Der Dilophosaurus kommt im ersten Jurassic Park Film vor!",
    "Der Dilophosaurus ist einer der mysteriösesten frühen Dinosaurier!",
  ],
  apatosaurus: [
    "Der Apatosaurus war einer der größten Dinosaurier mit 23 Metern Länge!",
    "Apatosaurus bedeutet trügerische Eidechse!",
    "Der Apatosaurus wog bis zu 25 Tonnen!",
    "Der Apatosaurus wurde früher Brontosaurus genannt!",
    "Der Apatosaurus war ein sanfter Pflanzenfresser!",
    "Der Apatosaurus lebte vor 152 Millionen Jahren!",
    "Der Apatosaurus hatte einen sehr langen Schwanz!",
    "Der Apatosaurus konnte mit dem Schwanz wie eine Peitsche knallen!",
    "Der Apatosaurus schluckte Steine, um die Verdauung zu unterstützen!",
    "Der Apatosaurus lebte in großen Herden!",
    "Die Beine des Apatosaurus waren wie Säulen!",
    "Der Apatosaurus wurde 1877 entdeckt!",
    "Der Apatosaurus lebte in Nordamerika!",
    "Der Apatosaurus konnte jeden Tag Hunderte Kilo Pflanzen fressen!",
    "Baby-Apatosaurier waren bei der Geburt schon ziemlich groß!",
    "Der Hals des Apatosaurus war sehr lang, aber nicht so flexibel!",
    "Der Apatosaurus ist einer der bekanntesten Dinosaurier!",
    "Der Apatosaurus lief langsam wegen seines enormen Gewichts!",
    "Der Apatosaurus lebte in der späten Jurazeit!",
    "Das Herz des Apatosaurus wog mehrere hundert Kilogramm!",
  ],
  plesiosaurus: [
    "Der Plesiosaurus war kein Dinosaurier, sondern ein Meeresreptil!",
    "Der Plesiosaurus hatte einen sehr langen Hals!",
    "Der Plesiosaurus schwamm mit vier Flossen wie ein Unterwasservogel!",
    "Der Plesiosaurus lebte vor 200 Millionen Jahren!",
    "Der Plesiosaurus fraß Fische und Tintenfische!",
    "Plesiosaurus bedeutet fast eine Eidechse!",
    "Manche glauben, das Ungeheuer von Loch Ness sei ein Plesiosaurus!",
    "Der Plesiosaurus konnte bis zu 15 Meter lang werden!",
    "Der Plesiosaurus hatte scharfe Zähne zum Fischfangen!",
    "Der Plesiosaurus lebte in Meeren auf der ganzen Welt!",
    "Der Plesiosaurus wurde 1821 entdeckt!",
    "Der Plesiosaurus konnte nicht an Land laufen!",
    "Der Hals des Plesiosaurus war länger als sein Körper!",
    "Der Plesiosaurus schluckte Steine, um unter Wasser zu bleiben!",
    "Der Plesiosaurus war ein Meeresjäger und jagte andere Meerestiere!",
    "Es gab Plesiosaurier in verschiedenen Größen, von klein bis riesig!",
    "Der Plesiosaurus konnte nicht den Kopf über Wasser heben wie in Filmen!",
    "Der Plesiosaurus ist eines der berühmtesten Meeresreptilien!",
    "Der Plesiosaurus starb zusammen mit den Dinosauriern aus!",
    "Wissenschaftler fanden Plesiosaurus-Fossilien auf allen Kontinenten!",
  ],
  mosasaurus: [
    "Der Mosasaurus war eines der größten Meeresraubtiere aller Zeiten!",
    "Der Mosasaurus konnte bis zu 17 Meter lang werden!",
    "Der Mosasaurus war kein Dinosaurier, sondern eine riesige Meereseidechse!",
    "Der Mosasaurus lebte vor 70 Millionen Jahren!",
    "Der Mosasaurus fraß Fische, Haie und andere Meeresreptilien!",
    "Mosasaurus bedeutet Eidechse von der Maas!",
    "Der Mosasaurus war eines der ersten Fossilien, die je gefunden wurden!",
    "Der Mosasaurus hatte einen kräftigen Schwanz zum Schwimmen!",
    "Der Mosasaurus ist verwandt mit den heutigen Waranen!",
    "Der Mosasaurus hatte Dutzende scharfer Zähne!",
    "Der Mosasaurus konnte schneller schwimmen als die meisten Haie!",
    "Der Mosasaurus wurde 1764 in den Niederlanden entdeckt!",
    "Der Mosasaurus konnte nicht an Land laufen!",
    "Der Mosasaurus herrschte in den Ozeanen am Ende der Kreidezeit!",
    "Der Mosasaurus kommt im Film Jurassic World vor!",
    "Der Mosasaurus hatte ein Gelenk im Kiefer, um große Beute zu schlucken!",
    "Der Mosasaurus hatte Flossen statt Beine!",
    "Der Mosasaurus starb gleichzeitig mit den Dinosauriern aus!",
    "Es gab über 40 Mosasaurier-Arten!",
    "Der Mosasaurus war der absolute Herrscher der urzeitlichen Meere!",
  ],
  dimetrodon: [
    "Der Dimetrodon war kein Dinosaurier, er lebte vor den Dinosauriern!",
    "Der Dimetrodon hatte ein großes Segel auf dem Rücken!",
    "Das Segel half dem Dimetrodon, seine Körpertemperatur zu regulieren!",
    "Der Dimetrodon lebte vor 280 Millionen Jahren!",
    "Der Dimetrodon war ein Fleischfresser mit scharfen Zähnen!",
    "Dimetrodon bedeutet zwei Maße von Zähnen!",
    "Der Dimetrodon war eher mit den Säugetieren verwandt als mit den Reptilien!",
    "Der Dimetrodon war bis zu 4 Meter lang!",
    "Der Dimetrodon war eines der größten Raubtiere seiner Zeit!",
    "Das Rückensegel konnte über 1 Meter hoch werden!",
    "Der Dimetrodon lief auf vier Beinen!",
    "Der Dimetrodon lebte im Perm, lange vor den Dinosauriern!",
    "Der Dimetrodon wurde 1878 entdeckt!",
    "Der Dimetrodon hatte verschiedene Zahntypen wie die Säugetiere!",
    "Der Dimetrodon wog bis zu 250 Kilogramm!",
    "Das Segel war mit Blutgefäßen durchzogen für die Temperaturregelung!",
    "Der Dimetrodon lebte im heutigen Nordamerika und Europa!",
    "Der Dimetrodon ist einer der bekanntesten Nicht-Dinosaurier!",
    "Der Dimetrodon verschwand 40 Millionen Jahre vor den Dinosauriern!",
    "Der Dimetrodon wird oft fälschlicherweise als Dinosaurier angesehen!",
  ],
  archaeopteryx: [
    "Der Archaeopteryx ist der berühmteste Urvogel!",
    "Der Archaeopteryx hatte Federn wie ein Vogel, aber Zähne wie ein Reptil!",
    "Archaeopteryx bedeutet alter Flügel!",
    "Der Archaeopteryx lebte vor 150 Millionen Jahren!",
    "Der Archaeopteryx war so groß wie eine Krähe!",
    "Der Archaeopteryx hatte Krallen an den Flügeln!",
    "Der Archaeopteryx ist das Bindeglied zwischen Dinosauriern und Vögeln!",
    "Der Archaeopteryx konnte wahrscheinlich kurze Strecken fliegen!",
    "Der Archaeopteryx wurde 1861 in Deutschland entdeckt!",
    "Der Archaeopteryx hatte einen langen, knöchernen Schwanz!",
    "Der Archaeopteryx wog nur etwa 1 Kilogramm!",
    "Der Archaeopteryx war etwa 50 Zentimeter lang!",
    "Der Archaeopteryx fraß Insekten und kleine Tiere!",
    "Der Archaeopteryx hatte drei Finger mit Krallen an jedem Flügel!",
    "Der Archaeopteryx lebte im heutigen Deutschland!",
    "Das Fossil des Archaeopteryx ist eines der wichtigsten der Wissenschaftsgeschichte!",
    "Der Archaeopteryx bewies, dass Vögel von Dinosauriern abstammen!",
    "Der Archaeopteryx konnte wahrscheinlich auf Bäume klettern!",
    "Es wurden nur 12 Archaeopteryx-Fossilien gefunden!",
    "Der Archaeopteryx konnte nicht so gut fliegen wie moderne Vögel!",
    "Der Archaeopteryx ist das berühmteste Übergangsfossil der Welt!",
  ],
};
