import type { DinoId } from "./dinosaurs";

export const dinoFunFactsEn: Record<DinoId, string[]> = {
  trex: [
    "T-Rex had teeth the size of bananas!",
    "T-Rex could feel vibrations in the ground through its feet!",
    "T-Rex's tiny arms were actually super strong!",
    "T-Rex lived 68 million years ago!",
    "T-Rex could eat 230 kilograms of meat in one bite!",
    "T-Rex means Tyrant Lizard King!",
    "T-Rex could run at 40 kilometers per hour!",
    "T-Rex had the strongest bite of any land animal!",
    "T-Rex's brain was bigger than most dinosaurs!",
    "T-Rex had better vision than an eagle!",
    "Scientists have found over 50 T-Rex skeletons!",
    "T-Rex was up to 12 meters long!",
    "Baby T-Rexes were born covered in feathers!",
    "T-Rex lived in what is now the United States and Canada!",
    "T-Rex's tail helped it balance while running!",
    "T-Rex is related to today's chickens!",
    "T-Rex could hear very low sounds, like earthquakes!",
    "T-Rex's skull could be up to 1.5 meters long!",
    "T-Rex replaced its teeth throughout its life, like sharks!",
    "T-Rex was one of the last dinosaurs before extinction!",
  ],
  triceratops: [
    "Triceratops had three horns on its face!",
    "The frill of Triceratops protected its neck!",
    "Triceratops was a herbivore and ate plants all day!",
    "Triceratops could weigh up to 12 tons!",
    "Triceratops means three-horned face!",
    "Triceratops lived in herds for protection!",
    "Triceratops' beak was like a parrot's!",
    "Triceratops lived at the same time as T-Rex!",
    "The Triceratops frill changed color to attract mates!",
    "Triceratops was up to 9 meters long!",
    "The Triceratops skull is one of the largest of any land animal!",
    "Triceratops had over 400 teeth for chewing plants!",
    "Scientists found Triceratops fossils with T-Rex bite marks!",
    "Triceratops walked on four legs, like a rhino!",
    "Triceratops lived about 68 million years ago!",
    "Triceratops horns could be 1 meter long!",
    "Triceratops is one of the most famous dinosaurs!",
    "Triceratops was discovered in 1887!",
    "Baby Triceratops had tiny little horns!",
    "Triceratops probably used its horns to fight rivals!",
  ],
  stegosaurus: [
    "Stegosaurus had plates on its back that regulated temperature!",
    "Stegosaurus' tail had spikes for defense!",
    "Stegosaurus' brain was the size of a walnut!",
    "Stegosaurus was up to 9 meters long!",
    "Stegosaurus lived 155 million years ago!",
    "Stegosaurus means roofed lizard!",
    "Stegosaurus was a herbivore and ate ferns!",
    "Stegosaurus' plates turned red when it was angry!",
    "Stegosaurus could weigh up to 5 tons!",
    "Stegosaurus had 17 plates on its back!",
    "The tail spikes were up to 60 centimeters long!",
    "Stegosaurus walked slowly on four legs!",
    "Stegosaurus was discovered in 1877 in the United States!",
    "Stegosaurus' back legs were bigger than its front legs!",
    "Stegosaurus lived long before T-Rex!",
    "Stegosaurus is the official dinosaur of Colorado!",
    "Stegosaurus' plates weren't actually armor!",
    "Stegosaurus had cheeks to store food!",
    "Baby Stegosaurus were born with small plates!",
    "Stegosaurus is one of the easiest dinosaurs to recognize!",
  ],
  brachiosaurus: [
    "Brachiosaurus was as tall as a 4-story building!",
    "Brachiosaurus ate up to 400 kilograms of plants a day!",
    "Brachiosaurus' neck was 9 meters long!",
    "Brachiosaurus could weigh up to 80 tons!",
    "Brachiosaurus had nostrils on top of its head!",
    "Brachiosaurus means arm lizard!",
    "Brachiosaurus lived 154 million years ago!",
    "Brachiosaurus' front legs were longer than its back legs!",
    "Brachiosaurus didn't chew — it swallowed plants whole!",
    "Brachiosaurus was up to 26 meters long!",
    "Brachiosaurus' heart was enormous to pump blood to its head!",
    "Brachiosaurus lived in the Jurassic period!",
    "Brachiosaurus appears in the movie Jurassic Park!",
    "Brachiosaurus probably lived in groups!",
    "Baby Brachiosaurus grew very quickly!",
    "Brachiosaurus was one of the largest animals ever!",
    "Brachiosaurus couldn't run because of its weight!",
    "Brachiosaurus was discovered in 1900!",
    "Brachiosaurus ate leaves from the tallest trees!",
    "Brachiosaurus' teeth were like spoons for stripping leaves!",
  ],
  velociraptor: [
    "Velociraptor was the size of a large turkey!",
    "Velociraptor had feathers all over its body!",
    "Velociraptor had a huge curved claw on each foot!",
    "Velociraptor means swift thief!",
    "Velociraptor lived 75 million years ago in Mongolia!",
    "Velociraptor was very smart for a dinosaur!",
    "Velociraptor hunted in packs to catch bigger prey!",
    "Velociraptor could run at 60 kilometers per hour!",
    "Velociraptor's claw was 6 centimeters long!",
    "Velociraptor was a carnivore and hunted other dinosaurs!",
    "The Velociraptor in Jurassic Park is much bigger than the real one!",
    "Velociraptor was only 2 meters long!",
    "Velociraptor weighed only 15 kilograms!",
    "Velociraptor had over 80 sharp teeth!",
    "Scientists found fossils of Velociraptor fighting Protoceratops!",
    "Velociraptor used its tail for balance when running!",
    "Velociraptor had excellent vision for hunting!",
    "Velociraptor lived in the Gobi Desert!",
    "Velociraptor's feathers weren't for flying!",
    "Velociraptor is one of the most studied dinosaurs!",
  ],
  pteranodon: [
    "Pteranodon wasn't a dinosaur — it was a flying reptile!",
    "Pteranodon's wingspan reached 7 meters!",
    "Pteranodon had no teeth!",
    "Pteranodon ate fish it caught from the sea!",
    "Pteranodon's crest helped stabilize its flight!",
    "Pteranodon means wing without teeth!",
    "Pteranodon lived 86 million years ago!",
    "Pteranodon weighed only 25 kilos despite its size!",
    "Pteranodon had hollow bones, like today's birds!",
    "Pteranodon glided long distances over the ocean!",
    "Males had bigger crests than females!",
    "Pteranodon lived in North America!",
    "Pteranodon walked on all fours on the ground!",
    "Pteranodon was one of the largest flying animals!",
    "Pteranodon's wings were made of stretched skin!",
    "Pteranodon could dive into water to catch fish!",
    "Pteranodon cared for its chicks in the nest!",
    "Pteranodon fossils were found in Kansas!",
    "Pteranodon was discovered in 1876!",
    "Pteranodon flew at up to 50 kilometers per hour!",
  ],
  ankylosaurus: [
    "Ankylosaurus was a living tank!",
    "Ankylosaurus' tail had a huge bony club!",
    "Ankylosaurus had armor made of bone plates!",
    "Ankylosaurus could break T-Rex's legs with its tail!",
    "Ankylosaurus means stiff lizard!",
    "Ankylosaurus lived 68 million years ago!",
    "Ankylosaurus was up to 10 meters long!",
    "Ankylosaurus was a herbivore and ate low plants!",
    "Ankylosaurus could weigh up to 6 tons!",
    "Even Ankylosaurus' eyelids had armor!",
    "Ankylosaurus had a small brain!",
    "The tail club could weigh 30 kilograms!",
    "Ankylosaurus walked slowly on four legs!",
    "Ankylosaurus lived alone, unlike other herbivores!",
    "Ankylosaurus was discovered in 1908!",
    "Ankylosaurus didn't need to run because it was so well-protected!",
    "Ankylosaurus' belly was the most vulnerable part!",
    "Ankylosaurus lived in what is now North America!",
    "Ankylosaurus' teeth were small and leaf-shaped!",
    "Ankylosaurus was one of the most armored dinosaurs ever!",
  ],
  spinosaurus: [
    "Spinosaurus was bigger than T-Rex!",
    "Spinosaurus had a huge sail on its back!",
    "Spinosaurus was the first dinosaur known to swim!",
    "Spinosaurus ate giant fish!",
    "Spinosaurus' snout looked like a crocodile's!",
    "Spinosaurus means spine lizard!",
    "Spinosaurus lived 95 million years ago in Africa!",
    "Spinosaurus was up to 15 meters long!",
    "The sail could be 1.8 meters tall!",
    "Spinosaurus had enormous claws on its hands!",
    "Spinosaurus could hold its breath underwater briefly!",
    "Spinosaurus had sensors in its snout to detect prey in water!",
    "Spinosaurus could weigh up to 7 tons!",
    "Spinosaurus walked on both two and four legs!",
    "Spinosaurus was discovered in 1912 in Egypt!",
    "The first Spinosaurus fossil was destroyed in World War II!",
    "Spinosaurus had conical teeth, different from T-Rex!",
    "Spinosaurus' tail was flat like a fish's!",
    "Spinosaurus is the largest land carnivore that ever existed!",
    "Spinosaurus appears in Jurassic Park 3!",
  ],
  parasaurolophus: [
    "Parasaurolophus had a hollow crest that made sounds like a trumpet!",
    "Parasaurolophus used its crest to communicate with the group!",
    "Parasaurolophus was a herbivore and ate leaves and fruits!",
    "Parasaurolophus could walk on two or four legs!",
    "Parasaurolophus means near crested lizard!",
    "Parasaurolophus lived 76 million years ago!",
    "The Parasaurolophus crest could be 1 meter long!",
    "Parasaurolophus was up to 10 meters long!",
    "Parasaurolophus lived in large herds!",
    "Parasaurolophus could weigh up to 5 tons!",
    "The crest sound was deep like a trumpet!",
    "Parasaurolophus had hundreds of teeth for chewing!",
    "Parasaurolophus was discovered in 1922 in Canada!",
    "Babies had smaller crests that grew over time!",
    "Parasaurolophus had a good sense of smell for detecting predators!",
    "Parasaurolophus is one of the most musical dinosaurs!",
    "The crest may have been colorful to attract mates!",
    "Parasaurolophus lived in North America!",
    "Parasaurolophus ran at up to 40 kilometers per hour!",
    "Parasaurolophus is known as the trumpet dinosaur!",
  ],
  diplodocus: [
    "Diplodocus was one of the longest dinosaurs at 27 meters!",
    "Diplodocus' tail could crack like a whip!",
    "Diplodocus had a 6-meter-long neck!",
    "Diplodocus was a herbivore and ate leaves all day!",
    "Diplodocus means double beam!",
    "Diplodocus lived 154 million years ago!",
    "Diplodocus could weigh up to 16 tons!",
    "Diplodocus had teeth only in the front of its mouth, like a comb!",
    "Diplodocus swallowed stones to help digest food!",
    "Diplodocus lived in large herds!",
    "Diplodocus was one of the first giant dinosaurs discovered!",
    "Diplodocus didn't chew — it stripped leaves and swallowed!",
    "Diplodocus had 15 vertebrae in its neck!",
    "Diplodocus was discovered in 1878!",
    "Diplodocus' tail had over 70 bones!",
    "Diplodocus could rear up on its back legs to reach trees!",
    "Diplodocus' heart was huge to pump blood throughout its body!",
    "Diplodocus lived in what is now North America!",
    "Baby Diplodocus grew very fast!",
    "Diplodocus is one of the most displayed dinosaurs in museums!",
  ],
  pachycephalosaurus: [
    "Pachycephalosaurus had a skull 25 centimeters thick!",
    "Pachycephalosaurus used its hard head for head-butting!",
    "Pachycephalosaurus means thick-headed lizard!",
    "Pachycephalosaurus lived 70 million years ago!",
    "Pachycephalosaurus was up to 5 meters long!",
    "Pachycephalosaurus walked on two legs!",
    "Pachycephalosaurus was an herbivore and omnivore!",
    "The dome was decorated with spikes and bumps!",
    "Pachycephalosaurus lived in North America!",
    "Pachycephalosaurus weighed about 450 kilograms!",
    "Males head-butted to compete for females!",
    "Pachycephalosaurus was discovered in 1931!",
    "Pachycephalosaurus' skull is one of the thickest of any animal!",
    "Pachycephalosaurus had small, pointy teeth!",
    "Pachycephalosaurus lived at the same time as T-Rex!",
    "Pachycephalosaurus could run fast on two legs!",
    "Pachycephalosaurus' eyes were on the side of its head!",
    "Pachycephalosaurus is the hard-headed dinosaur!",
    "Scientists debate whether head-butting would hurt the brain!",
    "The dome grew bigger as the animal aged!",
  ],
  iguanodon: [
    "Iguanodon was the second dinosaur ever named!",
    "Iguanodon had a thumb spike for defense!",
    "Iguanodon means iguana tooth!",
    "Iguanodon lived 125 million years ago!",
    "Iguanodon was up to 10 meters long!",
    "Iguanodon could walk on two or four legs!",
    "Iguanodon was a herbivore and chewed like a cow!",
    "Iguanodon was discovered in 1825 in England!",
    "Iguanodon could weigh up to 4 tons!",
    "The thumb spike was once mistaken for a nose horn!",
    "Iguanodon lived in large groups!",
    "Iguanodon had hundreds of teeth for grinding plants!",
    "Iguanodon lived in Europe, North America, and Asia!",
    "Iguanodon is one of the best-studied dinosaurs!",
    "Iguanodon's teeth were replaced throughout its life!",
    "Iguanodon had a long tongue for pulling leaves!",
    "Iguanodon ran at up to 35 kilometers per hour!",
    "Iguanodon had very flexible hands!",
    "Over 30 skeletons were found together in a mine in Belgium!",
    "Iguanodon helped scientists understand how dinosaurs lived!",
  ],
  compsognathus: [
    "Compsognathus was one of the smallest dinosaurs, the size of a chicken!",
    "Compsognathus weighed only 3 kilograms!",
    "Compsognathus was a fast and agile hunter!",
    "Compsognathus means elegant jaw!",
    "Compsognathus lived 150 million years ago!",
    "Compsognathus ate insects and lizards!",
    "Compsognathus was one of the first complete dinosaurs found!",
    "Compsognathus was only 1 meter long!",
    "Compsognathus ran very fast on two legs!",
    "Compsognathus lived in Europe, in what is now Germany and France!",
    "Compsognathus was discovered in 1859!",
    "Scientists found a lizard inside a fossil's stomach!",
    "Compsognathus had fine feathers on its body!",
    "Compsognathus was a distant relative of Velociraptor!",
    "Compsognathus had big eyes for good vision!",
    "Compsognathus is one of the cutest dinosaurs!",
    "Compsognathus hunted alone, not in packs!",
    "Compsognathus had three fingers on each hand!",
    "Compsognathus lived in the same period as Archaeopteryx!",
    "Compsognathus appears in Jurassic Park as the tiny dinosaur!",
  ],
  carnotaurus: [
    "Carnotaurus had horns above its eyes, like a bull!",
    "Carnotaurus had even tinier arms than T-Rex!",
    "Carnotaurus means meat-eating bull!",
    "Carnotaurus lived 72 million years ago in Argentina!",
    "Carnotaurus could run at 56 kilometers per hour!",
    "Carnotaurus was up to 8 meters long!",
    "Carnotaurus had skin with scales and bumps!",
    "Carnotaurus was one of the fastest predators!",
    "Carnotaurus weighed about 1.5 tons!",
    "Carnotaurus was discovered in 1985!",
    "Carnotaurus is one of the few dinosaurs with fossilized skin!",
    "Carnotaurus' horns were used for fights between males!",
    "Carnotaurus had a short snout and weak jaw!",
    "Carnotaurus made up for its weak jaw with speed!",
    "Carnotaurus lived in South America!",
    "Carnotaurus had forward-facing eyes for depth perception!",
    "Carnotaurus' arms were practically useless!",
    "Carnotaurus probably hunted herbivorous dinosaurs!",
    "Carnotaurus appears in Jurassic World!",
    "Carnotaurus is the most famous horned carnivore dinosaur!",
  ],
  dilophosaurus: [
    "Dilophosaurus had two beautiful crests on its head!",
    "Dilophosaurus did NOT spit venom — that was made up for the movie!",
    "Dilophosaurus means two-crested lizard!",
    "Dilophosaurus lived 193 million years ago!",
    "Dilophosaurus was up to 7 meters long!",
    "Dilophosaurus was one of the largest carnivores of its time!",
    "Dilophosaurus weighed about 400 kilograms!",
    "The crests were used to attract mates!",
    "Dilophosaurus didn't have the frill shown in the movie!",
    "Dilophosaurus lived in what is now Arizona, USA!",
    "Dilophosaurus was discovered in 1942!",
    "Dilophosaurus walked on two legs and ran fast!",
    "Dilophosaurus may have hunted in groups!",
    "The crests were fragile and probably not used for fighting!",
    "Dilophosaurus lived in the early Jurassic period!",
    "Dilophosaurus had a notch in its upper jaw!",
    "Dilophosaurus left footprints that scientists study today!",
    "Dilophosaurus had long, strong legs for running!",
    "Dilophosaurus is the state dinosaur of Connecticut!",
    "Dilophosaurus is one of the most misunderstood dinosaurs!",
  ],
  apatosaurus: [
    "Apatosaurus was once known as Brontosaurus!",
    "Apatosaurus was up to 23 meters long!",
    "Apatosaurus weighed up to 25 tons!",
    "Apatosaurus means deceptive lizard!",
    "Apatosaurus lived 150 million years ago!",
    "Apatosaurus ate hundreds of kilos of plants daily!",
    "Apatosaurus had a tiny head for its huge body!",
    "Apatosaurus' tail could crack like a whip!",
    "Apatosaurus was discovered in 1877!",
    "Apatosaurus swallowed stones to help digest food!",
    "Apatosaurus lived in large herds!",
    "The name Brontosaurus was used for over 100 years by mistake!",
    "Apatosaurus had a very long neck and tail!",
    "Apatosaurus couldn't chew — it swallowed leaves whole!",
    "Apatosaurus lived in the Jurassic period!",
    "Apatosaurus' bones are found in the western United States!",
    "Baby Apatosaurus grew incredibly fast!",
    "Apatosaurus could rear up on its back legs!",
    "Apatosaurus is one of the most famous long-necked dinosaurs!",
    "Apatosaurus had pencil-like teeth for stripping leaves!",
  ],
  plesiosaurus: [
    "Plesiosaurus wasn't a dinosaur — it was a marine reptile!",
    "Plesiosaurus had a very long neck!",
    "Plesiosaurus had four flippers for swimming!",
    "Plesiosaurus lived 200 million years ago!",
    "Plesiosaurus ate fish and squid!",
    "Plesiosaurus means near to lizard!",
    "Plesiosaurus inspired the Loch Ness Monster legend!",
    "Plesiosaurus had sharp teeth for catching fish!",
    "Plesiosaurus could be up to 15 meters long!",
    "Plesiosaurus gave birth to live babies in the water!",
    "Plesiosaurus couldn't leave the water!",
    "Plesiosaurus swam by flapping its flippers like wings!",
    "Plesiosaurus was discovered in 1824!",
    "Plesiosaurus lived in oceans around the world!",
    "Plesiosaurus breathed air and had to surface!",
    "Some Plesiosaurus had necks longer than their bodies!",
    "Plesiosaurus fossils are found on every continent!",
    "Plesiosaurus swallowed stones for ballast!",
    "Plesiosaurus was one of the first marine reptiles found!",
    "Plesiosaurus ruled the seas for over 135 million years!",
  ],
  mosasaurus: [
    "Mosasaurus was the king of the prehistoric seas!",
    "Mosasaurus could grow up to 17 meters long!",
    "Mosasaurus had powerful jaws to crush shells!",
    "Mosasaurus means Meuse River lizard!",
    "Mosasaurus lived 70 million years ago!",
    "Mosasaurus was related to modern monitor lizards!",
    "Mosasaurus breathed air and surfaced to breathe!",
    "Mosasaurus ate fish, turtles, and other marine reptiles!",
    "Mosasaurus had a double-hinged jaw like a snake!",
    "Mosasaurus was the top predator of its ocean!",
    "Mosasaurus was discovered in 1764 in the Netherlands!",
    "Mosasaurus was one of the first prehistoric animals identified!",
    "Mosasaurus had flippers and a powerful tail for swimming!",
    "Mosasaurus could weigh up to 15 tons!",
    "Mosasaurus gave birth to live young in the water!",
    "Mosasaurus had extra teeth on the roof of its mouth!",
    "Mosasaurus appears in the movie Jurassic World!",
    "Mosasaurus fossils are found all over the world!",
    "Mosasaurus went extinct 66 million years ago with the dinosaurs!",
    "Mosasaurus was a fast and agile swimmer!",
  ],
  dimetrodon: [
    "Dimetrodon wasn't a dinosaur — it lived before them!",
    "Dimetrodon had a huge sail on its back!",
    "The sail helped Dimetrodon regulate body temperature!",
    "Dimetrodon lived 280 million years ago!",
    "Dimetrodon means two measures of teeth!",
    "Dimetrodon had two types of teeth: sharp and flat!",
    "Dimetrodon was actually more related to mammals than reptiles!",
    "Dimetrodon was a top predator of its time!",
    "Dimetrodon was up to 4 meters long!",
    "Dimetrodon walked on four short legs!",
    "The sail could be over 1 meter tall!",
    "Dimetrodon lived before the first dinosaurs appeared!",
    "Dimetrodon was discovered in 1878!",
    "Dimetrodon lived in what is now North America and Europe!",
    "Dimetrodon had powerful jaws for hunting!",
    "Dimetrodon is often mistaken for a dinosaur!",
    "Dimetrodon ate other animals and insects!",
    "Dimetrodon went extinct about 40 million years before dinosaurs!",
    "The sail may have been colorful to attract mates!",
    "Dimetrodon is a synapsid, an ancestor of mammals!",
  ],
  archaeopteryx: [
    "Archaeopteryx is considered the first bird!",
    "Archaeopteryx had feathers like a bird but teeth like a dinosaur!",
    "Archaeopteryx lived 150 million years ago!",
    "Archaeopteryx means ancient wing!",
    "Archaeopteryx was about the size of a raven!",
    "Archaeopteryx had claws on its wings!",
    "Archaeopteryx could probably glide more than fly!",
    "Only 12 Archaeopteryx fossils have been found!",
    "Archaeopteryx lived in what is now Germany!",
    "Archaeopteryx is the link between dinosaurs and birds!",
    "Archaeopteryx had a long bony tail!",
    "Archaeopteryx weighed less than 1 kilogram!",
    "Archaeopteryx had three clawed fingers on each wing!",
    "Archaeopteryx was discovered in 1861!",
    "Archaeopteryx is one of the most important fossils ever found!",
    "Archaeopteryx's feathers were similar to modern bird feathers!",
    "Archaeopteryx ate insects and small animals!",
    "Archaeopteryx lived in trees and on the ground!",
    "Archaeopteryx could run fast on two legs!",
    "Archaeopteryx proves that birds evolved from dinosaurs!",
  ],
};
